### ISSUE TITLE
Getting error after giving 'go build' command

### ISSUE THREAD

**Issue by nidhinmohanc** [goadesign/goa#1015]
main.go:5:2: cannot find package "github.com/goadesign/goa/client" in any of:
	/usr/lib/go-1.6/src/github.com/goadesign/goa/client (from $GOROOT)
	($GOPATH not set)
main.go:6:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/lib/go-1.6/src/github.com/spf13/cobra (from $GOROOT)
	($GOPATH not set)
main.go:7:2: cannot find package "goa-adder/client" in any of:
	/usr/lib/go-1.6/src/goa-adder/client (from $GOROOT)
	($GOPATH not set)
main.go:8:2: cannot find package "goa-adder/tool/cli" in any of:
	/usr/lib/go-1.6/src/goa-adder/tool/cli (from $GOROOT)
	($GOPATH not set)

>go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by raphael** [comment]
Looks like you need to setup your workspace and GOPATH. See https://golang.org/doc/install.
