### ISSUE TITLE
integrate goa generated code into existing code (use gorilla mux)

### ISSUE THREAD

**Issue by yogihardi** [goadesign/goa#1017]
Hi,

I just curious, is that possible to integrate the generated code of `goa` into my existing project, that my project already using `gorilla mux` as web server.

thanks in advance.

**Comment by raphael** [comment]
The goa service `Mux` field is a `http.Handler` and can thus be mounted wherever a HTTP handler can, for example:
```go
    service := goa.New("..")
    // ... setup service by mounting controllers etc.
    r := mux.NewRouter() // gorilla mux
    r.Handle("/goa", service.Mux)
```
