### ISSUE TITLE
Add an `ErrForbidden` error

### ISSUE THREAD

**Issue by xcoulon** [goadesign/goa#1029]
This kind of error would be returned when a user is not allowed to perform an operation. This is different from the `unauthorized` kind of response, which is related to authentication (ie, the user is not recognized and should login first). 

See discussion on [stackoverflow](http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses#6937030) for more details.

**Comment by raphael** [comment]
Thank you!  The idea is for user code to define the error class they need that may not be defined in goa. goa cannot list all the possible errors. The list in goa are errors that goa itself (generated code and middlewares) depends on.

**Comment by xcoulon** [comment]
ok, I understand your point.
