### ISSUE TITLE
Example JSON in Swagger Definition for rest service returning collection of Custom View not correct

### ISSUE THREAD

**Issue by nidhinmohanc** [goadesign/goa#1031]
When a rest service returns a collection of non-default view, the generated code as well as the Swagger Definition looks good but the example generated as part of the swagger definition seems to take the default view.

Example - 

var UserMedia = MediaType("application/sio.io.user", func() {
	TypeName("user")
	Reference(UserUpdatePayload)

	Attributes(func (){
		Attribute("userid")
		Attribute("firstname")
		Attribute("lastname")
		Attribute("createdon")
		Attribute("status")
		Attribute("email")
		Attribute("address")
		Attribute("city")
		Attribute("state")
		Attribute("country")
		Attribute("phone")
		Attribute("organization")
		Required("userid")
	})

	View("default", func(){
		Attribute("userid")
		Attribute("firstname")
		Attribute("lastname")
		Attribute("createdon")
		Attribute("status")
		Attribute("email")
		Attribute("address")
		Attribute("city")
		Attribute("state")
		Attribute("country")
		Attribute("phone")
		Attribute("organization")
	})
	View("extended", func(){
		Attribute("userid")
		Attribute("firstname")
		Attribute("lastname")
		Attribute("email")
	})
})

	Action("list", func() {
		Routing(GET("/"))
		Description("returns users. organization and or users can be optionally passed for filtering")
		Params(func() {
			Param("organization", Integer, "Optional filter for fetching users specific to an organization")
			Param("group", Integer, "Optional filter for fetching users specific to a group. The group needs to be part of the organization specified")
		})
		Response(OK, func() {
			Description("This is the success response")
			Status(200)
			Media(CollectionOf(UserMedia), "extended")
		})
	})

The  swagger definition for the userExtendedCollection looks like below. Even though the definition is rightly pointing to an array of userExtended, the example specifies attributes from the default view.

"userExtendedCollection": {
      "title": "Mediatype identifier: application/sio.io.user; type=collection; view=extended",
      "type": "array",
      "items": {
        "$ref": "#/definitions/userExtended"
      },
      "description": "userExtendedCollection is the media type for an array of userExtended (default view)",
      "example": [
        {
          "address": "8ne",
          "city": "2i1z",
          "country": "p1w",
          "createdon": "Rem ex hic eum deserunt.",
          "email": "Aut sint dolorem quis porro.",
          "firstname": "3yyl",
          "lastname": "59pybe3zhu",
          "organization": "Atque dolorem dolorum culpa.",
          "phone": "Quia sit est.",
          "state": "jg",
          "status": "Ipsum ea quibusdam odit assumenda voluptatem explicabo.",
          "userid": "5793624c-6ad3-4a27-a0ff-5c01982d75f9"
        },
        {
          "address": "8ne",
          "city": "2i1z",
          "country": "p1w",
          "createdon": "Rem ex hic eum deserunt.",
          "email": "Aut sint dolorem quis porro.",
          "firstname": "3yyl",
          "lastname": "59pybe3zhu",
          "organization": "Atque dolorem dolorum culpa.",
          "phone": "Quia sit est.",
          "state": "jg",
          "status": "Ipsum ea quibusdam odit assumenda voluptatem explicabo.",
          "userid": "5793624c-6ad3-4a27-a0ff-5c01982d75f9"
        },
        {
          "address": "8ne",
          "city": "2i1z",
          "country": "p1w",
          "createdon": "Rem ex hic eum deserunt.",
          "email": "Aut sint dolorem quis porro.",
          "firstname": "3yyl",
          "lastname": "59pybe3zhu",
          "organization": "Atque dolorem dolorum culpa.",
          "phone": "Quia sit est.",
          "state": "jg",
          "status": "Ipsum ea quibusdam odit assumenda voluptatem explicabo.",
          "userid": "5793624c-6ad3-4a27-a0ff-5c01982d75f9"
        }
      ]
    },

Regards
Nidhin

**Comment by raphael** [comment]
Thank you for the report. Can you please provide a complete design that reproduces the issue?
