### ISSUE TITLE
How I put JSON in Any Type

### ISSUE THREAD

**Issue by perigee** [goadesign/goa#1033]
I defined a MediaType with

```
var StatusMedia = MediaType("application/vnd.errormedia+json", func() {
	Description("Status of service")
	TypeName("StatusMedia ")
	ContentType("application/json")
	Attributes(func() {
		Attribute("request_id", UUID, "requst ID")
		Attribute("message", String, "Response Message")
		Attribute("data", Any, "Data body")
		Required("request_id", "message")
	})
})
```

in such case, I defined attribute `data` as `Any` Type, since I will just embed a json inside data, but how can I assign a JSON in `data` ? Thank you in advance.

**Comment by raphael** [comment]
Do you mean a JSON string? is so data could just be a string. If you mean any value then what you have should work just fine. The generated code will produce a field of type `interface{}` and you should be able to assign anything to it that can be JSON marshaled.

**Comment by perigee** [comment]
I tried to use:

```
type StatusData struct {
  Status string `json:"status"`
}

... 

res := &app.StatusMedia {
     RequestID: uuid.NewV4(),
     Message:   "ok",
     Data:         &StatusData{ Status: "status ok"},
}
```

which is failed to compile

**Comment by perigee** [comment]
I got the idea, when the `Attribute`  `data` is not required, it will generate ` * interface {}` instead of `interface{}`, so i failed to compile.
