### ISSUE TITLE
Inconsistency between ErrorMedia and ErrorResponse

### ISSUE THREAD

**Issue by sotosof** [goadesign/goa#1038]
Goa's internal media type `ErrorMedia` which represents error has attribute `meta` defined as `Hash` (basically `Object`), but goa's type `ErrorResponse` which is used to generate error response has attribute `meta` defined as slice of maps (basically `Array of Objects`.

Attribute `meta` of type `ErrorResponse` should be changed to `map` to match `ErrorMedia`.

**Comment by raphael** [comment]
@sotosof I think we should go ahead with this, care to do the honor?

**Comment by sotosof** [comment]
@raphael Sure.
