### ISSUE TITLE
gen_main: flag to specify package name and a flag to omit the `main.go` file

### ISSUE THREAD

**Issue by hectorj2f** [goadesign/goa#1040]
We'd like to generate all the controllers into a specified folder. This is possible at this moment. However, we would like to specify the package name, instead of `main`. Also, we want to omit the generation of the `main.go` file. We need the later cause we want to create our own main file that afterwards imports the controllers from the controller pkg.

**Comment by raphael** [comment]
`gen_main` is meant to be used once when you start a new project. It's not meant to be used continuously. The files it generates are never overridden. It's as if you had written these files - just the tool helps you bootstrap. Adding more configuration to it would be going in the wrong direction in my opinion. If you look at the generated content it almost never changes and when it does it's just a matter of adding a couple of lines to implement the new method / interface or mount the controller.
