### ISSUE TITLE
Add support for grpc regarding code generation

### ISSUE THREAD

**Issue by hectorj2f** [goadesign/goa#1047]
I believe it could be quite useful to provide support for grpc as an alternative to the classic REST/HTTP.

**Comment by raphael** [comment]
Yes this is a big driver behind v2. Closing the issue since that's being worked on.

**Comment by hectorj2f** [comment]
Awesome! thanks @raphael

**Comment by retnuh** [comment]
Hi just wondering what the status of this is?  I'm looking at goa but am much more interested in gRPC than HTTP/Swagger

**Comment by raphael** [comment]
We are just starting the work now, you should see some activity in the `v2` branch soon. The first thing we need to do is come up with a list of tasks and make these public to give visibility. Out of curiosity: if goa generated the proto files and all the transport code would that be enough for you to get started? or do you require the need to also consume existing proto files? (something we are thinking about but would probably come later).

**Comment by retnuh** [comment]
For the moment the generation of proto files would probably be okay, but I can definitely see a future need to consume external protos.   One could argue that it would actually make sense, in many cases, to start with the protos, or have them be "equal partners" to the top-level design...

**Comment by jkchen46034** [comment]
I hate goa. It is anti-go. too complicated. too convoluted. Its making simple things very difficult. And it is not a micro service. so stop.
