### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by tchssk** [goadesign/goa#1059]
Implemented in pacakges at

- https://github.com/goadesign/goa/tree/v2/codegen
- https://github.com/goadesign/goa/tree/v2/cmd/goagen

**Comment by tchssk** [comment]
Please add `v2` label and `Version 2` project to this issue. @raphael

**Comment by raphael** [comment]
Added the v2 label. How do you want me to link this issue from the project? I think you need to create issues from tasks, not the other way around but maybe there is something I don't know...

**Comment by tchssk** [comment]
I think we should discuss the design of the generator's core in this issue. I will divide Individual tasks per plugins such as `gen_app` and `gen_client`.

You can link the project as you like because I can see it but can't edit it.

**Comment by raphael** [comment]
Closing this old issue.
