### ISSUE TITLE
about error message customize

### ISSUE THREAD

**Issue by syama666** [goadesign/goa#1076]
Hi
I want to ask about the error object generated after parameter (or attribute) validation.

for example (issune #473),
if overriding the goa error package variables, 
there is no way to override the message `"%s must match the regexp %#v but got value %#v` (in goa.InvalidPatternError func) .
Is there any way?

**Comment by raphael** [comment]
You can do it by checking the message in your `ErrInvalidRequest` implementation, for example:
```go
goaHandler := goa.ErrInvalidRequest
goa.ErrInvalidRequest = func(message interface{}, keyvals ...interface{}) error {
    s, ok := message.(string)
    if !ok {
        return goaHandler(message, keyvals...)
    }
    switch {
        case strings.Contains(s, "must match the regexp"):
           return &ErrorResponse{} // ... initialize response as you wish
        case // other checks...
        default:
            return goaHandler(message, keyvals...)
    }
}
```

**Comment by beeant** [comment]
How can I do overriding in goa? for example, where should I put the code example that you mentioned above?

**Comment by beeant** [comment]
@raphael How can I do overriding in goa? for example, where should I put the code example that you mentioned above?

**Comment by raphael** [comment]
In main when configuring the service.

**Comment by beeant** [comment]
@raphael thank you very much!

**Comment by beeant** [comment]
@raphael 

if I do the one above the response will be merged in detail, I can't pass meta.
for example:

```go
goa.ErrInvalidRequest = func(message interface{}, keyvals ...interface{}) error {
    ...
    return &goa.ErrorResponse{Code: "bad_reque", Meta: map[string]interface{}{"Test": "test"}}
}
```

it gives me this response:

```json
{
  "id":"01lFG5ef",
  "code":"bad_request",
  "status":400,
  "detail":"[] 0 bad_request: , Test: test"
}
```

How can I make it be like this:

```json
{
  "id":"01lFG5ef",
  "code":"bad_request",
  "status":400,
  "detail":"",
  "meta": {
    "Test": "test"
  }
}
```

**Comment by beeant** [comment]
I figured this out

**Comment by fuatto** [comment]
How did you cross out the [] 0 bad_request: part in the detail @beeant ? It would be great if you suggest the solution
