### ISSUE TITLE
How do i Unmarshal a *string type, getting error when dereference

### ISSUE THREAD

**Issue by lundin** [goadesign/goa#1082]
Hi!

Any insight on what am i doing wrong here.

Simple code with an POST endpoint
```
var _ = Resource("autodata", func() {
        BasePath("/autodata")
	DefaultMedia(AutodataMedia)
        Action("createpdf", func() {
                Routing(POST(""))
                Description("Returns a schema PDF")
                Params(func() {
                        Param("serviceschema",String, "Service Schema")
			Param("customerno", Integer, "Customerno")
                        Param("customername", Integer, "Customername")
                })
                Response(OK)                       
                Response(NotFound)
        })

 })
```
In a custom controller:
 ```
  s:=*ctx.Serviceschema
    if err := json.Unmarshal([]byte(s), &Autodatacontent); err != nil {
       return ctx.NotFound()
    }
```
sending raw json body with postman.

err="panic: runtime error: invalid memory address or nil pointer dereference\npanic(0x812fc0, 0xc42000c0c0)\n\t/usr/local/go/src/runtime/panic.go:458 +0x243\nreports/controllers.(*AutodataController).Createpdf(0xc420160a10, 0xc4201aca80, 0x0, 0x0)\n\t/appl/src/reports/controllers/controllers.go:122

Can i use type String for sending raw (nested) json ?

**Comment by raphael** [comment]
Yes you can use a string to send raw JSON. `Params` define query string parameters though - not request body. Use `Payload` to define the shape of the request body (see https://goa.design/design/overview/).
Also you may want to use `Required` to specify required fields (so they won't be generated as pointers in the first place). Finally you can use `service_schema`, `customer_no` and `customer_name` as attribute names to get nicer field names in the generated code.

**Comment by lundin** [comment]
Thanks for the heads up Raphael, very helpful info with the payload! Works like a charm!
For anyone else reading, i had a nested json and sended it as "Any" type and then
b, err := json.Marshal(payload.Serviceschema)
