### ISSUE TITLE
ErrConflict

### ISSUE THREAD

**Issue by nicholaswyoung** [goadesign/goa#1100]
Would it make sense to add a helper for [`goa.ErrConflict`](https://github.com/goadesign/goa/blob/master/error.go#L46), like `ErrBadRequest` etc? I find that I'm often creating 409 errors, and this addition would clean up my controllers a bit.

**Comment by raphael** [comment]
Thank you for the suggestion, the idea is for user code to define the error class they need that may not be defined in goa. goa cannot list all the possible errors. The list in goa are errors that goa itself (generated code and middlewares) depends on.
