### ISSUE TITLE
Integration with Gorilla websocket implementation

### ISSUE THREAD

**Issue by tpoxa** [goadesign/goa#1109]
[godoc.org/golang.org/x/net/websocket](https://godoc.org/golang.org/x/net/websocket)

> This package currently lacks some features found in an alternative and more actively maintained WebSocket package:

https://godoc.org/github.com/gorilla/websocket

Any plans to integrate it to goa.design?
Thank you!

**Comment by raphael** [comment]
I would happily accept a PR that does that :)

**Comment by tpoxa** [comment]
Unfortunately I cannot handle such work. Its still too difficult for me.
