### ISSUE TITLE
String Param Length Limited to 100 Characters

### ISSUE THREAD

**Issue by gavinwade12** [goadesign/goa#1113]
I noticed that when passing a string as a param, header, or field in the payload, the input is cut off at 100 characters. The logger will show the entire value, but by the time it hits any middleware or a controller, the value is shortened.

To recreate this issue, just spin up the goadesign/goa-cellar project and create a bottle with this payload:

```
{
	"name": "OneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTen",
	"vineyard": "name is greater than 100",
	"varietal": "name is greater than 100",
	"vintage": 1901,
	"color": "red",
	"sweetness": 1,
	"country": "name is greater than 100",
	"region": "name is greater than 100",
	"review": "name is greater than 100"
}
```

You'll notice the bottle that is saved will have the name: `"OneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSixSevenEightNineTenOneTwoThreeFourFiveSix"`.

I can't seem to find where this is happening in the goa source code.

**Comment by raphael** [comment]
Could you add a quick comment as to why you closed this issue? was this something in your code?

**Comment by gavinwade12** [comment]
I apologize. After tons of debugging time, I tried on the goa-cellar project and had this happening to me there as well. That's why I started the issue. I use Gogland for development, and it was leading us to believe the issue was related to goa. Instead, it was Gogland itself that possessed the issue.

**Comment by raphael** [comment]
no need to apologize! good to know, thank you.
