### ISSUE TITLE
goagen/gen_controller is not included into v1.1.0

### ISSUE THREAD

**Issue by hectorj2f** [goadesign/goa#1115]
Hi there,

We didn't find `gen_controller` in v1.1.0. We are using it in our code generation. 
Why isn't it in there :( ?

**Comment by raphael** [comment]
`v1.1.0` is a tag to a fixed commit. Follow the `v1` branch if you want the latest `v1`. `v1.2.0` to be released next month will include everything in the `v1` branch up to the release day.

**Comment by hectorj2f** [comment]
Awesome @raphael! +1. I'll keep one eye to migrate to `v1.2.0`
