### ISSUE TITLE
gen_controller: Specify app package path

### ISSUE THREAD

**Issue by brycereitano** [goadesign/goa#1117]
Currently you can specify the package name, and will assume you have an `app` package at the present working directory. Ideally, you should be able to specify where the `app` package resides. Helpful when you are changing the output directory of `gen_controller`, possibly `gen_main` as well.

**Comment by raphael** [comment]
The `--app-pkg` flag of the `controller` command now accepts a Go import path. The import path can be absolute or relative so that the default is still just `app`.
