### ISSUE TITLE
Generated code can't be compiled when using Metadata("struct:field:type")

### ISSUE THREAD

**Issue by van491018** [goadesign/goa#1131]
Hi, I'm another user trying to use Metadata("struct:field:type", "json.RawMessage") for attributes in payload. I found that goagen can't generate right type for such attributes in private user type. I have a design with this code snippet:

```
var **** = Type("******", func() {
    Attribute("data", Any, "", func() {
        Metadata("struct:field:type", "json.RawMessage", "encoding/json")
    })
})
```

There're two user type in generated user_types.go:
```
type exampleType struct {
    Data json.RawMessage `json:"data,omitempty"`
}

type ExampleType struct {
    Data json.RawMessage `json:"data"`
}
```

But Publicize() want to assign dereference of Data in exampleType to Data in ExampleType:
```
pub.Data = *ut.Data
```

**Comment by raphael** [comment]
@JKhawaja seems like the private field should be generated with a pointer, care to take a look? (I know it's not necessary in this case since `json.RawMessage` is a slice but it will work and will wok in the most general case where the custom type could be a struct as well).

**Comment by JKhawaja** [comment]
The pointer code is fixed. I can push that alone in a PR if we would like. The only other thing that needs to be changed (that I still need to get around to) is making sure that validation code is not generated on attributes that use the metadata tag.

**Comment by JKhawaja** [comment]
If @van491018 can confirm that his generated code builds properly  now (after a `go get -u github.com/goadesign/goa/... `) then this issue can probably be closed.

**Comment by van491018** [comment]
It works. Thank you!
