### ISSUE TITLE
Receiving an Error When Calling goagen

### ISSUE THREAD

**Issue by kmacmcfarlane** [goadesign/goa#1132]
I recently re-installed my development environment, and now I get an error when running goagen on my design files.

I am invoking like this:
`$ goagen bootstrap -d bitbucket.org/lockwobr/healthconnect/healthconnect/design`

The error I am getting:
`_=E:/work/bin/goagenexit status 1
missing API definition, make sure design is properly initialized`

It looks like the design.Design pointer in github.com/goadesign/goa/design must be null when the Generator object is created. How that pointer get's assigned to, I cannot determine from reading through the code briefly.

What other information can I get to help solve this issue?

When I run it with debug, here's my environment:
`** Code generator source dir: E:\work\src\bitbucket.org\lockwobr\healthconnect\healthconnect\goagen822954759
** Compiling with:
ACLOCAL_PATH=C:\Program Files\Git\mingw64\share\aclocal;C:\Program Files\Git\usr\share\aclocal
ALLUSERSPROFILE=C:\ProgramData
ANSICON=156x1000 (156x53)
ANSICON_DEF=7
APPDATA=C:\Users\rt\AppData\Roaming
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-4IGPDOA
COMSPEC=C:\Windows\system32\cmd.exe
CONFIG_SITE=C:/Program Files/Git/mingw64/etc/config.site
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
ConEmuANSI=ON
ConEmuAnsiLog=
ConEmuArgs2=
ConEmuArgs=
ConEmuBackHWND=0x0008075C
ConEmuBaseDir=C:\Program Files\ConEmu\ConEmu
ConEmuBuild=161206
ConEmuConfig=
ConEmuDir=C:\Program Files\ConEmu
ConEmuDrawHWND=0x00040814
ConEmuDrive=C:
ConEmuHWND=0x000B07B0
ConEmuHooks=Enabled
ConEmuPID=13668
ConEmuPalette=<Tomorrow Night Blue>
ConEmuServerPID=1700
ConEmuTask={Bash::Git bash}
ConEmuWorkDir=E:\work\src\bitbucket.org\lockwobr\healthconnect\healthconnect
ConEmuWorkDrive=E:
DISPLAY=needs-to-be-defined
EXEPATH=C:\Program Files\Git
GOPATH=e:\work\
GOROOT=C:\Go\
HOME=C:\Users\rt
HOMEDRIVE=C:
HOMEPATH=\Users\rt
HOSTNAME=DESKTOP-4IGPDOA
INFOPATH=C:\Program Files\Git\usr\local\info;C:\Program Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program Files\Git\share\info
INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
LANG=en_US.UTF-8
LOCALAPPDATA=C:\Users\rt\AppData\Local
LOGONSERVER=\\DESKTOP-4IGPDOA
MANPATH=C:\Program Files\Git\mingw64\share\man;C:\Program Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program Files\Git\usr\man;C:\Program Files\Git\share\man
MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\intel64_win_mic
MINGW_CHOST=x86_64-w64-mingw32
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
MINGW_PREFIX=C:/Program Files/Git/mingw64
MSYSTEM=MINGW64
MSYSTEM_CARCH=x86_64
MSYSTEM_CHOST=x86_64-w64-mingw32
MSYSTEM_PREFIX=C:/Program Files/Git/mingw64
NUMBER_OF_PROCESSORS=8
ORIGINAL_PATH=C:\Program Files\Git\cmd;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\PuTTY;C:\Program Files\Git\cmd;E:\androidsdk\platform-tools;E:\androidsdk\tools\bin;C:\Program Files\MongoDB\Server\3.4\bin;E:\Exe\nodejs;C:\Users\rt\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\rt\AppData\Roaming\npm
ORIGINAL_TEMP=C:/Users/rt/AppData/Local/Temp
ORIGINAL_TMP=C:/Users/rt/AppData/Local/Temp
OS=Windows_NT
OneDrive=C:\Users\rt\OneDrive
PATH=C:\Users\rt\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\PuTTY;C:\Program Files\Git\cmd;E:\androidsdk\platform-tools;E:\androidsdk\tools\bin;C:\Program Files\MongoDB\Server\3.4\bin;E:\Exe\nodejs;C:\Users\rt\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\rt\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl;E:\Exe\MinGW\bin;E:\Exe\nodejs;C:\Go\bin;E:\work\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PKG_CONFIG_PATH=C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program Files\Git\mingw64\share\pkgconfig
PLINK_PROTOCOL=ssh
PRINTER=HP Officejet 7200 series
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
PROGRAMFILES=C:\Program Files
PS1=\[\033]0;$TITLEPREFIX:${PWD//[^[:ascii:]]/?}\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PWD=E:/work/src/bitbucket.org/lockwobr/healthconnect/healthconnect
ProgramData=C:\ProgramData
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
SESSIONNAME=Console
SHELL=C:\Program Files\Git\usr\bin\bash.exe
SHLVL=1
SSH_ASKPASS=C:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\rt\AppData\Local\Temp
TERM=cygwin
TMP=C:\Users\rt\AppData\Local\Temp
TMPDIR=C:\Users\rt\AppData\Local\Temp
USERDOMAIN=DESKTOP-4IGPDOA
USERDOMAIN_ROAMINGPROFILE=DESKTOP-4IGPDOA
USERNAME=rt
USERPROFILE=C:\Users\rt
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
WINDIR=C:\Windows`

**Comment by raphael** [comment]
Please make sure you have the latest and try removing the vendor directory if there is one. Typically this happens if the `design` package used when running the DSL is not the same as the one used by the code generators (one is vendored - the other isn't). If that's the problem you could try running `goagen` from a different location with no `vendor` directory or you could generate programmatically as is described [here](https://goa.design/design/vendoring/).

**Comment by kmacmcfarlane** [comment]
Thank you! That did the trick :-)
