### ISSUE TITLE
Resource inheritance child inherits query string params

### ISSUE THREAD

**Issue by lockwobr** [goadesign/goa#1137]
I am running into a bug I believe were if you add parent relationship to a resource it is inheriting query params.

Example: User is parent.

     Action("show", func() {
		Routing(
			GET("/:UserId"),
		)
		Description("Retrieve account with given id.")
		Params(func() {
			Param("UserId")
			Param("view", String, "Which view of user would you like?", func() {
				Default("default")
				Enum("default", "short")
			})
		})
		Response(OK)
		Response(NotFound)
	})

Swagger yaml output were balance is child of user, and you can see view param is in there.

    /api/user/{UserId}/balance:
    get:
      description: Retrieve account with given id.
      operationId: Balance#show
      parameters:
      - description: Unique user ID
        in: path
        name: UserId
        required: true
        type: integer
      - default: default
        description: Which view of user would you like?
        enum:
        - default
        - short
        in: query
        name: view
        required: false
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaBalance'
        "204":
          description: No Content
      schemes:
      - http
      summary: show Balance
      tags:
      - Balance

I guess for reference here is part of my vendor file so you track the version I am using. Might be over kill but.

       		{
			"checksumSHA1": "Sf/0bt+aQfG4ng+Y061mu37KegI=",
			"path": "github.com/goadesign/goa/cors",
			"revision": "148222cf85d4578a0cfc591bd0c943d11d3038dd",
			"revisionTime": "2017-02-22T20:45:24Z"
		},
		{
			"checksumSHA1": "kv/fDGC+gKkUH9c0dviifYmHAIk=",
			"path": "github.com/goadesign/goa/design",
			"revision": "148222cf85d4578a0cfc591bd0c943d11d3038dd",
			"revisionTime": "2017-02-22T20:45:24Z"
		},
		{
			"checksumSHA1": "4XSXzkn+NcsVpXlIIyNVhp9dehk=",
			"path": "github.com/goadesign/goa/design/apidsl",
			"revision": "148222cf85d4578a0cfc591bd0c943d11d3038dd",
			"revisionTime": "2017-02-22T20:45:24Z"
		},
		{
			"checksumSHA1": "FJv1gV2WiyoZ+lqyprF43ul2OtI=",
			"path": "github.com/goadesign/goa/dslengine",
			"revision": "148222cf85d4578a0cfc591bd0c943d11d3038dd",
			"revisionTime": "2017-02-22T20:45:24Z"
		},
		{
			"checksumSHA1": "FnnFoOzCq0BmE92D4L6HZxGRcDc=",
			"path": "github.com/goadesign/goa/goagen/codegen",
			"revision": "148222cf85d4578a0cfc591bd0c943d11d3038dd",
			"revisionTime": "2017-02-22T20:45:24Z"
		},
               {
			"checksumSHA1": "Vxh5toX3tGFA/6UPZ9tFrPORx8k=",
			"path": "github.com/goadesign/goa/goagen/gen_swagger",
			"revision": "148222cf85d4578a0cfc591bd0c943d11d3038dd",
			"revisionTime": "2017-02-22T20:45:24Z"
		},

**Comment by raphael** [comment]
Thanks for the report, it should be fixed in both `master` and `v1`. Can you verify and close the issue if that's the case? Thanks!

**Comment by lockwobr** [comment]
Tested in v1 and the is fixed. Thanks!
