### ISSUE TITLE
Allow passing argument to ctx.Found()

### ISSUE THREAD

**Issue by eladitzhakian** [goadesign/goa#1149]
AFAIK the only way to redirect a client right now is like:
```
ctx.ResponseData.Header().Set("Location", "/some/path")
return ctx.Found()
```
Could be nicer to just pass the URL to `ctx.Found()` instead of explicitly setting the header

**Comment by raphael** [comment]
Thanks for the suggestion, this requires a little bit of thinking to make sure it fits with how the DSL and design works. I'll leave it as an enhancement request.
