### ISSUE TITLE
InvalidRangeError assumes integer values

### ISSUE THREAD

**Issue by RobertHenry6bev** [goadesign/goa#1150]
https://github.com/goadesign/goa/blob/master/error.go#L216
prints an error message where the reported value is formatted with %d, but the reported value (an interface{}) is given as a float64.  Needless to say the fmt.Sprintf complains dynamically; the output contains the info needed, but it is embedded in printf warning messages.

The Type of the Payload I've specified to the POST handler is given as "Number", with Minimum and Maximum values given as float64s.

I haven't looked at other places in the goa library code where the same mistake might also crop up.

**Comment by raphael** [comment]
Thanks for the report! At first glance that seems to be the only place with the problem. Would you care making a PR that changes the `%d` to `%v`?
