### ISSUE TITLE
About array  as query parameter

### ISSUE THREAD

**Issue by syama666** [goadesign/goa#1151]
Hi,

Query parameters as arrays are expressed as comma separated values on swagger doc, but if you actually throw a request, it will be treated as Badrequest.
Is this a specification?
If so, is there a mismatch with swagger?

e.g.) 
http://swagger.goa.design/?url=github.com/goadesign/goa-cellar/design#!/bottle/bottle_list
```
# bad request
$ curl "http://cellar.goa.design/cellar/accounts/1/bottles?years=123%2C456"
$ {"id":"iDcckUji","code":"invalid_request","status":400,"detail":"invalid value \"123,456\" for parameter \"years\", must be a integer","meta":[{"param":"years"},{"value":"123,456"},{"expected":"integer"}]}

# ok
$ curl "http://cellar.goa.design/cellar/accounts/1/bottles?years=123&years=456"
$ []
```

In my personal request,
As expressed by swagger, please pass it by comma and map to array.

regards

**Comment by tchssk** [comment]
It seems a bug of https://github.com/goadesign/swagger-service-ui and goa is working fine.

Would you try to request like below?

```sh
$ curl "http://cellar.goa.design/cellar/accounts/1/bottles?years=2011&years=2012"
```
