### ISSUE TITLE
Resource Params are not being generated

### ISSUE THREAD

**Issue by Tri125** [goadesign/goa#1155]
Version: c1d4a590f58755a969f6e3f61ec5a4548ef7b6b0

I have some params defined for a resource and they don't seems to be generated when running goagen.
They are absent from the context.go file and also from the swagger definition.

 In Release v1.1.0 the design was correctly generating the params.
Here's a small snippet of the design file:

```
var _ = Resource("card", func() {
	DefaultMedia(CardMedia)
	BasePath("/v0/cards")

	Response(InternalServerError)

	Params(func() {
		Param("limit", Integer, func() {
			Description("Number of cards to receive")
			Minimum(1)
			Default(20)
		})
		Param("offset", Integer, func() {
			Description("Offset of the starting count")
			Default(0)
			Minimum(0)
		})
	})

	Action("list", func() {
		Routing(GET(""))
		Description("Return a page of cards.")
		Params(func() {
			Param("name", String, "Query")
		})
		Response(OK, PageCard)
		Response(NotFound)
	})
})
```

**Comment by raphael** [comment]
Thanks for the report! This is indeed a regression that was introduced by #1144. This is fixed in #1158 with the additional missing tests.
