### ISSUE TITLE
How to declare a map from string to json.RawMessage?

### ISSUE THREAD

**Issue by van491018** [goadesign/goa#1168]
Is there a way to declare a map from string to json.RawMessage? I tried to do this with following code snippet when I came across such a scenerio:
```
var valueType = Type("abc", func() {
   Metadata("struct:field:type", "json.RawMessage", "encoding/json")
})
var someType = HashOf(String, valueType)
```
But goagen generates an empty struct. So I am wondering whether there is a function in apidsl which specify metadata for type. Can you tell me the right way to do this?

How to specify example for HashOf() and ArrayOf()?

**Comment by raphael** [comment]
https://github.com/goadesign/goa/pull/1171 adds the ability to use DSLs when defining `Hash` attributes. #1169 makes it possible to specify `struct:field:type` metadata in array and hash DSLs. So with the latest master and v1 you can now do:
```go
var someType = HashOf(String, String, func(){},func() {
    Metadata("struct:field:type", "json:RawMessage", "encoding/json")
})
```
Please give it a shot and if it works close the issue, thanks!

**Comment by van491018** [comment]
It works. Thank you!
