### ISSUE TITLE
How do goa support TLS when design? 

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#1183]
Does Goa support TLS?

I use code:

```
var _ = API("xwechatser", func() {
	Title("The weiapp server API")
	Description("The weiappser server API design")
	Host("localhost:443")

	Scheme("https")
	Version("v1")
})
```

But the main.go is 

```
func main() {
	// Create service
	service := goa.New("xwechatser")

	// Mount middleware
	service.Use(middleware.RequestID())
	service.Use(middleware.LogRequest(true))
	service.Use(middleware.ErrorHandler(service, true))
	service.Use(middleware.Recover())

	// Mount "ListDevice" controller
	c := NewListDeviceController(service)
	app.MountListDeviceController(service, c)

	// Start service
	if err := service.ListenAndServe(":443"); err != nil {
		service.LogError("startup", "err", err)
	}
}
```

How to support HTTPS when design?

**Comment by KerwinKoo** [comment]
I find the define in file service.go:

```
// ListenAndServeTLS starts a HTTPS server and sets up a listener on the given host/port.
func (service *Service) ListenAndServeTLS(addr, certFile, keyFile string) error {
	service.LogInfo("listen", "transport", "https", "addr", addr)
	return http.ListenAndServeTLS(addr, certFile, keyFile, service.Mux)
}
```

But shouldn't it auto generated by goagen command?

**Comment by raphael** [comment]
The proper way to signify HTTP is to use `Scheme("https")` in the design. That being said this still won't generate `ListenAndServeTLS`, I guess it could. Remember though that `main.go` is not generated each time, you have to modify it anyway. What's generated is just a starting point.

**Comment by KerwinKoo** [comment]
@raphael  I'm sorry for the design code example, I supplied it with code 

```
    Scheme("https")
    Version("v1")
```

but the `ListenAndServeTLS` was not generated yet.

By the way, how to use the DSL `Version("v1")` ? I didn't find the usage of it.

**Comment by raphael** [comment]
Like is said above "that being said this still won't generate ListenAndServeTLS". Maybe it could and I would accept a PR that makes that change but again at the end of the day `main.go` is just a starting point / example.
`Version` simply sets the version in the generated swagger, that's all it does.

**Comment by KerwinKoo** [comment]
@raphael Thank you!
