### ISSUE TITLE
Temporarily resolve problems caused by context package for GAE/Go 

### ISSUE THREAD

**Issue by tikasan** [goadesign/goa#1188]
Since GAE / Go currently uses Go version 1.6.x, `golang.org/x/net/context` is the standard package.
Therefore, you need to replace the `context` package with `golang.org/x/net/context`.
https://github.com/containerd/containerd/issues/337

Problem part
https://github.com/goadesign/goa/blob/master/context.go#L8
https://github.com/goadesign/goa/blob/8f0fdca409904318050f9e03579c3878f8928826/context.go#L8

This issue will be solved soon, as GAE / Go is scheduled to upgrade.
So, I'd like to create a branch of GAE / Go temporarily.
Also please tell me whether you need to add that to readme.
And If you have any problems, please propose.

**Comment by raphael** [comment]
Thanks for raising the issue, I had not realized that GAE was still using 1.6. Creating a branch is going to be a lot of work to maintain (having to back port every fix to `v1` is already quite cumbersome - adding one more branch is not going to be practical).

Maybe there could be a script that uses [govers](https://godoc.org/launchpad.net/govers) to swap the import. The script would also have to change the imports that are generated, i.e. revert https://github.com/goadesign/goa/pull/1177.

**Comment by tikasan** [comment]
If you use govers, it certainly can be solved. I decided to add a script for GAE and take countermeasures.

**Comment by raphael** [comment]
Great, do you think the script is worth sharing? Maybe it could be added to the https://github.com/goadesign/examples repo?

**Comment by tikasan** [comment]
If the script is successful, I will share it!

**Comment by tikasan** [comment]
Should that script be created as a command for GAE? or is it a 1.6 compatible script?

**Comment by raphael** [comment]
Maybe there could be a simple GAE example and part of the example is the script to apply with instructions in the README.
