### ISSUE TITLE
missing slash in swagger spec paths (required by the openapi spec)

### ISSUE THREAD

**Issue by zetsub0u** [goadesign/goa#1190]
Generated paths in swagger spec files do not start with a leading "/" (slash), even if they are relative to basePath they should still contain it as per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-fields

This causes issues with some clients incorrectly generating resource urls. In particular bravado doesn't like the specs generated by goa, related to #631, when using absolute url this problem is not present but the missing basePath: "/" is a different issue which also breaks some clients (like bravado).

**Comment by raphael** [comment]
I believe this is now fixed. Can you please confirmed? (#1286 fixed the empty case)
