### ISSUE TITLE
Can OAuth 2.0 authentication be done?

### ISSUE THREAD

**Issue by tikasan** [goadesign/goa#1212]
Can I use goa to use the authentication API of Github OAuth 2.0?
https://developer.github.com/v3/oauth/

Can you give me advice?

**Comment by tikasan** [comment]
I was able to use OAuth.
The redirect was a bit less intuitive and I got lost.

https://github.com/goadesign/goa/issues/1149

**Comment by josephbuchma** [comment]
@pei0804 can you provide an example ?

**Comment by pei0804** [comment]
https://github.com/pei0804/goa-oauth2-practice
This
@josephbuchma

**Comment by josephbuchma** [comment]
@pei0804 thanks !
