### ISSUE TITLE
Requests response time should be converted to an unique time unit 

### ISSUE THREAD

**Issue by hectorj2f** [goadesign/goa#1213]
When collecting the time taken by each request, we get different time units like seconds, milliseconds, nanoseconds. That makes harder to generate plots out of these values. Could we get these times converted to a consistent unit like e.g. milliseconds ?

I refer to the logs `time.Since(startedAt).String()`, that you can find in places such as: `log_request.go` and `client.go`.

**Comment by raphael** [comment]
I'm not sure I agree with that request :-) the intent of logs is to be readable by humans for troubleshooting. Drawing plots should be done using metrics, something like Prometheus, DataDog, NewRelic etc. I would hate to have to read 0.003ms or 21239712ms in logs and have to do the math to understand what that means.

Now while you can replace the middleware logger to do what you need you're stuck with the client struct :( Maybe the request here is to make it possible to override the logging in the client. For example, there could be a client middleware that contains the current behavior but could be overridden.

**Comment by hectorj2f** [comment]
> I'm not sure I agree with that request :-) the intent of logs is to be readable by humans for troubleshooting. Drawing plots should be done using metrics, something like Prometheus, DataDog, NewRelic etc. I would hate to have to read 0.003ms or 21239712ms in logs and have to do the math to understand what that means.

The application logs are data that is consumed by third party tools. If the produced logs provide consistent values, that'd be a benefit for the human and the third party that consumes them.

> Now while you can replace the middleware logger to do what you need you're stuck with the client struct :( Maybe the request here is to make it possible to override the logging in the client. For example, there could be a client middleware that contains the current behavior but could be overridden.

I already did that :). Generally I found difficult to hook the produced logs to add custom fields or adapt the produced ones. Therefore, it'd be great if we can hook the current logs to modify the produced ones.

**Comment by hectorj2f** [comment]
I also thought about passing a logging adapter that implements Info, Error and New functions. However, this adapter is a bit limited cause it might miss some interesting properties such as the context. Also, any customization might require to iterate over all the logging properties and do some plumbing in there.

So, my thoughts go more over on how to hook or replace the existing calls of for instance `goa.LogInfo(...)` with my own logging info functions. @raphael What do you think ?

**Comment by raphael** [comment]
Yes that sounds like a better approach and that is what goa already does: the `LogInfo` and `LogError` methods simply wrap a given logger. Could you implement your own adapter similar to e.g. https://github.com/goadesign/goa/blob/master/logging/log15/adapter.go ?

**Comment by hectorj2f** [comment]
@raphael I agree but the adapter isn't able to access to the current context where many data can be stored per request. That is our situation where the context has some data that we want to log. In the exiting log adapters, they just log the message and the propagated properties

**Comment by raphael** [comment]
OK the idea is to use the `New` `LogAdapter` method to add to the log context but I guess that doesn't work for you? It would be helpful if you could share an example of what you're trying to achieve.

**Comment by hectorj2f** [comment]
@raphael LogInfo receives as input parameter the context but it doesn't propagate it across the log adapter. 
```
func LogInfo(ctx context.Context, msg string, keyvals ...interface{}) {
	if l := ctx.Value(logKey); l != nil {
		if logger, ok := l.(LogAdapter); ok {
			logger.Info(msg, keyvals...)
		}
	}
}
```

For instance in my log info adapter function, I use the context to log additional data:

```
func Info(ctx context.Context, ....) {
                       ....
                        identityID, err := extractIdentityID(ctx)
			if err == nil {
				entry = entry.WithField("identity_id", identityID)
			}
                        ...
}
```
However with the current log adapter, I only receives the message and the key values defined in the LogInfo call.

**Comment by raphael** [comment]
Yeah so to do the above with the `LogAdapter` interface you'd do:
```go
ctx = goa.WithLogContext(ctx, "identity_id", identityID)
// ...
goa.LogInfo(ctx, "log entry")
```
You could do the log context setup in a middleware for example or at the start of a controller.

**Comment by hectorj2f** [comment]
Sorry, I think I didn't explain well the problem in my last comment. We use the logrus adapter that you provide but this one doesn't have any ctx in their input arguments.

```
// Info logs messages using logrus.
func (a *adapter) Info(msg string, data ...interface{}) {
	a.Entry.WithFields(data2rus(data)).Info(msg)
}

// Error logs errors using logrus.
func (a *adapter) Error(msg string, data ...interface{}) {
	a.Entry.WithFields(data2rus(data)).Error(msg)
}
```

Therefore, the logs generated by this adapter won't have the possibility to extract ctx data.

**Comment by raphael** [comment]
Sure they will :) Internally `WithLogContext` calls the `New` method of the adapter (implemented by all adapters since it's a method on the interface) which takes care of adding the key/value pairs. The code I have written above works independently of the logger that backs the adapter.
