### ISSUE TITLE
Attribute type will be covered when using Reference twice. 

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#1223]
In Goa apidsl Media Type design, Key word of `Reference` cannot be used twice simultaneously. Goa will only analyze the latest  `Reference` sentence.

For example:

```golang
var AType = Type("AType", func() {
	Attribute("isOnline", Boolean, "online test")
	Attribute("number", Integer, "number test")

	Required("isOnline", "number")
})

var BType = Type("BType", func() {
	Attribute("ID", Integer, "int ID")

	Required("ID")
})

var TestMedia = MediaType("application/t.test.json", func() {
	Reference(AType)
	Reference(BType)

	TypeName("DeviceMedia")
	Attributes(func() {
		Attribute("number")
		Attribute("isOnline")
		Attribute("ID")

		Required("isOnline", "ID", "number")
	})
	View("default", func() {
		Attribute("isOnline")
		Attribute("ID")
	})

})

```

I  referenced `AType` and `BType` at the same time, because I want reference `isOnline` and `ID` attributes which have defined in two types above. But the struct generated by  running `goagen bootstrap` in `media_types.go` is 

```golang

// DeviceMedia media type (default view)
//
// Identifier: application/t.test.json; view=default
type DeviceMedia struct {
	// int ID
	ID       int    `form:"ID" json:"ID" xml:"ID"`
	IsOnline string `form:"isOnline" json:"isOnline" xml:"isOnline"`
}

```

As we can see, type of `ID` is `int` which defined in  `BType`, but `IsOnline` is `string` type as default attribute type ( is same to `Attribute("isOnline")`  without `Reference(AType)` define). 

Can `Reference`  be used more than once in single `MediaType` define? If I want reference more than one `Type` or `MedaiType`, how do it? If no way or not recommend to using many times, could Goa throw errors when using `goagen`?

I think `Reference` or some other methods to support reference more than one `Type` at the same time will be awesome.

**Comment by raphael** [comment]
I understand the need for it, there has been a few rare occasions when I wished that was possible. However it would be a lot of added complexity both in the implementation but more importantly for users. Specifically you would have to decide of rules for when multiple "reference" types define the same attribute. If you make it forbidden then you make the experience fairly frustrating when the issue occur, if you decide that "the first" (has to be defined carefully) wins then a simple typo could have bad consequences that wouldn't be obvious (things would generate just fine). So in the end it seems like a case where simplicity wins over functionality. Yes it means you sometimes have to repeat attributes but in my experience that hasn't happened a lot (you can always introduce an intermediary type which has the duplication and use that everywhere). Maybe I'm missing a use case though so I'd be curious to know if that has been your experience too.
