### ISSUE TITLE
Null Scopes From Bearer Token

### ISSUE THREAD

**Issue by fluffybonkers** [goadesign/goa#1228]
I am having an issue with the bearer token submitted to my controllers returning "authorization failed" because of "scopes:null" using Postman. I am using Auth0 for authentication. The exact error in Postman is:

`{"id":"xOUR882s","code":"jwt_security_error","status":401,"detail":"authorization failed: required 'scopes' not present in JWT claim","meta":{"required":["read:meta"],"scopes":null}}`

However, my token does include the required scope `read:meta`. [jwt.io](url) gives back the following decoded bearer:

```
{
  "iss": "https://learnlogic.au.auth0.com/",
  "sub": "exJMkK7hXX56lrLwoTqna3s0jh7Gq67e@clients",
  "aud": "https://api.learn-logic.com",
  "exp": 1494855336,
  "iat": 1494768936,
  "scopes": "read:meta"
}
```
I am hoping someone can help me workout why, as I don't really understand what is going on in `middleware/jwt.go`.

I have the following `main.go` code:

```
b, err := ioutil.ReadFile("util/jwt.key")
	if err != nil {
		return
	}

	block, _ := pem.Decode([]byte(b))
	var cert *x509.Certificate
	cert, _ = x509.ParseCertificate(block.Bytes)
	rsaPublicKey := cert.PublicKey.(*rsa.PublicKey)
	fmt.Println(rsaPublicKey.N)
	fmt.Println(rsaPublicKey.E)
	fmt.Println(cert)

	var keyx = []jwt.Key{rsaPublicKey}

	var jwtResolver = jwt.NewSimpleResolver(keyx)

	app.UseJWTMiddleware(service, jwt.New(jwtResolver, nil, app.NewJWTSecurity()))
```

The certificate I am reading in is the same one used in [jwt.io](url) to decode the bearer token.

Any help is much appreciated.

**Comment by raphael** [comment]
If you log the content of `claims` after the line below what do you get?

https://github.com/goadesign/goa/blob/master/middleware/security/jwt/jwt.go#L163

Maybe @xeger has a better idea :)

**Comment by xeger** [comment]
Based on my reading of `jwt.go` and of `parseClaimScopes`, the only possible condition that could generate that error message, would be if your token were present, well-formed and signed by a valid key, but were missing a `scopes` claim. I know that it isn't, in the example you provided, but it may be that the token your service is receiving at runtime is somehow different. Suggest logging or printing the contents of `claims`to make sure that the scopes are present, and that they use the exact claim name of `"scopes"`.

**Comment by fluffybonkers** [comment]
It appears to work on Windows if I change  [](https://github.com/goadesign/goa/blob/master/middleware/security/jwt/jwt.go#L167)

to "scope" to match the JWT given back by Auth0. Is there no standard for naming scopes in JWT i.e. "scope" vs. "scopes"?

**Comment by xeger** [comment]
Correct; there are a number of OAuth extensions that describe how to receive JWTs via OAuth, or how to use a JWT as an OAuth credential -- but the contents _of_ JWTs, as they pertain to OAuth concepts, are deliberately left as an opaque implementation detail that will vary between providers.

If you think about it, the same applies to the concept of "scope" in the overall standard -- OAuth 2.0 doesn't really define a notation or semantic for scope; it just as a placeholder parameter and leaves providers to specify their own. So, it follows that the standard is not prescriptive about how to embed scope in JWTs.
