### ISSUE TITLE
Invoked Goagen requires to be ran from GOPATH or a subdirectory (Windows Command Shell)

### ISSUE THREAD

**Issue by dtrehas** [goadesign/goa#1229]
According to goagen help
...
Flags:
.....
  -d, --design string   design package import path
  -o, --out string      output directory (default ".")t

So if goagen is invoked and we are **not** inside the %GOPATH% (e.g. one directory higher)
**goagen bootstrap -d blablah/design -o %GOPATH%\src\blahblah**

it complains.
If I previously type 
**cd %GOPATH%**
**goagen bootstrap -d blablah/design -o %GOPATH%\src\blahblah**

There is no problem.

Is this behaviour by accident?

**Specifically**
**(1st try)**
C:\Prog\proj>cd %GOPATH%

C:\Prog\proj\gopath>cd ..

C:\Prog\proj>goagen bootstrap -d design -o %GOPATH%\src\blahblah
Go source file "C:\Prog\proj\goagen395299283\design" not in Go workspace, adjust GOPATH C:\Prog\proj\gopath
**(2nd try)**
C:\Prog\proj>cd %GOPATH%

C:\Prog\proj\gopath>goagen bootstrap -d design -o %GOPATH%\src\blahblah
src\blahblah\app
.(IT WORKS!)
.
.

Thank you in advance.

**Comment by raphael** [comment]
Can you provide the output of `goagen` when it fails?
