### ISSUE TITLE
CORS and caching

### ISSUE THREAD

**Issue by matteosuppo** [goadesign/goa#1234]
I have a funny problem with cors (which is only tangentially relavant to goa, but maybe goa has the solution).

Basically using the regex validation for Origin the api reply with 

`Access-Control-Allow-Origin: https://my-website-that-matches`

Unfortunately browsers cache these requests, and try to reuse them across websites (even if I tell them not to cache, because they are bad).

So I wondered... what if I returned `Access-Control-Allow-Origin: *` if an origin matches the regex rule?
Would there be security issues I can't see?

Here's the relevant code: https://github.com/goadesign/goa/blob/master/goagen/gen_app/writers.go#L749

**Comment by raphael** [comment]
That seems fine but I would like to understand the problem better first :) What is the browser caching exactly? Can you provide an example of a request/response sequence that shows the issue?

**Comment by matteosuppo** [comment]
All our sites call the users api when you are logged.

So if you go to https://store.arduino.cc this happens (which is fine)

```
Request Headers
:method:GET
:path:/v1/users/byID/me?scopes=public
authorization:Bearer dHM4NUgRIkxI9VWvSuH8
origin:https://store.arduino.cc
```
```
Response Headers
access-control-allow-credentials:true
access-control-allow-origin:https://store.arduino.cc
content-length:201
content-type:application/vnd.arduino.user+json
date:Tue, 23 May 2017 19:49:10 GMT
server:nginx/1.13.0
status:200
```

Then I go to https://forum.arduino.cc and this happens (still fine)

```
Request Headers
:method:GET
:path:/v1/users/byID/me?scopes=public
authorization:Bearer cPnBszRPbnqIeBXbLVZGyc35UL
origin:https://forum.arduino.cc
```
```
Response Headers
access-control-allow-credentials:true
access-control-allow-origin:https://forum.arduino.cc
content-length:201
content-type:application/vnd.arduino.user+json
date:Tue, 23 May 2017 19:49:33 GMT
server:nginx/1.13.0
status:200
```

Then I click the back button on the browser and this happens:

```
Request URL:https://auth.arduino.cc/v1/users/byID/me?scopes=public
Request Method:GET
Status Code:200  (from disk cache)
```
```
Request Headers
Provisional headers are shown
Accept:*/*
Authorization:Bearer dHM4NUgRIkxI9VWvSuH8
Origin:https://store.arduino.cc
```
```
Response Headers
access-control-allow-credentials:true
access-control-allow-origin:https://forum.arduino.cc
content-length:201
content-type:application/vnd.arduino.user+json
date:Tue, 23 May 2017 19:49:33 GMT
server:nginx/1.13.0
status:200
```

And I get 

```
XMLHttpRequest cannot load https://auth.arduino.cc/v1/users/byID/me?scopes=public. The 'Access-Control-Allow-Origin' header has a value 'https://forum.arduino.cc' that is not equal to the supplied origin. Origin 'https://store.arduino.cc' is therefore not allowed access.
```

**Comment by raphael** [comment]
Thank you, I was able to repro following your steps.... One more question: I don't see the "Vary" header in the response, is that because the origin policy in the design uses `"*"`? If that's the case then it seems the code should write `"*"` in the response header (but only when the policy specifies `*`).
