### ISSUE TITLE
Server does not exit upon canceling content

### ISSUE THREAD

**Issue by dtoubelis** [goadesign/goa#1240]
I'm trying to cleanly shutdown the server by calling `CancelAll()` method but the server does not exit. So, what is the proper way to shut it down? Here is my code:

```go
// Run executes the service
func Run(ctx context.Context, l net.Listener) error {

	// Create service
	service := goa.New("events")

	// Mount middleware
	service.Use(middleware.RequestID())
	service.Use(middleware.LogRequest(true))
	service.Use(middleware.ErrorHandler(service, true))
	service.Use(middleware.Recover())

	// Mount "events" controller
	c1 := controller.NewEventsController(service)
	app.MountEventsController(service, c1)

	c := make(chan error, 1)
	go func() {
		c <- service.Serve(l)
	}()

	select {
	case <-ctx.Done():
		service.CancelAll()
		<-c
		return ctx.Err()
	case err := <-c:
		return err
	}
}
```

The idea is that when the parent `context` is cancelled the `Run()` function must exit but it seems but it seems calling `CancelAll()` on the server does nothing and I see no other method to shut it down. I'm using `go-1.6`.

**Comment by raphael** [comment]
`CancelAll` simply calls `Cancel` on the context of requests currently in-flight, it doesn't affect the server. With Go 1.6 you can implement graceful shutdown as shown in this example: https://github.com/goadesign/examples/tree/master/graceful
With Go 1.8 the stdlib HTTP server supports graceful shutdown.

**Comment by dtoubelis** [comment]
If this is design limitation then I can certainly find another way. Thanks for clearing this out.

**Comment by raphael** [comment]
Yes it is outside of the scope of what goa provides. Closing the issue.
