### ISSUE TITLE
Pass parent `context` to `Serve()` method and it friends

### ISSUE THREAD

**Issue by dtoubelis** [goadesign/goa#1241]
It would be nice to be able to pass parent `context` (or `nil`) to `goa.Serve()` method that server shuts itself down when parent content is cancelled (`ServeWithContext()` would be a sensible name for the method). It seems that server already uses `context` internally, so being able to pass parent `context` to it just makes a lot of sense.

**Comment by raphael** [comment]
There is no simple way to implement graceful shutdown of the HTTP server in Go versions up to 1.8. There are entire libraries dedicated to implementing support for it such as https://github.com/tylerb/graceful. In [1.8](https://golang.org/doc/go1.8#http_shutdown) one can take advantage of the new [Server.Shutdown](https://golang.org/pkg/net/http/#Server.Shutdown) (and [Server.Close](https://golang.org/pkg/net/http/#Server.Close)) methods to implement this. In all cases though this is outside of the scope of what goa provides. goa implements the router / middleware support and relies on the Go stdlib to provide the server.

**Comment by dtoubelis** [comment]
Noted, Thanks.

**Comment by raphael** [comment]
Closing the issue.
