### ISSUE TITLE
[Question] Default JSON Responses

### ISSUE THREAD

**Issue by patrickml** [goadesign/goa#1269]
How can you create default responses for things like 404 not found that can return some kind of JSON, so that clients don't have parsing errors? Right now 404 is just returning an empty response.

**Comment by raphael** [comment]
One way to do this would be to define a response explicitly for it:
```
var ResponseType = MediaType(...)

Response("Missing", func() {
    Description("This is the 404 response")
    Status(404)
    Media(ResponseType)
})
```
For more details please take a look at https://goa.design/design/overview/ specifically the "Defining Responses" section.

**Comment by raphael** [comment]
Closing this for now, please re-open if you still have an issue.
