### ISSUE TITLE
[Proposal]Change lint tool

### ISSUE THREAD

**Issue by tikasan** [goadesign/goa#1278]
I always use goa. And they do a good job.

This time there are proposals around the development environment.
Currently, goimports and golint are executed individually.
Using them with alecthomas / gometalinter makes it easier to change.
https://github.com/alecthomas/gometalinter

I am ready to replace it.
https://github.com/tikasan/golint

**Comment by raphael** [comment]
I'm wondering if this is really better because it's adding a dependency on a third party package rather than using the built-in golint and golang goimport packages. Is there something that does not work or is painful with the current approach?

**Comment by tikasan** [comment]
If there is no particular plan to add lint from the current situation, there are not many merits.

**Comment by raphael** [comment]
OK yeah I think it's fine as is, thank you for the suggestion though!
