### ISSUE TITLE
Lookup should treat url path parameter

### ISSUE THREAD

**Issue by azihsoyn** [goadesign/goa#1279]
I'm using goa and [kami](https://github.com/guregu/kami) in same project (under refactoring).

So, I want to handle request which router can handle.

goa has Lookup method.
https://github.com/goadesign/goa/blob/master/mux.go#L78-L81

but this cannot treat url include path parameter

```
package main

import (
	"log"
	"net/http"
	"net/url"

	"github.com/goadesign/goa"
)

func main() {
	service := goa.New("test")
	service.Mux.Handle("GET", "/v1/bottles", func(http.ResponseWriter, *http.Request, url.Values) {
		log.Println("can lookup")
	})
	service.Mux.Handle("GET", "/v1/bottles/:id", func(http.ResponseWriter, *http.Request, url.Values) {
		log.Println("cannot lookup")
	})
	service.Mux.Lookup("GET", "/v1/bottles")     // can lookup
	service.Mux.Lookup("GET", "/v1/bottles/1")   // cannot lookup
	service.Mux.Lookup("GET", "/v1/bottles/:id") // can lookup
}
```

Now httptreemux support Lookup. (https://github.com/dimfeld/httptreemux/issues/52)

I want goa to use httptreemux's Lookup.

Thanks.

**Comment by azihsoyn** [comment]
I implement customized mux implements goa.ServeMux interface followed by https://github.com/goadesign/goa/pull/1280#issuecomment-310875364

like this

```
type mux struct {
	Router      *httptreemux.TreeMux
	handles     map[string]goa.MuxHandler
	kamiHandler http.Handler
}

func (m *mux) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
	if result, found := m.Router.Lookup(rw, req); found {
		m.Router.ServeLookupResult(rw, req, result)
		return
	}
	m.kamiHandler.ServeHTTP(rw, req)
}
```

This issue resolved.

Thanks.

**Comment by raphael** [comment]
Thanks for posting the details!
