### ISSUE TITLE
Trailing Slash in Routing removed

### ISSUE THREAD

**Issue by Ragnaroek** [goadesign/goa#1283]
Action("something", func() {
		Routing(POST("/path/with/trailing/slash/"))
})

Goa seems to remove (haven't found where) to remove the trailing slash before the path is given to
httptreemux. This is bad, because we have a client that calls our endpoint with a trailing slash and does not follow redirect. The redirect to the non slash version is automatically done by httptreemux. I need to have the reverse: the non-slash version redirects to the slash version.

**Comment by raphael** [comment]
https://github.com/goadesign/goa/blob/master/design/definitions.go#L766 and https://github.com/goadesign/goa/blob/master/design/definitions.go#L781 is where the paths are  computed. The algorithm uses `path.Join` which removes the trailing slashes.  It would probably be OK if `FullPath` added back the trailing slash if there was one originally. I'd be happy to merge a PR that did that...

**Comment by Ragnaroek** [comment]
Oh well, I looked at the code but didn't see that!
I will try to make a PR today.

**Comment by raphael** [comment]
Thank you for the PR!, closing the issue.
