### ISSUE TITLE
ContentType isn't applied to CollectionOf for mediaType

### ISSUE THREAD

**Issue by Tri125** [goadesign/goa#1288]
Using goagen 1.2.0 (revision 4786bafb8f888edb8555c11dba172460b57f2fdb).
I've checked the commit history to see if it was found/fixed on the latest for master but I didn't see anything.

When specifying the Response for an Action on a collection of a specific media type, the content-header of the media type will not be used but instead the identifier.

Related? #694

Minimal design:

```
package design


import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("adder", func() {
	Title("The adder API")
	Description("A teaser for goa")
	Host("localhost:8080")
	Scheme("http")
})

var _ = Resource("category", func() {
	DefaultMedia(CategoryMedia)
	BasePath("/categories")

	Action("list", func() {
		Routing(GET(""))

		Response(OK, CollectionOf(CategoryMedia))
	})

	Action("show", func() {
		Routing(GET("/:categoryID"))
		Params(func() {
			Param("categoryID")
		})
		Response(OK)
	})
})

var CategoryMedia = MediaType("application/vnd.gwentapi.category+json", func() {
	ContentType("application/json; charset=utf-8")
	Attributes(func() {
		Attribute("name")
	})

	View("default", func() {
		Attribute("name")
	})
})

```

If you go to http://localhost:8080/categories/ you will see the following content type: ``application/vnd.gwentapi.category+json; type=collection``. I'm expecting ``application/json; charset=utf-8; type=collection``.

If you visit http://localhost:8080/categories/:id the content type will be correct: ``application/json; charset=utf-8``.

**Comment by dtoubelis** [comment]
Try this:
```go
Response(OK, CollectionOf(CategoryMedia, func() {
	ContentType("application/json")
}))
```

**Comment by Tri125** [comment]
I'm getting ``invalid use of ContentType in response "Ok"``

**Comment by dtoubelis** [comment]
Note, that `func()`  is inside of `CollectionOf()`. If it is still not working, post your code.

**Comment by Tri125** [comment]
My bad. Yes the above correction will allow me to specify the ContentType for the collection. I will still have to specify it for every action that returns a collection as well as remembering to manually write ``;type=collection`` which is far from being ideal but this works out just fine.

:+1:

**Comment by Tri125** [comment]
I'm reporting that it doesn't affect the generated swagger. It will still wrongly document the response content type as the name of the MediaType` (`application/vnd.gwentapi.category+json``).

**Comment by raphael** [comment]
Thanks for the report (and thank you for the workaround @dtoubelis). This is indeed a bug.

**Comment by raphael** [comment]
Actually I take that back :) It's not clear to me that the content type defined for a media type should also be used when rendering a collection of that media type. The "proper" solution here seems to be to define the collection media type explicitly so that it's possible to define the content type:

```go
var CategoryListMedia = CollectionOf(CategoryMedia, func() {                          
         ContentType("application/json; charset=utf-8")                                
})           

 Action("list", func() {                                                       
         Routing(GET(""))                                                                                       
         Response(OK, CategoryListMedia)
})              
```
@Tri125 does that work for you?

**Comment by raphael** [comment]
Closing this issue.
