### ISSUE TITLE
[Question] Adding Cookies to Design

### ISSUE THREAD

**Issue by patrickml** [goadesign/goa#1299]
is it possible to add cookies to the design, the reason I ask is testing becomes a huge pain if you are using cookies as part of your api. I'd imagine if cookies can be added to the design then the generated test functions could have a place to add cookies. Plus the generated docs could include the cookie name as well.

**Comment by raphael** [comment]
Yes that should be possible. I don't intend on adding this functionality any time soon but would be happy to help putting together a PR.
