### ISSUE TITLE
[question] different response type depending on parameter

### ISSUE THREAD

**Issue by hekigan** [goadesign/goa#1302]
Hi!

I have a `search` route.
This route can -depending on a 'type' parameter- be searching for a `MediaA`, `MediaX`, etc...

My current code is :

```
var _ = Resource("search", func() {
	BasePath("/search")

	Action("list", func() {
		Description("Get all search")
		Routing(GET(""))
		Params(func() {
			Param("q", String, "query to search for")
			Param("type", String, "products, images, users, etc...")
			Param("offset", Integer, "Start of the list", func() {
				Default(0)
			})
			Param("limit", Integer, "limit list to X items", func() {
				Default(50)
			})
		})
		Response(OK, CollectionOf(ProductMedia))
		// Response(OK, CollectionOf(UserMedia))
		Response(NotFound)
	})
})
```

So basically, what would be the best way to deal with the alternative types of media, depending on the query `type` parameter (`Response(OK, CollectionOf(XxxxMedia))`)? 

If possible, I don't want to make a sub-route like `search/:type` .

Thank you for your help!

**Comment by raphael** [comment]
You could use views to achieve what you need: define a media type that contains the union of all attributes of all the different media types you need to return. Then define views - one per media type - that list the specific attributes. `goagen` will generate one response method per view so the controller can look at the incoming parameters and use the proper response method.

As an example imagine you needed to return "accounts" or "bottles":

```go
var GenericMediaType = var Account = MediaType("application/vnd.generic", func() {
	Attributes(func() {
		Attribute("id", Integer)               // Common to bottle and account
		Attribute("bottle_name", String)    // Specific to bottle
		Attribute("account_name", String) // Specific to account
        })
        View("default", func() {}) // Unused
        View("account", func() {
               Attribute("id")
               Attribute("account_name")
        })
        View("bottle", func() {
               Attribute("id")
               Attribute("bottle_name")
        })
})
```

**Comment by hekigan** [comment]
Thank you for the detailed answer, I will try that

**Comment by raphael** [comment]
closing this issue for now, re-open or create a new one if you have more questions. Also consider joining the [slack channel](https://gophers.slack.com/messages/goa) (join [here](https://invite.slack.golangbridge.org/))

**Comment by saniales** [comment]
just solved, I saw OK`viewType` instead of `ok` and I used it
