### ISSUE TITLE
ArrayOf  (instead of CollectionOf) yields invalid return value from controller  (template issue)

### ISSUE THREAD

**Issue by dgaedcke** [goadesign/goa#1305]
This syntax:
```go
Response(OK,  ArrayOf(TradeEntityMtMsg))
```

is generating:
```go
	res := *app.TradeEntityMtMsg{}
	return ctx.OK(res)
```
Instead of:
```go
       []*app.TradeEntityMtMsg{}
```

**Comment by raphael** [comment]
I'm not able to reproduce this, the following design:
```go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("adder", func() {
	Title("The adder API")
	Description("A teaser for goa")
	Host("localhost:8080")
	Scheme("http")
})

var _ = Resource("category", func() {
	Action("list", func() {
		Routing(GET(""))
		Response(OK, ArrayOf(CategoryMedia))
	})
})

var CategoryMedia = MediaType("application/vnd.gwentapi.category+json", func() {
	Attributes(func() {
		Attribute("name")
	})

	View("default", func() {
		Attribute("name")
	})
})
```
Produces:
```go
// List runs the list action.
func (c *CategoryController) List(ctx *app.ListCategoryContext) error {
        // CategoryController_List: start_implement

        // Put your logic here

        // CategoryController_List: end_implement
        return nil
}
```
which is what I would expect as the code checks whether the response type is a media type and if not generates `return nil`. `ArrayOf` does not return a media type hence the code above. Are you able to repro? if so could you add a complete design to the issue? thanks!

**Comment by dgaedcke** [comment]
I'm sure it was some error on my part.....I'm still a beginner so who knows how I ended up there.  I'm tied up on the client (IOS) for the next few weeks but if I can reproduce it, i'll come back and re-open this ticket.

**Comment by raphael** [comment]
Great thank you, my money would be on a stale file. The `main` package is scaffold code that does not get overridden automatically so it is possible that the design changed and that it wasn't an array before but the controller file wasn't deleted between `goagen` re-run.
