### ISSUE TITLE
"bare" value support

### ISSUE THREAD

**Issue by BrianHicks** [goadesign/goa#132]
My use case: wrap K/V stores with a type interface (github.com/asteris-llc/gestalt, functionality is currently in the `feature/web` fork).

I'd like to use `interface{}` as a payload/return type (the value in a K/V store), instead of having to marshal/unmarshal that myself. In addition, it'd be super if I could use `Hash(String, Any)` as a media type directly (for a hash of values)

**Comment by raphael** [comment]
Fixed by #308 and #309, this now works:
```go
package design

import (
    . "github.com/goadesign/goa/design"
    . "github.com/goadesign/goa/design/apidsl"
)

var _ = Resource("foo", func() {
    BasePath("/foo")

    Action("baz", func() {
        Routing(PUT("/kall"))
        Payload(HashOf(String, Any))
        Response(OK, ArrayOf(String))
    })
})
