### ISSUE TITLE
Document customizing error responses.

### ISSUE THREAD

**Issue by brycereitano** [goadesign/goa#1323]
Once this #1321 is closed, it should be documented.

@raphael Could you provide a list of locations you would like this documented?

**Comment by raphael** [comment]
@brycereitano I was thinking that the description could go in the error documentation: https://goa.design/implement/error_handling/ (source: https://github.com/goadesign/goa.design/blob/master/content/implement/error_handling.md). Maybe next to the section that describes how to create new error classes using `goa.NewErrorClass`. There could be a new section explaining that it is also possible to create arbitrary structs as long as they implement either `ServiceError` or the new mergeable interface. That would be a good place to describe the point of the mergeable interface.

**Comment by wayneashleyberry** [comment]
Looking forward to this being documented! I thought goa didn't actually support this until I did a search around the issues and pull requests.
