### ISSUE TITLE
Array element validation

### ISSUE THREAD

**Issue by klauspost** [goadesign/goa#1347]
The [documentation](https://goa.design/reference/goa/design/apidsl/#func-arrayof-a-name-apidsl-arrayof-a) states that Array elements can be validated, but only lists a regex as an example. It seems that at least some of the validation isn't possible. Using this design:

```Go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var ElementIDsPayload = Type("ElementIDs", func() {
	Attribute("ids", ArrayOf(Integer), func() {
		Minimum(0)
		Maximum(100)
	})
})
```

Gives this error:
```
>goagen bootstrap -d goatest/design
exit status 1
[problem.go:10] invalid minimum validation definition: attribute must be an integer or a number (but type is array)
[problem.go:11] invalid maximum validation definition: attribute must be an integer or a number (but type is array)
```

It may simply be a missing feature and require a lot of work to fix, in that case the documentation should IMO be adjusted.

**Comment by raphael** [comment]
The correct syntax to do the above is:

```go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var ElementIDsPayload = Type("ElementIDs", func() {
	Attribute("ids", ArrayOf(Integer, func() {
		Minimum(0)
		Maximum(100)
	}))
})
```
The validation DSL is an argument to `ArrayOf` and not to `Attribute`.
