### ISSUE TITLE
Timezone shouldn't affect generated swagger docs.

### ISSUE THREAD

**Issue by brycereitano** [goadesign/goa#1353]
Currently your time zone can affect your generated code. Causing unnecessary diffs during code reviews.

```diff
-          expiresAt: 1985-01-19T01:52:13-07:00
+          expiresAt: 1985-01-19T08:52:13-06:00
```

I think defaulting to UTC would suffice and if you want to show a time zone in your examples then you will provide one. Instead of providing an example on all DateTime attributes to workaround this issue.
```patch
diff --git a/design/random.go b/design/random.go
index af7c8a8..15d452a 100644
--- a/design/random.go
+++ b/design/random.go
@@ -55,7 +55,7 @@ func (r *RandomGenerator) DateTime() time.Time {
 	// values get generated for a given API.
 	max := time.Date(2016, time.July, 11, 23, 0, 0, 0, time.UTC).Unix()
 	unix := r.rand.Int63n(max)
-	return time.Unix(unix, 0)
+	return time.Unix(unix, 0).UTC()
 }
 
 // UUID produces a random UUID.
```

**Comment by jim-slattery-rs** [comment]
Just to provide another workaround, we set the TZ environment variable `TZ=UTC` when running goagen.

**Comment by raphael** [comment]
@brycereitano makes sense to me, this is a bug really as the intent was to generate DateTime examples in UTC.
