### ISSUE TITLE
serving ws + http on same port

### ISSUE THREAD

**Issue by dfarago** [goadesign/goa#1357]
Is it possible to use goa to generate a microservice that combines http and ws on the same port? If so, what would be the steps?

**Comment by raphael** [comment]
The WS(S) protocol uses the same port as HTTP(S) "by definition" (a websocket connection is established by first making a standard HTTP requests which gets "promoted"). See https://github.com/goadesign/examples/tree/master/websocket for an example.

**Comment by dfarago** [comment]
I actually tried to combine the two, and http works fine but ws is giving an error. Here are the details:

My design.go file is:

	package design
	
	import (
		. "github.com/goadesign/goa/design"        		// Use . imports to enable the DSL
		. "github.com/goadesign/goa/design/apidsl"
	)
	
	
	var _ = API("testgoa1", func() { 				// API defines the microservice endpoint and
	
		Title("Virtual bank" )           			// other global properties. There should be one
		Description("A simple goa service" )        	// and exactly one API definition appearing in
		Scheme("http", "ws" )                      // the design.
		Host("localhost:8080" )
	})
	
	
	var _ = Resource("account", func() {         	// Resources group related API endpoints
	
		BasePath("/accounts" )                      // together. They map to REST resources for REST
		DefaultMedia( AccountMedia )                  	// services.
	
		Action("show", func() { // Actions define a single API endpoint together
			Scheme("http" )
			Description("Get account by id")    		// with its path, parameters (both path
			Routing( GET("/:accountID" ) )        // parameters and querystring values) and payload
			Params( func() {                    		// (shape of the request body).
				Param("accountID", Integer, "Account ID" )
			})
			Response( OK )                       		// Responses define the shape and status code
			Response( NotFound )                 		// of HTTP responses.
		})
	})
	
	var _ = Resource("echo", func() {
		Action("connect", func() {
			Routing( GET("/:echo" ) )
			Scheme("ws")
			Description("echo websocket server")
			Params(func() {
				Param("initial", String, "Initial message to echo")
			})
			Response( SwitchingProtocols )
		})
	
	})
	
	// AccountMedia defines the media type used to render accounts
	
	var AccountMedia = MediaType("application/vnd.goa.example.account+json", func() {
	
		Description("A virtual bank account")
	
		Attributes( func() {                         	// Attributes define the media type shape.
			Attribute("id", Integer, "Unique account ID")
			Attribute("href", String, "API href for making requests on the account")
			Attribute("name", String, "Name of account")
			Required("id", "href", "name")
		})
		View("default", func() {                	// View defines a rendering of the media type.
			Attribute("id")                     	// Media types may have multiple views and must
			Attribute("href")                   	// have a "default" view.
			Attribute("name")
		})
	})

I then generated the code with goa, which generated the various files, including main.go, echo.go and account.go. 

These files, which I modified, are as follows:

main.go:

	//go:generate goagen bootstrap -d github.com/defgolang/testgoa1/design
	
	package main
	
	import (
		"log"
	
		"github.com/defgolang/testgoa1/app"
		"github.com/goadesign/goa"
		"github.com/goadesign/goa/middleware"
	)
	
	func main() {
	
		// Create service
		httpservice := goa.New("testgoa1")
		wsservice := goa.New( "testws")
	
		// Mount middleware
		httpservice.Use(middleware.RequestID())
		httpservice.Use(middleware.LogRequest(true))
		httpservice.Use(middleware.ErrorHandler(httpservice, true))
		httpservice.Use(middleware.Recover())
	
		// Mount "account" controller
		c1 := NewAccountController(httpservice)
		app.MountAccountController(httpservice, c1)
	
		// Start service
		if err := httpservice.ListenAndServe(":8080"); err != nil {
			httpservice.LogError("startup", "err", err)
		}
	
		// Mount "echo" controller
		c2 := NewEchoController( wsservice )
		app.MountEchoController( wsservice, c2 )
	
		log.Fatal( wsservice.ListenAndServe(":8080") )
	
	}

account.go:

	package main
	
	import (
		"github.com/defgolang/testgoa1/app"
		"github.com/goadesign/goa"
		"fmt"
	)
	
	
	// AccountController implements the account resource.
	type AccountController struct {
		*goa.Controller
	}
	
	
	// NewAccountController creates a account controller.
	func NewAccountController(service *goa.Service) *AccountController {
		return &AccountController{Controller: service.NewController("AccountController")}
	}
	
	
	
	// Show runs the show action
	
	func ( c *AccountController ) Show( ctx *app.ShowAccountContext ) error {
	
		// AccountController_Show: start_implement
		if ctx.AccountID == 0 {
			// Emulate a missing record with ID 0
			return ctx.NotFound()
		}
	
		// Build the resource using the generated data structure
	
		account := app.GoaExampleAccount {
			ID:   ctx.AccountID,
			Name: fmt.Sprintf("Account #%d", ctx.AccountID),
			Href: app.AccountHref(ctx.AccountID),
		}
	
		// AccountController_Show: end_implement
		return ctx.OK( &account )
	}
	
echo.go:

	package main
	
	import (
		"github.com/defgolang/testgoa1/app"
		"github.com/goadesign/goa"
		"golang.org/x/net/websocket"
		"io"
	)
	
	
	// EchoController implements the echo resource.
	type EchoController struct {
		*goa.Controller
	}
	
	
	// NewEchoController creates a echo controller.
	func NewEchoController(service *goa.Service) *EchoController {
		return &EchoController{Controller: service.NewController("echo")}
	}
	
	
	// Connect runs the connect action.
	func (c *EchoController) Connect(ctx *app.ConnectEchoContext) error {
		c.ConnectWSHandler(ctx).ServeHTTP(ctx.ResponseWriter, ctx.Request)
		return nil
	}
	
	
	// ConnectWSHandler establishes a websocket connection to run the connect action.
	func (c *EchoController) ConnectWSHandler(ctx *app.ConnectEchoContext) websocket.Handler {
		return func(ws *websocket.Conn) {
			// EchoController_Connect: start_implement
	
			// Put your logic here
	
			// EchoController_Connect: end_implement
			ws.Write([]byte("connect echo"))
			// Dummy echo websocket server
			io.Copy(ws, ws)
		}
	}


These files build fine, and the app runs.

Here is the output for the http request:
	
	Daves-Mac-mini:testgoa1-cli dfarago1$ curl -icurl -i localhost:8080/accounts/1
	HTTP/1.1 200 OK
	Content-Type: application/vnd.goa.example.account+json
	Date: Thu, 17 Aug 2017 16:25:51 GMT
	Content-Length: 50
	
	{"href":"/accounts/1","id":1,"name":"Account #1"}
	

Here is the output for the ws request:

	Daves-Mac-mini:testgoa1-cli dfarago1$ wsc ws://localhost:8080/echo
	2017/08/17 12:27:17 connecting to ws://localhost:8080/echo...
	2017/08/17 12:27:17 websocket.Dial ws://localhost:8080/echo: bad status

The console output for the ws request is:

	2017/08/17 12:27:17 [INFO] started req_id=XxRYOKNiNm-7 GET=/echo from=::1 ctrl=<unknown> action=<unknown>
	2017/08/17 12:27:17 [INFO] headers req_id=XxRYOKNiNm-7 Upgrade=websocket Connection=Upgrade Sec-Websocket-Key=2VKqNOyE/zZWwi95LhjSpw== Origin=ws://localhost:8080/echo Sec-Websocket-Version=13
	2017/08/17 12:27:17 [INFO] completed req_id=XxRYOKNiNm-7 status=404 error=bkAppOs7 bytes=67 time=121.052µs ctrl=<unknown> action=<unknown>

I am propbably doing something wrong, and your insight is much appreciated.

**Comment by dfarago** [comment]
I also tried Routing( GET("echo" ) ) in the design.go file (which makes a difference in the uncombined ws example), but I still get the bad status error.

**Comment by dfarago** [comment]
I solved it!! 

The issue was in the main.go file. You just need to start one service, and mount separate controllers for ws and http.

The modified code for main.go is:


	package main
	
	import (
		"github.com/defgolang/wstest1/app"
		"github.com/goadesign/goa"
		"github.com/goadesign/goa/middleware"
	)
	
	func main() {
		// Create service
		service := goa.New("vbank")
	
		// Mount middleware
		service.Use(middleware.RequestID())
		service.Use(middleware.LogRequest(true))
		service.Use(middleware.ErrorHandler(service, true))
		service.Use(middleware.Recover())
	
		// Mount "echo" controller
		c := NewEchoController(service)
		app.MountEchoController(service, c)
	
		// Mount "account" controller
		c1 := NewAccountController(service)
		app.MountAccountController(service, c1)
	
		// Start service
		if err := service.ListenAndServe(":8080"); err != nil {
			service.LogError("startup", "err", err)
		}
	
	}

**Comment by raphael** [comment]
Glad you figured it out!
