### ISSUE TITLE
Question about []byte type

### ISSUE THREAD

**Issue by dalu** [goadesign/goa#1359]
I have just started writing an experiment with goa.
```go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("iloveu", func() {
	Title("iloveu dating app")
	Version("0.1")
	Host("localhost:8080")
	Scheme("http")
	BasePath("/v1")
})

var Account = MediaType("application/vnd.account+json", func() {
	Description("A user account")
	Attributes(func() {
		Attribute("id", Integer, "ID of account")
		Attribute("email", String, "user's email")
		Attribute("password", CollectionOf(byte))})
	})
})
```

How do I represent a binary type?
I'll be using gorma.
But I'm not really sure how it all works.
Where can I ask questions?

Well basically there's

type Account struct {
ID uint
Email string
Password []byte // or rather passwordhash
}
So how do I define a binary attribute?

Is there an alternative to writing my account management in goa?
You're all so busy developing this but it's so inaccessible.
Account management is the largest problem.
I know there's this wine cellar demo but it doesn't really do authentication.

**Comment by raphael** [comment]
There's an active [slack channel](https://gophers.slack.com/messages/goa/) (sign up [here](https://gophersinvite.herokuapp.com/)) where questions like these would be better directed. For this use case I would use a `String` in the design to represent the password (even if it's binary data). goa v2 has a native `Byte` data type which would map better, v2 is still WIP though.
