### ISSUE TITLE
Default ErrorMedia does not define correct media type

### ISSUE THREAD

**Issue by CuBiC3D** [goadesign/goa#1371]
The default Goa ErrorMedia has "application/vnd.goa.error" as content type. Is there any way to change this to "application/vnd.goa.error+json"?

JSON consumer do not recognise this as JSON and generating a lot of trouble. Same goes for the official Swagger UI, try on http://petstore.swagger.io using locally running goa api. Any endpoint that responds with ErrorMedia shows "Response body: Unknown response type" instead of the error response.

**Comment by raphael** [comment]
This change cannot be done unilaterally since some APIs do not return JSON. However the value is stored in a public variable in the design package so that it's possible to override it:

```go
design.ErrorMediaIdentifier = "application/vnd.goa.error+json"
design.ErrorMedia.Identifier = "application/vnd.goa.error+json"
```

should do the trick.

**Comment by CuBiC3D** [comment]
Thanks, that worked very well! :wink:

**Comment by uzimith** [comment]
We need to override the value of goa package also in runtime, I guess.

```
goa.ErrorMediaIdentifier = "application/vnd.goa.error+json"
```

**Comment by CuBiC3D** [comment]
What's the use case for that? It would change the specification while serving the API. The media identifier is part of the type description itself.

**Comment by uzimith** [comment]
We need to tell what type the response is to parse json error response to the client (browser, curl, swagger etc). So goa sever should response with media type suffix.

I checked httpie need `goa. ErrorMediaIdentifier` to parse it, so I guess goa become to add suffix automatically to response with multi media type.

**Comment by CuBiC3D** [comment]
I agree with you, that without the suffix on the identifier, the ErrorMedia is not gonna be parsed by clients.

That was the point to open this issue and it turned out, that you can set the identifier right in the design package, so design.go would be a good place in the project.

What do you exactly mean by override in runtime? Can you make an example of a situation?

**Comment by blackheart01** [comment]
When returning a goa.ServiceError from a controller, and allowing ErrorHandler to handle the error, it sets the Content-Type header to goa.ErrorMediaIdentifier. If you don't change that to "application/vnd.goa.error+json" at runtime, clients will not parse it.

Making the change in the design package does not help the above situation. If instead you use the generated controller response functions, the change in the design package does work.
