### ISSUE TITLE
Issue in goa v2 with go 1.9

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1378]
Getting error when using generator.

```goa gen gitlab.com/kumar/goa_v2/design```
Error - 
```cannot find package "." in:```

I tried after https://github.com/goadesign/goa/commit/c20b6a78755b08fdd81a4d115a11b48e4f78043d also

**Comment by raphael** [comment]
I'm not able to repro. Please provide a design that reproduces the issue.

**Comment by raphael** [comment]
This is now fixed, thanks!
