### ISSUE TITLE
Responses listing the same model create multiple Produces entries

### ISSUE THREAD

**Issue by dgildeh** [goadesign/goa#1379]
If I do an action with multiple error responses referring to the error model like below:

```
Action("list", func() {
		Description("Returns a list of all the dashboards a user has access to in an account.")
		Routing(
			GET(""),
		)
		Response(OK, CollectionOf(Dashboard))
		Response(NotFound, ErrorMedia)
		Response(Unauthorized, ErrorMedia)
		Response(BadRequest, ErrorMedia)
	})
```

It produces the following Swagger spec:

```
get:
      description: Returns a list of all the dashboards a user has access to in an
        account.
      operationId: dashboard#list
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.outlyer.dashboard+json; type=collection
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/OutlyerDashboardCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
```

The produces section lists 'application/vnd.goa.error' for each response entry which causes the Swagger spec to raise errors in Swagger Editor and blocks us generating SDKs from the spec unless we manually go in and fix the generated Swagger spec to remove the multiple errors.

We want error responses returned in the body for all errors. Are we defining this behaviour the wrong way or is this a bug in the Goa framework?

**Comment by raphael** [comment]
Thanks for the report, this seems like a bug as the design is correct.

**Comment by dgildeh** [comment]
Great! Wasn't sure if we were doing it wrong. Will look out for the fix as this is stopping all our Swagger client generation from working right now. Thanks.

**Comment by raphael** [comment]
This is now fixed.
