### ISSUE TITLE
Headers not getting populated

### ISSUE THREAD

**Issue by GolfRider** [goadesign/goa#1389]
Hi,

Thanks for the great tool. I faced some issues while trying out the v2 issues.
I am not able to get the 'headers' generated in the json file, probably it is ignored ?
Basically I was trying to set the authorization headers as required, but couldn't 

Apart from that, I have noticed these issues as well:
1.  Param (when used as query params) it gives some issues
2. Payload doesn't accept 'Empty' , for work around I did this way:
    Payload(func() {}) // work-around for empty ?
3. Headers are ignored at all levels : API, Service, Method level ?
4. Response with Error types doesn't work well.
       -  Error("some_error")
       - Response("some_error", BAD_REQUEST)  // doesn't work

for eg:
```
Method("GetBookById", func() {
		Description("Get Book Details By ID")
		Payload(func() {
			Attribute("bookId", String, "uuid of book")
			Attribute("auth", String, "auth ")
			Required("bookId")
			Required("auth")
		})
		Result(BookDetails, "Book Details ")
		Error("not_found")
		HTTP(func() {
			GET("/{bookId}")
			Header("auth:Authorization", String, "API KEY")
			Response(func() {
				Description("book Details ")
				Body(BookResult) // though redundant here ?
				Code(StatusOK)
			})
			Response(BAD_REQUEST)
			Response(NOT_FOUND)
			Response(INTERNAL_SERVER_ERROR)
			Response(UNAUTHORIZED)
		})
	})
```

I understand this version is still a work in progress, but thought of highlighting some issues I came across, hopefully they might get addressed in the future releases.

Small observation:
   1. I found DSL in v2 much simpler than v1
   2. But the generated code in v1 was simpler than v2  :-)

Thanks again for the great work.

**Comment by raphael** [comment]
thanks for the feedback! As you've noted v2 is still work in progress. The issues you have listed should be all getting addressed soon. There is no security support in v2 yet, when it comes it will be in the form of a plugin.

As for the generated code v2 generates different layers: the service layer, the endpoint layer and the transport layer. This makes it possible to implement multiple transports for the same service while still wrapping the endpoints in transport independent middleware for example. So yes there's a little upfront complexity in understanding that (and hopefully the docs will help there) but once you do the result is much more flexible and composable that the generated code produced in v1.
