### ISSUE TITLE
Issues with generated swagger.json and swagger-ui v3.2.1

### ISSUE THREAD

**Issue by vcabbage** [goadesign/goa#1396]
When rendering and using the generated `swagger.json` in swagger-ui (v3.2.1) I've run into trouble using the "Try it out" functionality due to the returned Content-Type header.

swagger-ui won't display the response at all if it doesn't understand the returned Content-Type, instead it opts to show the message "Unknown response type". And of course it doesn't understand any `application/vnd...` content type.

There seem to be a couple work arounds for this:

* Specify `ContentType("application/json")` in the media type and collection definitions.
* Add a `+json` suffix to the media type names.

I don't find either of these ideal since they result in the response Content-Type always being set to JSON even if the client requests XML or GOB via the Accept header. Perhaps I'm missing something but it seems like the simple thing to do would be to respond with the Content-Type header set to whatever was requested by the client via the Accept (provided the server supports the requested type).

---

A related but somewhat separate issue I ran into is that even when the server supports multiple response types, each path in the swagger definition gets `produces` set to the media type of the response (I assume this was done due to #1074). Due to this the user cannot select the desired response content type in the UI even when multiple are supported by the server.

---

Thank you for considering this issue and for all your work on this project!

**Comment by raphael** [comment]
The behavior you describe where the encoder sets the `Content-Type` header is what is done in `v2` (see https://github.com/goadesign/goa/blob/v2/http/encoding.go#L89-L118) however this would be a breaking change in `v1`. Note that the generated code only sets the header if not set already so you could write a middleware that sets it as a workaround for `v1`.

The related issue should also be alleviated in v2 since the Content-Type values are not specific to each endpoint by default.

**Comment by vcabbage** [comment]
> Note that the generated code only sets the header if not set already so you could write a middleware that sets it as a workaround for v1.

I tried this with no luck. Looking at the generated code, it seems like the header is set unconditionally:
```
// OK sends a HTTP response with status code 200.
func (ctx *GetThingsContext) OK(r *Client) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.things.thing")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}
```

**Comment by raphael** [comment]
Yes you're right :-( I'd be happy to accept a PR that adds a `if` statement around that line.

**Comment by raphael** [comment]
I think this can be closed? Thank you for the contribution!

**Comment by vcabbage** [comment]
Yes, thanks!
