### ISSUE TITLE
JWT security apparently incompatible with Auth0

### ISSUE THREAD

**Issue by iancmcc** [goadesign/goa#1398]
Auth0 generates JWTs that include scopes using the claim `scope`, and, as far as I can tell, there's no way to control that. Goa is hardcoded to look for the claim `scopes`, and there's no way to control that, either, short of patching it. 

Is there any solution to this impasse? If not, would a PR that, say, adds `ScopesClaim` as a DSL func be welcome?

**Comment by raphael** [comment]
Thanks for bringing this up. Adding this to the DSL would work, the `JWTSecurity` struct would then have the name of the scope claim which the middleware could leverage. However I'm wondering if it wouldn't be better to just modify the middleware to check for both `scope` and - if not present - `scopes`. Seems unlikely another name would be used to store them and it would alleviate the need to add another "keyword" to the DSL. I'd be happy to merge a PR that made the change to the middleware (https://github.com/goadesign/goa/blob/master/middleware/security/jwt/jwt.go#L172).

**Comment by iancmcc** [comment]
Aw heck, I was half done :-).  Simpler middleware change coming right up...

**Comment by raphael** [comment]
Thanks for the great PR! and sorry for the extra work but keeping the DSL simple is probably worth it :-)
