### ISSUE TITLE
How to retrieve error detail on the client-side?

### ISSUE THREAD

**Issue by kovetskiy** [goadesign/goa#1409]
Hi, how can I retrieve error `detail` field on the client-side?

When I request problem URL using curl I get: (example from https://goa.design/learn/guide/)
```
{"code":"invalid_request","status":400,"detail":"invalid value \"n\" for parameter \"bottleID\", must be a integer"}
```

But when I use generated client I can't see any method to get this message, when I call method like `GetSomeData` that returns `(*http.Response, error)` I get pure http.Response with StatusCode == 400 nil as error. I can call method `DecodeSomeData` but it will not produce error, because Decode-like methods don't validate response at all (only unmarshal). I can call `ValidateSomeData()` method on response of `DecodeSomeData`, but it will produce only error like some field is required but missing. But real error is not about invalid response, error is about invalid request and I want to get this `detail` message and show it to user.

How I can do it?

**Comment by raphael** [comment]
If the error response is a serialized [ErrorResponse]( https://github.com/goadesign/goa/blob/master/error.go#L114) like in the example above then unmarshal the response body using an instance of this struct. All the generated validation code use this struct to write the response body.

**Comment by kovetskiy** [comment]
@raphael so I need to make such function in every application that uses goa generated code? Like as following:
```
response, err := client.GetSomeData()
if response.StatusCode >= 400 {
     var errorResponse ErrorResponse
     err :=json.NewDecoder(response.Body).Decode(&errorResponse)
     return errorResponse.Detail
}
```


What you think about adding such method like `DecodeErroResponse` to Goa?

**Comment by kovetskiy** [comment]
@raphael ping

**Comment by raphael** [comment]
Sorry for the delay. Yes the response needs to be unmarshaled appropriately if it's an error. v2 addresses that by generating code that does the unmarshaling in the transport layer and returns the error to the service method. In v1 though you have to do something like what you are describing above.
