### ISSUE TITLE
Getting error while run the basic cellar code 

### ISSUE THREAD

**Issue by KashyakSupport** [goadesign/goa#1410]
Hi,
I am working on Goa cellar code from 
[https://goa.design/learn/guide/](https://goa.design/learn/guide/)

**go build -o cellar**
I have run this command from command Prompt.it is created a file with _cellar_
Then run the below command
**./cellar**
it is throwing below error
`'.' is not recognized as an internal or external command,
operable program or batch file.` 

I am new to this Goa , Could you please help me to fix this issue.

**Comment by raphael** [comment]
Are you running this on Windows? if so then just run the executable with `cellar.exe` - no need to specify the path.

**Comment by KashyakSupport** [comment]
Thank you , It is working

**Comment by KashyakSupport** [comment]
Thank you i am running on windows and it is working.
