### ISSUE TITLE
Design reuse

### ISSUE THREAD

**Issue by derbexuk** [goadesign/goa#1411]
I am working on a project that will involve many sub projects whose servers will use some of the same types. Is there a way of reusing the user and media types across these sub projects other than cut & paste? What I would like is a library of these types that I can pull into my design as needed.

**Comment by derbexuk** [comment]
It seems this can be done using Go's normal import method. I mucked up my original test, but have now fixed it and have included a user type imported into my design from another package.

**Comment by raphael** [comment]
Yup a pattern that might be helpful to adopt is to split the design package into a "private" package (not intended to be imported by other services) and a "public" package that contains the types intended to be reused by other services. The private design package has the `API` function call and other service specific DSL and imports the public package that defines the shared types.
