### ISSUE TITLE
best way to enable case-insensitive paths 

### ISSUE THREAD

**Issue by Ashtonian** [goadesign/goa#1417]
I'd like to make paths case-insensitive for our api. I was wondering what the best way to do so is? I tried using a middleware layer to handle it, and it seems like that is executed after path resolution.

**Comment by euller88** [comment]
You can write your actions this way:

```
var _ = Resource("operands", func() {
        Action("add", func() {
                Routing(GET("add/:left/:right"))
                Routing(GET("ADD/:left/:right"))

                Description("add returns the sum of the left and right parameters in the response body")

                Params(func() {
                        Param("left", Integer, "Left operand")
                        Param("right", Integer, "Right operand")
                })

                Response(OK, "text/plain")
        })

})
```

This is an awful solution. Is it effective? Yes. Is it efficient? No.

A better way should be changing the router to be case insensitive, or write personalized mounting functions. But I don't have the skill nor the time to write a solution right now.

**Comment by raphael** [comment]
You could create your own handler using the stdlib mux and have that handler modify the `Request` object `URL.Path` field. Then have it call the goa service mux handler. Have not tried it though :)

**Comment by Ashtonian** [comment]
thanks, I ended up hacking the not found handler a bit. I may try and wrap the mux handler instead. 

If anyone needs it here is a simplified version
```go 
func NotFoundHandler(mux goa.ServeMux) goa.MuxHandler {
	return func(rw http.ResponseWriter, r *http.Request, u url.Values) {
		// check to see if its path casing issue.
		handler := mux.Lookup(r.Method, strings.ToLower(r.URL.Path))
		if handler != nil {
			handler(rw, r, u)
			return
		}
	}
}
// elsewhere 
service.Mux.HandleNotFound(controller.NotFoundHandler(service.Mux))
```
