### ISSUE TITLE
Not clear what version(s) of the Swagger/OpenAPI spec the generated JSON/YAML should adhere to

### ISSUE THREAD

**Issue by cies** [goadesign/goa#1419]
Maybe I'm overlooking it. But I think that should be mentioned on the root README, as I'd say it is rather important.

BTW. Props for the cool project. Have you seen haskell-servant?

**Comment by raphael** [comment]
Yeah I guess it could be explicitly stated. The version is in the generated file though (2.0). Thank you for the kind words! no I haven't seen haskell-servant (don't know haskell).

**Comment by cies** [comment]
Thanks for clarifying. Servant puts the API at type level. So all your app is compile-time-guaranteed to adhere to it; like Goa it also has the Swagger manifest generated from "the code".
