### ISSUE TITLE
goa v2: add missing tests.

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#1423]
Go through goa v2 packages and increase test coverage. In particular:

* Add tests to design packages
* Add tests to DSL packages
* Add tests to goa package

**Comment by tchssk** [comment]
This is still not over.

**Comment by tchssk** [comment]
These functions and methods are very simple. It is suitable for first-time contributors.

* [ ] `design.APIExpr.EvalName()`
* [ ] `design.APIExpr.Hash()`
* [ ] `design.ContactExpr.EvalName()`
* [ ] `design.DocsExpr.EvalName()`
* [ ] `design.LicenseExpr.EvalName()`
* [ ] `design.ServerExpr.Attribute()`
* [ ] `design.ServerExpr.EvalName()`
* [ ] `design.ServerParamExpr.EvalName()`

**Comment by raphael** [comment]
Thank you for identifying these! Would be great to have individual issues for each labeled with `v2` and `good first issue`. Maybe the issue description could point to an example (one of the tests you've written).
