### ISSUE TITLE
goa v2: generated unmarshal functions do not check for nil

### ISSUE THREAD

**Issue by jsimonetti** [goadesign/goa#1446]
there's an issue in the `unmarshal_TYPE_RequestBodyTo_TYPE_` function generation.
The argument `v *_TYPE_RequestBody` is not checked for `nil`. This results in a nil pointer dereference when an attribute is optional and not specified in the request body.

file `gen/http/_SERVICE_/server/encode_decode.go`

If I add
```
    if v == nil {
        return nil
    }
```
to the start of the function body, this issue is fixed.

**Comment by raphael** [comment]
Can you please provide a complete design that reproduces the issue?

**Comment by jsimonetti** [comment]
Took me a while, but I managed to find a small design to repro the problem:

```
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

var _ = API("agent", func() {
	Title("agent")
	Version("0.1")
	Server("http://localhost:8080")
})

var Type1 = Type("Type1", func() {
	Attribute("name", String)
	Attribute("type2", Type2)
	Required("name")
})

var Type2 = Type("Type2", func() {
	Attribute("name", String)
})

var _ = Service("agent", func() {
	HTTP(func() {
		Path("/agent")
	})

	Method("add", func() {
		Payload(Type1)
		Result(String)
		HTTP(func() {
			POST("/")
			Response(StatusCreated)
		})
	})
})
```

Generating this design will create the `unmarshalType2RequestBodyToType2` in `gen/http/agent/server/encode_decode.go` with the problem.
In this function the `v *Type2RequestBody` is not checked for nil.

Since Type2 is optional, when you create a request to this service with type2 unspecified in the json request body, this will result in a nil pointer dereference, since it is directly called from `NewAddType1`:

```
// NewAddType1 builds a agent service add endpoint payload.
func NewAddType1(body *AddRequestBody) *agent.Type1 {
	v := &agent.Type1{
		Name: *body.Name,
	}
	v.Type2 = unmarshalType2RequestBodyToType2(body.Type2)
	return v
}
```

**Comment by raphael** [comment]
Thank you for all the details, this is really helpful! I'm working on a fix.

**Comment by raphael** [comment]
This is now fixed, thanks again for the detailed report!
