### ISSUE TITLE
Support for Swagger 2.0 Tags

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#145]
Swagger 2.0 supports tags: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md

would be great to have some annotation in the DSL for that!

**Comment by abourget** [comment]
If you go to: http://editor.swagger.io/ -> _File_ menu -> Open example -> select `default.yaml` .. you'll see tags on the right side.. they're annotated with `tags: ["list", "of", "tags"]` .. allows you to filter out endpoints..

**Comment by abourget** [comment]
btw, I'd like to dive into `goa` and contribute some things, would this feature be approcheable for a newcomer ?

**Comment by raphael** [comment]
One question I had wrt tags support was whether it needed its own DSL or whether the existing `Metadata` function could be reused. I like the idea of reusing Metadata because that's really what tags are: they don't affect the actual API behavior. So maybe you can take a look at the Swagger generator and see whether encoding Swagger tags in goa Metadata makes sense? Thanks for volunteering!

**Comment by abourget** [comment]
oh yeah.. that'd be great.. maybe with some sort of namespacing ? `Metadata(`swagger:"tags"`, []string{"one", "two", "three"})` and the `swagger` generator could pick those up.. ?

**Comment by abourget** [comment]
or simply, a could of metadata keys could have a special effect.. if it's documented, it could work.. maybe we could even implement the security things this way.. at least temporarily

**Comment by raphael** [comment]
One thing to consider too is that Swagger tags are not just strings, they can have a description and link to documentation. Where I left it at when I last looked at it was something like:
```go
Metadata("tags", `[{"name": "foo", "description": "bar", "docs": "http://example.com/docs.html"}]`)
```
but I wasn't too thrilled by having to write that JSON by hand.

**Comment by abourget** [comment]
Why not have some Metadata objects.. that Metadata() could receive ?
```
type TagMetadata struct {
    Name string
    Description string
    Docs string
}
```

couldn't we make `Metadata` accept `interface{}` as a second argument ? so generators could poke at the type.. would keep things structured, and optional as need be.

Would look like:

```
Metadata("tags", TagMetadata{Name: "hello world"})
```

**Comment by raphael** [comment]
Maybe the `Metadata` function calls `json.Marshal` on the given object? that object is then free to implement its own custom marshaler. Also it would probably have to be a variadic function to allow for multiple tags.

**Comment by abourget** [comment]
well.. I can imagine certain generators that would want the raw data.. and not necessarily dealing with JSON.. certainly we could make sure `TagMetadata` fits the JSON Swagger model..

For the Swagger generator, I can see also that if Docs and Description are empty, it could be rendered as a simple list of strings too.. so I'd implement the logic in the generators, with structured data being passed around, so decisions like that can be taken down the pipe.

Having a variadic seems good too.. would build a sort of `url.Values` underneath ?

**Comment by raphael** [comment]
OK I was trying to avoid having to break existing use of metadata (e.g. in [gorma](https://github.com/bketelsen/gorma)) but I agree that in the long run being able to pass the raw data is probably better (and the fix pretty easy). +1 on the sort of `url.Values` (`map[string][]interface{}`).

**Comment by bketelsen** [comment]
we don't have to fail metadata if the json included doesn't parse

**Comment by raphael** [comment]
PR #229 Added the ability to generate Swagger tags. The syntax is:
```go
Metadata("swagger:tag=SomeTag", "tag description", "tag doc URL", "tag doc description")
```
where all the parameters but the first are optional.
