### ISSUE TITLE
Support for type "File"

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#146]
The swagger spec allows for something like:

```
name: avatar
in: formData
description: The avatar of the user
required: true
type: file
```

with `type: file` and `in: formData` .. I've also seen `in: body` over [here](http://stackoverflow.com/questions/14455408/how-to-post-files-in-swagger)

I've crawling the docs and I can't see a way to currently handle a file upload.

Have you guys needed to do such thing? Do you simply use a `String` field and base64 encode everything, and write it as text in the description of your service ?

**Comment by raphael** [comment]
This is something on the roadmap (support for different encodings and transports). Today you'd have to do what you something like you describe (have the client encode in JSON).

**Comment by raphael** [comment]
There is now proper file server support in goa.
