### ISSUE TITLE
goagen: How about move `end_implement` mark to the end of function definition?

### ISSUE THREAD

**Issue by tanatana** [goadesign/goa#1462]
Currently, `end_implement` mark is placed before response creation and return statement. In many cases, I delete them and rewrite them newly before the mark.

So when  we use `goagen main --regen`, response creation and return statement are re-generated and break the source code.

I feel it is better that put `end_miplement` mark at the end of function definition.

**Comment by raphael** [comment]
If I understand correctly you would like the response creation and return statement to be generated once in the block but then not generated if the block already exists? That makes sense, would be happy to merge a PR that did that.

**Comment by raphael** [comment]
I believe this can be closed?

**Comment by tugusuke** [comment]
Yes, sorry I forgot to inform you. Thank you!

**Comment by tanatana** [comment]
Yes, sorry I forgot to inform you.

**Comment by raphael** [comment]
Thank you for the great contribution!
