### ISSUE TITLE
LogAdapter implementation for the standard logger ?

### ISSUE THREAD

**Issue by agnivade** [goadesign/goa#1477]
The documentation says -

```
goa comes with a number of LogAdapter implementations for common logging packages including the standard logger, log15, logrus and the go-kit logger.
```

However, I could not find any implementation of the standard logger. Am I missing something or do I have to implement the standard logger myself ?

This is a great project btw. Thanks !

**Comment by raphael** [comment]
Thank you for the kind words! The standard logger is the default logger used by goa, see https://github.com/goadesign/goa/blob/master/logging.go#L36

**Comment by agnivade** [comment]
Ah I see. Didn't realise it was inside the `goa` package.
