### ISSUE TITLE
Parameters with regex validations causing panic in generated tests if invalid input passed in

### ISSUE THREAD

**Issue by lsh246** [goadesign/goa#1482]
If you create a parameter to an endpoint, and give the parameter a regex validation, the test functions all panic if you pass in something that fails the regex validation, rather than giving an error. If a payload attribute has a regex validation pattern, the auto generated test validates the attributes. Seems like it should validate the parameters also.

This modified Goa-cellar demonstrates the issue. See modified files:

controllers/bottle_test.go
design/resources.go
design/user_types.go

I added a validation to a parameter on the bottle payload to demonstrate that that validates without a panic, and I added a test param to the create bottle endpoint with a validation to demonstrate the panic. Both are executed in bottle_test.go -> TestCreateBottle()

[goa-cellar.zip](https://github.com/goadesign/goa/files/1587597/goa-cellar.zip)

**Comment by lsh246** [comment]
Also, perhaps this is a second issue, but shouldn't calling CreateBottleBadRequest with an invalid payload attribute, as well as an invalid param, succeed? Instead, it fails with an error. Aren't those both bad requests?

**Comment by raphael** [comment]
Thanks for the report! #1484 fixes the bug. The `CreateXXX` functions return an error in case of an invalid payload so that the test helpers know not to call the controller code in that case as the input would be invalid. This is mirroring the behavior of the (non test) generated code.
