### ISSUE TITLE
Thrift Support

### ISSUE THREAD

**Issue by quannh25595** [goadesign/goa#1483]
Hi. I'm using this with Apache Thrift. Therefore I need to parse the data between goa's Type/MediaType struct and Thrift's struct. Is there anyway that we can intergrate them together so that no parsing is needed anymore? Thanks.

**Comment by raphael** [comment]
That's a good feature request for v2 which is designed to support multiple transport. To be clear though: would it be enough if the `.thrift` files were generated from the goa design or do you also need to consume pre-existing Thrift interface definitions?

**Comment by quannh25595** [comment]
> the .thrift files were generated from the goa design
I can't get it. `.thrift` files should be generated by the thrift tool,  not by goa, right? Do you mean if it would be enough if goa handles with the generated thrift or goa also handles with `.thrift` interface definitions files? In this case, according to me, I'll go with the first one. The second also sounds cool, but I think it gonna be a little bit harder to implement.
