### ISSUE TITLE
Support `Consumes()` and `Produces()` DSL

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#149]
The idea is to support mimetypes other than `application/json`, which is hard-coded right now (at least in the swagger generation).

`application/json` could be the default, but specifying `Consumes()` at the `API()` or `Action()` level could override the fallback value, and you could add one or more of those mime types.

When generating the `app`, we could do all the magic and validation when `application/json` is present,
but otherwise leave the user free to do all the unmarshalling / reading the body if it's not `application/json`..

What do you think ?

**Comment by raphael** [comment]
Agreed, I was envisioning a modular system where encoders/decoders could be registered with goa and associated with content-types. goa would then implement a content type negotiation algorithm where preferred content-type encodings could be specified. goa would come with a set of supported encodings (proabably JSON and form encoding to start with). The client generation code could also take advantage of that information to use the proper encoding when building requests.

**Comment by derekperkins** [comment]
@raphael We never discussed how our code interacts with `Produces` and `Consumes`. Does it need to?

**Comment by raphael** [comment]
It would be nice if `goagen` generated code that setup the encoders / decoders according to the spec. The tricky thing is that `goa` cannot have all possible encoders built-in but that may work for common cases (JSON, XML, octet-stream, others?)

**Comment by derekperkins** [comment]
We should at least be able to do that for built-in / `goa-middleware` versions. As it stands, `json`, `xml` and `gob` are all supported by default and you'd have to manually override them with `app.SetEncoder` or `app.SetDecoder` to turn them off. That'd get annoying pretty quickly.

**Comment by raphael** [comment]
Closing this as the DSL now supports [Consumes](https://godoc.org/github.com/goadesign/goa/design/apidsl#Consumes) and [Produces](https://godoc.org/github.com/goadesign/goa/design/apidsl#Produces)
