### ISSUE TITLE
mux.Lookup() doesn't work for paths with a parameter 

### ISSUE THREAD

**Issue by Ashtonian** [goadesign/goa#1494]
Hello I was wondering if you would be able to direct me in the right direction. The end goal is to find the handler for a path with a parameter in it for example `/api/someresource/{id}/somedetail`. It seems that the `mux.Lookup()` function doesn't do that, and I'm having a hard time finding where that logic is being handled - would you be able to point me in the right direction?

**Comment by raphael** [comment]
Just to be clear is this with `v1` or `v2`?

**Comment by Ashtonian** [comment]
v1 

```
"checksumSHA1": "4WRCAIvTGNkzkEpPxlL/bOc+U3U=",
"path": "github.com/goadesign/goa",
"revision": "5646a430cdeb66983d5ace3384e0a667c185abc7",
"revisionTime": "2017-08-25T05:29:01Z"
```

**Comment by raphael** [comment]
Sanity check: have you tried `/api/someresource/:id/somedetail`? `v1` uses the `:param` notation and `v2` the `{param}` notation.

**Comment by Ashtonian** [comment]
I'm sorry, I wasn't clear so I'm trying to find the handle for an actual route so i'm passing the real path into the lookup function so `mux.Lookup("api/somereouce/1/somedetail")` and that doesn't work. I'm assuming because it needs to be cleaned up a bit, and I'm trying to figure out how goa does that for regular requests.

**Comment by raphael** [comment]
Ah ok yeah the argument given to `Lookup` needs to be `api/someresource/:id/somedetail` where `:id` is whatever notation is used in the design. Looking at the [goa-cellar](https://github.com/goadesign/goa-cellar) example, this the generated call to the `Handle` function that populates the mux `handlers` field:

Generated call:
https://github.com/goadesign/goa-cellar/blob/master/app/controllers.go#L87

`Handle` method:
https://github.com/goadesign/goa/blob/HEAD/mux.go#L71

`Lookup` then uses that path:
https://github.com/goadesign/goa/blob/HEAD/mux.go#L95

**Comment by Ashtonian** [comment]
awesome, but where in goa do you take a request path `api/someresource/1/somedetail` and turn it into `api/someresource/:id/somedetail` so that you can get the correct handler?

**Comment by raphael** [comment]
Unfortunately that's not available to you - this is done in the code of the router (package [httptreemux](https://github.com/dimfeld/httptreemux)). What you can do is use the [wildcard regular expression](https://github.com/goadesign/goa/blob/master/design/api.go#L79) to iterate through all routes and see which one matches.
