### ISSUE TITLE
Add gRPC support

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#1499]
Implement gRPC transport for v2, see

https://github.com/goadesign/goa/blob/56b3e98091713990b084a93deb3ffac5914bba3a/DESIGN_PRINCIPLES.md

**Comment by kumarsiva07** [comment]
Is this dependent with go-kit?

**Comment by raphael** [comment]
no but it should be compatible in the end

**Comment by BigJoe01** [comment]
Have any roadmap or planned release date?

**Comment by sulthonzh** [comment]
Hi, is gRPC released at v2? but why GRPC function is undifined?

**Comment by raphael** [comment]
Not released yet

**Comment by SantoshSah** [comment]
@raphael , any tentative date for release of V2?

**Comment by raphael** [comment]
We've been working hard at it - hopefully  v2 will be fully ready in the next couple of weeks!
