### ISSUE TITLE
Is there a way to specify Required property in a particular view ?

### ISSUE THREAD

**Issue by agnivade** [goadesign/goa#1503]
If I have a media type like this - 

```go
var PersonMedia = MediaType("application/vnd.goa.person+json", func() {
	Description("Response body of a person")
	Reference(PersonPayload)
	Attributes(func() {
		Attribute("id", Integer, "ID of person", func() {
			Example(1)
		})
		Attribute("name")
		Attribute("phone_no")
		Attribute("email")
		Required("id", "name", "phone_no", "email")
	})
	View("default", func() {
		Attribute("id")
		Attribute("name")
	})
	View("student", func() {
		Attribute("id")
		Attribute("name")
		Attribute("phone_no")
		Attribute("email")
	})
	View("teacher", func() {
		Attribute("id")
		Attribute("name")
		Attribute("email")
	})
})
```

Is it possible for the different views generated to have different sets of required properties ? For eg. I want the student view to have id and email as required, and the teacher view to have id and name as required. From the docs, I see that `Required can be used in: Attributes, Headers, Payload, Type, Params`.

The reason I ask because all non-required properties convert to pointer types in the generated struct. So as a result, I have a mix of pointer and non-pointer types which makes it very confusing to code. I can understand that without pointer types, all types will be set to their nil values which makes it difficult to differentiate between value-not-set and nil-value-set. But, if I can specify required types for each view then I can atleast set the required types from the code without converting them to pointers.

**Comment by raphael** [comment]
No this is not supported. The idea is that attribute requiredness is a property of a type and not a representation of the type. If different attributes are required for different views then you have to create different types, each with their own list of required attributes. What you can do here is leverage `Reference` and define a type with all the attributes where none is required. I see you already refer to the payload type so I guess you already know how to do that :)

**Comment by agnivade** [comment]
I see. Thanks. Great project btw. :)

**Comment by raphael** [comment]
Thank you! :)
