### ISSUE TITLE
Head comment in go files suddenly has changed value for --out line

### ISSUE THREAD

**Issue by dkeza** [goadesign/goa#1505]
This is not so important, but I can't figure it out, why it suddenly happens.
My version of app/contexts.go file in source repository, before calling 
goagen from command prompt:

```
D:\keza\code\develop\go\src\citadel\deskapi
λ goagen bootstrap -d citadel/deskapi/design

```
looks so:
```
// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "deskapi": Application Contexts
//
// Command:
// $ goagen
// --design=citadel/deskapi/design
// --out=$(GOPATH)\src\citadel\deskapi
// --version=v1.3.1

package app
```
and after goagen
```
// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "deskapi": Application Contexts
//
// Command:
// $ goagen
// --design=citadel/deskapi/design
// --out=D:\keza\code\develop\go\src\citadel\deskapi
// --version=v1.3.1

package app
```
--out line is now changed, and I don't know why. I didn't changed version of Go (1.9.2). I am using Windows 10 (10.0.16299.192) 64 Bit.

Now I have bunch of differences in many go files which I must commit to source repository, but I changed nothing, just called goagen.
go build works as usual.

**Comment by raphael** [comment]
The code that generates the header comment hasn't changed recently, you can see it here: https://github.com/goadesign/goa/blob/af615d5c3a6f02fb14b0952343cadcb2e6c5dabf/goagen/codegen/helpers.go#L30:6
It reads the `GOPATH` environment variable and checks whether the output path prefix matches it and if so replaces it with `$(GOPATH)`. So it seems that for some reason when this code runs the output path prefix does not match the value of the `GOPATH` environment variable.

**Comment by dkeza** [comment]
Now it works again properly. I have suspecting that goagen binary somehow doesn't see GOPATH environment variable, but how this was possible, I don't know.
Maybe it has to do with Windows 10 update, or quirks with [Cmder](http://cmder.net/), who knows?
