### ISSUE TITLE
"Required" validation doesn't work if there is only one attribute required

### ISSUE THREAD

**Issue by Ashtonian** [goadesign/goa#1507]
It seems that the validator is never generated for required fields if there is only one required field. 

```go 
var Request = Type("exampleRequest", func() {
	Attribute("id", Integer, "")
	Attribute("startTime", DateTime, "")
	Attribute("endTime", DateTime, "")

	Required("id")
})
```

Hitting it with `CURL -d '{}' http://localhost:8080/api/bug` returns a 200 instead of a 400.  

Upon further investigation - .Validate() call in unmarshall code inside of controllers.go is not generated if there is only one required primitive property and no actual validations for that property. This seems like it's a bug. It's found at goa/goagen/gen_app/writers.go:781.

Following that up the stack we get to the comment in goa/goagen/codegen/validation.go:269-274 which seems to allude to and attempt to deal with this edge case. From there, I had a bit of trouble following the code. I've also made a repository to demonstrate this. See https://github.com/Ashtonian/goa-bug-repro

**Comment by raphael** [comment]
Thank you for the detailed report! That does sound like a bug, will look into it.

**Comment by raphael** [comment]
Thank you, this is now fixed.

**Comment by Ashtonian** [comment]
awesome thanks!
