### ISSUE TITLE
Param Example() not working

### ISSUE THREAD

**Issue by miguelmota** [goadesign/goa#1509]
I've tried the following and it didn't show in the swagger docs:

```	go
  Params(func() {
    Param("myparam", String, "My Param", func() {
     Example("foobar")
    })
```

Does goa support examples for path params?

Thanks

**Comment by raphael** [comment]
Please can you provide a complete example, and a snippet showing what you would expect where exactly? thank you!

**Comment by miguelmota** [comment]
Here's a full snippet from my `design.go`

```go
Action("orderStatus", func() {
  Description("Get order status")
  Routing(GET("/orders/:orderId"))
  Params(func() {
    Param("orderId", String, "Order ID", func() {
      Pattern("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")
      Example("f242c453-e323-4161-afc2-e665a3a5340d")
    })
  })
  Response(OK, OrderMedia)
})
```

and here's a screenshot of swagger docs showing that the example value is not being shown

<img width="637" alt="screen shot 2018-02-11 at 7 45 49 pm" src="https://user-images.githubusercontent.com/168240/36083129-86c282c2-0f64-11e8-89d2-b91c035d6616.png">

Expected:

Example value (`f242c453-e323-4161-afc2-e665a3a5340d`) to show in input field.

**Comment by raphael** [comment]
Just looked and can confirm there's no way to set an example for params in Swagger 2.0, see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject.
