### ISSUE TITLE
Links example in goa Overview is incorrect

### ISSUE THREAD

**Issue by MarkSonghurst** [goadesign/goa#1511]
Thanks a great approach to API design and implementation, which I'm now learning with the aim to put into production use. I'm currently trying to get my head around how Links work.

There appears to be a bug in the [Overview Links]( https://goa.design/design/overview/) example code 

```
View("default", func() {   // Defines the default view
        Attribute("value")     // Includes the "value" field in the default view
        Links()                // And render links
    })
```

The empty call to Links() doesn't pass goa bootstrap.
Please can the example be updated so I can understand how Links work?

Many thanks

**Comment by raphael** [comment]
Thank you for pointing that out! the proper way to render links is to add an attribute named `links` to the view (this is shown in the MediaType [godocs](https://godoc.org/github.com/goadesign/goa/design/apidsl#Links) example). This is now fixed in the overview page as well.
