### ISSUE TITLE
goa v2: Error() in service section generates improper code

### ISSUE THREAD

**Issue by psschroeter** [goadesign/goa#1526]
branch: v2 (master)
Error() in Service() section generates bad code. I.e. compiling with the code generates errors like:
gen/http/dummy/client/types.go:29:47: undefined: dummysvc.Error
gen/http/dummy/client/types.go:30:8: undefined: dummysvc.Error

If the same Error() is specified in a Method() section, everything seems to work fine.

Example gist:
https://gist.github.com/psschroeter/620b06b655f67df0fa54cf51b394445a

**Comment by raphael** [comment]
This should be fixed in the latest v2 - can you please verify and if so close this ticket? thank you!

**Comment by psschroeter** [comment]
Works now, thanks
