### ISSUE TITLE
goa v2: Response in Service() section segfaults

### ISSUE THREAD

**Issue by psschroeter** [goadesign/goa#1527]
Response in Service() section segfaults in some DupAttribute method of goa gen. Same Response in Method() section seems to work as expected.

Example code:
https://gist.github.com/psschroeter/620b06b655f67df0fa54cf51b394445a

**Comment by raphael** [comment]
This should be fixed in the latest v2 - can you please verify and if so close this ticket? thank you!

**Comment by psschroeter** [comment]
Works now, thanks
