### ISSUE TITLE
Goa v2: openapi.json missing alternate return codes

### ISSUE THREAD

**Issue by psschroeter** [goadesign/goa#1528]
The openapi.json appears to be missing the error return codes.

Example gist:
https://gist.github.com/psschroeter/620b06b655f67df0fa54cf51b394445a

In the example gist, I expect the Dummy.Index() method to list 200 OK and 422 UnprocessibleEntity as possible return codes, but it only has the 200 OK in there.

**Comment by raphael** [comment]
Thank you this is now fixed.
