### ISSUE TITLE
goa v2: optional booleans code generation error

### ISSUE THREAD

**Issue by psschroeter** [goadesign/goa#1535]
See example gist:
https://gist.github.com/psschroeter/dca69aa15ad9a08805799727060accca

Do "goa generate" then "go build ./cmd/dummysvc", which generates an error:
```
# tmp/gen/http/dummy/server
gen/http/dummy/server/types.go:116:8: cannot use val.Foo (type bool) as type *bool in field value
```
Seems like it's messing up whether its the type or a pointer to the type somewhere in the generation logic.

**Comment by raphael** [comment]
Thank you for providing a complete design to repro, I see the error - looking into it.

**Comment by raphael** [comment]
This is now fixed.
