### ISSUE TITLE
Swagger site not working

### ISSUE THREAD

**Issue by kwk** [goadesign/goa#1538]
Hi,

we used to use http://swagger.goa.design/?url=fabric8-services%2Ffabric8-wit%2Fdesign# to have our swagger definition generated.

Now we get an error saying: "Can't read from server. It may not have the appropriate access-control-origin settings."

![bildschirmfoto von 2018-02-14 12-45-03](https://user-images.githubusercontent.com/193408/36202660-fbb5babe-1184-11e8-8bbf-1cc888d9fa66.png)

Is this an expected behavior?

Regards
Konrad

**Comment by kwk** [comment]
I started to work again. It would be nice to know if there was an issue.

**Comment by raphael** [comment]
There was - basically the backend is using Google Flexible Appengine and they changed how the configuration works for it. They ended up killing the old server January 31st forcing people to update the config which I have now done. Thank you for the report!
