### ISSUE TITLE
erroneous error on goa gen

### ISSUE THREAD

**Issue by dgaedcke** [goadesign/goa#1554]
## Expected Behavior
expected to generate successfully

## Actual Behavior
goa gen github.com/dgaedcke/nmg_admin_service/design
exit status 1
service "News" method "create": field newsEntityType - defines a view but is not a result type
service "News" method "create": field postedDtTm - defines a view but is not a result type
attribute: field newsEntityType - defines a view but is not a result type
attribute: field postedDtTm - defines a view but is not a result type
make: *** [gen] Error 1

## Steps to Reproduce the Problem (including complete and simple design if relevant)
goa gen on the attached design doc

## Specifications

  - goa Version: V2
  - Platform (Linux/Windows etc.):  MacOS
[GoaV2DesignExample.zip](https://github.com/goadesign/goa/files/1764789/GoaV2DesignExample.zip)

**Comment by raphael** [comment]
Thank you for the report, this is now fixed in the latest v2.
