### ISSUE TITLE
Metadata("struct.field.external", "-") not ignoring field on CopyTo()

### ISSUE THREAD

**Issue by dgaedcke** [goadesign/goa#1557]
## Expected Behavior
in this DSL
	ConvertTo(admin.NewsDS{})

	Attribute("newsEntityType", String, "newsEntityType", func() {
		Enum(enum.Values("NewsType")...)
		// this att intentionally omitted from convertTo
		// proper enum type in admin.NewsDS{}
		Metadata("struct.field.external", "-")
	})

Metadata("struct.field.external", "-") should ignore field on CopyTo()

## Actual Behavior
getting the following data type mismatch error:
	return fmt.Errorf("types don't match: type of %s is %s but type of corresponding attribute is %s", rec.path, to.Name(), from.Name())

## Steps to Reproduce the Problem (including complete and simple design if relevant)
when you look in:
shared/models/admin/news.go
you will see these field types:
	NewsEntityType enum.NewsType `datastore:"newsType"` // newsLevel: app, event, game, team
	PostedDtTm     time.Time     `datastore:"postedDtTm, noindex"` // time.Time

note that the data-types are DIFFERENT from the API payload (both string)
This should not be a problem to the CopyTo() function but it is....

try 
[GoaV2DesignExample.zip](https://github.com/goadesign/goa/files/1769928/GoaV2DesignExample.zip)

**Comment by dgaedcke** [comment]
the shared repo from Github DOES NOT have the correct news.go file to demo the problem
you must use the one in the enclosed ZIP to reproduce....

**Comment by dgaedcke** [comment]
or you can edit the struct data-types yourself.....

**Comment by raphael** [comment]
Thanks for the report, this is now fixed.
