### ISSUE TITLE
Conflicting marshal methods for imported attribute types

### ISSUE THREAD

**Issue by andrewalonis** [goadesign/goa#1568]
## Expected Behavior

Should be able to import the same type for multiple attributes.

## Actual Behavior

When importing the same type for multiple attributes within a design type, it generates conflicting methods with identical names.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

Something like this...

```go
var result = ResultType(func() {
   Attributes(func() {
       Attribute(“created_by”, imported.User)
       Attribute(“updated_by”, imported.User)
   })\n
})
```

... generates two methods `marshalUserToUser` in .../encode_decode.go that conflict.

## Specifications

  - goa Version: V2
  - Platform (Linux/Windows etc.): OSX

**Comment by raphael** [comment]
@andrewalonis were you able to test the fix done by @nitinmohan87 ? Can this be closed?

**Comment by andrewalonis** [comment]
This fixed it. Closing the issue.
