### ISSUE TITLE
Goa v2: missing security scopes from openapi.json

### ISSUE THREAD

**Issue by psschroeter** [goadesign/goa#1577]
This is for latest goa v2. For a security scheme like:

```
var JWT = JWTSecurity("JWT")
Method("foo", func() {
	Security(JWT, func() {
		Scope("foo:read")
	})
        ...
```

Would expect the "foo:read" scope to show up in the openapi.json. Right now nothing is showing up.

**Comment by nitinmohan87** [comment]
Should be fixed in this - https://github.com/goadesign/plugins/pull/15
