### ISSUE TITLE
How to vendor goagen using dep instead of glide?

### ISSUE THREAD

**Issue by Danlock** [goadesign/goa#1587]
https://goa.design/design/vendoring/ shows how to vendor the goagen dependency using glide, but I am trying to do the same with dep and I noticed the .gitignore file that ignores the entire goagen/ directory.

Doesn't this prevent the ability to vendor the goagen dependency? And if it doesn't please let me know how to vendor it using dep.

I just got bit by my docker build using a newer version of goagen than I was locally, and it took me a while to figure it out.

**Comment by MarkSonghurst** [comment]
I've managed to get it working using Goa v1 with this code in my Gopkg.toml

```
required = ["github.com/goadesign/goa/goagen", 
  "github.com/goadesign/goa/goagen/gen_app", 
  "github.com/goadesign/goa/goagen/gen_client", 
  "github.com/goadesign/goa/goagen/gen_controller", 
  "github.com/goadesign/goa/goagen/gen_js", 
  "github.com/goadesign/goa/goagen/gen_main", 
  "github.com/goadesign/goa/goagen/gen_schema",
  "github.com/goadesign/goa/goagen/gen_swagger"]
```
