### ISSUE TITLE
Goa gen v2 Payload Extend has no effect

### ISSUE THREAD

**Issue by dotLou** [goadesign/goa#1603]
## Expected Behavior
Payload is extended with attributes from the Payload specified in `Extend()`
## Actual Behavior
Payload is not extended, compilation fails if expecting those items in the payload

## Steps to Reproduce the Problem (including complete and simple design if relevant)

`goa gen testing/design`

`design.go`:
```go
package design

import . "goa.design/goa/http/design"
import . "goa.design/goa/http/dsl"

// API describes the global properties of the API server.
var _ = API("collections", func() {
	Title("collections Service")
	Description("HTTP service for the collections resource")
})

// PayloadA is the payload to be used to extend PayloadB
var PayloadA = Type("PayloadA", func() {
	Attribute("a", String)
})

// PayloadB should be extended by the attributes of PayloadA
// If you comment out the "a" attribute in PayloadB, `goa gen` does not work
var PayloadB = Type("PayloadB", func() {
	Attribute("b", String)
	// Attribute("a", String)
	Extend(PayloadA)
})

var _ = Service("service", func() {
	Method("do", func() {
		Payload(PayloadB)
		Result(Int)
		HTTP(func() {
			GET("/service/{a}/{b}")
			Response(StatusOK)
		})
	})
})

```

## Specifications

  - goa Version: v2, latest branch (specifically 8ae8493dac8f54248c5d540a15ea694944ca7144)
  - Platform (Linux/Windows etc.): Mac
  - go version go1.10 darwin/amd64

**Comment by raphael** [comment]
Interesting, I'm getting this error when trying to generate from this design:
```
service "service" HTTP endpoint "do": Param "a" is not found in Payload.
```
which is also a bug but seems different?

**Comment by dotLou** [comment]
Oops, I meant to include that in my initial report. I also get the same error when I try that:

```exit status 1
service "service" HTTP endpoint "do": Param "a" is not found in Payload.```
