### ISSUE TITLE
Path parameter parser incorrectly matches URL suffix as parameter if parameter is empty.

### ISSUE THREAD

**Issue by gfl-chris** [goadesign/goa#1614]
## Expected Behavior
If a path parameter is empty, the path parameter value should be an empty string. For example, an action defined with the route:
```
Routing(GET("/foobar/:foobar/bazbar"))
...
Param("foobar", String)
...
```
invoked with the URL
```
/foobar//bazbar
```
should bind an empty string to the `foobar` parameter.

## Actual Behavior
The string value `bazbar` is bound to `foobar`.

## Steps to Reproduce the Problem (including complete and simple design if relevant)
Example above.

## Specifications

  - goa Version: 5646a430cdeb66983d5ace3384e0a667c185abc7
  - Platform (Linux/Windows etc.): Linux

**Comment by raphael** [comment]
I'm not sure the underlying router supports this. But even if it did that seems like a pretty awful way to design an API :) There seems to be too many ways this could go wrong (any proxy or NAT that sanitizes URLs would get rid of the double slash). Is there a reason you can't make `:foobar` a query string parameter which would be the proper way to implement optional parameters in URLs.

**Comment by gfl-chris** [comment]
Well, there are two issues going at the same time. :)

The parameter isn't optional, but due to a bug in a client application it provided an empty string. (That's on me not properly validating arguments on the client side.) Yet, there seems to be a parser bug because

a.) it ended up in the correct action, but
b.) it bound the path suffix as the parameter value.
