### ISSUE TITLE
Example authorization stubs duplicated across files

### ISSUE THREAD

**Issue by andrewalonis** [goadesign/goa#1633]
## Expected Behavior

Generated example files have only the authorization stubs that apply to their service.

## Actual Behavior

When declaring multiple services within one design file, an authorization stub is created for all of the services in each of the service-specific example files.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

Example design:
```go_lang
var _ = API("MyAPI")

var _ = Service("MyFirstService", func() {
  Security(GlobalSession)
})

var _ = Service("MySecondService", func() {
  Security(GlobalSession)
})

var GlobalSession = JWTSecurity("GlobalSession")
```

When example files are generated, `MyFirstService.go` and `MySecondService.go` both have the same two authorization stubs:

```golang
func MyFirstServiceAuthJWTFn(...) {
}

func MySecondServiceAuthJWTFn(...) {
}
```

## Specifications

  - goa Version:
  - Platform (Linux/Windows etc.):

**Comment by raphael** [comment]
This was a security plugin bug, fixed in https://github.com/goadesign/plugins/pull/35
