### ISSUE TITLE
TypeName error "as invalid use of TypeName in attribute" from inside Type when running goa gen

### ISSUE THREAD

**Issue by joejarlett** [goadesign/goa#1638]
## Expected Behavior
`var coursesData = Type("CoursesData", func() {
    TypeName("Data")
}
`
Allowing a namespace like courses.Data instead of courses.CoursesData. 
This currently works in ResultType and is indicated to work in the Type from within the documentation.

## Actual Behavior
error on goa gen: 
"invalid use of TypeName in attribute"

## Steps to Reproduce the Problem (including complete and simple design if relevant)
include the above code in the design package and run goa gen

## Specifications
v2

**Comment by raphael** [comment]
This is now fixed, thank you!
