### ISSUE TITLE
Starting an identifier with a number causes massive unhelpful error message

### ISSUE THREAD

**Issue by Shenung** [goadesign/goa#1652]
## Expected Behavior
A clean error that explains that you cannot start an identifier with a number.

## Actual Behavior
Outputs a complete copy of the generated code with an error message pointing into the generated code.

## Steps to Reproduce the Problem (including complete and simple design if relevant)
Attempt to generate the app for this design:
`goagen app -d testsample/design`

```go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("test", func() {
	Title("Test")
})

var _ = Resource("2fa", func() { // This is the bad line
	BasePath("/auth/2fa")
	Action("enable", func() {
		Description("Creates 2 factor auth for user.")
		Routing(POST(""))

		Response(OK, "text/plain")
		Response(InternalServerError, ErrorMedia)
	})
})
```

## Specifications

  - goa Version: v1
  - Platform (Linux/Windows etc.): Windows

**Comment by raphael** [comment]
The generators dump the generated source when it's incorrect to help troubleshoot. This is a bug as the code should be generating a valid Go identifier even if the design does not. I probably won't look into it (focusing on v2) as it's not a blocker but happy to help put together a PR.
