### ISSUE TITLE
Got an error when setting a default value to the Param(Boolean)

### ISSUE THREAD

**Issue by MiCHiLU** [goadesign/goa#1664]
## Expected Behavior
The `Param` be settable a default value by `Default` in the Goa DSL.

## Actual Behavior
Set the `Param` to `true` by `Default`.
I got an error when `go build`, as below:
```shell
tool/cli/commands.go:239:34: cannot use true (type bool) as type string in argument to cc.Flags().StringVar
```
`tool/cli/commands.go:239` is below:
```go
	cc.Flags().StringVar(&cmd.Bool, "bool", true, ``)
```

## Steps to Reproduce the Problem (including complete and simple design if relevant)
`design.go`:
```go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("dummy", func() {
	Title(`Dummy API`)
})

var _ = Resource("dummy", func() {
	Action("get", func() {
		Routing(GET(""))
		Params(func() {
			Param("bool", Boolean, "", func() {
				Default(true)
			})
		})
		Response(OK)
	})
})
```

`goagen` and `go build`:
```shell
$ goagen client -d $(go list) && go build tool/dummy-cli/main.go
```

## Specifications
- goa Version: goagen v1.3.1 (3146386, 2018-04-04)
- Platform (Linux/Windows etc.): macOS 10.13.3 (17D102)
- go version go1.10.1 darwin/amd64

**Comment by raphael** [comment]
This should now be fixed, can you please confirm? thank you!

**Comment by MiCHiLU** [comment]
@raphael I have confirmed the fix now. Thank you so much!
