### ISSUE TITLE
How to use multipart file upload in v2?

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1665]
How to use multipart file upload in v2? I want upload a file to server.
![image](https://user-images.githubusercontent.com/7725174/38463909-9372852e-3b21-11e8-943e-f4017cb9b5c8.png)
```Method("upload", func() {
        Description("Upload menu")
        Payload(func() {
            Attribute("path", String, "Path to the file", func() {
                Metadata("server:file:path", "/tmp")
            })
        })
        HTTP(func() {
            POST("/upload")
            MultipartRequest()
            Response(StatusOK)
        })
    })```

Already raised this in slack channel too

**Comment by nitinmohan87** [comment]
@kumarsiva07 We have an example to implement multipart decoder and encoder - https://github.com/goadesign/goa/blob/v2/examples/cellar/design/storage.go#L86-L98
The code generator creates a multipart encoder and decoder stubs in the example service file which you must implement. https://github.com/goadesign/goa/blob/v2/examples/cellar/design/storage.go#L86-L98

I think for your needs you can implement the decoder similar to the example above and store the payload to a file using an io writer.

**Comment by kumarsiva07** [comment]
@nitinmohan87 Can you give an example with file upload? That example only have multiform with normal fields.

**Comment by nitinmohan87** [comment]
@kumarsiva07 I am not sure what you mean by "normal fields". Goa v2 generates both the multipart decoder and encoder stubs which you can implement as per your use case. The encoder gets an instance of [multipart writer](https://golang.org/pkg/mime/multipart/#Writer) and the payload and the decoder gets an instance of [multipart reader](https://golang.org/pkg/mime/multipart/#Reader) and the payload. The [multipart Part](https://golang.org/pkg/mime/multipart/#Part) type already implements `io` Reader. I believe you can simply create a file handler (which implements `io` Writer) and use `io` package to write to file?

**Comment by kumarsiva07** [comment]
https://github.com/goadesign/goa/blob/2bc548321403ce7cf441c2bb985fe197a0e638be/examples/cellar/design/storage.go#L89

How do I mention type File like `Attribute("ids", ArrayOf(String), "IDs of the bottles to be updated")` ?

**Comment by nitinmohan87** [comment]
@kumarsiva07 Why do you need a `File` type? Now, I am not sure what you are trying to do. Let me clarify. Are you trying to implement a service endpoint that receives a multipart request where each part contains contents of a file and you want to store the parts into a file on the server side? Are you trying to set the name of the file to be stored in the servier in the `Payload`? If yes, couldn't you use a string attribute (say `filename`) and use that field in the multipart encoder stub to [create a part with filename field](https://golang.org/pkg/mime/multipart/#Writer.CreateFormFile)? And in the mulitpart decoder you could just call https://golang.org/pkg/mime/multipart/#Part.FileName to retrieve the file name using which you can open a file handle on the server side and just write the part to the handler.

Please let us know in detail what exactly you are trying to do if you think my answers are not clearing things for you. I am sure my earlier comments would be sufficient to implement the decoders/encoders for uploading a file.

**Comment by MOstafaMRady** [comment]
Examples links are broken!
