### ISSUE TITLE
[enhancement] sensitive headers are being logged in middleware/log_request.go

### ISSUE THREAD

**Issue by adam-hanna** [goadesign/goa#1676]
First, thanks for the awesome work. Long-time user. Introduced it to our team a few months ago. Whole team loves it and we pretty much moved all of our api's over to goa.

Just have a quick suggestion. Wanted to pass it by the you / the community. Would be happy to open a PR.

We use `service.Use(middleware.LogRequest(true))` and we noticed some sensitive headers were being logged (basic auth, access tokens, etc).

A simple solution (but not one that's backwards compatible) could be to change the function definition to
` func LogRequest(verbose bool, suppressHeadersLower map[string]bool) goa.Middleware { `.  Then a minor change starting on line 65:

```
if len(r.Header) > 0 {
    logCtx := make([]interface{}, 2*len(r.Header))
    i := 0
    for k, v := range r.Header {
        logCtx[i] = k

        if suppressHeadersLower[strings.ToLower(k)] {
            logCtx[i+1] = "<secret>"
        } else {
            logCtx[i+1] = interface{}(strings.Join(v, ", "))
        }

        i = i + 2
    }
    goa.LogInfo(ctx, "headers", logCtx...)
}
```

**Comment by adam-hanna** [comment]
I'm on it!

**Comment by raphael** [comment]
haha I was still "fixing" my code :)
