### ISSUE TITLE
v2: Generated OpenAPI files does not adhere to JSON Schema

### ISSUE THREAD

**Issue by nicholaslam** [goadesign/goa#1692]
## Expected Behavior

Generated OpenAPI files adhere to JSON Schema.

## Actual Behavior

Generated OpenAPI files do not adhere to JSON Schema.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

From http://json-schema.org:

> For example, the “type” keyword can be used to restrict an instance to an object, array, string, number, boolean, or null

Example design:

``` go
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
	_ "goa.design/plugins/goakit"
)

var _ = API("things", func() {
	Title("things API")
	Description("Responsible for things")
	Version("1.0.0")
	HTTP(func() {
		Consumes("application/json")
		Produces("application/json")
	})
})

var _ = Service("things", func() {
	Method("create", func() {
		Payload(Bytes) // <-----
		Result(Int)
		Error("not_found", func() {
			Temporary()
		})
		HTTP(func() {
			POST("/things/{id}")
			Response(StatusOK)
			Response("not_found", StatusNotFound)
		})
	})
})

var _ = Service("openapi", func() {
	Files("/openapi", "../../gen/http/openapi.json")
})
```

Generated openapi.json snippet:

```
"schema": {
    "type": "bytes"
}
```

## Specifications

  - goa Version: v2
  - Platform (Linux/Windows etc.): mac

**Comment by raphael** [comment]
Thanks for the detailed report! This is now fixed.
