### ISSUE TITLE
goagen does not respect build tags

### ISSUE THREAD

**Issue by bontibon** [goadesign/goa#1696]
## Steps to Reproduce the Problem (including complete and simple design if relevant)

Try to run goagen bootstrap on a package that contains multiple packages, but protected by build tags.

## Expected Behavior

Build without error.

## Actual Behavior

```
# goagen009007601 bootstrap -d goatest/design
more than one Go package found in /tmp/goa/src/goatest/design (design,main)
```

## Specifications

  - goa Version: goagen v1.3.1
  - Platform (Linux/Windows etc.): Linux

**Comment by raphael** [comment]
Could you describe a little bit the use case here? adding support for this is feasible but a lot of extra complexity so want to make sure that there's a real need for it.

**Comment by bontibon** [comment]
I have two files in this folder:

- design.go (package design)
    - goa design file
    - contains a go:generate command (`go run generate_main.go`)
- generate_main.go (package main)
    - runs goagen (I am not able to simply call `goagen` using go:generate in `design.go`)

I could just put my `generate_main.go` file in a package that goagoa is not operating on, but I found it strange that my current setup did not work.

**Comment by raphael** [comment]
Makes sense. It is not a goal of `goagen` to support all the features of the Go compiler. In general design packages should only contain design code so the use case here seems a bit specific and I'm not sure the work involved in supporting build tags is worth it. Just curious: why does the `go:generate` tag not work when set in `design.go`?
