### ISSUE TITLE
Unable to fetch and install goa

### ISSUE THREAD

**Issue by puneetugru** [goadesign/goa#1701]
I'm trying to fetch and install goa on my Mac (OS: macOS Sierra 10.12.6) with below command,

go get -u github.com/goadesign/goa/...

But, I'm getting below error message,

package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: x509: certificate signed by unknown authority)

I've tried the same command multiple times and at different times spanning around 1 hour, but the issue still persists.

Any workaround for this?

**Comment by raphael** [comment]
Not sure what's going on here, maybe you can try to download the yaml package manually. In any case this is not a problem with goa so I'm closing this issue.
