### ISSUE TITLE
String Array element validation using Enum

### ISSUE THREAD

**Issue by eclipse1985** [goadesign/goa#1711]
The documentation says that Array elements can be validated like other elements. I'm trying to manage the simple case `/show?type=banana&type=apple` using `ArrayOf(String)` validation but I see that no validation code is actually generated in contexts.go file. 

```go
_ = API("test", func() {
	Host("localhost:8080")
	Scheme("http")
})

var _ = Resource("test", func() {
	Action("show", func() {
		Routing(GET("show"))
		Params(func() {
			Param("type", ArrayOf(String, func() {
				Enum("banana", "apple")
			}))
		})
		Response(OK, "text/plain")
	})

})
```

  - goa Version: 1.3.1
  - Ubuntu 16.04

**Comment by raphael** [comment]
Thanks for the detailed report! this is now fixed.
