### ISSUE TITLE
Add ability to design HTTP cookies

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#1717]
Make it possible to use `cookie` when designing the HTTP transport of a method, e.g.:

```go
	Method("display", func() {
		Payload(func() {
			Attribute("value", String, "Value to display")
			Attribute("session", String, "Session ID")
			Required("value", "session")
		})
		Result(func() {
			Attribute("session", String, "Session ID")
		})
		Error("invalid")
		HTTP(func() {
			GET("/display/{value}")
			// Read "session" attribute value from HTTP cookie named "SessionID"
			Cookie("session:SessionID")
			Response(func() {
				Status(StatusOK)
				// Write back session cookie
				Cookie("session:SessionID", func() {
					Path("/foo")
					Domain("foo.com")
					MaxAge(3600)
					Secure(true)
					HTTPOnly(true)
				})
			})
			Response("invalid", func() {
				Status(StatusBadRequest)
				// Write back session cookie
				Cookie("session:SessionID", func() {
					Path("/foo")
					Domain("foo.com")
					MaxAge(3600)
					Secure(true)
					HTTPOnly(true)
				})
			})
		})
	})
```

The generated code should check the request cookie expiration and skip reading the value if expired (if the attribute is required this results in a bad request). The DSL function in the `Cookie` expression in the `Response` is optional.

**Comment by raphael** [comment]
@tchssk is that something that seems interesting to you to implement?

**Comment by tchssk** [comment]
OK. I'll give it a try.

**Comment by raphael** [comment]
Great! thank you.

**Comment by tchssk** [comment]
It seems we have to define a struct `CookieData` in `http/codegen`, and add a field `Cookies` typed `[]*CookieData` to `RequestData` in `http/codegen`. Is this correct?

**Comment by sachnk** [comment]
Hi @raphael 

Until this is implemented, what's the recommended approach to handle cookie processing with Goa? I'm familiar with implementing session lookups from a given cookie with Gorilla, Echo, etc. But how does one do it with Goa?

**Comment by yyoshiki41** [comment]
@raphael 

I also need handle cookies.
https://github.com/goadesign/goa/issues/1717#issuecomment-435457548

**Comment by raphael** [comment]
Cookie support was added in 3.2.0, see https://pkg.go.dev/goa.design/goa/v3@v3.2.0/dsl?tab=doc#Cookie

**Comment by yyoshiki41** [comment]
@raphael 

Sorry, bother you.
Thanks!!
