### ISSUE TITLE
Optional Attributes with Default value are no longer optional

### ISSUE THREAD

**Issue by douglaswth** [goadesign/goa#1731]
## Expected Behavior

I would expect the client struct for a type that has optional attributes with default values to have the type of those attributes be pointers so `nil` can be passed in so that defaults will be filled in on the server side.

## Actual Behavior

The client struct for a type that has optional attributes with default values just has the normal types for attributes which means that I cannot leave them unset. However, the behavior for optional attributes without default values seems to be correct with pointer types instead of normal types.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

With the given file `design/public/types.go`:

```golang
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var JWTBearerParams = Type("JWTBearerParams", func() {
	Attribute("alg", String, "The cryptographic algorithm to use when computing signatures", func() {
		Enum("RS256")
		Default("RS256")
		Example("RS256")
	})
	Attribute("aud", String, "Identifies the authorization server as an intended audience. Defaults to value of \"token_url\".", func() {
		Example("https://www.googleapis.com/oauth2/v4/token")
	})
	Attribute("max_minutes", Integer,
		"Maximum time, in minutes, that signer token should remain valid before needing refresh. "+
			"Authorization services may differ on the allowed time limit. Defaults to one hour", func() {
			Default(60)      // hour
			Minimum(30)      // refresh at most once every 15 minutes (max_minutes/2)
			Maximum(24 * 60) // day
		})
})
```

You get the following ``:

```golang
// JWTBearerParams user type.
type JWTBearerParams struct {
	// The cryptographic algorithm to use when computing signatures
	Alg string `form:"alg" json:"alg" xml:"alg"`
	// Identifies the authorization server as an intended audience. Defaults to value of "token_url".
	Aud *string `form:"aud,omitempty" json:"aud,omitempty" xml:"aud,omitempty"`
	// Maximum time, in minutes, that signer token should remain valid before needing refresh. Authorization services may differ on the allowed time limit. Defaults to one hour
	MaxMinutes int `form:"max_minutes" json:"max_minutes" xml:"max_minutes"`
}
```

## Specifications

  - goa Version: v1.3.0
  - Platform (Linux/Windows etc.): Windows

**Comment by raphael** [comment]
Make sense, this looks like a bug. The fields shouldn't be pointers in types that result from unmarshaling (payload fields server side and result fields client side) but should be pointers otherwise.

**Comment by douglaswth** [comment]
Probably shouldn't have a `v2` label as this is in `v1`. 😉

**Comment by raphael** [comment]
Looked more into it and I understand the issue however I'm not sure we can change the behavior at this point in `v1`. This would be a breaking change that affects all current users. As there is a workaround (set the default value in the client struct) I'm going to close this issue. Will make sure `v2` does not have this problem.
