### ISSUE TITLE
Support text/html response

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1757]
Now all the responses encoded as json, xml or gob. There is no support for html. All the html tags are encoded like `\u003cdiv id='`

**Comment by nitinmohan87** [comment]
@kumarsiva07 You can have your own decoder/encoder passed in to the server and client - https://github.com/goadesign/goa/blob/v2/examples/cellar/cmd/cellarsvc/main.go#L89-L90
I think that will work for you.
