### ISSUE TITLE
Need to support date and date time data type in design.

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1763]
Need to support date and date time data type in design.
Now we are using string to get date and date time. But this needs to be converted inside app.

**Comment by raphael** [comment]
This request comes up often but we are not planning on adding this built-in in v2 at this point. Adding types to the type system is a lot of work initially and on an on-going basis (plugins need to support it, all transports need to support it etc.). The recommended approach is to use the appropriate date format and to do the transformation in the service method. goa takes care of validating the format so the service method does not need to do error handling.
