### ISSUE TITLE
Body is not working in response 

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1767]
I have Result payload with response_string attribute.
![image](https://user-images.githubusercontent.com/7725174/41767306-e3dfeba6-7626-11e8-8c1d-ad1e9b6a4840.png)

`Response(StatusOK, func() {
				Header("content_type:Content-Type")
				Body("response_string")
			})`

`tracker/gen/http/form/server/encode_decode.go:199:14: res.ResponseString undefined (type *views.FormPage has no field or method ResponseString)
`

**Comment by nitinmohan87** [comment]
Thanks for the bug report! Your issue should be fixed by the commit above.
