### ISSUE TITLE
Example service does not match generated interface

### ISSUE THREAD

**Issue by ccrossley** [goadesign/goa#1770]
running `goa example` produces a service which does not satisfy the generated service interface.

The DSL at the bottom of this issue will generate the following code:

./gen/service_body_multiple_view/service.go:

`// Service is the ServiceBodyMultipleView service interface.
type Service interface {
	// MethodBodyMultipleView implements MethodBodyMultipleView.
	MethodBodyMultipleView(context.Context, *MethodBodyMultipleViewPayload) (res *Resulttypemultipleviews, err error)
}`

./service_body_multiple_view.go:

`func (s *serviceBodyMultipleViewSvc) MethodBodyMultipleView(ctx context.Context) (res *servicebodymultipleview.Resulttypemultipleviews, view string, err error) {
     ...
}`

Please fill the sections below:

## Expected Behavior
`goa example` produces functioning code
## Actual Behavior
`goa example` produces code incompatible with `goa gen`
## Steps to Reproduce the Problem (including complete and simple design if relevant)
`goa gen` then `goa example` and observe compile errors
## Specifications
  - goa Version: v2.0.0-wip
  - Platform OSX 10.13.2

Example DSL:

```
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

var _ = API("goa-bug-repros", func() {
	Title("GOA-Bug-Repros")
	Description("For Debugging")
	Server("http:/localhost:8080")
})

var RT = ResultType("ResultTypeMultipleViews", func() {

	Attribute("a", String)
	Attribute("b", String)
	Attribute("c", String)

	View("default", func() {
		Attribute("a")
		Attribute("b")
		Attribute("c")
	})

	View("tiny", func() {
		Attribute("c")
	})
})

var _ = Service("ServiceBodyMultipleView", func() {
	Method("MethodBodyMultipleView", func() {

		Result(RT, func() {
			View("tiny")
		})

		HTTP(func() {
			POST("/")
			Response(StatusOK, func() {
				Header("c:Location")
			})
		})
	})
})
```

**Comment by nitinmohan87** [comment]
Thanks for reporting this issue. This should now be fixed by the PR above.
