### ISSUE TITLE
Usage of Goa with a message broker (NATS) in an Event Sourced Architecture

### ISSUE THREAD

**Issue by gedw99** [goadesign/goa#1786]
I familiar with GOA and been using it for a while, but i was wondering if anyone has seen GOA used with a message broker like NATS ?

Here is the Architecture use case:
Currently the MicroServices  are generated with Goa. 
Between the Client ( Dart actually ) and the MicroServices we use NATS to give us the ability to push to many Clients ( and other MicroServices )  so that they can catch up if they are partitioned.  This is a pretty typical usage of a Message broker in larger decoupled systems. 
In summary, this design allows us to have n Event Sourcing style of architecture with GOA.

TO get into the details a bit.. In order for each client to only get the Delta the MicroServices Response Payload outputs an event message that has the row and change type ( CRUD ) onto NATS. In this way each client can be told of the change to the MicroServices Response Payloads and keep their Cache up to date of our Materialised View. 

Questions / Solutions:
Maybe someone has done this before and so i would be curious how they approached this ?

Maybe i would have to copy some of the existing standard GOA code generators to do this ? If so is it a valuable thing for the community i wonder as it would be great if more people ned this to scale out a MicroService Architecture.

**Comment by raphael** [comment]
We have a similar use case where a message bus sits in between the clients and the services. The design pattern we are following consists of having an "adapter" service that reads messages from the bus and makes requests to the goa service. The adapter is in charge of handling the message lifecycle (acking etc.) and is a goa service that exposes metric APIs (consumed by Prometheus in our case).  The backend goa services that receives requests from the adapter is a "vanilla" goa service, its APIs are designed solely considering the needs of the business logic and independently of the fact that it sits behind a message bus. There are a few advantages to this design:
* The service and adapters can be scaled independently
* The adapter can handle throttling responses appropriately (e.g. by slowing down how often it forwards messages, creating back pressure onto the bus).
* The message lifecycle logic is cleanly separated from the actual service logic

**Comment by gedw99** [comment]
This does help massively @raphael.

So the adapter is generic for each MQ or you code into it the calls to each Goa vanilla service ?

Is any of the adapter code public ?

**Comment by raphael** [comment]
The adapter is generic, it is configured at startup with the endpoint of the back service. The code is not open source unfortunately.
