### ISSUE TITLE
how can i have unified error result when the input request is bad

### ISSUE THREAD

**Issue by richardyicai** [goadesign/goa#1801]
hello everyone. how can the client get unified JSON encoded error object when the request is a bad request e.g. something wrong with the validation.  the default code will send a plain texted message , but i want JSON. the generated code( in server.go ) is something like:
```go
ctx := context.WithValue(r.Context(), goahttp.AcceptTypeKey, r.Header.Get("Accept"))
		ctx = context.WithValue(ctx, goa.MethodKey, "create_vendor")
		ctx = context.WithValue(ctx, goa.ServiceKey, "manufacture")
		payload, err := decodeRequest(r)
		if err != nil {
			eh(ctx, w, err)
                        return
		}
```

and eh (ErrorHandler in main.go) would just **send plain text and the http status code is 200**. I think `eh(ctx, w, err)` SHOULD be `encodeError(ctx, w, err)`  and if I change the code like this the result will be **400 and JSON formatted**.

How can I change this default behavior through DSL? 

Thank you!

**Comment by raphael** [comment]
Hello, the error handler is provided to the constructor of the decoder func by your main function. Change it to do whatever you need it to.
