### ISSUE TITLE
is there an example showing how to upload/download files using goa V2

### ISSUE THREAD

**Issue by richardyicai** [goadesign/goa#1804]
I'd like to have the upload example for V2 thanks . I define the method as follows:
```g
Method("upload_file", func() {
		Description("upload a file")
		Payload(func(){
			Attribute("content", Bytes)
			Required("content")
		})

		Result(Empty)

		HTTP(func() {
			POST("")
			Body("content")
			Response(StatusOK)
		})
	})
```

but get the error:
```json
{
    "name": "decode_payload",
    "id": "Xck14OIR",
    "message": "invalid character 'p' looking for beginning of value",
    "temporary": false,
    "timeout": false,
    "fault": false
}
```

Will I need to implement the multipart/form-data encoder/decoder?  There is no interfaces for registering decoder/encoders so it's hard to extend the framework. what's your indication?

**Comment by richardyicai** [comment]
I solved the problem by  adding the http request object in the context and call ParseMultipartForm in the service handler. but it's not very elegant way and I changed the generated code.

**Comment by nitinmohan87** [comment]
@richardyicai There is no example showing how to upload a file. But this example should give you an idea - https://github.com/goadesign/goa/blob/v2/examples/cellar/storage.go#L147
You can use the `NextPart` function in `multipart.Reader` to get a `multipart.Part` which implements the io `Reader` interface. You can then use `io.Copy` to copy the contents of a multipart to a file.
```
file, err := os.Create("foo.bar")
for {
		part, err := mr.NextPart()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("failed to load part: %s", err)
		}
		io.Copy(file, part)
}
```
This should be sufficient for you I hope.

**Comment by nitinmohan87** [comment]
Oh and here is the design you can use to make a request multipart - https://github.com/goadesign/goa/blob/v2/examples/cellar/design/storage.go#L76-L84
See `MultipartRequest` DSL

**Comment by richardyicai** [comment]
@nitinmohan87 thank you

**Comment by SantoshSah** [comment]
@nitinmohan87 Could you please update above links for v3?
