### ISSUE TITLE
Add 1.x.y release tag

### ISSUE THREAD

**Issue by jiekang** [goadesign/goa#1807]
I submitted some changes [1][2] that I would like to see in a release tag to be used in a project I work on which currently uses 1.3.0. It would be best for a 1.4.y or 1.3.y release tag.

[1] https://github.com/goadesign/goa/pull/1792
[2] https://github.com/goadesign/goa/pull/1800

What needs to be done for this? Is there anything I can do to help?

**Comment by raphael** [comment]
Thanks for the nudge, it's probably time for 1.4.0! The only "requirement" really is to gather all the bug fixes and additional features since the last release (1.3.1). The lists are used to write a blog (for example https://goa.design/blog/006-v_1_3_0/), it should contain a link to the PR(s), the names of the authors and a quick description. I might have time this weekend but if you wanted to build an initial list that would be helpful!

**Comment by jiekang** [comment]
Okay, I will try to build an initial list and post it as a comment here by end of Friday. Cheers!

**Comment by jiekang** [comment]
New Features

Add support for multipart form requests #1606 - Taichi Sasaki
https://github.com/goadesign/goa/pull/1606

Add a primitive type File #1642 - Taichi Sasaki
https://github.com/goadesign/goa/pull/1642

Add ability to suppress sensitive headers from log #1691 - @adam-hanna
https://github.com/goadesign/goa/pull/1691

Add support for readonly attributes #1776 - Daniel I. Khan Ramiro
https://github.com/goadesign/goa/pull/1776

Add RFC3339 date format #1780 - Konstantin Lepa
https://github.com/goadesign/goa/pull/1787

Add support for JWT Token authorization via query parameter #1800 - Jie Kang
https://github.com/goadesign/goa/pull/1800

Bug Fixes

Properly format JavaScript generator Go example code #1497 - Raphael Simon
https://github.com/goadesign/goa/pull/1497

Properly test for required attributes when unmarshaling #1521 - Raphael Simon
https://github.com/goadesign/goa/pull/1521

Remove the unused valiable #1550 - @ikawaha
https://github.com/goadesign/goa/pull/1550

Prevent "Any" fields from pointing to *interface{} #1591 - Alex Brausewetter
https://github.com/goadesign/goa/pull/1591

v1: Prevent pointer to '*interface{}' in user types #1611 - Alex Brausewetter
https://github.com/goadesign/goa/pull/1611

Fix MuxHandler initialization race #1627 - Robert Wooley
https://github.com/goadesign/goa/pull/1627

validate different wildcards only if request method is the same #1583 - Taichi Sasaki
https://github.com/goadesign/goa/pull/1639

Make sure to finalize parent resources first. #1655 - Raphael Simon
https://github.com/goadesign/goa/pull/1655

Fix serialization of default values for non string and non integer attributes. #1681 - Raphael Simon
https://github.com/goadesign/goa/pull/1681

Properly generate validation for URL parameter arrays #1721 - Raphael Simon
https://github.com/goadesign/goa/pull/1691

add a yaml tag to generated types fields #1733
https://github.com/goadesign/goa/pull/1733

Make request header logging order consistent #1748 - Raphael Simon
https://github.com/goadesign/goa/pull/1748

Fix for v1 multipart/form-data Swagger semantic error #1744 - Mark Songhurst
https://github.com/goadesign/goa/pull/1744

Remove lint git clone hack #1747 - Raphael Simon
https://github.com/goadesign/goa/pull/1747
// I think this is a removal of something added to v1 that was not included in a release (https://github.com/goadesign/goa/commit/f7c66e073d37351483c6c3bf9becff085d58c136) I think it does not need to be included in the release notes

Make sure default output dir is set #1751 - Raphael Simon
https://github.com/goadesign/goa/pull/1751

Fix gocyclo dependency #1772 - Konstantin Lepa & Raphael Simon
https://github.com/goadesign/goa/pull/1772

Fix minItems/maxItems for array type #1775 - Konstantin Lepa
https://github.com/goadesign/goa/pull/1775

Fix recursive types #1774 - Konstantin Lepa
https://github.com/goadesign/goa/pull/1774

Fix client tests when GOPATH is /go #1773
https://github.com/goadesign/goa/pull/1773

Fix design.HasFile for recursive user types #1791 - Konstantin Lepa
https://github.com/goadesign/goa/pull/1791

**Comment by jiekang** [comment]
@raphael I've gone through the `v1` branch and created a list in Markdown format. Full links are included on a newline for each PR (see plaintext). 

P.s. I hope the @ syntax for usernames in the list doesn't actually send a notification; I'm sorry!

**Comment by raphael** [comment]
Looks great, thank you for putting that together! I'm planning on releasing this weekend.

**Comment by raphael** [comment]
Released! thanks for the help. [Release Notes](https://goa.design/blog/007-v_1_4_0/)
