### ISSUE TITLE
GOA doesn't like int64 with default values

### ISSUE THREAD

**Issue by dgaedcke** [goadesign/goa#1809]
## Expected Behavior
buildable code

## Actual Behavior
non-buildable code

## Steps to Reproduce the Problem-- run this snippet
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

type WantedResult struct {
	Int64Value int64
}

var _ = Service("Example", func() {
	Method("show", func() {
		Payload(Empty)
		Result(BrokenExampleMedia)
		Error("internal_error", ErrorResult)
		HTTP(func() {
			GET("/{id}")
			Response(StatusOK)
			Response("internal_error", StatusInternalServerError)
		})
	})

	Method("list", func() {
		Payload(Empty)
		Result(CollectionOf(BrokenExampleMedia))
		Error("internal_error", ErrorResult)
		HTTP(func() {
			GET("/list")
			Response(StatusOK)
			Response("internal_error", StatusInternalServerError)
		})
	})
})

var BrokenExample = Type("BrokenExample", func() {
	Attribute("int64Value", Int64, func() {
		Default(1000)
	})
})

var BrokenExampleMedia = ResultType("application/test.brokenexample", func() {
	Description("Broken Example response")
	TypeName("BrokenExampleMedia")

	CreateFrom(WantedResult{})
	ContentType("application/json")
	Reference(BrokenExample)

	Attributes(func() {
		Attribute("int64Value", Int64)
	})
})package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

type WantedResult struct {
	Int64Value int64
}

var _ = Service("Example", func() {
	Method("show", func() {
		Payload(Empty)
		Result(BrokenExampleMedia)
		Error("internal_error", ErrorResult)
		HTTP(func() {
			GET("/{id}")
			Response(StatusOK)
			Response("internal_error", StatusInternalServerError)
		})
	})

	Method("list", func() {
		Payload(Empty)
		Result(CollectionOf(BrokenExampleMedia))
		Error("internal_error", ErrorResult)
		HTTP(func() {
			GET("/list")
			Response(StatusOK)
			Response("internal_error", StatusInternalServerError)
		})
	})
})

var BrokenExample = Type("BrokenExample", func() {
	Attribute("int64Value", Int64, func() {
		Default(1000)
	})
})

var BrokenExampleMedia = ResultType("application/test.brokenexample", func() {
	Description("Broken Example response")
	TypeName("BrokenExampleMedia")

	CreateFrom(WantedResult{})
	ContentType("application/json")
	Reference(BrokenExample)

	Attributes(func() {
		Attribute("int64Value", Int64)
	})
})

## Specifications

  - goa Version:   goa version v2.0.0-wip
  - Platform:  Mac

**Comment by nitinmohan87** [comment]
Thanks for the bug report. The PR above should fix this issue.
