### ISSUE TITLE
1.4 released, but still 1.3 in the code

### ISSUE THREAD

**Issue by eclipse1985** [goadesign/goa#1817]
https://github.com/goadesign/goa/blob/master/version/version.go

**Comment by raphael** [comment]
The code of `v1.4.0` is actually correct: https://github.com/goadesign/goa/blob/v1/version/version.go and https://github.com/goadesign/goa/blob/v1.4.0/version/version.go. `master` is something else entirely at this point (has diverged from the `v1` branch). Maybe we should change the version there to reflect that. To be clear all the features and fixes in v1.4.0 are also in master but master can break at any time. `v1` is the stable branch and the branch that contains the `v1.4.0` tag.

**Comment by eclipse1985** [comment]
Ok, but when you install GOA using go get, points to master, didn't it? Also, I tried to reinstall using go get in order to try the new feature, and they didn't work

**Comment by raphael** [comment]
The idea is to use a vendoring tool to peg to the stable branch. Please open an issue describing what you were expecting, what didn't work etc.
