### ISSUE TITLE
CopyTo and CreateFrom with sub-structs creates invalid code

### ISSUE THREAD

**Issue by dgaedcke** [goadesign/goa#1853]
Please fill the sections below:

## Expected Behavior
Buildable code

## Actual Behavior
errors at build are:
gen/user/convert.go:74:15: cannot use marshalEmailInfoToEmailInfo(t.EmailInfo) (type *EmailInfo) as type user.EmailInfo in assignment
gen/user/convert.go:74:46: cannot use t.EmailInfo (type *EmailInfo) as type *user.EmailInfo in argument to marshalEmailInfoToEmailInfo
gen/user/convert.go:77:15: cannot use marshalMobileInfoToPhoneInfo(t.PhoneInfo) (type *user.PhoneInfo) as type user.PhoneInfo in assignment
gen/user/convert.go:90:17: cannot convert nil to type user.EmailInfo
gen/user/convert.go:91:49: cannot use v.EmailInfo (type user.EmailInfo) as type *user.EmailInfo in argument to marshalEmailInfoToEmailInfo
gen/user/convert.go:93:17: cannot convert nil to type user.PhoneInfo
gen/user/convert.go:94:50: cannot use v.PhoneInfo (type user.PhoneInfo) as type *user.PhoneInfo in argument to marshalPhoneInfoToMobileInfo
gen/user/convert.go:123:54: marshalEmailInfoToEmailInfo redeclared in this block
	previous declaration at gen/user/convert.go:101:49

## Steps to Reproduce the Problem (including complete and simple design if relevant)
Sample design attached
Download zip and extract it to:  github.com/NewMillennialGames/
run: 
goa gen github.com/NewMillennialGames/NmgApi/api/design
goa example github.com/NewMillennialGames/NmgApi/api/design
go build cmd/nmgapi_svc/main.go

you will see the errors above

## Specifications
 - go version:  go version go1.9.5 darwin/amd64
  - goa Version:  goa version v2.0.0-wip  (just pulled latest with go get -u goa.design/goa/...)
  - Platform: Mac

[NmgApi.zip](https://github.com/goadesign/goa/files/2362975/NmgApi.zip)

**Comment by raphael** [comment]
Thank you for the detailed report, the issue is now fixed. Note that there is a limitation where the external type fields that are structs must used pointers. So in the attached code the user mode `UserInfo` and `EmailInfo` fields must be pointers.

**Comment by dgaedcke** [comment]
Thanks Raph!!
