### ISSUE TITLE
Please set the ctx.RequestURI to the context generated by the test helper

### ISSUE THREAD

**Issue by grassy-48** [goadesign/goa#1861]
## Expected Behavior
Please set the ctx.RequestURI to the context generated by test helper.

```
goagen app -d my-app/design
```

## Use Case

`ctx.RequestURI` returned of controllers test helper function generated is always empty strings.
Because this value is not set in the test helper.

* my controller(sample)
```golang
	// Put your logic here
	r := ctx.RequestURI
	data := myLogic()
	pages := map[string]string{
		"self": r,
		"prev": prevLink(r),
		"next": nextLink(r),
	}
	res := &app.SampleResponse{
		Data:  data,
		Links: pages,
	}

```
My controller is like this. But, In test helper code generated,

```golang
	// Setup request context
	rw := httptest.NewRecorder()
	u := &url.URL{
		Path: fmt.Sprintf(“/sample-path”),
	}
	req, err := http.NewRequest("GET", u.String(), nil)
```
I want to use `ctx.RequestURI` in controller tests if my controller returns the correct value.

## Specifications
  - goa Version:1.3.1

**Comment by raphael** [comment]
I'm reopening the issue as the request makes sense. I would be happy to merge a PR that did the above :)
