### ISSUE TITLE
some attribute-type in Type cause compile errors in generated code when use as Payload

### ISSUE THREAD

**Issue by aya-eiya** [goadesign/goa#1862]
I found some unexpected behave in some goa generated codes.

## Expected Behavior

goagen generates no defect codes.

## Actual Behavior

the codes generated with goagen has some odd lines as golang code and those can't be compiled.

1. ArrayOf for Payload causes defined but not be used error
2. non-required Integer Type for Payload causes strconv.Itoa(int) type mismatch error

this seems to arise only if set multipart-form.

```
# github.com/aya-eiya/goa-test/apps/app
apps/app/controllers.go:72:2: rawArrs declared and not used
# github.com/aya-eiya/goa-test/apps/client
apps/client/my_resorce.go:63:28: cannot use payload.IntVal (type *int) as type int in argument to strconv.Itoa
```

## Steps to Reproduce the Problem (including complete and simple design if relevant)

I made the error reproducing project here.

https://github.com/aya-eiya/goa-test

## Specifications

  - goa Version:1.4.0
  - Platform:MacOSX

**Comment by aya-eiya** [comment]
I made a PR( #1863 ) for fix this.
I confirmed the fix for error 2 above firstly.

**Comment by aya-eiya** [comment]
I added a fix for error 1 to PR( #1863 ).

Both fix are not perfect to avoid all error cases like I noticed but I think it is somewhat better than current behavior.

**Comment by raphael** [comment]
Thanks! I will review the PR soon.

**Comment by aya-eiya** [comment]
PR #1865 and #1863 were merged, so I close this.

**Comment by raphael** [comment]
Thank you for the hard work on this!
