### ISSUE TITLE
Which version is the master branch ?

### ISSUE THREAD

**Issue by aya-eiya** [goadesign/goa#1867]
## Expected Behavior

master branch points the stable last release version.

## Actual Behavior

I can't figure out the master branch points what state is.

## Steps to Reproduce the Problem

```bash
git checkout master
git diff v1          # has changes. 'master' is not stable of 'v1'
git diff tags/v1.4.0 # has changes. 'master' is not current release

git diff v2          # also 'master' is not working snapshot
```

<code>go get</code> command gets the latest master branch version as default. so I want to figure out the master version is what released version is.

## Specifications

  - goa Version: v1.4.0 (?)
  - Platform : All

**Comment by raphael** [comment]
The master branch is a dead end going forward. The plan is for the `v2` branch to become the master branch when `v2` is released. The `master` branch will get renamed to something else so that users that rely on it can still do so.
