### ISSUE TITLE
Support of OpenTracing

### ISSUE THREAD

**Issue by difengo** [goadesign/goa#1869]
Hi,

I'm currently looking at OpenTracing and was wondering if GOA 2 could ease the integration of this standard in the generated micro-services. 

I suppose that it could take the form of a plugin but i'm a bit confused about the plugin architecture. 

How such a thing could be done knowing that it should add some code in already generated functions ?

**Comment by raphael** [comment]
Hello, a plugin would indeed probably be the right approach here. Plugins can modify the templates before the final code is generated. You can see an example here where the cors plugin modifies the default template: https://github.com/goadesign/plugins/blob/master/cors/generate.go#L149. There is no documentation explaining how to write plugins at this time other than the godocs in the goa source code. Looking at the cors example is probably the best way to learn. Feel free to join the slack channel (see link in README) if you have specific questions.
