### ISSUE TITLE
Access to logger from UserBasicAuth

### ISSUE THREAD

**Issue by difengo** [goadesign/goa#1871]
Hi,

I created a small service with basic authentication enabled. As expected the 
UserBasicAuth function was generated. 

However, how can I access to the logger from that method as I can do it from the endpoints ? I could of course create a global variable but this would make the s.logger useless in endpoints funcs no?

**Comment by raphael** [comment]
I believe this is not an issue anymore thanks to your great contributions :) - Please close the issue if that's the case otherwise provide a description of what is still pending. Thank you!
