### ISSUE TITLE
V2: The use of the method "ConvertTo" leads to the generation of invalid code

### ISSUE THREAD

**Issue by nikolaas** [goadesign/goa#1874]
Hello!

I got wrong code when I used `ConvertTo` to convert a designed type to an external type.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

1. Create the file `mydomain.org/myapi/model/filter.go` and define the type `Filter`:
```golang
package model

type Filter struct {
	Field *string
	Value *string
	Cond  *string
}
```

2. Create the file `mydomain.org/myapi/design/design.go` and define the api:
```golang
package design

import (
	"net/http"
	. "goa.design/goa/http/dsl"
	. "goa.design/goa/http/design"
	"mydomain.org/myapi/model"
)

var _ = API("myapi", func() {
	Title("My api")
})

var Filter = Type("Filter", func() {
	ConvertTo(model.Filter{})
	Attribute("field", String)
	Attribute("value", String)
	Attribute("cond", String)
})

var Person = Type("Person", func() {
	Attribute("firstName", String)
	Attribute("secondName", String)
})

var _ = Service("person", func() {
	Method("getPersons", func() {
		Payload(Filter)
		Result(ArrayOf(Person))

		HTTP(func() {
			GET("/persons")
			Response(StatusOK)
		})
	})
})
```
3. Generate the code:
```bash
$ goa gen mydomain.org/myapi/design
```

## Actual Behavior

The generated file `mydomain.org/myapi/gen/person/service.go` contains the type `Filter`:
```golang
type Filter struct {
	Field *string
	Value *string
	Cond *string
}
```

The generated file `mydomain.org/myapi/gen/person/convert.go` contains the code:
```golang
// Code generated by goa v2.0.0-wip, DO NOT EDIT.
//
// person service type conversion functions
//
// Command:
// $ goa gen mydomain.org/myapi/design

package person

import (
	model "mydomain.org/myapi/model"
)

// ConvertToFilter creates an instance of Filter initialized from t.
func (t *Filter) ConvertToFilter() *model.Filter {
	v := &model.Filter{}
	if t.Field != nil {
		v.Field = *t.Field
	}
	if t.Value != nil {
		v.Value = *t.Value
	}
	if t.Cond != nil {
		v.Cond = *t.Cond
	}
	return v
}
```
It is a wrong code. Fields `Field`, `Value` and `Cond` of  the external type `model.Filter` is pointers to a string.  Fields `Field`, `Value` and `Cond` of the generated type `person.Filter` is also pointers to a string. Therefore the operation of assignment should not use the operator `*`

## Expected Behavior

I expect the code:
```golang
// Code generated by goa v2.0.0-wip, DO NOT EDIT.
//
// person service type conversion functions
//
// Command:
// $ goa gen mydomain.org/myapi/design

package person

import (
	model "mydomain.org/myapi/model"
)

// ConvertToFilter creates an instance of Filter initialized from t.
func (t *Filter) ConvertToFilter() *model.Filter {
	v := &model.Filter{
		Field: t.Field,
		Value: t.Value,
		Cond:  t.Cond,
	}
	return v
}
```

The documentation for the expression `ConvertTo` says:
>The default algorithm used to match the external type fields to the design attributes is as follows:
>
>1. Look for an attribute with the same name as the field
>2. Look for an attribute with the same name as the field but with the first letter being lowercase
>3. Look for an attribute with a name corresponding to the snake_case version of the field name

but current implementation does not generate a code correctly when the name of the field of the external type starts with uppercase letter and the name of the attribute of the designed type starts with lowercase letter.

If I will change the first letter of attributes name to uppercase:
```golang
var Filter = Type("Filter", func() {
	ConvertTo(model.Filter{})
	Attribute("Field", String)
	Attribute("Value", String)
	Attribute("Cond", String)
})
```
the code will be generated correctly.

I tried to fix the problem using the expression `Metadata`:
```golang
var Filter = Type("Filter", func() {
	ConvertTo(model.Filter{})
	Attribute("field", String, func() {
		Metadata("struct.field.external", "Field")
	})
	Attribute("value", String, func() {
		Metadata("struct.field.external", "Value")
	})
	Attribute("cond", String, func() {
		Metadata("struct.field.external", "Cond")
	})
})
```
but that doesn't fix it.

## Specifications

  - goa Version: v2 (commit 596581536ff486a8262223c95d552a45eac2c0fb)
  - Platform (Linux/Windows etc.): macOS 10.13.6

**Comment by nikolaas** [comment]
I found that the problem is in the method `transformObject` (`goa.design/goa/codegen/service/transform.go`, row 167):
The expression `tgtPtr := target.IsPrimitivePointer(n, true)` returns `false` for fields in the case described above. It happens because `target` object does not contains the attribute with name `"field"` (on the example of the attribute "field"). Instead it contains the attribute with name `"field:Field"`.

I tried to fix the bug: I changed the method `Attribute` that `design.Object` uses to search for an attribute by name:
```diff
// Attribute returns the attribute with the given name if any, nil otherwise.
func (o *Object) Attribute(name string) *AttributeExpr {
	for _, nat := range *o {
+		attrName := strings.Split(nat.Name, ":")[0]
+		if attrName == name {
-		if nat.Name == name {
			return nat.Attribute
		}
	}
	return nil
}
```
This change fix the problem but I'm not sure that it's the right way.

**Comment by raphael** [comment]
Thank you for the detailed report and great troubleshooting! Goa has a concept of mapped attribute which makes it possible to give an external name to an attribute. Such external name may represent HTTP header names, HTTP parameters etc. The bug you found is that the algorithm considers the attribute name instead of the mapped attribute name. The function `design.NewMappedAttribute` initializes a mapped attribute from a raw attribute. It then makes it possible to retrieve the mapped attribute name. So a better fix here would be to create a mapped attribute from the attribute (if none is created prior in the code) then retrieve the name from it.

**Comment by raphael** [comment]
Thank you for the great PR!
