### ISSUE TITLE
V2: Proposal for a DSL expression "TransformTo"

### ISSUE THREAD

**Issue by nikolaas** [goadesign/goa#1880]
Hello!

In our application we use the Link HTTP header to send back pagination links. The links is an absolute URLs. For example, `https://example.org/some/path?params`. So, we need to use `http.request.URL` to build the links.

In according to Goa v2 design a service doesn't have access to a HTTP request directly. Therefore our service should return the links without any information about URL. 

## Example

For instance, we created a design file:
```golang
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

var _ = API("api", func() {
	Title("Api")
})

var Link = Type("Link", func() {
	Attribute("type", String)
	Attribute("anchor", String)
	Required("type")
})

var Person = Type("Person", func() {
	Attribute("name", String)
})

var Persons = Type("Persons", func() {
	Attribute("data", ArrayOf(Person))
	Attribute("links", ArrayOf(Link))
})

var _ = Service("person", func() {
	Method("getPersons", func() {
		Result(Persons)

		HTTP(func() {
			GET("/persons")

			Response(http.StatusOK, func() {
				Header("links:Link")
			})
		})
	})
})
```

Next we generated the code and wrote implementation of a service:
```golang
package service

import (
	"context"
	"example.org/app/gen/person"
)

type PersonService struct {}

func (s PersonService) GetPersons(ctx context.Context) (*person.Persons, error) {
	var data []*Person
	// getting the data...

	links := []*Link{
		{Type: "prev", Anchor: "some anchor"},
		{Type: "next", Anchor: "some anchor"},
	}

	return &person.Persons {
		Links: links,
		Data: data
	}
}
```

After that, on the HTTP layer the server would convert the links' data to absolute URLs, and it would send them as the Link header.

Unfortunately the current implementation of Goa v2 doesn't allow to perform that kind of transformations.

## Proposal

We would like to be able to specify a custom transform function. It would receive data from a service, and it would return data in an appropriate way for the HTTP layer.

We suggest to add a DSL expression `TransformTo`. It should appear in `HTTP`:

```diff
+var HTTPPersons = Type("HTTPPersons", func() {
+	Attribute("data", ArrayOf(Person))
+	Attribute("links", ArrayOf(String))
+})

var _ = Service("person", func() {
	Method("getPersons", func() {
		Result(Persons)

		HTTP(func() {
+			TransformTo(HTTPPersons)
			GET("/persons")

			Response(http.StatusOK, func() {
				Header("links:Link")
			})
		})
	})
})
```

The `TransformTo` expression defines a type to which the result type must be converted. After that, the HTTP layer should perform all subsequent transformations with this type instead of the result type.

To transform the `Result` type to the `TransformTo` type `godegen` generates a interface of a transformer and injects it to the method for creation of the new server:
```golang
// example.org/app/gen/http/person/server/server.go

type PersonsToHTTPPersonsTransformer interface {
	TransformPersonsToHTTPPersons(r *http.Request, result *person.Persons) (*person.HTTPPersons, error)
}

func New(
	e *person.Endpoints,
	mux goahttp.Muxer,
	t *PersonsToHTTPPersonsTransformer,
	dec func(*http.Request) goahttp.Decoder,
	enc func(context.Context, http.ResponseWriter) goahttp.Encoder,
	eh func(context.Context, http.ResponseWriter, error),
) *Server
```

After that, we implement the transformer interface:

```golang
package transform

import (
	"net/http"
	"example.org/app/gen/person"
)

type PersonsToHTTPPersonsTransformer struct {}

func (t PersonsToHTTPPersonsTransformer) TransformPersonsToHTTPPersons(r * http.Request, result *person.Persons) (*person.HTTPPersons, error) {
	return &personsrv.HTTPPersons{
		Data: result.Data,
		Links: convertLinksToURLs(result.Links),
	}, nil
}

func convertLinksToURLs(links []*personLink) []string {
	/* convert the links here */
}
```

This enhancement also will be useful in more complex cases. For instance, when [HAL](http://stateless.co/hal_specification.html) is used the `Persons` result should be transformed as written below:
```json
{
    "_links": {
        "prev": { "href": "<prev link url>" },
        "prev": { "href": "<next link url>" }
    },
    "_embedded": {
        "ea:people": [
            {
                "_links": {
                    "self": { "href": "<Bob self url>" }
                },
                "name": "Bob"
            }, 
            {
                "_links": {
                    "self": { "href": "<Jack self url>" }
                },
                "name": "Jack"
            }
        ]
    }
}
```

If you agree with this proposal I can make a PR.

Thanks

**Comment by raphael** [comment]
Thank you for the proposal! The standard way of dealing with this kind of need in v2 would be to use the [Request](https://github.com/goadesign/goa/blob/v2/http/middleware/request.go) middleware to inject the HTTP path into the request context. One issue I see with this proposal is that it doesn't provide a reverse function that would potentially be needed client side (how do you get back a `Person` from a `HTTPerson`?). It might not be needed in this use case but in general it would be.

**Comment by nikolaas** [comment]
As I understood, a service in v2 is the business logic layer and it should not know anything about the transport layer.

For instance, assume that we have a some API server. It provides the API by the REST and GRPC protocols. According to the protocol the server should return the response in an appropriate way for the protocol. Going back to the example in my comment above, the server should return the links in HTTP header for REST requests and in GRPC Metadata for GRPC requests. 

if we will use your proposed approach we will have to add the Request middleware in the HTTP transport layer. Also we will have to add a similar middleware on the GRPS transport layer. After that we will have to return from a service an object with "HTTPLinks" and "GRPCLinks" fields (because them may have different types). All this complicates the development and the support of the code. So I think that it is better to transform the data at the transport layer, instead of putting the data of the  transport layer into the context and using it in a service.

With regard to the reverse transformation function, we may replace the `TransformTo` expression with `DecodeFrom` and `EncodeTo` expressions: 
1. the `DecodeFrom` expression appears in the `HTTP` expression inside the `Method` expression to transform the HTTP payload to the payload of a service;
2. the `EncodeTo` expression appears in the `Response` expression to transform the response of a service to the HTTP response.

Pros:
- we get a full control over the payload and response of the method;
- the business logic layer is isolated from the transport layer, adding of a new transport layer doesn't affect the code of a service.

Cons:
- the user have to re-define the payload/response for each transport protocol,
- the approach complicate a designing and implementation of services

**Comment by raphael** [comment]
I agree that the middleware solution breaks the transport encapsulation and understand the need for the mechanism - thank you for bringing it up. One thing that seems to be missing in this proposal is taking into account the client side. Both in the DSL and in the implementation. I think what we are saying is that there should be a mechanism by which transport specific data structures can be created off of service level data structures. This seems like a generic statement that should work for payloads and for results for both servers and clients. On the DSL what if we allowed redefining the payload and result types:
```diff
var _ = Service("person", func() {
	Method("getPersons", func() {
		Result(Persons)

		HTTP(func() {
+			Result(HTTPPersons)
			GET("/persons")

			Response(http.StatusOK, func() {
				Header("links:Link")
			})
		})
	})
})
```
This would make it possible to inject transformation functions both in the server and client encoding and decoding code. Does that make sense?

**Comment by pablomadoery** [comment]
Hello,
I am currently using goa v2 and I am interested in being able to 
1) Obtain the URL from the query as a string. 
For example "http://localhost:80/v1/radio?id=7&page=3&page_size=10"
2) Change a parameter value of that string.
For example "http://localhost:80/v1/radio?id=7&page=4&page_size=10"
3) Return the modified string in the response.

Is that possible. How can I achieve that ?
Thank you

**Comment by raphael** [comment]
There are multiple ways to achieve the above. The "cleanest" would be to define a payload type for the method that lists the query string parameter then map these to the HTTP transport using the `Params` function. You'll end up with a value given to the service method that is a struct with all the fields corresponding to the query string parameters. Another way would be to use a HTTP middleware to save the original HTTP request query string into the context for example. The service method would then have access to that value in the context. 

In terms of writing the response again there are many ways to do that, maybe the simplest is to define the result type as a string (`Result(String)`) then use the standard library http package to encode the values in a query string that gets written to the response body (or build the string yourself if it's simple).
