### ISSUE TITLE
V2: Services which have an access to the transport layer

### ISSUE THREAD

**Issue by nikolaas** [goadesign/goa#1894]
Hello!

In our team we're trying to write Goa v2 HTTP app, and we have many problems with it (e.g. #1880). The main problem is isolation of the service layer and transport layer. This isolation is unimportant for HTTP only (or GRPC only) services, but they need the transport layer information (e.g. headers, URL path, cookies). Now, we have to find workarounds for all these problems.

Besides universal services, we offer to add the HTTP and GRPC services. For example,
```golang
HTTP(func() {
	Service("HTTPService", func() {
	})
})

GRPC(func() {
	Service("GRPCService", func() {
	})
})
```

Handlers for these services would get access to http.ResponseWriter and *http.Request.

What do you think about that?

Thanks

**Comment by raphael** [comment]
It would be trivial to add a middleware that put the HTTP request and response objects in the context. We considered then rejected this approach in favor of the current request middleware that adds the pieces of the request object to the context instead to avoid abuse. The generated code assumes it has full control on the response for example. It also loads and unmarshals the request body (you can configure the decoder to reset the reader though). So in general it is not safe to manipulate these directly from service handlers. Obviously as long as you are aware of the caveats you are free to break the separation of concerns. I would be curious to understand the use cases better though.

**Comment by raphael** [comment]
@nikolaas I'm reviewing all the issues and wondering if you'd be able to share a bit more about your use case? The clean architecture pattern is not just about making it possible to support multiple transports. It's also about encapsulating logic in layers that make it easier to maintain the service code in the long term. What do you need to do that this separation of layers makes impossible? It could be that goa is not suited for your use case but again I'd be curious to understand a bit more about it.
