### ISSUE TITLE
support building code outside of GOPATH for go module support

### ISSUE THREAD

**Issue by jtnord** [goadesign/goa#1914]
If I have a project that is using [Go Modules](https://golang.org/doc/go1.11#modules) (as opposed to the old `GOPATH `layout) I would still like to be able to use goagen.  Alas it seems goagen will not work at all unless you are using the legacy GOPATH layout.

## Expected Behavior

`goagen app -d ${PACKAGE_NAME}/${DESIGN_DIR} -o pkg/controller` works with no error.

## Actual Behavior

goagen errors with

`Go source file "C:\workarea\source\github\someorg\some-repo\goagen053437807\design" not in Go workspace, adjust GOPATH C:\PATH\to\go`

## Specifications

  - goa Version: goagen v1.3.1
  - Platform (Linux/Windows etc.): Windows 10

**Comment by raphael** [comment]
Thank you for the report. At this point I'm focusing on v2 and will make sure it supports Go module. I'd be happy to accept a PR that added Go module support to v1 though.

**Comment by raphael** [comment]
Go modules are now supported in v1 (thank you @tchssk!). Please open a new issue if things don't work out as expected.
