### ISSUE TITLE
HashOf fail when used in a Media Response

### ISSUE THREAD

**Issue by pablomadoery** [goadesign/goa#1931]
Hello, I need the body response to be a dictionary (hash).

## Expected Behavior
goagen to compile and generate all the controllers an app

## Actual Behavior
exit status 1
[design/resources.go:61] media type must be a string or a pointer to MediaTypeDefinition, got &design.Hash{KeyType:(*design.AttributeDefinition)(0xc0002c7400), ElemType:(*design.AttributeDefinition)(0xc0002c7480)} in response "OK"

## Steps to Reproduce the Problem (including complete and simple design if relevant)
- When using this in the design:
		Response(OK, func() {
			Media(HashOf(String, UpsMedia))
		})
It throws the mentioned error.

- When using:
		Response(OK, func() {
			Media(CollectionOf(UpsMedia))
		})
It works OK!

- When using a MediaType() auxiliar variable with the hash inside:
var UpsResponseMedia = MediaType("application/vnd.Upsresponsemedia+json", func() {
	Attributes(func() {
		Attribute("hash", HashOf(String, UpsMedia))
		Required("hash")
	})

	View("default", func() {
		Attribute("hash")
	})
})
It works OK!

## Specifications
  - goa Version: V2
  - Platform (Linux/Windows etc.): Linux (Ubuntu 16.04)

**Comment by raphael** [comment]
Thank you for the report! can you please provide a complete design that reproduces the issue?

**Comment by pablomadoery** [comment]
Hello. Thank you for your answer.
Here there is a "not_working_design.go"
and also a "working_design.go" which I am currently using as a workaround solution
that does not do exactly what I want (that is, to have a dictionary as a body response).

//not_working_design.go
`package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("data_service", func() {
	Title("data_service")
	Description("get/post data")
	Version("1.0")
	BasePath("/v1")
	Scheme("http")
	Host("localhost:80")
	Consumes("application/json")
})

var _ = Resource("Ups", func() {
	BasePath("/ups")

	Action("create", func() {
		Routing(POST("/"))
		Description("Store an array of one or more ups logs")

		Payload(ArrayOf(UpsPayload))

		Response(Created, func() {
			Media(HashOf(String, Any))
		})

		Response(BadRequest, ErrorMedia)
	})
})

var UpsPayload = Type("UpsPayload", func() {
	Attribute("id", String, func() {
		MinLength(1)
	})
	Attribute("measured_power", String, func() {
		MinLength(1)
	})
	Required("id",
		"measured_power")
})`

//working_design.go
`package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("data_service", func() {
	Title("data_service")
	Description("get/post data")
	Version("1.0")
	BasePath("/v1")
	Scheme("http")
	Host("localhost:80")
	Consumes("application/json")
})

var _ = Resource("Ups", func() {
	BasePath("/ups")

	Action("create", func() {
		Routing(POST("/"))
		Description("Store an array of one or more ups logs")

		Payload(ArrayOf(UpsPayload))

		Response(Created, func() {
			Media(UpsResponseMedia)
		})

		Response(BadRequest, ErrorMedia)
	})
})

var UpsPayload = Type("UpsPayload", func() {
	Attribute("id", String, func() {
		MinLength(1)
	})
	Attribute("measured_power", String, func() {
		MinLength(1)
	})
	Required("id",
		"measured_power")
})

var UpsResponseMedia = MediaType("application/vnd.Upsresponsemedia+json", func() {
	Attributes(func() {
		Attribute("response_data", HashOf(String, Any), "Hash with response data")
	})
	View("default", func() {
		Attribute("response_data")
	})
})

`

**Comment by raphael** [comment]
Thank you for the design (pro tip: you can use code fences in comments to format the code). Using Hashes directly to define a response type is not supported in goa v1 but works in v2, the following design generates the correct code in v2:
```go
package design

import . "goa.design/goa/dsl"

var _ = API("data_service", func() {
	Title("data_service")
	Description("get/post data")
	Version("1.0")
	Server("server", func() {
		Host("development", func() {
			Description("Development hosts.")
			URI("http://localhost:80/calc")
			URI("grpc://localhost:8080")
		})
	})
	HTTP(func() {
		Path("/v1")
		Consumes("application/json")
	})
})

var _ = Service("Ups", func() {
	HTTP(func() {
		Path("/ups")
	})
	Method("create", func() {
		Description("Store an array of one or more ups logs")
		Payload(ArrayOf(UpsPayload))
		Result(MapOf(String, Any))
		HTTP(func() {
			POST("/")
			Response(StatusCreated)
		})
	})
})

var UpsPayload = Type("UpsPayload", func() {
	Attribute("id", String, func() {
		MinLength(1)
	})
	Attribute("measured_power", String, func() {
		MinLength(1)
	})
	Required("id", "measured_power")
})
```
I recommend you upgrade to [v2](https://github.com/goadesign/goa/tree/v2) if your API requires this as v2 includes many other benefits.

**Comment by pablomadoery** [comment]
Ok Thank you very much. I will try v2
