### ISSUE TITLE
"Origin()" equivalence for goa v2 

### ISSUE THREAD

**Issue by pablomadoery** [goadesign/goa#1934]
Hello, I am trying to serve swagger files locally (from inside the same project).
In **goa v1**, in order to define the CORS policy for a given origin
i am using the "**Origin()**" function inside the API definition. 

**Origin()** does not seems to be working in **goa v2**.
Is there an equivalent way to achieve this in v2?

```
package design

import (
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("data_service", func() {
	Title("data_service")
	Description("get/post data")
	Version("1.0")
	BasePath("/v1")
	Scheme("http")
	Host("localhost:80")
	Consumes("application/json")

	Origin("*", func() {
		Methods("GET", "POST", "PUT", "PATCH", "DELETE")
		MaxAge(600)
		Credentials()
	})
})

**Comment by proepkes** [comment]
Like this: https://github.com/proepkes/SpeedDate/blob/go/src/authsvc/design/authorize.go#L12

**Comment by pablomadoery** [comment]
Great !. Thank you, I didn't know about these plugins for goa v2.

**Comment by nitinmohan87** [comment]
Thanks for the report @pablomadoery  and thank you @proepkes as well for answering. I am going to close this issue.
@pablomadoery You can checkout this repo https://github.com/goadesign/plugins for more info on goa v2 plugins.
