### ISSUE TITLE
V2: snake case payload field name doesn't work

### ISSUE THREAD

**Issue by akm** [goadesign/goa#1940]
App generated by goa v2, which expects payload including fields with snake case name doesn't work well.

## Expected Behavior

Accepts fields with snake case name

## Actual Behavior

Ignores the values of snake case fields.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

I made a project to reproduce this problem:
https://github.com/akm/goa_v2_post_payload_including_snake_case_fields

You can run the test by the following command:
```
$ git clone https://github.com/akm/goa_v2_post_payload_including_snake_case_fields.git $GOPATH/src/github.com/akm/goa_v2_post_payload_including_snake_case_fields
$ cd $GOPATH/src/github.com/akm/goa_v2_post_payload_including_snake_case_fields
$ go test
```

### Without snake case names

Using [design.go without snake case names](https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/blob/before_change_field_names/design/desgin.go)
```
$ git checkout before_change_field_names
$ go test
LOG: user.go:24: user.create
PASS
ok  	github.com/akm/goa_v2_post_payload_including_snake_case_fields	0.025s
```

### With snake case names

Using [design.go with snake case names](https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/blob/4acac5f581efab441fb49f2834c25cf19e25d1fa/design/desgin.go)

```
$ git checkout master
$ go test
--- FAIL: TestUserCreate (0.00s)
	user_test.go:61: Status code must be 201 but was 400. Response body: {"name":"missing_field","id":"kutxn_KF","message":"\"first_name\" is missing from body","temporary":false,"timeout":false,"fault":false}
		
FAIL
exit status 1
```

## Specifications

  - goa Version: v2.0.0-wip 75f4ecdc0d34475de8c68f9f9b237d189eb0305c
  - Platform (Linux/Windows etc.): Mac OS X 10.14.2（18C54）

## Memo

I read the generated source code, it seems that [body of NewCreateUserPayload  in gen/http/user/server/types.go](https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/blob/master/gen/http/user/server/types.go#L33-L36) must have json tag. The test passes with [fixing generated source code](https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/commit/3f51c2d2a1bb50a87eda4b571249d4d8b85e2dfd), but I can't fix the generator.

**Comment by nitinmohan87** [comment]
@akm Thank you for reporting this issue. This PR should fix your issue - https://github.com/goadesign/goa/pull/1928
Would really appreciate if you could verify it and let me know if you run into any problems.

**Comment by akm** [comment]
@nitinmohan87 Thank you for your great work. I made sure that it passed the test. And I pushed the commit as  https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/commit/ca07a8806aa61e4b44ad6fa8a22dcae6dc91d40f. 

So I'll close this issue after #1928 is merged. Is it OK?

**Comment by akm** [comment]
@nitinmohan87 I confirmed the test passed with [the latest commit on v2](https://github.com/goadesign/goa/commit/804fa17870b567cb979ff2ab60938e727dd2edf9)  . Thank you for merging #1928 .
