### ISSUE TITLE
Duplicated payload definition and validation method for 2 methods with same payload

### ISSUE THREAD

**Issue by akm** [goadesign/goa#1969]
`goa gen` generates payload definition and validation method twice `create` and `update` methods using same payload.

## Example

```go
var _ = Service("user", func() {
	HTTP(func() {
		Path("/users")
	})

	Method("create", func() {
		Payload(UserPayload)
		Result(User)
		HTTP(func() {
			POST("")
			Body(UserPayload)
			Response(StatusCreated)
		})
	})

	Method("update", func() {
		Payload(func() {
			Attribute("id", Int)
			Attribute("user", UserPayload)
			Required("id", "user")
		})
		Result(User)
		HTTP(func() {
			PUT("/{id}")
			Body("user")
			Response(StatusOK)
		})
	})
})
```

`create` and `update` use `UserPayload`.

See https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/blob/c22b6ae8e39937c3d118ac1cd61ca1190643caa6/design/desgin.go for more detail.

## Expected Behavior

Generate payload definition and validation method once only like this: https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/blob/remove_duplicated_generated_code/gen/http/user/server/types.go

## Actual Behavior

Generate payload definition and validation method twice like this: https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/blob/211fb042d3230eb20acf3d4fd9d55736156fac2d/gen/http/user/server/types.go

## Steps to Reproduce the Problem (including complete and simple design if relevant)

I made a project to reproduce this problem:
https://github.com/akm/goa_v2_post_payload_including_snake_case_fields

You can run the test by the following command:

```
$ git clone https://github.com/akm/goa_v2_post_payload_including_snake_case_fields.git $GOPATH/src/github.com/akm/goa_v2_post_payload_including_snake_case_fields
$ cd $GOPATH/src/github.com/akm/goa_v2_post_payload_including_snake_case_fields
$ go test
```

### current output

```
# github.com/akm/goa_v2_post_payload_including_snake_case_fields/gen/http/user/server
gen/http/user/server/types.go:26:6: UserPayload redeclared in this block
	previous declaration at gen/http/user/server/types.go:19:6
gen/http/user/server/types.go:100:50: ValidateUserPayload redeclared in this block
	previous declaration at gen/http/user/server/types.go:92:50
FAIL	github.com/akm/goa_v2_post_payload_including_snake_case_fields [build failed]
```

## Specifications

  - goa Version: v2.0.0-wip b70dea21c455aacc9404d1bb3e7861d2e1950029
  - Platform (Linux/Windows etc.): Mac OS X 10.14.2（18C54）

**Comment by akm** [comment]
@nitinmohan87 Thank you for fixing.
I verified that `goa gen` doesn't generate duplicate code with `fix_duplicate_payload_def` branch on https://github.com/akm/goa_v2_post_payload_including_snake_case_fields/compare/verify_fix_duplicate_payload_def

**Comment by nitinmohan87** [comment]
@akm Thanks a lot for the bug report and verifying the fix.
