### ISSUE TITLE
No way to validate the requests

### ISSUE THREAD

**Issue by bubenkoff** [goadesign/goa#1979]
I'm implementing FB messenger platform client using goa and can't figure out how to inject custom code to validate request
What FB messenger does is it sends POST requests to the client which needs to validate the request that it's really from FB (as there's no other auth)
this validation is described here: https://developers.facebook.com/docs/messenger-platform/webhook
![screen shot 2019-01-29 at 21 46 56](https://user-images.githubusercontent.com/427136/51978864-c2470880-248b-11e9-9f8d-71594bc94a00.png)

so my question is, how do I access raw request body AND the headers to calculate and check checksum. I looked into implementing custom decoder but it doesn't have access to the request headers

## Specifications

  - goa Version: 1

**Comment by Serjlee** [comment]
An approach which worked fine for me was to specify the exact header in the resource DSL without specifying a Payload, ie:

```
var _ = Resource("webhooks_v1", func() {
	BasePath("/v1/webhooks")
	Description("Webhooks")

	Headers(func() {
		Header("X-Hub-Signature")
		Required("X-Hub-Signature")
	})

	Action("new", func() {
		Description("Listen for webhooks")
		Routing(POST("/"))
		Response(OK)
		Response(BadRequest, ErrorMedia)
	})
})
```

You can then do whatever with the request:
```
func (c *WebhooksV1Controller) New(ctx *app.WebhooksEventsV1Context) error {
	rawBody, err := ioutil.ReadAll(ctx.Request.Body)
	...
	signature := ctx.XHubSignature
	...
	return ctx.OK(nil)
}
```

**Comment by bubenkoff** [comment]
@Serjlee 
thanks, that approach will mean to give up on automatic payload parsing, but it's a workable way
thanks again
