### ISSUE TITLE
[breaking] goa gen with dep ius not working

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1992]
I just ran `dep init` and `goa gen goa.design/goa/examples/calc/design -o test`.

I got below error

```
exit status 1
design must define at least one service
```

I tried to add this line`required = ["goa.design/goa/codegen/generator"]` in gopkg.toml.

Now I could not run dep ensure.
```
Solving failure: 
	(1) exit status 128
```

**Comment by nitinmohan87** [comment]
@kumarsiva07 I am not able to reproduce your issue. Where are you running this `dep init`? goa v2 by itself doesn't require to run `dep`.

**Comment by nitinmohan87** [comment]
I could not reproduce this problem following your steps.
