### ISSUE TITLE
v2: Tracing streaming requests

### ISSUE THREAD

**Issue by arangamani** [goadesign/goa#1998]
Tracing (with X-Ray) for streaming requests today doesn't seem to work very well. I'm proposing some changes here that may work for both gRPC streaming as well as websocket requests in the HTTP transport.

## Stream Server Interceptor
The stream server interceptor doesn't finish until the streaming request finishes. Segments are not sent to X-Ray daemon until the request finishes (including any subsegments created by the service). Also error information is not recorded for streaming requests. Streaming requests can run for an indefinite amount time. There may be other downstream services reporting segments and without the segment from the originating service we may not have the proper context when looking at the traces.

### Proposal
The proposal here is to send an in-progress segment to X-Ray daemon as we receive a streaming request. We do the same for any stream subsegments that get created. When the streaming request finished, we can complete the in-progress segments. We can include a boolean in the Segment struct that helps us identify whether a (sub)segment corresponds to a streaming request. The X-Ray daemon handles batching segments sent to X-Ray so it should be okay to send in-progress segments as soon as we identify them.

## Stream Client Interceptor
The stream client interceptor creates a client stream and finishes immediately so currently the subsegments for streaming request is very short and only corresponds to initiating the streaming request. 

### Proposal
The example here wraps the client stream and intercepts the messages sent by the server stream and finishes the client span if any error is returned: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/tracing/opentracing/client_interceptors.go It seems very simple to do and should work for us.

I think the proposal here can apply to websocket requests as well. If it makes things simpler, we can actually send in-progress segments for regular requests as well. It might just be a lot of messages sent to the X-Ray daemon if the request finishes quickly.

**Comment by jim-slattery-rs** [comment]
Hi Kannan, what a coincidence, I was just looking at the X-Ray tracing last week and have created this `v1` PR for reporting in-progress segments:
https://github.com/goadesign/goa/pull/2000

I haven't looked at gRPC or websocket requests, but I suspect the same approach would work nicely, just as you propose.

**Comment by raphael** [comment]
I believe @jim-slattery-rs's approach works well and could be applied to all requests - not just streaming requests (as also pointed out by @arangamani). If we do that consistently then we shouldn't need to differentiate between streaming and non-streaming requests which would be nice.
