### ISSUE TITLE
SPEC Request: context should be close after all handler called or not.

### ISSUE THREAD

**Issue by kazuki-ma** [goadesign/goa#2001]
Please tell me context object should be closed after all handler called or not.
In other words, we can expect context will close after finishing handler.

Backgroound
====
Middleware.timeout implementation closes context after handler call finished.
(Not only timeout)

https://github.com/goadesign/goa/blob/master/middleware/timeout.go#L35 implementation.

## Expected Behavior (?)
* Context status after all handler call, is closed.
* `defer cancel()`  in Middleware.timeout is not needed.

## Actual Behavior
* Context status after all handler call, is open.
* If we apply Middleware.timeout, context is closed even if not timeout reached.

**Comment by raphael** [comment]
Hello, yes calling `cancel` here is intentional. This is following the pattern established in the standard library, see https://github.com/golang/go/blob/go1.11.5/src/context/context.go#L443-L444
