### ISSUE TITLE
Goa V2 struct:field:type equivalent?

### ISSUE THREAD

**Issue by DejeroDaniel** [goadesign/goa#2013]
Is there a way to set the type for the generated structs in goa v2 like you could in goa v1?
I typically used this for partially parsing json using json.RawMessage, and for settings ObjectIds using bson.ObjectId.

```
	apidsl.Metadata("struct:field:type", "bson.ObjectId", "github.com/globalsign/mgo/bson")
```

**Comment by raphael** [comment]
There isn't at the moment but we'd be happy to accept a PR that added that functionality.

**Comment by DejeroDaniel** [comment]
If I wanted to edit that roughly where in the generator should I start looking for simlar functionality? Like where is the implementation for "struct:field:type"?

**Comment by nitinmohan87** [comment]
@DejeroDaniel Here is how `struct:field:name` is used for example - https://github.com/goadesign/goa/blob/v2/codegen/goify.go#L40

This is the function that generates Go types for the given attribute expressions - https://github.com/goadesign/goa/blob/v2/codegen/scope.go#L107
We could use the `struct:field:type` here to make sure the generated type is set to whatever provided as the value for it.

We also have these transformation functions to convert a service type to transport type (and vice versa) in the server and client code generators. We need to make sure they work when we add support for overriding the field type.

**Comment by Danlock** [comment]
I downloaded the repo and tried make, and it immediately broke on me at make depend. Is there any guide for new contributors?

**Comment by Danlock** [comment]
So I added support for changing the type of an Attribute, but getting stuck on where to add the necessary import statements.
I tried manipulating codegen/service.go File() to add user imports to the `header := codegen.Header()` but those don't show up in the final generated code. Where should I add the imports so they stick?

**Comment by Danlock** [comment]
Added pull request here https://github.com/goadesign/goa/pull/2053
