### ISSUE TITLE
v2: How to add PopulateRequestContext when running `goa example`

### ISSUE THREAD

**Issue by sadayuki-matsuno** [goadesign/goa#2031]
How can I automatically add `PopulateRequestContext` to `cmd/api/http.go` when running `goa example` ?

**Comment by raphael** [comment]
This is not possible out-of-the-box. It should be fairly simple to write a plugin that does that though. The point of the `example` command is to be just that: an example. The intent is to help get started and learn Goa and not be used each time the design changes for example. Hope that makes sense...
