### ISSUE TITLE
goa v2 grpc multiple services with matching method names conflicting types

### ISSUE THREAD

**Issue by zak-blake** [goadesign/goa#2047]
I have a design with two services, each having a method called create. 

When I run my service and hit any endpoint, my client gives these errors:
`2019/03/19 11:08:57 proto: duplicate proto type registered: svc1.CreateRequest
2019/03/19 11:08:57 proto: duplicate proto type registered: svc1.CreateResponse`

That looks like it's caused by this same exact line `proto.RegisterType((*CreateRequest)(nil), "svc1.CreateRequest")` being run in both `gen/grpc/svc1/pb/svc1.pb.go` and `gen/grpc/svc2/pb/svc2.pb.go`

maybe also related: my svc2.proto file includes `package svc1;`

**Comment by nitinmohan87** [comment]
This issue should be fixed by the PR above. Thanks for the report!
