### ISSUE TITLE
migration document from v1 to v2

### ISSUE THREAD

**Issue by voidhaze** [goadesign/goa#2051]
Hi Guys,

We are currently rolling out Goa in own new environment. We picked up development at v1.4 and are looking to move to v2 as it supports gRPC. However we have not found a new features (what is different) list for v2. We were wondering if there is any plans to produce such a list?

**Comment by raphael** [comment]
Yes I'm currently working on this. Will update here once the document is pushed.

**Comment by voidhaze** [comment]
Thanks.

**Comment by raphael** [comment]
Just merged: https://github.com/goadesign/goa/blob/v2/docs/Upgrading.md
