### ISSUE TITLE
How to use swagger as swagger.goa.design

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#206]
How can I create a swagger like swagger.goa.design?

I looked through the [goa swagger](http://goa.design/swagger.html) intro in [goa.design/swagger](http://goa.design/swagger.html) and runed `goagen swagger`, but it just created a file named `swagger.json`, I want a swagger server to show it. 

BTW,  [goa.design/swagger](http://goa.design/swagger.html) is `422 error` after clicking `Go`.
How can I do that?

**Comment by derekperkins** [comment]
That's just the definition. Swagger UI is the html/css/js that references that to generate your docs. To test out, you can reference a swagger.json file here: http://petstore.swagger.io/. 

If you actually build your API with goa, then it will automatically serve that swagger.json file in addition to powering the matching API functions.

**Comment by KerwinKoo** [comment]
Thanks @derekperkins .

If I want to show my API Intro in Swagger UI , I should must published this API server on web right? Would there any tools to show local Swagger formated JSON file?

Thanks again!

**Comment by derekperkins** [comment]
https://github.com/swagger-api/swagger-ui

From their docs: "You can use the swagger-ui code AS-IS! No need to build or recompile--just clone this repo and use the pre-built files in the dist folder. If you like swagger-ui as-is, stop here."

**Comment by KerwinKoo** [comment]
@derekperkins Thank you very much!
