### ISSUE TITLE
App generated files are empties

### ISSUE THREAD

**Issue by MathieuDoyon** [goadesign/goa#208]
Each generated file into app/ directory have no code under `package app`

**Comment by moorereason** [comment]
Can you share your API `design` package?

**Comment by MathieuDoyon** [comment]
https://gist.github.com/MathieuDoyon/252f74ddac5e4141a46c

**Comment by moorereason** [comment]
Goa now lives at `github.com/goadesign/goa`.  Try updating your import paths and installing a new `goagen` binary.

Hop on the Slack #goa channel if you want to get help troubleshooting.

**Comment by MathieuDoyon** [comment]
Thanks
