### ISSUE TITLE
GOA v2 -- Validation function for grpc client not generated

### ISSUE THREAD

**Issue by MLoewenberg** [goadesign/goa#2088]
For a method using grpc I've created a type for the result. This type contains an array of another type. The inner type has some validations.
If I use that type as the payload the file gen/grpc/servicename/server/types.go contains a validation function for both types.

## Expected Behavior
The file gen/grpc/servicename/client/types.go should contain a validation function for every type used in the result.

## Actual Behavior
The file gen/grpc/servicename/client/types.go contains a ValidateMainType function for the type directly referenced in the result. This function also calls the ValidateSubType function. But the ValidateSubType function itself is never generated.

## Steps to Reproduce the Problem
Rename the file [example.txt](https://github.com/goadesign/goa/files/3165800/example.txt)
 to example.go and run the generation.

## Specifications

  - goa Version: V2

> revision = "f54109e9aaafaf82e58417fc69006c22328f418d"

  - Platform (Linux/Windows etc.): Windows Subsystem for Linux with Ubuntu 18.04 and go version 1.12.1

**Comment by raphael** [comment]
Thank you for the detailed report, I was able to confirm the issue.

**Comment by raphael** [comment]
This should now be fixed, could you validate and close the issue if it is? thanks!

**Comment by MLoewenberg** [comment]
Thank you. It works fine for me.
