### ISSUE TITLE
v3: Using BasicAuth with custom scopes

### ISSUE THREAD

**Issue by CuBiC3D** [goadesign/goa#2105]
As mentioned in #1959, we kinda 'misuse' BasicAuth in v1 by supplying scopes to it. This allows us to extract the scopes via goa.ContextRequiredScopes(ctx) in the middleware, authenticate the user against LDAP and match the scopes against LDAP groups. It even generates correct swagger, which contains the required scope, e.g.: BasicAuth (users:list). As far as I can see, v3 does not allow scopes to be defined on Security(BasicAuth) and also requires to have username and password payload defined on every method, instead of handling everything in middleware only.

Is there any approach to move this to v2/v3 or any idea how we could solve this? :smiley:

**Comment by raphael** [comment]
Hello, you are right that v3 doesn't currently do anything with scopes defined on BasicAuth schemes. It would probably be fine to add Scopes to the [BasicScheme](https://github.com/goadesign/goa/blob/v3/security/scheme.go#L20) struct and modify the code generation [algorithm](https://github.com/goadesign/goa/blob/v3/codegen/service/endpoint.go#L209) to initialize the `Scopes` and `RequiredScopes` similarly to how it's done for JWT tokens for example. Happy to merge a PR that would do that.
