### ISSUE TITLE
v2 api with https still using http

### ISSUE THREAD

**Issue by manirahul83** [goadesign/goa#2109]
I have the Host part described as follows. However in the generated code i still don't see the generated code using TLS. We had to add code to use the schema. Is there something i am missing here?
```go
	// List the Hosts and their transport URLs.
		Host("production", func() {
			Description("Control Plane API.")
			// Transport specific URLs, supported schemes are:
			// 'http', 'https', 'grpc' and 'grpcs' with the respective default
			// ports: 80, 443, 8080, 8443.
			URI("https://localhost:8443/{version}")

			// Variable describes a URI variable.
			Variable("version", String, "API version", func() {
				// URL parameters must have a default value and/or an
				// enum validation.
				Default("v1")
			})
		})
```

**Comment by manirahul83** [comment]
Any help on this?

**Comment by raphael** [comment]
Yeah you're right that the current example generation only generates HTTP servers. I'd happily accept a PR that fixes that. Note that the code generated by the `example` command can (and should) absolutely be modified - this command is not meant to be re-run after changing the design for example - it is meant to be run once to bootstrap. This is the template used to generate the example that would have to be modified. There would need to be code that checks whether TLS should be used in which case there would have two be two additional command line flags defined for the cert and key required to call `ListenAndServerTLS`. https://github.com/goadesign/goa/blob/v3/http/codegen/example_server.go#L287

**Comment by manirahul83** [comment]
> Yeah you're right that the current example generation only generates HTTP servers. I'd happily accept a PR that fixes that. Note that the code generated by the `example` command can (and should) absolutely be modified - this command is not meant to be re-run after changing the design for example - it is meant to be run once to bootstrap. This is the template used to generate the example that would have to be modified. There would need to be code that checks whether TLS should be used in which case there would have two be two additional command line flags defined for the cert and key required to call `ListenAndServerTLS`. https://github.com/goadesign/goa/blob/v3/http/codegen/example_server.go#L287

That is exactly what we did as changes in our generated code. however when we change stuff, its getting difficult to update. In v1 version, we had commented code where when we added between those lines, it would keep those while updating remaining code. We need that back somehow.

However that being said, TLS supported out of the box would be awesome.

**Comment by manirahul83** [comment]
https://github.com/goadesign/goa/pull/2122

**Comment by kmeehl** [comment]
Implementation submitted here: https://github.com/goadesign/goa/pull/2122
