### ISSUE TITLE
Setting a basepath in the URI of service https://localhost:8443/v1 is not mounting on all paths.

### ISSUE THREAD

**Issue by manirahul83** [goadesign/goa#2110]
When we set a base path after the host:port, it does not work for all methods like in v1 and we have to add to all methods.

example https://localhost:8443/v1. Here /v1 is not added by default to all methods and we have to explicitely add /v1 to all methods.

**Comment by manirahul83** [comment]
Do we have any help on this?

**Comment by raphael** [comment]
Can you please provide a complete repro including a complete design that shows the problem? Also please explain where the problem is in the generated code. Thank you!

**Comment by manirahul83** [comment]
So when i set this 
	Server("cp-api", func() {
		// List the Hosts and their transport URLs.
		Host("development", func() {
			URI("http://localhost:8080/v1")
		})

		Host("production", func() {
			URI("https://localhost:8443/v1")
		})
	})

I expected v1 to be part of the base path and any services like foo or bar when it has methods i can just put it as /foo and /bar and the complete url would be https://localhost:8443/v1/foo or https://localhost:8443/v1/bar. However what i observed was that we need to have methods as /v1/foo or /v1/bar for that implementation. This beats the version being added to the host URL completely.

**Comment by cubic3d** [comment]
Here's a minimal example design:
```
package design

import . "goa.design/goa/v3/dsl"

var _ = API("api", func() {
	Server("apisvr", func() {
		Host("default", func() {
			URI("http://0.0.0.0:8000/v1")
		})
	})
})

var _ = Service("svc", func() {
	Method("test", func() {
		Result(String)

		HTTP(func() {
			GET("/")
			Response(StatusOK)
		})
	})
})
```
The method is mounted on `/` after generating examples:
```
#: http localhost:8000/v1
HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Mon, 27 May 2019 12:01:39 GMT
X-Content-Type-Options: nosniff

404 page not found
```

**Comment by nitinmohan87** [comment]
I think this a bug in the docs for the URI which suggests that you can define URI paths in this expression. The docs also mentions that URI expression is used to define only the authority part of the URI (which is actually the correct usage).

So, to answer your question, we either need to fix `URI` DSL to support paths like you have or fix the documentation to say URI DSL only supports domain names. I think the fixing the URI DSL to support URI paths is the way forward. We should also make it aware of `Path` DSL which can be defined at the service level.

**Comment by raphael** [comment]
Just one question: what would be the meaning of the URI path component for gRPC servers?

**Comment by yogihardi** [comment]
as mentioned here: https://goa.design/learn/upgrading/

> The following changes have been made to the API DSL:
> The `Host`, `Scheme` and `BasePath` DSLs are replaced with `Server`.

on previous version we can use `BasePath` on all `Action` without adding `/v1` to all methods.
right now it doesn't
