### ISSUE TITLE
v1 import not working, getting routed to v2

### ISSUE THREAD

**Issue by jsteenb2** [goadesign/goa#2111]
setup: `go version go1.11.10 linux/amd64`

Instructions to install the goa toolchain are not working as expected.

Attempting to install v1 goagen via:

`go get -u goa.design/v1/goa` does not hit the v1 `gopkg`, but rather v2. 

Not sure how to remedy this, any docs/work arounds available?

**Comment by raphael** [comment]
Goa v1 can be installed with
```bash
go get -u -v github.com/goadesign/goa/...
```
Note that the `master` branch and the `v1` branch are similar but not equivalent. The `master` branch is deprecated so it is recommended to use a vendoring tool (e.g. `dep`) to pin Goa to the `v1` branch.

**Comment by agnivade** [comment]
In my case, it is trying to fetch v3. This has essentially stopped out builds in CI. Let me know how to resolve this - 

```
go get -v -u github.com/goadesign/goa/...
github.com/goadesign/goa (download)
Fetching https://goa.design/goa/v3/codegen?go-get=1
Parsing meta tags from https://goa.design/goa/v3/codegen?go-get=1 (status code 200)
get "goa.design/goa/v3/codegen": found meta tag get.metaImport{Prefix:"goa.design/goa", VCS:"git", RepoRoot:"https://gopkg.in/goadesign/goa.v2"} at https://goa.design/goa/v3/codegen?go-get=1
get "goa.design/goa/v3/codegen": verifying non-authoritative meta tag
Fetching https://goa.design/goa?go-get=1
Parsing meta tags from https://goa.design/goa?go-get=1 (status code 200)
goa.design/goa (download)
package github.com/goadesign/goa/cmd/goa
	imports goa.design/goa/v3/codegen: cannot find package "goa.design/goa/v3/codegen" in any of:
	/usr/local/go/src/goa.design/goa/v3/codegen (from $GOROOT)
	/go/src/goa.design/goa/v3/codegen (from $GOPATH)
Fetching https://goa.design/goa/v3/pkg?go-get=1
Parsing meta tags from https://goa.design/goa/v3/pkg?go-get=1 (status code 200)
get "goa.design/goa/v3/pkg": found meta tag get.metaImport{Prefix:"goa.design/goa", VCS:"git", RepoRoot:"https://gopkg.in/goadesign/goa.v2"} at https://goa.design/goa/v3/pkg?go-get=1
get "goa.design/goa/v3/pkg": verifying non-authoritative meta tag
package github.com/goadesign/goa/cmd/goa
	imports goa.design/goa/v3/pkg: cannot find package "goa.design/goa/v3/pkg" in any of:
	/usr/local/go/src/goa.design/goa/v3/pkg (from $GOROOT)
	/go/src/goa.design/goa/v3/pkg (from $GOPATH)
```

**Comment by agnivade** [comment]
This is because v3 is the default branch. So essentially there is no way to use GOPATH mode and keep using v1. I had to move to module mode to keep using v1. In future, I would request to proceed with caution to avoid breaking your users' codebase.

**Comment by raphael** [comment]
Yeah it's not great, on the other hand keeping the default on GitHub to the old master is also pretty bad as newcomers would be misled. I don't really see a good way out, do you? Obviously it's possible to use git to clone the repo and checkout the v1 branch - that makes it possible to use v1 without Go modules but is an extra unexpected step. I'll add these instructions to the v1 README.
