### ISSUE TITLE
v3: Content-Type header of response does not respect the ResultType identifier

### ISSUE THREAD

**Issue by cubic3d** [goadesign/goa#2117]
Defining a ResultType with
```
var MyResult = ResultType("application/vnd.myapi.myresult", func() {
...
```
leads to following response headers:
```
HTTP/1.1 200 OK
Content-Length: 74
Content-Type: application/json
Date: Fri, 24 May 2019 09:26:39 GMT
```
expected Content-Type should be `Content-Type: application/vnd.myapi.myresult+json` or for XML `Content-Type: application/vnd.myapi.myresult+xml`

**Comment by nitinmohan87** [comment]
To override the content type you should explicitly use the [ContentType DSL](https://godoc.org/goa.design/goa/dsl#ContentType) in the ResultType DSL.

**Comment by nitinmohan87** [comment]
@raphael We could update the [ResultType DSL](https://godoc.org/goa.design/goa/dsl#ResultType) to explicitly state that the default content-type does not override the actual content-type in the response and we must use `ContentType` DSL to do so.

**Comment by cubic3d** [comment]
@nitinmohan87 but `ContentType` does not set the appropriate format(`+json`, `+xml`) right?

**Comment by nitinmohan87** [comment]
@CuBiC3D Correct.. The [default goa response encoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L84) does not append the `+json` or `+xml` suffix to the content-type header in response.

You can also provide your own response encoder implementation instead of the default goa http response encoder [here](https://github.com/goadesign/examples/blob/master/encodings/cmd/encodings/http.go#L37).

**Comment by raphael** [comment]
Actually @nitinmohan87 , the default response encoder does properly set the suffix see https://github.com/goadesign/goa/blob/v3/http/encoding.go#L161. @CuBiC3D  I believe you can get to what you want by using the `ContentType` DSL to set the media type identifier without suffix. As long as the HTTP response is encoded using the default goa encoder into JSON or XML then the proper suffix will get added.
