### ISSUE TITLE
v3: command line client only prints the error description for primitive error types.

### ISSUE THREAD

**Issue by cubic3d** [goadesign/goa#2124]
Using the following minimal design:
```
package design

import . "goa.design/goa/v3/dsl"

var _ = Service("svc", func() {
	Method("test", func() {
		Error("notfound", String, "Item not found")

		HTTP(func() {
			GET("/")
			Response("notfound", StatusNotFound)
		})

		GRPC(func() {
			Response("notfound", CodeNotFound)
		})
	})
})
```
And `test` defined like:
```
// Test implements test.
func (s *svcsrvc) Test(ctx context.Context) (err error) {
	return svc.Notfound("This should be the error message!")
}
```
A HTTP request against `/` gives:
```
#: http localhost                                                                                                                                                                                  
HTTP/1.1 404 Not Found
Content-Length: 36
Content-Type: application/json
Date: Mon, 27 May 2019 11:28:05 GMT
Goa-Error: notfound

"This should be the error message!"

```
Using gRPC however does not override the error message from the design:
```
#: go run ./cmd/svc-cli svc test                                                                                                                                                           
Item not found
exit status 1
```

**Comment by nitinmohan87** [comment]
Actually this is not a bug. But something we should discuss what needs to happen on the generated client. When you run `go run ./cmd/svc-cli`, the generated client, by default, hits the HTTP endpoint. So the error message is returned is whatever is defined for the Notfound type's `Error()` method which is "Item not found".
```
// Item not found
type Notfound string

// Error returns an error description.
func (e Notfound) Error() string {
  return "Item not found"
}

// ErrorName returns "notfound".
func (e Notfound) ErrorName() string {
  return "notfound"
}
```
Instead of using the generated goa client, when you hit the endpoint directly using a `curl`, it returns the custom error message defined in the service implementation. We should probably make the generated client honor the custom error messages defined in the service implementation for primitive type errors.

@raphael Any thoughts on this one ^

**Comment by nitinmohan87** [comment]
FYI, this behavior is not gRPC specific. It is just the way goa was implemented in general.

**Comment by cubic3d** [comment]
Right, I haven't paid attention, it actually uses HTTP, I assumed based on the build output of `go run` ->`run '/tmp/go-build184295209/b001/exe/grpc --help' for detailed usage.` it would use gRPC.

But requesting via gRPC without any goa CLI interaction using official gRPC CLI:
```
# grpc_cli --protofiles svc.proto call localhost:8080 svc.Svc/Test ""
connecting to localhost:8080
Received trailing metadata from server:
grpc-status-details-bin :Item not found�N
'type.googleapis.com/goapb.ErrorResponse#
faulreUyiiLU�Item not found0
Rpc failed with status code 5, error message: Item not found
Reflection request not implemented; is the ServerReflection service enabled?
```
still gives "Item not found".

**Comment by raphael** [comment]
This behavior is expected: the error being returned to the client is the string returned by the server code. What you are seeing here is the client command line tool printing the value returned by the `Error()` method which returns the description set in the design. We could also have the client print the actual error data structure (which in this case happens to be a string) - I wouldn't be opposed to merging a PR that does that. But this is just about what the command line client decides to show on the console - there is no issue with the actual error object itself.

**Comment by cubic3d** [comment]
@raphael I'm still confused why this is related to the generated client :confused:. I used [HTTPie](https://httpie.org/) for the HTTP request and [grpc_cli](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md) for gRPC (ignore the generated CLI usage in the opening comment). None of them is is related to goa nor they interact with the code. grpc_cli via plain gRPC returns `Item not found` instead of `This should be the error message!`. Am I still missing something?
```
#: http localhost
HTTP/1.1 404 Not Found
Content-Length: 36
Content-Type: application/json
Date: Mon, 27 May 2019 11:28:05 GMT
Goa-Error: notfound

"This should be the error message!"
```
```
# grpc_cli --protofiles svc.proto call localhost:8080 svc.Svc/Test ""
connecting to localhost:8080
Received trailing metadata from server:
grpc-status-details-bin :Item not found�N
'type.googleapis.com/goapb.ErrorResponse#
faulreUyiiLU�Item not found0
Rpc failed with status code 5, error message: Item not found
Reflection request not implemented; is the ServerReflection service enabled?
```
