### ISSUE TITLE
 V3 generates  `gen` code to introduce package path to relative path

### ISSUE THREAD

**Issue by tp-life** [goadesign/goa#2125]
Using the calc in the example, after generating the code using `goa gen calcsvc/design`, the package `calc "./calc"` in `gen/http/calc/server/server.go` should be: `calc "calcsvc/ Gen/calc"`. The import path of many packages in the generated `gen` directory has this problem.
![image](https://user-images.githubusercontent.com/16291855/58425362-37d68480-80cc-11e9-9c58-b862cae3cbcd.png)

**Comment by cubic3d** [comment]
Can't reproduce here using v3 with modules. Didn't use calc, but every other design generated does have correct imports:
```
import (
	"context"
	"net/http"
	svc "test3/gen/svc"

	goa "goa.design/goa/v3"
	goahttp "goa.design/goa/v3/http"
)
```
Your goa import does not indicate v3, but the directory structure does not look like v1. Are you using /v3 3.0.0 im modules?

**Comment by tp-life** [comment]
Yes, I tried it based on the example of calcsvc. Goa version v3.0. Is this related to the `design` design?
![image](https://user-images.githubusercontent.com/16291855/58448449-93d7f200-813a-11e9-90a4-e18a0c4b181a.png)

**Comment by cubic3d** [comment]
Just generated the example
```
package design

import . "goa.design/goa/v3/dsl"

// API describes the global properties of the API server.
var _ = API("calc", func() {
        Title("Calculator Service")
        Description("HTTP service for adding numbers, a goa teaser")
        Server("calc", func() {
		Host("localhost", func() { URI("http://localhost:8088") })
        })
})

// Service describes a service
var _ = Service("calc", func() {
        Description("The calc service performs operations on numbers")
        // Method describes a service method (endpoint)
        Method("add", func() {
                // Payload describes the method payload
                // Here the payload is an object that consists of two fields
                Payload(func() {
                        // Attribute describes an object field
                        Attribute("a", Int, "Left operand")
                        Attribute("b", Int, "Right operand")
                        // Both attributes must be provided when invoking "add"
                        Required("a", "b")
                })
                // Result describes the method result
                // Here the result is a simple integer value
                Result(Int)
                // HTTP describes the HTTP transport mapping
                HTTP(func() {
                        // Requests to the service consist of HTTP GET requests
                        // The payload fields are encoded as path parameters
                        GET("/add/{a}/{b}")
                        // Responses use a "200 OK" HTTP status
                        // The result is encoded in the response body
                        Response(StatusOK)
                })
        })
})
```
This results in:
```
import (
	calc "calcsvc/gen/calc"
	"context"
	"net/http"

	goa "goa.design/goa/v3"
	goahttp "goa.design/goa/v3/http"
)
```

Are you in a GOPATH? Or in any other go related directory? Do you have a project inside GOPATH named calcsvc from before? Make sure to stay outside of GOPATH and check for `$GOPATH/src/calcsvc` is not present there.

**Comment by tp-life** [comment]
Yes, I am sure it is outside of GOPATH, and there is no directory with the same name in GOPATH. I re-replace the directory and try again, but this problem still occurs. I don't know if there is a problem with my installation, or where is the problem?

**Comment by tp-life** [comment]
![image](https://user-images.githubusercontent.com/16291855/58525827-b2ec8780-81ff-11e9-97c7-b62afabb93ac.png)
There should be a problem with `pkg.ImportPath` return `.`

**Comment by raphael** [comment]
I just tagged `v3.0.1` which contains a few bug fixes. Would you mind trying with the latest?

**Comment by tp-life** [comment]
Ok, let me try.

**Comment by tp-life** [comment]
There was a problem with the code package that was pulled before. Delete the cache code and re-pull it normally.
