### ISSUE TITLE
v2: crash when two fields use the same type

### ISSUE THREAD

**Issue by tmcladam** [goadesign/goa#2127]
Use this design to reproduce:

[repro2.go.txt](https://github.com/goadesign/goa/files/3232685/repro2.go.txt)

Error message / stack trace:

[crash.log.txt](https://github.com/goadesign/goa/files/3232715/crash.log.txt)

Suggested patch:

[crash.diff.txt](https://github.com/goadesign/goa/files/3232722/crash.diff.txt)

A nil TransformFunctionData is returned when the function has already been seen. This should either not be appended to the array (as in the patch above), or nil elements should be ignored whenever iterating over the array.

**Comment by raphael** [comment]
Good catch, makes sense! Would you mind putting a couple of PRs together (one for `v2` and one for `v3`)? Thank you!

**Comment by tmcladam** [comment]
Done, cheers
