### ISSUE TITLE
v3: how to properly serve different status codes?

### ISSUE THREAD

**Issue by ilmaruk** [goadesign/goa#2134]
I'm currently using a ResultType Attribute  as a Tag in a Method HTTP Response, in order to be able to respond to requests with a `304`, instead of a `200`, where necessary (see design at the bottom).
The problem is that the Attribute (`status` in my design below) is then shown in the Swagger documentation, as part of the response JSON payload example.

Am I missing anything? Is there a way to avoid such Attributes ending up in the response payload example, the way it works for Attributes that are used as Headers?

Thanks! 

```
var myResult = ResultType("my-result-type", func() {
	Attribute("status", String)

	// Headers
	Attribute("eTag", String)
	Attribute("lastModified", String)
})

var _ = Service("my-service", func() {
        Method("get", func() {
		Result(myResult)

		HTTP(func() {
			GET("/foo")

			Headers(func() {
				Header("ifNoneMatch:If-None-Match")
				Header("ifModifiedSince:If-Modified-Since")
			})

			Response(StatusOK, func() {
				Header("lastModified:LastModified")
				Header("eTag:ETag")
			})
			Response(StatusNotModified, func() {
				Tag("status", "not-modified")
				Body(Empty)
				Header("lastModified:LastModified")
				Header("eTag:ETag")
			})
		})
	})
})
```

**Comment by raphael** [comment]
Define the `Default` view explicitly on the result type and omit the "status" attribute from it.

**Comment by ashtonian** [comment]
```go
var myResult = ResultType("my-result-type", func() {

	// Headers
	Attribute("SomJsonField", String)
    View("default")
})

var _ = Service("my-service", func() {
        Method("get", func() {
		Result(myResult)

		HTTP(func() {
			GET("/foo")

			Response(StatusOK, func() {
	        Body(myResult)
			})
			Response(StatusNotModified, func() {
				Body(Empty)
			})
		})
	})
})
```

How do you get it to return the 204 from the service side? If I `return nil, nil` for the `func foo()(*myresult,error)` it errors out.
