### ISSUE TITLE
v2: How to get the URL from the GET Method

### ISSUE THREAD

**Issue by pablomadoery** [goadesign/goa#2145]
Hello, I am trying to have some "pagination" functionality and, along with the response data, I need to return a "link" to the "next" page with data. I imagine I could do that if I had access to the URL
of the GET Method (maybe by using the context data), and modifying that URL to change the "page" parameter.
I couldn't find and answer on how to do that.

**Comment by nitinmohan87** [comment]
@pablomadoery You can write a HTTP middleware that populates the context with the URL. You can look into the [RequestID middleware](https://github.com/goadesign/goa/blob/v3/http/middleware/requestid.go#L22) as an example.
