### ISSUE TITLE
V3: How to handle unmarshalling errors?

### ISSUE THREAD

**Issue by ilmaruk** [goadesign/goa#2148]
I have a design that looks roughly like this:
```package design

import (
    . "goa.design/goa/v3/dsl"
)

var _ = API("test-api", func() {
    Server("test-server", func() {
        Services("test-service")
    })
})

var _ = Service("test-service", func() {
    Method("put-exams", func() {
        Payload(func() {
            Attribute("studentId", Int, "The student id (numeric).")
            Attribute("exams", ArrayOf(examType), "The list of exams for a specific student.")
            Required("studentId", "exams")
        })

        Error("not-found")

        HTTP(func() {
            PUT("/students/{studentId}/exams")

            Params(func() {
                Param("studentId")
            })

            Response(StatusNoContent)
            Response("not-found", StatusNotFound)
        })
    })
})

var examType = ResultType("exam", func() {
    Attribute("name", String)
    Attribute("mark", Int)
    Attribute("notes", String)
    Required("name", "mark")
})
```
and I'm getting the following error, if the request has a body that doesn't match the expected structure:
```
2019/06/10 14:47:34 http: panic serving 127.0.0.1:50452: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc0001d41e0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x7fe980, 0xbc3210)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
goa/gen/http/test_service/server.unmarshalExamRequestBodyToTestserviceExam(...)
	/tmp/goa/gen/http/test_service/server/encode_decode.go:99
[..]
```
E.g.:
```
$ echo '{"exams":[{}]}' | http PUT localhost:9090/users/1973/exams
```
which happens before the handling function is invoked.
Is there a way of handling such incorrect payloads nicely (e.g.: returning a 400)?

**Comment by nitinmohan87** [comment]
Definitely a bug! The generated validation code for the request body only checks if the `exams` is present in the request body. It must have also validated the contents of each `exam` item.

**Comment by ilmaruk** [comment]
I believe the bug lies in the assumption that unmarshalling would return an error if the provided JSON was not "compatible" with the receiving structure. Unmarshalling instead returns an error only if the JSON blob is malformed or if an object is defined where a list is expected, etc.
But if a well formed JSON blob, yet incompatible with the receiving structure is provided, unmarshalling doesn't return any error and the receiving structure is simply left empty.

I reckon the `unmarshal*` functions should check the required fields are not `nil`, before accessing them.

**Comment by raphael** [comment]
That description makes sense @ilmaruk. Would you be able to take a crack at it?

**Comment by ilmaruk** [comment]
I'll try my best. I must admit I'm not yet very much acquainted with how code is generated, but I'll gladly look into it.

**Comment by raphael** [comment]
Thank you, happy to help with questions. Feel free to join the Goa channel in the [Gophers](https://gophers.slack.com/messages/C0FK8EV28/) slack (join [here](https://invite.slack.golangbridge.org/) ).

**Comment by raphael** [comment]
@ilmaruk thank you for the detailed report, this is now fixed. The bug was preventing correct validation of elements of collection of user types, nice catch! This will be in v3.0.4.
