### ISSUE TITLE
V3: Service Discovery Mechanism

### ISSUE THREAD

**Issue by SantoshSah** [goadesign/goa#2156]
Which service discovery mechanism has been used in goa?

**Comment by nitinmohan87** [comment]
@SantoshSah Could you please elaborate more? I am not sure I understand what you are trying to do. [Goa](https://goa.design/) is a framework to build and document microservices. It generates swagger docs for HTTP services. There is a [goa plugin which generates a JSON file](https://github.com/goadesign/plugins/tree/v3/docs) that documents the services and endpoints.

**Comment by SantoshSah** [comment]
Hi @nitinmohan87,
I meant to say that since service instances have dynamically assigned network locations and set of service instances changes dynamically because of auto-scaling, failures, and upgrades, how can one service knows network location(IP address and port) of another service instance? Distributed service mesh like consul, etcd, Zookeeper and others can be used for this purpose. So my question was which distributed service mesh has been used in goa and how someone can use of his/her choice?

**Comment by raphael** [comment]
There is nothing specific to Goa that would make it better or less suited to any particular service discovery mechanism. The process can be configured via flags or environment variables, you get to write the code that does that. We've used Consul, Kubernetes and Itsio.

**Comment by SantoshSah** [comment]
Thank you. Is there any example of goa consisting multiple services, where Consul, Kubernetes and Itsio have been used and that example can be used as starting point for real application?

**Comment by raphael** [comment]
No there isn't such an example that I know of. Any Go example would be directly applicable though. Also I'd be happy to merge a PR to the [examples](https://github.com/goadesign/examples) repo that did that.
