### ISSUE TITLE
V3: add support for text/plain context-type

### ISSUE THREAD

**Issue by ilmaruk** [goadesign/goa#2157]
Unless I'm mistaken, currently the only way of returning plain text is to set the `text/html` context-type (along with either `Return(String)` or `Return(Bytes)`), which is not ideal if one's returning plain text (`text/plain`).

I'd like to add support for `text/plain` MIME type, if that's alright?

I'll close a related issue I opened a few days ago:
https://github.com/goadesign/goa/issues/2155

**Comment by nitinmohan87** [comment]
@ilmaruk You can provide your own encoder/decoder implementation that supports `text/plain` and initialize it on the server side here - https://github.com/goadesign/examples/blob/master/basic/cmd/calc/http.go#L36-L37

We could add support for it in goa itself. I will let @raphael decide on that one. But for the time being you can add your own implementation.

**Comment by ilmaruk** [comment]
Thanks @nitinmohan87 I'll do it that way; much appreciated.

Please be aware that the document mentioned in the example you pointed me to (goa.design/encoding) doesn't exist, though.

**Comment by nitinmohan87** [comment]
@ilmaruk Do you mean this link? - https://github.com/goadesign/examples/blob/master/basic/cmd/calc/http.go#L36-L37

It is a public goa examples repo. Are you not able to access it?

**Comment by ilmaruk** [comment]
Sorry @nitinmohan87 , I didn't make myself clear: the link _you_ posted works alright, but at line 34 of the referred example it says: "[..]see goa.design/encoding", but that document doesn't exist (assuming it's an HTML document it's referring to).

**Comment by raphael** [comment]
I think it would be good for Goa to support this encoding natively, I'd happily merge a PR that did that.

**Comment by ilmaruk** [comment]
Happy to contribute.

**Comment by raphael** [comment]
Thank you for the great contribution!
