### ISSUE TITLE
build-error occur when build generated code 

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#216]
I just run the test code in [READEM.md](https://github.com/goadesign/goa).

After running `$ goagen bootstrap -d goa-adder/design`, when I `go build` the generated code, some error showed in the terminal:

```
# goa-adder
./main.go:21: cannot use service (type "github.com/goadesign/goa".Service) as type "github.com/raphael/goa".Service in argument to NewOperandsController:
	"github.com/goadesign/goa".Service does not implement "github.com/raphael/goa".Service (wrong type for DecodeRequest method)
		have DecodeRequest(*"github.com/goadesign/goa".Context, interface {}) error
		want DecodeRequest(*"github.com/raphael/goa".Context, interface {}) error
./operands.go:16: cannot use OperandsController literal (type *OperandsController) as type app.OperandsController in return argument:
	*OperandsController does not implement app.OperandsController (wrong type for ErrorHandler method)
		have ErrorHandler() "github.com/raphael/goa".ErrorHandler
		want ErrorHandler() "github.com/goadesign/goa".ErrorHandler

``` 

I don't know what causes that, but It's fun befor I running `go get -v -u https://github.com/goadesign/goa` to update `Goa package`. Can it be possible that  the error caused by the new version?

**Comment by raphael** [comment]
Is it possible that you have an old `goagen` laying around? I see that the code is using `raphael/goa` instead of the new location `goadesign/goa`. Maybe try doing a `go get -u github.com/goadesign/goa/goagen`.

**Comment by KerwinKoo** [comment]
I knew what happend. When I after updating by running "go get -u", it created a new directory named `github.com/raphael/`, `goimport` can thus import this `raphael` package. 

Now I deleted this wrong package path. But I also don't know why the `raphael` can be created after updating?

**Comment by raphael** [comment]
Probably because the code where you did `go get -u` still had reference to the `raphael` repo. I would do this:

1. Remove all the generated code directories (`./app`, `./swagger`, etc.)
2. Search and replace `github.com/raphael` with `github.com/goagen` in all your files
3. `go get -u github.com/goadesign/goa/goagen`
4. For good measure (shouldn't be needed): `rm -rf $GOPATH/src/github.com/raphael/goa`

**Comment by KerwinKoo** [comment]
It works after running `go get -u github.com/goadesign/goa/goagen`. Thank you @raphael .

But I still don't understand why created the `raphael` path, I never `go get` the  `goa` package in  `raphael`.

Thanks again!
