### ISSUE TITLE
middleware/xray non-test code imports "testing"

### ISSUE THREAD

**Issue by tmcladam** [goadesign/goa#2160]
middleware/xray/testing.go imports "testing" which causes flags.Usage() to include testing flags and should not be included in production code.
Is it as simple as renaming this file to testing_test.go?

**Comment by raphael** [comment]
Yes that makes sense, happy to merge a PR that makes the change :)

**Comment by tmcladam** [comment]
It was a little more involved - those helpers are also used by the transport-specific middleware tests in other packages, so created a separate package.
