### ISSUE TITLE
V3: Validation function for http client not generated

### ISSUE THREAD

**Issue by johnmanjiro13** [goadesign/goa#2164]
I created a type for the result for a method using http. This type contains an array of another type.
The inner type has some validations.

The file gen/http/api/client/types.go call a ValidateThirdTypesResponseBody function.
But the ValidateThirdTypesResponseBody function is never generated.

## Sample design
I wrote a sample design file which cause this problem.
https://gist.github.com/johnmanjiro13/91ced09ba87ee7a21739d21d216d9be7

**Comment by johnmanjiro13** [comment]
I changed a .txt file in a description to a gist.

**Comment by raphael** [comment]
Thank you, I was able to reproduce the bug.
