### ISSUE TITLE
v3: verbose logs

### ISSUE THREAD

**Issue by dohnto** [goadesign/goa#2167]
Hello, I am quite new to goa so excuse for my possible ignorance.

I use goa for my API and if I run my server and got an error (see example bellow) this is very uninformative. I need to know what error actually happened.
```
[api] 08:44:13  id=OJtCEZ0y req=GET /v2/services from=127.0.0.1
[api] 08:44:13  id=OJtCEZ0y status=500 bytes=145 time=23.626896ms
```

From the service response I can see, that there is a database error, but it would be convenient to see the errors in also logs.
```json
{
  "name": "fault",
  "id": "UfM79e3B",
  "message": "Error 1146: Table 'myservice.servicesx' doesn't exist",
  "temporary": false,
  "timeout": false,
  "fault": true
}
```

Is there a way to turn on more verbose logging? The first that comes to my mind is to write custom middleware, that parses responses and searches for key `.fault=true` but this feel clumpsy. Is there a better way?

**Comment by raphael** [comment]
Hello, the HTTP logger works at the transport level and thus does not have access to the error returned by the endpoint. It seems you want a endpoint middleware that logs errors, something like:

```go
func ErrorMiddleware(log *log.Logger) func(goa.Endpoint) goa.Endpoint {
    return func ErrorLogger(e goa.Endpoint) goa.Endpoint {
        return goa.Endpoint(func(ctx context.Context, request interface{}) (response interface{}, err error) {
            response, err = e(ctx, request)
            if err != nil {
                log.Printf("[ERROR] %v.%v: %s", ctx.Value(goa.ServiceKey), ctx.Value(goa.MethodKey), err.Error())
            }
        })
    }
}
```
The middleware can be mounted using the `Use` function that's generated on the `Endpoints` struct, taking the `calc` example:
```go
// ...
calcEndpoints = calc.NewEndpoints(calcSvc)
calcEndpoints.Use(ErrorMiddleware(logger))
// ...
```

**Comment by dohnto** [comment]
@raphael Thank you, did't know the `.Use`.

I will just paste working solution without some errors in your code for community
```go

func ErrorMiddleware(log *log.Logger) func(endpoint goa.Endpoint) goa.Endpoint {
	return func (e goa.Endpoint) goa.Endpoint {
		return goa.Endpoint(func(ctx context.Context, request interface{}) (interface{}, error) {
			response, err := e(ctx, request)
			if err != nil {
				log.Printf(" [ERROR] %v.%v: %s", ctx.Value(goa.ServiceKey), ctx.Value(goa.MethodKey), err.Error())
			}
			return response, err
		})
	}
}

// ...
calcEndpoints = calc.NewEndpoints(calcSvc)
calcEndpoints.Use(ErrorMiddleware(logger))
// ...
...
```

**Comment by ciolo** [comment]
I'm trying this solution but it doesn't print anything. Always like this:
`[subscriptionrequest] 15:23:12 id=g2jdMk78 req=POST /storage/subscription-requests from=::1
[subscriptionrequest] 15:23:12 id=g2jdMk78 status=400 bytes=243 time=824.771µs`
Where am I doing wrong?
