### ISSUE TITLE
v3: Unable to specify file upload mechanism

### ISSUE THREAD

**Issue by delkopiso** [goadesign/goa#2177]
I'm trying to test document uploads to my service via swagger, but there doesn't seem . to be a clear way of doing that via the DSL. I already looked at
https://github.com/goadesign/goa/issues/1665, but that issue was closed without a resolution.  

## DSL:
```go
	Method("add", func() {
		Payload(func() {
			Attribute("file", Bytes)
		})

		HTTP(func() {
			POST("/")
			MultipartRequest()
			Response(StatusCreated)
		})
	})
```

### Expected swagger YAML:
```yaml
    post:
      tags:
      - storage
      summary: add storage
      operationId: storage#add
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: Created
      schemes:
      - http
```
based on https://swagger.io/docs/specification/describing-request-body/

### Actual swagger YAML:
```yaml
    post:
      tags:
      - storage
      summary: add storage
      operationId: storage#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/StorageAddRequestBody'
      responses:
        "201":
          description: Created response.
      schemes:
      - http
```

I'm forced to include the payload field because removing it throws 
```
service "storage" HTTP endpoint "add": MultipartRequest is set but Payload is not defined
```

What should my method declaration have in it, so that the generated swagger file is correct?

**Comment by raphael** [comment]
Thank you for the report! Goa generates OpenAPI spec v2 documents when `requestBody` is a v3 element. Adding OpenAPI v3 support to Goa would be an awesome contribution.
