### ISSUE TITLE
v3: Would be nice if gen didn't delete non .go files

### ISSUE THREAD

**Issue by cquinn** [goadesign/goa#2180]
I like to put a README in the gen dir for project documentation and to keep the gen dir around in git. But currently `goa gen` deletes all files in gen, including my README. Could it be changed to only delete *.go files, and least at the gen/ top-level?

**Comment by raphael** [comment]
Yes that should be fine: the behavior would become "delete all folders and all Go files in gen". I'd happily merge a PR that introduced that change.
