### ISSUE TITLE
V3: The version of goa specified in go.mod is ignored and rewritten

### ISSUE THREAD

**Issue by ikawaha** [goadesign/goa#2181]
According to [The go blog: Using Go modules](https://blog.golang.org/using-go-modules), `go get` changes the required version of a dependency (or adds a new dependency).

Since `goa gen` (or `goa example`) executes `go get` at runtime, 
even if the goa version is specified in the go.mod file, it is ignored and rewritten.

Isn't this behavior causing confusion? There is also a problem that the latest 
goa specified by the latest commit number can not be used.

### Example:

**before**
go.mod
```
module github.com/ikawaha/calc

go 1.12

require (
...snip...
        goa.design/goa/v3 v3.0.3-0.20190704022140-85024ebc66dc  // latest version
)
```

**after goa gen/example**

```shellsession
$ goa gen calc/design
```

```
module github.com/ikawaha/calc

go 1.12

require (
...snip...
        goa.design/goa/v3 v3.0.2
)
```

**Comment by raphael** [comment]
Thank you for the fix!
