### ISSUE TITLE
Cross compilation on Linux to Windows fails with "fork/exec goa751784457/goa: exec format error"

### ISSUE THREAD

**Issue by NotoriousPyro** [goadesign/goa#2189]
See: https://travis-ci.com/flexera/beacon-monitoring/jobs/214382422

Trying to cross-compile on Linux for Windows fails with:
fork/exec goa751784457/goa: exec format error

Code: https://github.com/flexera/beacon-monitoring/commit/822e4c230750d63035edb638239ec02b833d7260

**Comment by raphael** [comment]
As you know this is a public open source repository, people reading this won't have access to the private link you posted (I don't have access either). Would you mind posting a different issue with proper repro steps? thank you!
