### ISSUE TITLE
Modify Goify to support all the things Gorma does

### ISSUE THREAD

**Issue by bketelsen** [goadesign/goa#220]
so that it will be the OneTrueSource of names in both directions.

**Comment by bketelsen** [comment]
CamelCase to camel_case
camel_case to CamelCase
Title to title
title to Title
BlueID to blue_id
blue_id to BlueID

**Comment by raphael** [comment]
Like we discussed I'm not sure this is the right approach. You can't have a deterministic algorithm that can produce these two way transforms in a deterministic way for all possible strings. `Goify` is about producing a valid `Go` identifier from a random string.
