### ISSUE TITLE
x-www-form-urlencoded body unsupported?

### ISSUE THREAD

**Issue by tomjohnburton** [goadesign/goa#2208]
How can I configure the API to accept x-www-form-urlencoded from the DSL?

**Comment by tomjohnburton** [comment]
Decided to requisition and alter the existing decoder and modify it specifically for x-www-form-urlencoded body.

```
func RequestDecoder(r *http.Request) goahttp.Decoder {
	contentType := r.Header.Get("Content-Type")
	if contentType == "" {
		// default to JSON
		contentType = "application/json"
	} else {
		// sanitize
		if mediaType, _, err := mime.ParseMediaType(contentType); err == nil {
			contentType = mediaType
		}
	}
	switch contentType {
	case "application/json":
		return json.NewDecoder(r.Body)
	case "application/x-www-form-urlencoded":
		return form.NewDecoder(r.Body)
	default:
		return json.NewDecoder(r.Body)
	}
}
```

**Comment by raphael** [comment]
Perfect, this is the intended approach.

**Comment by wasimsse** [comment]
From where I can get the documentation of the goa design to understand different features/functions used. For example, What is DSL?

**Comment by evnsio** [comment]
@tomjohnburton stumbled across this whilst facing a similar issue. Do you mind sharing how you configured your DSL design to get this working? Thanks!

**Comment by raphael** [comment]
@evnsio encoders and decoders are configured at runtime, see https://goa.design/implement/encoding/ for additional details. The TL;DR is that your code provides the encoder and decoder functions when calling the generated function that creates the HTTP server. The default used by the generated example makes use of [RequestDecoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L62) and [ResponseEncoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L99) server side (and the mirror functions client side). You can provide your own functions that make use of any encoding/decoding scheme (for example for form encoding the implementation could use https://github.com/ajg/form). The [encodings example](https://github.com/goadesign/examples/tree/master/encodings) shows how to use custom encoders/decoders ([encoding.go](https://github.com/goadesign/examples/blob/master/encodings/cbor/encoding.go) implements the custom encoders/decoders and are used in the server and client main tools (https://github.com/goadesign/examples/blob/master/encodings/cbor/cmd/concat/http.go#L36-L39 and https://github.com/goadesign/examples/blob/master/encodings/cbor/cmd/concat-cli/http.go#L28-L29)
