### ISSUE TITLE
question - ability to use web sockets ?

### ISSUE THREAD

**Issue by joeblew99** [goadesign/goa#222]
I am looking at using Goa, or maybe GRPC or Flatbuffers etc.

I know that i need to be able to PISH content to Users, over web sockets.
I did a search but found nothing in the code. Can someone pleae comment to let me know the situation.
If this is just not going to support this use case that fines but i just need to know.

thanks in advance.

**Comment by derekperkins** [comment]
What is `PISH`?

**Comment by derekperkins** [comment]
The short answer is that Websockets are not natively supported yet, but they are on the roadmap.

**Comment by ernesto-jimenez** [comment]
@derekperkins I'm guessing he meant PUSH? :P

**Comment by derekperkins** [comment]
@ernesto-jimenez haha, that was a lot more obvious than I made it. I Googled `PISH` wondering if it was some kind of encoding or special connection. :)
