### ISSUE TITLE
v2/v3: Proposal to support custom zero values (a.k.a Zero DSL) for gRPC

### ISSUE THREAD

**Issue by nitinmohan87** [goadesign/goa#2221]
~~NOTE: This will be a **breaking** change.~~

Due to [protocol buffer's handling of missing values](https://developers.google.com/protocol-buffers/docs/proto3#default) it is impossible to figure out if the default value is set by the application or protobuf. As a consequence, there is a limitation for required attributes to never fail validation because such attributes are always initialized to a default value by protobuf. To workaround this situation and provide parity with how Goa treats required attributes in HTTP, we propose a `Zero` DSL which can be set to a custom value on an `Attribute` in the design to denote its zero-value.

## The `Zero` DSL
```
Service("my_service", func() {
    Method("my_method", func() {
        Payload(func() {
            Field(1, "my_string", String, "My zero is different", func() {
                Zero("this_is_my_zero_value")
            })
            Field(2, "no_zero_string", String, "My zero is not different")
            Required("my_string", "no_zero_string")
        })

        Result(func() {
            Field(1, "my_integer", Int, "My zero is also different", func() {
                Zero(-199999999)
                Minimum(0)
            })
            Field(2, "no_zero_integer", Int, "My zero is not different")
        })

        GRPC(func() {})
    })
})
```
### Validations
* If `my_string == ""` in the message then goa-generated validation will fail (since `my_string` is required). If `my_string ==  "this_is_my_zero_value"`, validation succeeds.
* If `no_zero_string == ""` in the message then goa-generated validation WILL NOT fail (there is no way to know who set the empty string).
### Transforming Protobuf Request Message to Goa Payload type
* `my_string` in goa payload will be automatically set to empty string.
* `no_zero_string` in goa payload will have the same value as the protobuf message.

### Validations
* If `my_integer == -199999999`, goa-generated validation won't fail even though `Minimum` is set to `0` on the attribute.
### Transforming Protobuf Response Message to Goa Result
* If `my_integer == 0` in the message then goa result will have `my_integer` set to `nil` because it is an optional field. If `my_integer == -199999999`, then goa result will have `my_integer` set to a pointer to `0`.
* If `no_zero_integer == 0`  in the message then goa result will have `no_zero_integer` set to a pointer to `0` (no way to know who set the zero value) because it is an optional field.

The `Zero` DSL will have no effect for HTTP endpoints.

**Comment by smessier** [comment]
What if I want my zero value to be the actual zero value (e.g. Zero(0)), will that give me the behavior that the value is considered to be missing if it has the zero value? Currently it is not considered missing when Required and it has the default zero value.

**Comment by nitinmohan87** [comment]
That is correct. If you set zero-value for a required string to be an empty string, then validations will fail if protobuf message contains an empty string.

**Comment by laches1sm** [comment]
Currently working on this issue :) hopefully will be done sometime in the near future!

**Comment by laches1sm** [comment]
Right, I've got some time back and intending to work on this soon! :)
