### ISSUE TITLE
bad access: nil dereference when using goahttp.Doer

### ISSUE THREAD

**Issue by tomjohnburton** [goadesign/goa#2228]
I have the following set up:
- 2 microservices A and B
- Both are using GoaV3
- We store the design files of A and B in `modules.go`. This allows me to use the `gen` clients from B in A. (Can you confirm this is the intended idea?)
- While making a request on A, I need to make a http call to B.
- During this part, the `goahttp.Doer` throws a nil dereference.

When using my own configuration of a `Doer` the request works no problem.

My response output on my intellij debugger is as follows

![image](https://user-images.githubusercontent.com/39559415/62309024-e7dabc00-b486-11e9-8370-2bacf65ff4b7.png)

Part of me is wondering whether I am barking up the wrong tree trying to integrate clients like so. Would be very grateful for some clarification. Hope my explanation made sense.

**Comment by tomjohnburton** [comment]
UPDATE
This is how I initialise the client for service B in my `cmd/server/main.go`

```
var doer goahttp.Doer
	customerClient := customers.NewClient("http", "0.0.0.0:8500", doer, goahttp.RequestEncoder, goahttp.ResponseDecoder, false)
```

I also just ran the debugger and go the following output:
![image](https://user-images.githubusercontent.com/39559415/62309542-fc6b8400-b487-11e9-8e08-cb4bf8002292.png)

As you can see the `Doer`'s are returning nil which might explain the error I am getting. Any ideas?

**Comment by tomjohnburton** [comment]
UPDATE: Turns out I needed to actually assign a value to the `Doer`, i.e.:

```
	var doer goahttp.Doer
	doer = &http.Client{Timeout: time.Duration(10) * time.Second} // forgot this
	customerClient := customers.NewClient("http", "0.0.0.0:8500", doer, goahttp.RequestEncoder, goahttp.ResponseDecoder, false)
```
#softwaredevelopment

**Comment by raphael** [comment]
Just a note that the http package `DefaultClient` can also be used:
```go
customerClient := customers.NewClient("http", "0.0.0.0:8500", http.DefaultClient, goahttp.RequestEncoder, goahttp.ResponseDecoder, false)
```
