### ISSUE TITLE
Async ?

### ISSUE THREAD

**Issue by joeblew99** [goadesign/goa#223]
Does this support Http Calls that are Async in the DSL and code gen ?

**Comment by derekperkins** [comment]
Are you talking about the Go side or the Javascript client?

**Comment by raphael** [comment]
If the question is whether a specific API endpoint can be implemented asynchronously (e.g. handled by another goroutine) then the answer is yes: controller actions send the response by calling a method on the context. That call can happen at any time - that is the controller action method can return and the call to `ctx.Respond` can be made later.

**Comment by joeblew99** [comment]
That's exactly it - thanks for clarification.

**Comment by delfick** [comment]
Hey @raphael, has goa changed since that comment?

if I do something like

	func (c *V1Controller) Thing(ctx *app.ThingV1Context) error {
		go func() {
			time.Sleep(2 * time.Second)
			ctx.OK([]byte{})
		}()
		return nil
	}

Then it seems to respond to the request straight away and then after a couple seconds complains that it's trying to write multiple times....

**Comment by raphael** [comment]
Yeah I realized that it didn't make sense to do it this way because at the end of the day goroutines are very cheap. The added complexity is just not worth it.

**Comment by delfick** [comment]
I'm not sure I understand. Are you saying every request already spawns a
goroutine? So I should use a waitlock in my action?

My application will need to send requests and wait for replies on what is
essentially a message bus.

Thanks :)

**Comment by raphael** [comment]
Yes exactly the stdlib http server already spawns a goroutine to handle every request. So a controller action that looks something like this:
```
...
var wg sync.WaitGroup
wg.Add(1)
go func() {
     // Do something asynchronous
     wg.Done()
}()
wg.Wait()
...
```
would be just fine. The Go runtime takes care of suspending the inactive goroutine so that the cost is really minimal.

**Comment by delfick** [comment]
Ok then. Thanks :)
