### ISSUE TITLE
goa gen vs goagen

### ISSUE THREAD

**Issue by webern** [goadesign/goa#2236]
Here we have `goa gen calc/design`: https://goa.design/learn/getting-started/

Here we have `goagen`: https://goa.design/implement/goagen/

What is the difference between these two binaries? `goagen` appears to be more feature-rich than the `goa` command. Is this interpretation correct?

**Comment by raphael** [comment]
`goagen` is the tool used by Goa v1 while `goa` is the tool used by v2 and v3. Might make a good entry for the [FAQ](https://goa.design/learn/faq/)...

**Comment by webern** [comment]
So what I don't understand is that it appears the v2 and v3 have less functionality than v1. It appears that goagen supported a JavaScript client. It also had options for 3rd party generators and scaffolding `--regen`. These seem like really nice features. Are the gone in v2/v3?

**Comment by webern** [comment]
I'm not sure how I got to the confusing link https://goa.design/implement/goagen/ which matches  https://goa.design/v1/implement/goagen/

I'm seeing that v1's Implement documentation, which somehow read from a non-v1 url looks like this:

![image](https://user-images.githubusercontent.com/6260372/62843420-8973c180-bc6e-11e9-8ea2-c781e95e1e56.png)

While the v2/v3 documentation looks like this:

![image](https://user-images.githubusercontent.com/6260372/62843434-9bedfb00-bc6e-11e9-8c0b-581c97bb38fb.png)

**Comment by raphael** [comment]
One design goal of v2/v3 was to be more composable, both the library packages and the generated code. As a result v2 and v3 have a more robust plugin system that replaces some of that functionality. See https://github.com/goadesign/plugins. However you are correct that the JavaScript client generation has no equivalent in v2/v3 yet. This would make a great plugin though.
