### ISSUE TITLE
Unable to install goagen

### ISSUE THREAD

**Issue by webern** [goadesign/goa#2237]
The instructions here https://goa.design/implement/goagen/ for installing `goagen` did not work for me.

First of all, it's unclear whether or not the instructions assume I'm using `go modules` (I am). However, it looks like the instruction is for a 'global' (non modules) install. So I tried this.

```
$ echo $GOPATH
/Users/brigmatt/repos/go
$ cd /Users/brigmatt/repos # this is outside of any go.mod project
$ GO111MODULE=off go install github.com/goadesign/goa/goagen
can't load package: package github.com/goadesign/goa/goagen: cannot find package "github.com/goadesign/goa/goagen" in any of:
	/usr/local/go/src/github.com/goadesign/goa/goagen (from $GOROOT)
	/Users/brigmatt/repos/go/src/github.com/goadesign/goa/goagen (from $GOPATH)
```

That didn't work, so I tried (still outside of any modules project):

```
$ GO111MODULE=off go get github.com/goadesign/goa/goagen
package github.com/goadesign/goa/goagen: cannot find package "github.com/goadesign/goa/goagen" in any of:
	/usr/local/go/src/github.com/goadesign/goa/goagen (from $GOROOT)
	/Users/brigmatt/repos/go/src/github.com/goadesign/goa/goagen (from $GOPATH)
```

Well this url `github.com/goadesign/goa/goagen` gives a 404, so I guess that's the issue.

Is the documentation out of date?

See #2236 regarding my confusion about `goa gen` and `goagen`. I think both issues are about documentation, because I'm pretty sure I read all of it that is hosted on https://goa.design/

**Comment by webern** [comment]
I've made some progress understanding this. the directory goagen exists on the `master` branch, but not on the `v3` branch (and `v3` is the default branch).

So I can do this:
```
git clone https://github.com/goadesign/goa.git
cd goa
git checkout master
git pull origin master
cd goagen
go build
sudo cp goagen /usr/local/bin
```

So now I have goagen. Maybe `goagen` is intentionally removed from the `v3` branch because it is incompatible with `v3`? I guess I'll find out.

**Comment by webern** [comment]
Yeah, so goagen doesn't work with v3 I guess:

```
$ ./gen.sh #goagen bootstrap path/to/design -o "$OUTPUT_DIR"
invalid plugin package import path: go/build: importGo github.com/goadesign/goa/goagen/gen_app: exit status 1
go: finding github.com/goadesign/goa/goagen/gen_app latest
go: finding github.com/goadesign/goa/goagen latest
can't load package: package github.com/goadesign/goa/goagen/gen_app: unknown import path "github.com/goadesign/goa/goagen/gen_app": cannot find module providing package github.com/goadesign/goa/goagen/gen_app
```

**Comment by raphael** [comment]
Yeah `goagen` is the tool used by Goa v1 while `goa` is the tool used by `v2` and `v3`. I would be interested to know what links to the page located at https://goa.design/implement/goagen/ - the intent is that only the `v1` docs should link to it.

**Comment by sixonethreehosting** [comment]
This is what worked for me:
git clone the repo
cd into goa/cmd/goa
go build

that generates a goa binary

cp or mv goa to /somewhere/on/your/path
