### ISSUE TITLE
v3: gRPC generates incorrect field names

### ISSUE THREAD

**Issue by cubic3d** [goadesign/goa#2238]
Using v3.0.3 (goa and cli).
The following design generates wrong field names for names containing multiple upper case characters in sequence:

```
package design

import . "goa.design/goa/v3/dsl"

var _ = API("api", func() {
	Server("apisvr", func() {
		Host("default", func() {
			URI("http://0.0.0.0:8000")
			URI("grpc://0.0.0.0:8080")
		})
	})
})

var _ = Service("svc", func() {
	Method("test", func() {
		Result(Test)

		HTTP(func() {
			GET("/")
			Response(StatusOK)
		})

		GRPC(func() {
			Response(CodeOK)
		})
	})
})

var Test = ResultType("application/vnd.test", func() {
	Attributes(func() {
		Field(1, "customerID", UInt)
	})
})
```

Gives `Customerid` instead of `CustomerID`
```
gen/grpc/svc/server/types.go:20:10: message.CustomerID undefined (type *svcpb.TestResponse has no field or method CustomerID, but does have Customerid)
```

Generated message in svc.proto:
```
message TestResponse {
	uint32 customerid = 1;
}
```

Generated Response by goa:
```
func NewTestResponse(result *svcviews.TestView) *svcpb.TestResponse {
	message := &svcpb.TestResponse{}
	if result.CustomerID != nil {
		message.CustomerID = uint32(*result.CustomerID)
	}
	return message
}
```

Resulting `svc.pb.go` snippet by protoc-gen-go:
```
type TestResponse struct {
	Customerid           uint32   `protobuf:"varint,1,opt,name=customerid,proto3" json:"customerid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

Same applies to names like `myIDTag` -> `MyidTag` (I know, that one is not Go conventional, but `myID` is)

**Comment by cubic3d** [comment]
That's a tricky one. I tried to replace the [`SnakeCase`](https://github.com/goadesign/goa/blob/14db099b7a749da32585f58d294750a029981442/codegen/funcs.go#L151) function with a simple
```
var matchFirstCap = regexp.MustCompile("(.)([A-Z])")
var matchAllCap = regexp.MustCompile("([a-zA-Z0-9])([A-Z])")

// SnakeCase produces the snake_case version of the given CamelCase string.
func SnakeCase(name string) string {
	for u, l := range toLower {
		name = strings.Replace(name, u, l, -1)
	}
	snake := matchFirstCap.ReplaceAllString(name, "${1}_${2}")
	snake = matchAllCap.ReplaceAllString(snake, "${1}_${2}")
	return strings.ToLower(snake)
}
```
This replacement does not handle runes (for test purposes). It generates a pretty ugly `customer_i_d` field for the .proto file and works at least with the simple design from above.
```
message TestResponse {
	uint32 customer_i_d = 1;
}
```

As far as I can see, there is no other possibility to achieve a deterministic conversion between CamelCase to snake_case and back to CamelCase like goa does: Generate .proto using CamelCase->snake_case and running protoc-gen-go to generate the Client using CamelCase again.

Not sure how to properly fix that.

**Comment by raphael** [comment]
Thank you for the repro and all the details, this is now fixed.
