### ISSUE TITLE
v3: Authentication on static files service

### ISSUE THREAD

**Issue by cubic3d** [goadesign/goa#2240]
Defining a service for static files like
```
var _ = Service("web", func() {
	Security(ResourceAuth, func() {
		Scope("docs:view")
	})

	Files("/swagger.json", "swagger.json", func() {
		Description("Swagger file")
	})
})
```
does not respect the `Security` DSL and there is no way to define a `Payload` for the credentials, since it's possible on `Method` only. This was possible in v1. Should a middleware be used or is it unintended?

**Comment by raphael** [comment]
Good catch. It's an interesting problem as the current implementation relies on the HTTP [file server](https://golang.org/pkg/net/http/#FileServer) and therefore completely bypasses the endpoint layer which is where security is enforced (so the same security logic can be applied to requests coming from different transports). Maybe the code generator should generate a corresponding endpoint method in this case.

**Comment by cubic3d** [comment]
That would also cleanly solve the `Payload` problematic. One thing to consider: It would also be great to be able to set a custom `http.FileSystem` for the file server - one thing that is widely used is to embed static files into the binary by using a virtual file system like [vfsgen](https://github.com/shurcooL/vfsgen). Maybe the file endpoints could return a file system as result?

**Comment by raphael** [comment]
Interesting idea, would you care putting together an example that would imitate what should be generated to illustrate the above?
