### ISSUE TITLE
Metric middleware

### ISSUE THREAD

**Issue by matteosuppo** [goadesign/goa#2255]
I have a service method which accepts a payload

When I make a request, here's what happens:

- all transport middlewares are inititated
- the context is populated with service and method
- the payload is validated
- if the payload is validated all the endpoint middlewares are initiated
- if the payload is validated the endpoint middleware finish
- the transport middlewares finish

where should I put a middleware that tracks stats about requests?
If I put it in the transport stack, I don't have access to the service and method invoked, and that makes it kinda useless
If I put it in the endpoint stack, it doesn't execute when the request is not validated, and that makes it kinda useless because I need stats on failed requests

**Comment by raphael** [comment]
I don't think there's a way to do that today. One possibility here would be to take the code that initializes the context out of the HTTP handler function and to make it a separate public function that the HTTP handler function would call. Your middleware could also call it and get access to the method and service name from the context. Something like:
```go
func NewAddHandler(
	// ...
) http.Handler {
	var (
		// ...
	)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := NewAddContext(r)
}
// ...

// NewAddContext initializes a new context for HTTP requests made to the "add" method of the "calc" service.
func NewAddContext(r *http.Request) context.Context {
	ctx := context.WithValue(r.Context(), goahttp.AcceptTypeKey, r.Header.Get("Accept"))
	ctx = context.WithValue(ctx, goa.MethodKey, "add")
	ctx = context.WithValue(ctx, goa.ServiceKey, "calc")
	return ctx
}
```
I'd happily merge a PR that implemented the change above.

**Comment by raphael** [comment]
Interesting problem :) One way to address these requirements would be to wrap both the response and error encoders to track these metrics as they have access to the context which would be initialized at that point. The request decoder might have been a better place but it doesn't have access to the context in the current design.

**Comment by matteosuppo** [comment]
I tried with this:

```
package metrics

import (
	"context"
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/sirupsen/logrus"
	goahttp "goa.design/goa/v3/http"
	httpmdlwr "goa.design/goa/v3/http/middleware"
	goa "goa.design/goa/v3/pkg"
)

type contextKey string

const MetricsMetaKey = contextKey("metrics-meta")

// HTTPMiddleware measures the duration of a request. It depends on WrapResponseEncoder to populate data
func HTTPMiddleware() func(http.Handler) http.Handler {
	summary := prometheus.NewSummaryVec(
		prometheus.SummaryOpts{
			Name:       "http_request_duration_nanoseconds",
			Help:       "The requests latencies in nanoseconds of api calls",
			Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
		},
		[]string{"method", "service", "code"},
	)
	prometheus.MustRegister(summary)

	return func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()

			startedAt := time.Now()
			rw := httpmdlwr.CaptureResponse(w)

			data := map[string]string{}
			ctx = context.WithValue(ctx, MetricsMetaKey, data)

			h.ServeHTTP(rw, r.WithContext(ctx))

			summary.WithLabelValues(data["method"], data["service"], strconv.Itoa(rw.StatusCode)).
				Observe(float64(startedAt.Nanosecond())) // request duration nanoseconds
		})
	}
}

// WrapResponseEncoder adds the method and service metadata to the Metrics metadata so that they are available to the middleware
func WrapResponseEncoder(encoder func(context.Context, http.ResponseWriter) goahttp.Encoder) func(context.Context, http.ResponseWriter) goahttp.Encoder {
	return func(ctx context.Context, w http.ResponseWriter) goahttp.Encoder {
		data, ok := ctx.Value(MetricsMetaKey).(map[string]string)
		if !ok {
			panic("data not found in context. Have you setup the HTTPMiddleware middleware?")
		}

		method, ok := ctx.Value(goa.MethodKey).(string)
		if ok {
			data["method"] = method
		}
		service, ok := ctx.Value(goa.ServiceKey).(string)
		if ok {
			data["service"] = service
		}
		return encoder(ctx, w)
	}
}

func Serve(l *logrus.Entry) {
	http.Handle("/metrics", promhttp.Handler())
	l.Infof("Listening prometheus metrics on %s/metrics", ":8888")
	l.Fatal(http.ListenAndServe(":8888", nil))
}

```

which is then used as this

```
dec := goahttp.RequestDecoder
enc := metrics.WrapResponseEncoder(goahttp.ResponseEncoder)

...

handler = metrics.HTTPMiddleware()(handler)
```

Seems to be working. A little hacky maybe

**Comment by raphael** [comment]
Yeah makes sense, maybe having two keys to store the service and action names might make it slightly more efficient (no need to allocate a map on each request).

**Comment by matteosuppo** [comment]
The map is needed to let the outermost middleware get those info:

httpmiddleware doesn't have service/method, defines the map which is a pointer)
.. handler defines service/method in the context
.....wrapresponseencoder has access to both map and service/method, fills map
httpmiddleware still doesn't have service/method, but it has a filled map

It's a context trick that I don't see anywhere explained so I guess it's probably a disaster waiting to happen but it's the only way I can think of to send values downstream a middleware chain.

**Comment by raphael** [comment]
Shouldn't it be possible to simply use string pointers that are initialized in the HTTP middleware and whose pointed values are set in the response encoder?

**Comment by matteosuppo** [comment]
Yeah probably yes

**Comment by matteosuppo** [comment]
Anyway I think I can close this issue now

**Comment by fazzywuzzy** [comment]
> The map is needed to let the outermost middleware get those info:
> 
> httpmiddleware doesn't have service/method, defines the map which is a pointer) .. handler defines service/method in the context .....wrapresponseencoder has access to both map and service/method, fills map httpmiddleware still doesn't have service/method, but it has a filled map
> 
> It's a context trick that I don't see anywhere explained so I guess it's probably a disaster waiting to happen but it's the only way I can think of to send values downstream a middleware chain.

hey, by doing this you're able to get the value of the metrics metadata in HTTP middleware, or where you initialize the MetricsMetaKey. But what if you want that value in more than one middleware? Will this work as well, and how can i obtain the same?
