### ISSUE TITLE
Goav3 generated E2E Tests

### ISSUE THREAD

**Issue by michaelkleinhenz** [goadesign/goa#2256]
It looks like the `goa gen` does not generate test stubs. What is the best way of doing testing of the service endpoints? Imo this is currently missing from the documentation.

**Comment by raphael** [comment]
That's correct Goa v3 does not have a test stub generator at this point. This would make a great plugin. Did you find documentation indicating that Goa v3 could generate tests?

**Comment by michaelkleinhenz** [comment]
No, and that was irritating me as GoaV1 had an extensive test stub feature and integration that was really nice. The current doc does not mention tests at all, which confused some people over here.

**Comment by raphael** [comment]
I'd be happy to merge a PR that added a test stub generator plugin to the [plugins repo](https://github.com/goadesign/plugins).
