### ISSUE TITLE
mux uses default encoder

### ISSUE THREAD

**Issue by matteosuppo** [goadesign/goa#2259]
https://github.com/goadesign/goa/blob/v3/http/mux.go#L68

here it's using the default goa encoder, while someone may want to use their custom one. Not a big deal, they could just create a new mux, but maybe you didn't notice

**Comment by raphael** [comment]
Thanks for raising the issue. This is the default "invalid route" handler which always returns just a string so the encoding is probably less important. As you say it can be overridden if not appropriate.
