### ISSUE TITLE
Developers consuming the generated client should not compose paths by hand

### ISSUE THREAD

**Issue by ernesto-jimenez** [goadesign/goa#226]
Taking the example from the README, the generated function is this one:
```
func (c *Client) AddOperands(path string) (*http.Response, error)
```

This will require developers to build the path by hand, which is more error-prone.

Two options to address this:

### Helper to build the path

Have `app` define a function to build the path. e.g:
```func AddOperandsPath(left, right int) (string, error)```

Pros:

 - `AddOperandsPath` can build a path with type safety and client-side validation about params constraints
 - It'll tolerate certain changes in the path without having to update the manually-composed 
 - The same function can be used when building a REST API to link to resources

### Struct to hold the params

Change the generated context in `app` to:
```
type AddOperandsContext struct {
    *goa.Context
    AddOperandsParams
}

type AddOperandsParams struct {
    Left  int
    Right int
}
```

And the client function to:
```
func (c *Client) AddOperands(params AddOperandsParams) (*http.Response, error)
```

Pros:

 - Again: Type safety and more change-resistant.
 - `AddOperandsParams` can have a `Validate() error` method to check whether the params are valid before issuing the request. Developers can validate the input without issuing a request if the params are OK

**Comment by raphael** [comment]
I'm thinking helpers to build the path is probably what makes the most sense. As you note they may be helpful in isolation. Also there's a case to be made about paths being actually more helpful that individual parameters in some cases. API documentations tend to be path centric (look at Swagger UI for example) and paths may make more intuitive sense. Forcing the use or parameters may actually be counter-productive in some cases as it may mean that the end user has to reverse engineer the documented path to figure out which parameter corresponds to which position.

**Comment by raphael** [comment]
The latest goagen produces this function in the lclient:
```go
// AddOperandsPath computes a request path to the add action of operands.
func AddOperandsPath(left int, right int) string {
        return fmt.Sprintf("/add/%v/%v", left, right)
}
```

**Comment by ernesto-jimenez** [comment]
@raphael cool, closing the issue :)
