### ISSUE TITLE
v3 question: Reuse ResultType in multiple services

### ISSUE THREAD

**Issue by cubic3d** [goadesign/goa#2260]
I have multiple services and `ResultType` defined in the design. `ResultType` is defined in the same hierarchy level as a `Service`, but binding a `ResultType` by `Result(MyResult)` to a service, generates a go type inside of the service package which becomes not interchangeable between services. I kinda expected the `ResultType` being independent of a `Service`.

For example having a `CollectionOf(Point)` defined as a `Result` in `Service` `a` and `b` will generate the types `a.PointCollection` and `b.PointCollection`. This makes it hard to reuse business code, since go lacks generic typing e.g. on fetching data from databases and scan the rows directly into the `Point` object.

Since ResultTypes are defined only on top level design, namespaces can not collide. Was there any reason to generate the `ResultType`s into the service package?

**Comment by raphael** [comment]
The idea here is to enable the "clean monolith" pattern where services that currently live in the same process could easily be split between multiple remote processes in the future as the need for scaling one versus the other changes for example. The service is the atomic unit of execution and having common external packages that they depend on would create coupling. That being said and the theory left aside for a minute you should be able to take advantage of ConvertTo (https://godoc.org/goa.design/goa/dsl#ConvertTo) and CreateFrom to map all the result types to a single type that you define.

**Comment by cubic3d** [comment]
Thank for the info, I missed `ConvertTo` and `CreateFrom`!
