### ISSUE TITLE
v1: Refresh JWT validation keys

### ISSUE THREAD

**Issue by jarlefosen** [goadesign/goa#2264]
I'm using Firebase authentication in my app using the JWT security middleware. However I notice that the keys I'm using get expired after a while which causes requests to become unauthorized.

I wonder if there is a possibility of refreshing the keys specified in the JWT middleware from time to time without restarting my app instance? Or are there any preferred methods solving this problem?

**Comment by raphael** [comment]
One strategy I have seen used is to refresh the token afte half its lifetime has elapsed. A "token source" object encapsulates that logic and uses a refresher Goroutine that simply waits until the half time before making a request to retrieve a new token. Clients use the token provided by the "token source" which owns the token and takes care of refreshing it. The details here are very much implementation specific and do not have much to do with Goa per se.

**Comment by jarlefosen** [comment]
I've looked a bit more into this, and I might be a bit confused here.

**Client side:** There is currently no issue with retrieving and updating JWT on the client side, this is done automatically between the device and Firebase. This has nothing to do with my server.

**Server side:** However when the client is sending requests to the server, after a few weeks, the requests are invalid due to the keys supplied to the `middleware/security/jwt` gets outdated.

I'm doing firebase JWT validation on my server to verify that the users are in fact authenticated with Firebase and that they have the required scopes.

```go
func New(validationKeys interface{}, validationFunc goa.Middleware, scheme *goa.JWTSecurity) goa.Middleware
```

I think my issue is that I cannot update the `validationKeys` used by the JWT security middleware, and therefore decoding the JWTs result in the signatures not matching after the validationKeys are expired. Typically after some weeks.
A solution would be to recreate the JWT security middleware periodically with new keys, but I'm not quite sure how I would replace the middleware. If that is the way to go.

**Comment by raphael** [comment]
OK so applying the high level idea of using a dynamic token source what you could do is define your own middleware constructor function that accepts a function that returns the validation keys instead of taking a static set, for example:
```go
func New(tokenSource func() interface{}, validationFunc goa.Middleware, scheme *goa.JWTSecurity) goa.Middleware
```
This function would end up using the same logic as the one in the existing middleware but instead of using a static set of keys it would call the given function to retrieve the keys. That function would get fresh keys that are periodically refreshed.
