### ISSUE TITLE
FastHTTP Integration

### ISSUE THREAD

**Issue by sarmadali20** [goadesign/goa#2269]
FastHTTP is 10X faster then standard net/http package goa should allow for plug and play http packages.

Happy to open a PR!

**Comment by raphael** [comment]
Thank you for the offer! This would be a great [plugin](https://github.com/goadesign/plugins) for goa. There is some [information](https://goa.design/extend/plugins/) on the goa.design website on how plugins work. Happy to help with specific questions as well.
