### ISSUE TITLE
goagen cli is not working

### ISSUE THREAD

**Issue by ernesto-jimenez** [goadesign/goa#227]
```
% goagen bootstrap -d goa-adder/design
goagen: error: duplicate long flag --pkg, try --help
```

**Comment by zhumingjian1229** [comment]
boostrap registers all the sub-commands flags, but genapp and genmain both had "pkg" flag.

**Comment by derekperkins** [comment]
@raphael is in the middle of refactoring the cli to use https://github.com/spf13/cobra instead of https://github.com/alecthomas/kingpin. In the meantime, if you rollback kingpin to https://github.com/alecthomas/kingpin/commit/871a069a9e0d336e58dee8413d1178d1eec70174, it should work.

**Comment by raphael** [comment]
@zhumingjian1229 these are flags for different commands not global flags so it should work.

**Comment by raphael** [comment]
Ah I understand what's going on now: the `bootstrap` command is the one that registers the flag twice. Fix is in progress...

**Comment by raphael** [comment]
This is now fixed, thank you!
