### ISSUE TITLE
v3: Example of customising the response encoder for better validation messages

### ISSUE THREAD

**Issue by huysamen** [goadesign/goa#2276]
The current validation schema simply returns all errors marshalled into a single string separated by `;`.  Issue #1801 I think might have addressed this in `v2`, however the error handler passed in the generated `http.go` never gets called during validation errors.

**Comment by raphael** [comment]
The error handler given to the server constructor is here to handle encoding and decoding errors and in general should be rarely invoked if at all. The errors returned by the service methods and generated validation code are encoded using the same response encoder used to encode results (also passed to the server constructor). So you want to wrap the encoder given to encode responses into your own that handles validation errors differently.

**Comment by huysamen** [comment]
I see...  We can hook in there and try to deconstruct the validation errors again.  I was hoping there would be some place we can hook in before the generated validation code calls `goa.MergeErrors` for each failed validation (in the generated `types.go`).  The current one string with all error is a bit unfriendly for front-end clients to consume.  If there was some array of errors we can access in the error handler this would be great.  The default error handler could always at that point merge any given number of errors, rather than the validation code doing it up-front.

**Comment by raphael** [comment]
I see your point, a proper solution here would probably have to involve new DSL because we'd want the design to reflect the type being used to return validation error so that other generators like the OpenAPI spec generator are aware (I just checked and that generator doesn't seem to generate validation error responses at the moment - it should).
