### ISSUE TITLE
Meta("type:generate:force", "service1") won't generate type conversion to/from transport format

### ISSUE THREAD

**Issue by cssf00** [goadesign/goa#2282]
Hello, 
I have an external Goa type, which is not the payload of a method, but as bytes field in the payload, which I need to use for my gRPC service. Hoping that I could leverage Goa to generate json encoded object and the validation that Goa provides.

```go
// Summary description of the event
var Summary = Type("Summary", func() {
	Meta("type:generate:force", "abc_svc")
	Description("Summary description of the event")
	Field(1, "message", String, "Message of the event for translation matching and substitution", func() {
		Example("{0} Computers Ignored")
		Default("")
	})
	Field(2, "parameters",
		MapOf(Int32, String, func() {
			Key(func() { Minimum(0) })
		}), "Indexed parameters to construct the message, index start from zero")
})
```

use as:
```go
Field(10, "summary", Bytes, "A JSON blob for dynamic summary from different sources")
```

But when I run goa gen on abc_svc, only the transport agnostic  go struct is generated, but the followings are missing:
1.) json/protobuf encoded go struct
2.) the conversion methods that convert between both types
3.) the validation methods are not generated.

**Comment by raphael** [comment]
Thank you this was by design - the intent was only to generate the struct - but I can see that it would be useful to generate these methods as well. I'll leave this opened as a feature request.
