### ISSUE TITLE
generated BuildRequest uses interface{}

### ISSUE THREAD

**Issue by matteosuppo** [goadesign/goa#2284]
If you look https://github.com/goadesign/examples/blob/master/basic/gen/http/calc/client/encode_decode.go#L24

it accepts a interface{} and then it converts the interface{} into the proper payload.

What's the reason why the generated code couldn't just accept the proper payload?

**Comment by raphael** [comment]
This is because the HTTP requests are built from the endpoint methods which use the generic signature: https://github.com/goadesign/examples/blob/master/basic/gen/http/calc/client/client.go#L60
