### ISSUE TITLE
ArrayOf(String) does not support Pattern() as documented

### ISSUE THREAD

**Issue by smessier** [goadesign/goa#2285]
I have a payload parameter of type ArrayOf(String) and I am trying to validate items in the array using a pattern:
`$GOPATH/src/foo/design/api.go`
```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = Service("Foo", func() {
	Method("something", func() {
		Payload(func() {
			Field(2, "bar", ArrayOf(String), func() {
				Pattern("^[a-z]+$")
			})
		})
		Result(String)

		GRPC(func() {
			Response(CodeOK)
		})
	})
})
```
The ArrayOf type is documented as supporting Pattern(): https://github.com/goadesign/goa/blob/v3/dsl/user_type.go#L124-L126
but I get an error when generating code:
```
$ goa gen foo/design
exit status 1
[../../pkg/mod/goa.design/goa/v3@v3.0.6/dsl/validation.go:178] invalid pattern validation definition: attribute must be a string (but type is array) in attribute
```
Is the documentation wrong or is this a bug?

**Comment by raphael** [comment]
The anonymous function should be the second argument of the `ArrayOf` function:
```go
ArrayOf(String, func() { Pattern("^[a-z]+$") }))
```

**Comment by smessier** [comment]
Ah, missed that. Sorry.
