### ISSUE TITLE
ConvertTo generated methods produce wrong struct name when Type name is the same as external struct

### ISSUE THREAD

**Issue by lobocv** [goadesign/goa#2288]
Hi there,
When using ConvertTo DSL with an external struct that has the same name as the goa Type, the generated ConvertTo<STRUCT>  references the struct name with a 1 at the end.

Here is a small self-contained example:

```
package design

import (
	"github.com/lobocv/learncheck/internal/goamodels"
	. "goa.design/goa/v3/dsl"
)

var _ = Service("professional", func() {

	Method("register", func() {
		Description("Register a professional in the system")
		Payload(func() {
			Attribute("professional", Professional)
			Attribute("password")
			Required("professional", "password")
		})
		Result(Int64)
		HTTP(func() {
			POST("/professional")
			Response(StatusCreated)
		})
	})

	Method("get", func() {
		Description("Get a professional registered in the system.")
		Payload(func() {
			Attribute("id", Int64, "ID of the professional")
			Required("id")
		})
		Result(StoredProfessional)
		HTTP(func() {
			GET("/professional/{id}")
			Response(StatusOK)
		})
	})

})

var Professional = Type("user", func() {
	ConvertTo(goamodels.User{})
	Attribute("first_name", String)
	Required("first_name")
})


var StoredProfessional = ResultType("stored_user", func() {
	Attribute("id", Int64)
	Attribute("first_name", String)
	Required("first_name")
})
```

With external struct in goamodels package:
```
type User struct {
	ID           int64
	FirstName string
}
```

The generated ConvertToUser method is:

```
// ConvertToUser creates an instance of User initialized from t.
func (t *User) ConvertToUser() *goamodels.User {
	v := &goamodels.User1{
		FirstName: t.FirstName,
	}
	return v
}
```
Notice that inside the function it reference goamodels.User1 and not goamodels.User. Oddly enough, the return type is correct.

If I change the Type("user") to Type("SomethingElse") OR if I renamed goamodels.User, the generation works as expected:

```

// ConvertToUser creates an instance of User initialized from t.
func (t *SomethingElse) ConvertToUser() *goamodels.User {
	v := &goamodels.User{
		FirstName: t.FirstName,
	}
	return v
}

```

**Comment by raphael** [comment]
Thank you for the detailed report.

**Comment by tmcladam** [comment]
This fixes it but I don't like it, it really only avoids the problem in this case:
 
https://github.com/goadesign/goa/compare/v3...tmaflexera:external_type_scoping

The problem is using the NameScope of the generated code to output the type declared in another package. To fix it properly, I think NameScope should include a Package field to explicitly tie the scope to the package, or otherwise wrap the NameScope and Package together instead of passing them in separately as is done in many places.

Thoughts? @goadesign/hackers

**Comment by raphael** [comment]
@tmaflexera makes sense, I like the idea of putting the package as part of the scope - I believe this would help simplify other parts of the code and would potentially fix other hidden bugs. That is a bigger change but would result in more robust code. I think it also means that we need to look at all the call sites and make sure that they create/use a scope with the "right" package field which actually is a good thing to do.

**Comment by tmcladam** [comment]
Thanks @raphael I will head down that path then

**Comment by tchssk** [comment]
Hi.

Focusing on `ConvertTo`, `service.ConvertFile` seems better to give a new name scope to each context for external type.

https://github.com/tchssk/goa/commit/30cbc4840b82a2dbfa37bb98d065f76c761fcab6

The extenal types are existing and their names are unrelated to the service name scope, right?

**Comment by tmcladam** [comment]
I think you're right, these types are existing and we are not creating new names in that package, so it would seem safe to given them an empty scope. I need to create a few test cases around it to convince myself.

**Comment by raphael** [comment]
@tmaflexera are you able to confirm that the fix suggested by @tchssk works? Would you mind creating a PR if that's the case? thank you!
