### ISSUE TITLE
package goa.design/goa/v3/cmd/goa: cannot find package "goa.design/goa/v3/cmd/goa"

### ISSUE THREAD

**Issue by sredxny** [goadesign/goa#2289]
Hello, I am trying to install Goa v3 with no sucess until now, I am following the instructions placed in the readme.md file. If I execute:

`go get -u goa.design/goa/v3/cmd/goa`

Then I get:

```
package goa.design/goa/v3/cmd/goa: cannot find package "goa.design/goa/v3/cmd/goa" in any of:
	/usr/local/go/src/goa.design/goa/v3/cmd/goa (from $GOROOT)
	/home/myuser/go/src/goa.design/goa/v3/cmd/goa (from $GOPATH)
```

The paths are correctly set, but I still don't know what is happening. My current Go version is _go1.11.2 linux/amd64_

I need to install normally without go modules. Any suggestion? thanks you so much in advance

**Comment by raphael** [comment]
Goa v3 requires the use of Go modules, use Goa v2 if you cannot use Go modules (Goa v2 is functionally equivalent to v3 but does not support Go modules).
Install Goa v2 with:
```
go get -u goa.design/goa/...
```
