### ISSUE TITLE
Add health checks to DSL

### ISSUE THREAD

**Issue by derekperkins** [goadesign/goa#230]
As discussed on Slack ([beginning of conversation](https://gophers.slack.com/archives/goa/p1453998801002059)), we should add a place for health checks to the DSL.

It should probably accept a variadic number of functions, with some basic service checks like network connectivity or db availability provided by goa, gorma or other plugins.

From @raphael:
> just as a source of inspiration what we ended up standardizing on here is one non versioned health check that does a quick validation that all the ​*required*​ / critical components are ok (i.e. DB and any service in the critical path). Then we have versioned health_report that return a JSON object where keys are the hostnames of dependent services (one per node for e.g. mongoDB) and a simple value "OK" or "NOTOK". the former is used by the FE / load balancer and the latter by prod support to troubleshoot.

From @bketelsen:
> but [the versioned healt report] could be an interface - component check interface - `Name() Status() ….` maybe more, and you just register a type that implements it

**Comment by ernesto-jimenez** [comment]
Rather than inventing something new, I would recommend seeing whether you can align with [prometheus](http://prometheus.io) an open source monitoring system and time series database written in Go by people in Soundcloud and quite popular.

Some projects like kubernetes are exposing metrics and status in prometheus format natively. It might be a good idea as an option to expose metrics and status about the APIs.

**Comment by derekperkins** [comment]
@ernesto-jimenez That's a great idea and I think @bketelsen has done some work with metrics, but that's not the core purpose of this issue. This is a much simpler health check to be hit by a load balancer to determine whether to send any traffic to the instance.

**Comment by bketelsen** [comment]
correct, i have the start of a metrics middleware in the middleware repo.  It works but has no docs yet.  This ticket is specifically about load balancer health checks.

**Comment by raphael** [comment]
I'm closing this as being "out of scope" for now. You can - and should - implement health check endpoints using goa, not sure it requires specific DSL.
