### ISSUE TITLE
Field uses the grpc tag of the Reference field instead of its own

### ISSUE THREAD

**Issue by tmcladam** [goadesign/goa#2303]
When a Field is a Reference to a Field in another type, the attribute ends up with two "rpc:tag" values, the first belonging to the reference field, and the second belonging to itself. The first Meta("rpc:tag") value seen is the one used for code generation (and validation).

Obvious approaches are:

1. Have Field set its tag before the reference type's
2. Use the last "rpc:tag" value instead of the first
3. Put a special case in Meta to force a single value only for "rpc:tag", with overwrite rather than append behavior.

Thoughts? Are there any other Meta tags for which it doesn't make sense to have multiple values, and that maybe we should apply 3. to, to avoid similar issues with references?

Or, is the intention that field references don't change the tag?

**Comment by raphael** [comment]
Thank you for raising this issue. It seems that references should also bring in metadata as that is consistent with the intent. In all the options listed option #2 might make the most sense: the metadata associated with the name "rpc:tag" is "special" and its handling requires understanding the semantic (i.e. picking the last value). Happy to hear other point of views though.

**Comment by tmcladam** [comment]
Fixed using approach 2 above.
