### ISSUE TITLE
v3: Accessing HTTP request object in service methods.

### ISSUE THREAD

**Issue by anshap1719** [goadesign/goa#2308]
Hello,

I am building an authentication microservice. It has a session controller which basically keeps record of a logged in user's sessions along with data like device, ip, location, etc and allows the user to specifically log out of particular sessions.

I am migrating from v1 where I used to get the required info with `ctx.Request`. Here's an example method that I am using that needs the request object:

```
func (c *SessionController) createSession(req *http.Request, userID string, isAdmin, isBrandManager bool) *database.Session {
	ip, _, err := net.SplitHostPort(req.RemoteAddr)
	if err != nil {
		ip = req.RemoteAddr
	}

	ua := user_agent.New(req.UserAgent())
	os := ua.OSInfo()
	if os.Name == "OS" {
		os.Name = ua.Platform()
	}
	browse, vers := ua.Browser()

	location, coord := getIPLocation(req.Header)

	newSession := &database.Session{
		UserID:         userID,
		LastUsed:       time.Now(),
		IP:             ip,
		Os:             os.Name + " " + os.Version,
		Browser:        browse + " " + vers,
		Location:       "",
		Coordinates:    "",
		IsMobile:       ua.Mobile(),
		IsAdmin:        isAdmin,
		IsBrandManager: isBrandManager,
	}
	return newSession
}
```

I am wondering how I can get the Request Object or at least the headers from it that I need. I tried searching around docs, asking on goa gophers slack channel, looking through issues, but couldn't find anything. Let me know if there's a way to do this.

**Comment by raphael** [comment]
@anshap1719 the basic idea is to put the data you need from the request that is not part of the method payload into the context. Note that in general everything including headers should be in the payload but there are exceptions for things like logging and monitoring or other orthogonal concerns. The [PopulateRequest](https://github.com/goadesign/goa/blob/v3/http/middleware/request.go) middleware does exactly that and you can obviously create your own to add more.
