### ISSUE TITLE
Suggestion: More automated error transformation 

### ISSUE THREAD

**Issue by lobocv** [goadesign/goa#2309]
Hi there,
As I was trying to convert my errors from my database package into Goa errors, I thought that there had to be a better way than manually checking and converting the errors like in the example below:

```go
err = s.db.SetAdmin(ctx, p.ID, p.AdminID, false)
	if _, ok := err.(models.NotFoundError); ok {
		return course.MakeNotFound(err)
	}
	if err != nil {
		return err
	}
```
Proposal 1:
I noticed that the goa.ServiceError is a struct. If it was an interface instead, I could define my own errors like `models.NotFoundError` to satisfy the interface and goa Encode<API>Error() methods would be able to handle them directly.
Currently the generated Encode<API>Error() method does a type check `res := v.(*goa.ServiceError)` so my errors cannot satisfy them, I must manually convert each time. This is probably a breaking change though.

Proposal 2:
Another approach would be to allow writing  "outerwear", (if you could call it that), which would allow me to look at the error returned from the endpoint, and convert it to the corresponding goa.Endpoint as I see fit. This would be super helpful and possibly easier to implement.

Would love to hear your thoughts on this

**Comment by raphael** [comment]
Thank you for the thoughts! One thing to consider here is that the generated code needs to instantiate the error object and initialize its fields according to the design. We went though a few iterations including using interfaces which would require having the generated code leverage a mix of factory methods and setter methods to initialize the error objects. The end result using interfaces was fairly convoluted and didn't feel very idiomatic (factory methods, setter methods - all anti-patterns in Go) hence the current solution. Can you give an example of what proposal #2 would look like?

**Comment by calvin-stratoscale** [comment]
My proposal 2 is still not ideal because I still have to convert to a specific service error, so if the same error is raised by different services, I should be writing one conversion middleware for each and using the MakeNotFound method from each service. If the goa methods used interfaces instead of concrete types, this wouldn't be needed.

**Comment by lobocv** [comment]
I'm not sure I follow you. Can you not instantiate the error the same way you are doing now but just pass it around as an interface instead of a concrete type? That way, if the user wants to make any errors they can pass them through the generated code without a problem (as long as they implement the interface).
You would need to have the interface define getters for all the goa.ServiceError fields (Name, ID, Message, Temporary, Timeout, Fault). For example, for the generated code which instantiates the error object:

Before:
```
func NewSessionGetNotFoundResponseBody(res *goa.ServiceError) *SessionGetNotFoundResponseBody {
	body := &SessionGetNotFoundResponseBody{
		Name:      res.Name,
		ID:        res.ID,
		Message:   res.Message,
		Temporary: res.Temporary,
		Timeout:   res.Timeout,
		Fault:     res.Fault,
	}
	return body
}
```
After
```
func NewSessionGetNotFoundResponseBody(res *goa.ServiceErrorInterface) *SessionGetNotFoundResponseBody {
	body := &SessionGetNotFoundResponseBody{
		Name:      res.Name(),
		ID:        res.ID(),
		Message:   res.Message(),
		Temporary: res.Temporary(),
		Timeout:   res.Timeout(),
		Fault:     res.Fault(),
	}
	return body
}

```

And the error encoding generated code would go from

Before
```
func EncodeGetError(encoder func(context.Context, http.ResponseWriter) goahttp.Encoder) func(context.Context, http.ResponseWriter, error) error {
	encodeError := goahttp.ErrorEncoder(encoder)
	return func(ctx context.Context, w http.ResponseWriter, v error) error {
		en, ok := v.(ErrorNamer)
		if !ok {
			return encodeError(ctx, w, v)
		}
		switch en.ErrorName() {
		case "NotFound":
			res := v.(*goa.ServiceError)
			enc := encoder(ctx, w)
			body := NewGetNotFoundResponseBody(res)
			w.Header().Set("goa-error", "NotFound")
			w.WriteHeader(http.StatusNotFound)
			return enc.Encode(body)
		default:
			return encodeError(ctx, w, v)
		}
	}
}
```

To

After
```
func EncodeGetError(encoder func(context.Context, http.ResponseWriter) goahttp.Encoder) func(context.Context, http.ResponseWriter, error) error {
	encodeError := goahttp.ErrorEncoder(encoder)
	return func(ctx context.Context, w http.ResponseWriter, v error) error {
		en, ok := v.(ErrorNamer)
		if !ok {
			return encodeError(ctx, w, v)
		}
		switch en.ErrorName() {
		case "NotFound":
			res := v.(*goa.ServiceErrorInterface)
			enc := encoder(ctx, w)
			body := NewGetNotFoundResponseBody(res)
			w.Header().Set("goa-error", "NotFound")
			w.WriteHeader(http.StatusNotFound)
			return enc.Encode(body)
		default:
			return encodeError(ctx, w, v)
		}
	}
}
```

You could also allow users to pick their own value for encodeError. Right now it is hard-coded to goahttp.ErrorEncoder(encoder), which always calls the encoder with a goa.ServiceError and in the implementation of NewErrorResponse you type-check to a goa.ServiceError. These could all be interfaces so that the user can pass their own errors down instead of forcing them to create goa.ServiceError structs.



About Proposal 2:

As I'm typing this, I just realized that I can already do this :) Here is what I'm planning to do. I can write a middleware that checks the errors returned and maps them to goa.ServiceError all in one place (rather than on each API method). This is super convenient because you would only need to write this middleware once and then in your APIs, simply return the errors. 

```
func ConvertError() func(goa.Endpoint) goa.Endpoint {
	return func(ApiEndpoint goa.Endpoint) goa.Endpoint {
		return func(ctx context.Context, req interface{}) (interface{}, error) {

			res, err := ApiEndpoint(ctx, req)

			switch pkgErr := err.(type) {
			case models.NotFoundError:
				err = professional.MakeNotFound(pkgErr)
			case models.UnAuthorizedError:
				err = professional.MakeUnauthorized(pkgErr)
			}
			return res, err
		}
	}
}
```

**Comment by lobocv** [comment]
My proposal 2 is still not ideal because I still have to convert to a specific service error, so if the same error is raised by different services, I should be writing one conversion middleware for each and using the MakeNotFound method from each service. If the goa methods used interfaces instead of concrete types, this wouldn't be needed.

**Comment by raphael** [comment]
@lobocv Sorry for the delay... Clarifying a bit my initial comment: Goa makes it possible to define the properties of an error in the design - for example whether it is temporary or not. It is important for the generated code to honor the design as it is one of the core values of Goa: ensuring that implementation matches the design. This is why Goa generates factory methods for the errors, these methods make sure that the properties are initialized according to the provided design. 

Using interfaces would thus require that the interface also exposes setter methods so that the generated code may set the values. The interface and structs would then look something like:
```go
	// ServiceError is the default error type used by the goa package to
	// encode and decode error responses.
	ServiceError struct {
		// Name is a name of the error class.
		Name string
		// ID is the unique identifying value for for the error occurrence.
		ID string
		// Message contains the error occurrence details.
		Message string
		// Is the error a timeout?
		Timeout bool
		// Is the error temporary?
		Temporary bool
		// Is the error a server-side fault?
		Fault bool
	}

	// ServiceErrorer is the interface implemented by errors returned by service methods.
	ServiceErrorer interface {
		// GetName returns the name of the error class.
		GetName() string
		// GetID returns the unique identifying value for for the error occurrence.
		GetID() string
		// GetMessage returns the error occurrence details.
		GetMessage() string
		// GetTimeout returns whether the error is due to a system timeout.
		GetTimeout() bool
		// GetTemporary returns whether the method call can be retried.
		GetTemporary() bool
		// GetFault indicates whether the error was triggered by a fault (bug).
		GetFault() bool
		// SetTimeout sets whether the error is due to a system timeout.
		SetTimeout()
		// SetTemporary sets whether the method call can be retried.
		SetTemporary()
		// SetFault sets whether the error was triggered by a fault (bug).
		SetFault()
	}

	func (e *ServiceError) GetName() { return e.Name }
	// ...
	func (e *ServiceError) SetFault() { e.Fault = true }
```
which isn't great Go code :)

Did you have something else in mind? While I understand the intent in the proposal and the extra work involved in doing the mapping using a concrete type does simplify things quite a bit...

**Comment by raphael** [comment]
#2413 adds the ability to provide a `formatter` function that gets invoked prior to errors being encoded. The function accepts the error and can return an arbitrary data structure that gets encoded into the response. The data structure must implement a `StatusCode() int` function which is called by the generated code for errors that have no mapping defined in the design (otherwise the status code specified in the design is used). The generated HTTP server and endpoints factory methods accept an extra argument that can be used to specify the formatter. If the value is `nil` then the generated code reverts to the behavior used prior to the PR. The [error](https://github.com/goadesign/examples/tree/master/error) example shows how to take advantage of this new functionality (see bottom of README).

**Comment by lobocv** [comment]
Hi @raphael , thank you for the response. 
My method of using middleware to convert my library errors to Goa errors is working well for me so I'm okay if you close this issue.

 It looks like the formatter you added does something similar but may be a little less full-featured as how I'm doing it now (since I'm converting to Goa errors, I get the error ID, error name set for me, not just the error code). 

I agree that the interface you proposed is quite big. Forgive me because I don't have as deep a knowledge in the Goa code base as you do: I feel you don't need the Setter methods on that interface. From what I've seen, the generated Goa code is read-only on errors, and errors should be as immutable as possible. 


For the record, I created a middleware that converts and `Error` into a `goa.ServiceError` base on custom logic. It works really well for me, is quite simple to implement and keeps a strong boundary between my library defined errors and goa defined errors:

```go
func ErrorHandler(logger *logging.Logger, convertErr func(err error) *goa.ServiceError) func(goa.Endpoint) goa.Endpoint {
	return func(next goa.Endpoint) goa.Endpoint {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			var convertedErr *goa.ServiceError
			// Call the original endpoint function.
			res, err := next(ctx, req)
			if err != nil {
				convertedErr = convertErr(err)
			}
			if convertedErr != nil {
				return res, convertedErr
			} else {
				return res, err
			}
		}
	}
}

```

**Comment by raphael** [comment]
The above makes a lot of sense - I'll close the issue. The ability to specify a formatter is a good addition nonetheless as it allows overriding the default logic for computing the status code being returned for errors that are not defined in the design which is a need that has come up a few times as well. For the record the need for having setter methods comes from the fact that the generated code needs to be able to create the error objects and set the fields. Again your approach makes sense for what you need.
