### ISSUE TITLE
go get goa.design/goa/v3/...: malformed module path "goa.design/goa/v3/...": double dot

### ISSUE THREAD

**Issue by tanxiaolong** [goadesign/goa#2320]
new to goa, when i run command "go get goa.design/goa/v3/...", terminal outputs this notice.

how can i get it rightly?

thank you!

**Comment by raphael** [comment]
There are a few things that could go wrong:
1. Goa v3 requires Go version 1.11 or newer 
2. The `GO111MODULE` environment variable must be set to `"on"`
3. There needs to be a `go.mod` file in the current directory (create one with `go mod init`, see the [docs](https://blog.golang.org/using-go-modules).
