### ISSUE TITLE
static Files not served correctly when using wildcard

### ISSUE THREAD

**Issue by rozagerardo** [goadesign/goa#2321]
I defined a service to serve static files using a wildcard (as described in [the documentation](https://godoc.org/goa.design/goa/dsl#Files)):
```
var _ = Service("static", func() { 
	Files("/static/*filepath", "./static/")
})
```
But when I run the service, the endpoint **always** retrieves all the content it finds in the _./static/_ directory, it seems it doesn't take into account the wildcard section at all.

For example, if I have _./static/uploads/file1.jpg_ and I request _localhost/static/uploads/file1.jpg_ or _localhost/static/anything_ , then the service retrieves the following:
```
<pre>
<a href="uploads/">uploads/</a>
</pre>
```

Digging into the code, I believe the problem is in the generated _/gen/http/static/server/server.go_ file:
```
// Mount configures the mux to serve the static endpoints.
func Mount(mux goahttp.Muxer, h *Server) {
	MountCORSHandler(mux, h.CORS)
	MountStatic(mux, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./static/")
	}))
}

// MountStatic configures the mux to serve GET request made to
// "/static/*filepath".
func MountStatic(mux goahttp.Muxer, h http.Handler) {
	mux.Handle("GET", "/static/*filepath", handleStaticOrigin(h).ServeHTTP)
}
```
For what I see, the generated code is serving what we passed as base path no matter what, it doesn't take into account if we configured a wildcard at all (it only uses it to match the request, but not to customize the file that we'll serve).

I believe this was working ok in v2, I found this issue in the process of migrating to v3.

**Comment by raphael** [comment]
Thank you for the report, there is a typo in the docs, the path in the design needs to be `/static/{*filepath}` instead (with curly braces surrounding the wildcard).

**Comment by rozagerardo** [comment]
cool, thanks for the quick response @raphael  :)
I now verified, and it's working perfectly with that change.

Let me know if you want me to make the change in the docs (I guess in [http_file_server.go](https://github.com/goadesign/goa/blob/922f55e91729e31573b9011401cc454025947172/dsl/http_file_server.go) right?).

**Comment by raphael** [comment]
I've already made the change, thank you!
