### ISSUE TITLE
v3: Multiple methods with the same type in the result body generates bad code

### ISSUE THREAD

**Issue by oralordos** [goadesign/goa#2344]
If you create a result that returns either a `Type` or a `ResultType`, and then you use the `Body` function in the HTTP response block to return that value directly in two different methods in the same service, the generated code will not compile.

The error says that it only generated a single function that attempts to convert the result type into the body. But this generated function takes in the result from the first method that returns that type. So the second method tries to use it and it is passing the incorrect type into it.

Here is an example design:
```go
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = API("test", func() {})

var User = Type("application/user", func() {
	Field(1, "name", String)
	Required("name")
})

var _ = Service("test", func() {
	Method("x", func() {
		Result(func() {
			Field(1, "user1", User)
		})

		HTTP(func() {
			GET("/x")
			Response(func() {
				Body("user1")
			})
		})
	})

	Method("y", func() {
		Result(func() {
			Field(1, "user2", User)
		})

		HTTP(func() {
			GET("/y")
			Response(func() {
				Body("user2")
			})
		})
	})
})
```

**Comment by raphael** [comment]
Thank you for reporting the issue! Definitely a bug.
