### ISSUE TITLE
how to create custom error response for 400 and 500?

### ISSUE THREAD

**Issue by samlee1203** [goadesign/goa#2349]
In Goa, if I don't provide a required attribute on the request body, I get 400 BadRequest error response automatically.
What I want to do is to customize the response son format.
currently it returns like this:
```
{
    "name": "missing_field",
    "id": "w39vamu6",
    "message": "\"username\" is missing from body",
    "temporary": false,
    "timeout": false,
    "fault": false
}
```
but I want to change this format to:
```
{
    "error_code": "400", <-- static/hard-coded for all 400 BadRequest responses.
    "message": "\"username\" is missing from body".  <-- dynamic/inherited from original "message" value.
}
```

I want to do the same for 500 InternalServerError.

How can I achieve this?

Thanks

**Comment by johnholiver** [comment]
Hi, I can't explain step by step but I know this is possible as I've done this for some services of mine.
You might want to have a look here: https://goa.design/design/handling_errors/

Besides, I've just had a look at one of my projects and found some stuff on my design.go that might serve as an example:

- Custome Error definitions
```
var ContentOrNoteMustBeProvided = Type("ContentOrNoteMustBeProvided", func() {
	Description("ContentOrNoteMustBeProvided is the error type returned when both content and note is missing while adding an information request. At least one thing must be provided.")
	Attribute("message", String, "Message of error", func() {
		Example("Instance with id 646116 not found")
	})
	Required("message")
})

var InvalidStatusStateTransition = Type("InvalidStatusStateTransition", func() {
	Description("InvalidStatusStateTransition is the error type returned when attempting an invalid transition of review status.")
	Attribute("message", String, "Message of error", func() {
		Example("Block 646116 can not execute invalid transition (Invalid transition (StatusState: TO_BE_REVIEWED -> APPROVED)")
	})
	Reference(Review)
	Attribute("id")
	Attribute("oldStatus", String, "OldStatus defines the current status of the review process", func() {
		Example("TO_BE_REVIEWED")
	})
	Attribute("newStatus", String, "NewStatus defines the status which was attempted to be set to the review process", func() {
		Example("APPROVED")
	})
	Required("message", "id", "oldStatus", "newStatus")
})
```

- Method definition with usage of custom errors
```
Method("addInformationRequest", func() {
	Description("Adds an information request to a review.")
	Payload(InformationRequestQuery)
	Result(StoredReview)
	Error("NotFound", NotFound, "Instance not found")
	Error("BadRequest", BadRequest, "Bad Request")
	Error("ContentOrNoteMustBeProvided", ContentOrNoteMustBeProvided, "Content and Note missing.")
	Error("InvalidStatusStateTransition", InvalidStatusStateTransition, "Block can not execute invalid state transition")
	HTTP(func() {
		POST("/{id}/informationRequests")
		Response(StatusOK)
		Response("NotFound", StatusNotFound)
		Response("BadRequest", StatusBadRequest)
		Response("ContentOrNoteMustBeProvided", StatusBadRequest)
		Response("InvalidStatusStateTransition", StatusBadRequest)
	})
})
```

And, **most importantly**, you must bind your ErrorEncoder to your http handlers properly, otherwise, you won't see the responses formatted properly. Usually you will construct the http handler passing an endpoint, a request decoder, and a response encoder, but because of the custom error decoding, you need to provide an extra argument. Unfortunately, this snippet is not goa vanilla, I use the gokit plugin, but I'd expect the behavior of goa vanilla to be very much similar.
```
reviewqueueAddInformationRequestHandler = kithttp.NewServer(
	endpoint.Endpoint(reviewqueueEndpoints.AddInformationRequest),
	reviewqueuekitsvr.DecodeAddInformationRequestRequest(mux, dec),
	reviewqueuekitsvr.EncodeAddInformationRequestResponse(enc),
	kithttp.ServerErrorEncoder(reviewqueuekitsvr.EncodeAddInformationRequestError(enc)),
)
```
Here is how it looks when I don't have custom errors
```
reviewqueueListHandler = kithttp.NewServer(
	endpoint.Endpoint(reviewqueueEndpoints.List),
	reviewqueuekitsvr.DecodeListRequest(mux, dec),
	reviewqueuekitsvr.EncodeListResponse(enc),
)
```

I hope that's enough to get you started!

**Comment by raphael** [comment]
@johnholiver this is great, there is also a new feature that was added in https://github.com/goadesign/goa/pull/2413 that makes it possible to pass in a formatter that can be used at runtime to modify the shape of error responses (this is equivalent to the `ErrorEncoder` used by Go kit).

**Comment by johnholiver** [comment]
@raphael Cool! I'll check the link, in which version has this feature been added? I don't recall seeing a changelog for goa... I do remember you had blog posts in the site tho

**Comment by raphael** [comment]
This specific PR hasn't been released yet. You can try it by pointing to the head of the `v3` branch. I'm planning on releasing v3.0.9 soon that will contain this change.

**Comment by sevein** [comment]
v3.0.9 has been out for quite a while, maybe this issue can be closed @raphael @samlee1203?

**Comment by raphael** [comment]
Thanks for the reminder, I think this can be closed.
