### ISSUE TITLE
Code in README can't work

### ISSUE THREAD

**Issue by sheepbao** [goadesign/goa#235]
When I input the code: `$ goagen bootstrap -d goa-adder/design`
I got this tip,but didn't  genrate `main.go` and `adder.go` :
`more than one Go package found in /home/lstbao/work/listomego/src/goa-adder/design (design,main)`

**Comment by raphael** [comment]
Looks like you have a go file with `package main` in that directory. All the files in the directory must be in the `design` package.

**Comment by sheepbao** [comment]
Thanks ,it can work now
