### ISSUE TITLE
Configuring which interface server should be listening

### ISSUE THREAD

**Issue by slaterx** [goadesign/goa#2352]
I have an application I'm migrating to v3. In v1, to make the compiled server to list on, say eth2 (instead of eth0 or localhost), I would just give the ip address and port to directive `service.ListenAndServe` (or even `:8080` if I would like to bind on all interfaces on server).

However, on v3, we need to use the Host construct:

```bash
Host("localhost", func() {
	URI("http://localhost:8080/api/v1")
})
```

Which is very neat because you can define a list of addresses you can bind your server to. That's great, however, when running on dynamic services (such as kubernetes), where you can't define beforehand which IP address, or when actual DNS address is a public load balancer and your app is behind a proxy/loadbalancer, this doesn't work:

```
Host("localhost", func() {
	URI("http://myserver.foo.bar:8080/api/v1")
})

(...)

[api] 23:31:15 HTTP server listening on "myserver.foo.bar:8080"
[api] 23:31:15 exiting (listen tcp 10.20.30.40:8080: bind: can't assign requested address)
[api] 23:31:15 shutting down HTTP server at "myserver.foo.bar:8080"


```

Just wondering if I'm thinking this wrong or actually there's a construct for host that addresses this user case? Happy to create a PR to add this option in the design if anyone gives me the directions.

Thanks!

**Comment by raphael** [comment]
Hello, the idea here is to use that information to generate docs and examples. The actual value being given at runtime can be anything (the generated example files are just that: you own that code and should edit it, test it etc.). We use Kubernetes to run our Goa services as well and simply configure the port using flags and/or environment variables.

**Comment by slaterx** [comment]
I was under the impression that the files changed by `Host` where all in the ./gen folder, but you are correct, they are all in the example application. 

Nervermind my question, then! Thanks again!
