### ISSUE TITLE
goa gen using response header and collectionOf error

### ISSUE THREAD

**Issue by emargob** [goadesign/goa#2358]
Hello devs,

I'm getting the following error when doing goa gen (V3) on a DSL with a HTTP response header and a Result containing a CollectionOf(SomeType), like:
```
Method("list", func() {
        Description("")
        HTTP(func() {
            GET("/")
            Response(StatusOK, func() {
                Header("SomeResponseHeader")
            })
        })

        Result(CollectionOf(SomeResultType))
    })
```
Error:
```
exit status 1
/home/emargob/dev/go/src/gitlab.com/gt/gen/http/testservice/server/encode_decode.go:31:20: expected selector or type assertion, found '!='

========
Content:
// Code generated by goa v3.0.7, DO NOT EDIT.
...
```
Full example of faliure:
```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var TestMedia = ResultType("application/vnd.imsi+json", func() {
	TypeName("TestType")
	Description("The test type")

	Attributes(func() {
		Attribute("Name", String, "The name", func() {
			Example("Alice")
		})
	})
})

var _ = Service("testservice", func() {

	HTTP(func() {
		Path("/testpath/")
	})

	Method("list", func() {
		Description("List")
		HTTP(func() {
			GET("/path")
			Response(StatusOK, func() {
				Header("ResponseHeader")
			})
		})

		Payload(Empty)
		Result(CollectionOf(TestMedia))
	})
})

var _ = API("testapi", func() {
	Title("API")
	Description("API")

	Server("apiserver", func() {
		Description("App server")
		Services("testservice")
		Host("localhost", func() {
			Description("default host")
			URI("http://localhost:8080/")
		})
	})
})
```

**Comment by raphael** [comment]
Definitely a bug, thank you for the report!

**Comment by raphael** [comment]
So the design has an issue in that the HTTP transport refers to the non-existent result attribute `"ResponseHeader"`. An equivalent design could be:

```go
package design

import (
	. "goa.design/goa/v3/dsl"
)

var TestMedia = ResultType("application/vnd.imsi+json", func() {
	TypeName("TestType")
	Description("The test type")

	Attributes(func() {
		Attribute("Name", String, "The name", func() {
			Example("Alice")
		})
	})
})

var CollectionTestMedia = ResultType("application/vnd.imsi.collection+json", func() {
    TypeName("CollectionTestType")
    Attributes(func() {
        Attribute("Collection", CollectionOf(TestMedia))
        Attribute("ResponseHeader", String)
    })
})

var _ = Service("testservice", func() {

	HTTP(func() {
		Path("/testpath/")
	})

	Method("list", func() {
		Description("List")
		HTTP(func() {
			GET("/path")
			Response(StatusOK, func() {
				Header("ResponseHeader")
			})
		})

		Payload(Empty)
		Result(CollectionTestMedia)
	})
})

var _ = API("testapi", func() {
	Title("API")
	Description("API")

	Server("apiserver", func() {
		Description("App server")
		Services("testservice")
		Host("localhost", func() {
			Description("default host")
			URI("http://localhost:8080/")
		})
	})
})
```
This is still a bug as the tool should catch the error and report it.

**Comment by emargob** [comment]
Thanks for the work around! Should work for us.

**Comment by raphael** [comment]
You're welcome. Just to be clear it's not a workaround but how the Goa design works :) All the elements that appear in transport specific sections (e.g. HTTP request and response) must be defined in the method (payload and result). See https://goa.design/design/overview/ for more information.

**Comment by emargob** [comment]
Using above example, I'm getting a json object containing a json array of objects. Like:

{
  "Collection": [
    {object}, {object}
  ]
}

Which is logical. What I want is a json array, containing objects:
[
  {object}, {object}
]

If i just skip the response header and use CollectionOf on the Result directly, then I get what I want from a json perspective. If I do that, and add the:
Attribute("ResponseHeader", String)
to the TestMedia ResultType, I still get an error.

Am I doing something wrong here?

**Comment by raphael** [comment]
You can achieve what you're after using the `Body` function in the `HTTP` section. `Body("Collection")`.

**Comment by raphael** [comment]
The `goa` tool now generates an error in this case:
```
service "testservice" HTTP endpoint "list": Array result is mapped to an HTTP header but is not an array of primitive types.
```
This error indicates that the method result is being mapped to the HTTP response header as there is no body being defined. This does not work in this case because the type is an array of objects which cannot be encoded automatically in a header.
