### ISSUE TITLE
Can't install Goa; cannot find package?

### ISSUE THREAD

**Issue by ndguardian** [goadesign/goa#2359]
First off, I want to start by saying that I doubt this is an issue explicitly with Goa itself, but I was trying to do the Getting Started guide, and of course first thing is to install Goa. Easy enough, go get, so on and so forth. So I try to do that, and I get a package not found error, shown below. Got any thoughts on this? I seem to be able to go get other packages just fine. Thanks in advance!

```
C:\Users\derik>go get -u goa.design/goa/v3
package goa.design/goa/v3: cannot find package "goa.design/goa/v3" in any of:
        c:\go\src\goa.design\goa\v3 (from $GOROOT)
        C:\Users\derik\go\src\goa.design\goa\v3 (from $GOPATH)

C:\Users\derik>go version
go version go1.13.3 windows/amd64

**Comment by ndguardian** [comment]
I looked on the repo main page and found that if you want to just install it globally, there is a different endpoint recommended for use. I just tried that as well, but to no avail. Just wanted to let you know I saw that real quick.

```
C:\Users\derik>go get -u goa.design/goa/v3/cmd/goa
package goa.design/goa/v3/cmd/goa: cannot find package "goa.design/goa/v3/cmd/goa" in any of:
        c:\go\src\goa.design\goa\v3\cmd\goa (from $GOROOT)
        C:\Users\derik\go\src\goa.design\goa\v3\cmd\goa (from $GOPATH)

**Comment by NotoriousPyro** [comment]
What version of go do you have?
```
go version
```

**Comment by saschajullmann** [comment]
I'm currently facing the same issue... I guess it would be nice if there was a goa binary provided...

**Comment by raphael** [comment]
Starting with Go 1.12, this should work:
```
env GO111MODULE=on go get goa.design/goa/v3/cmd/goa@v3
```
