### ISSUE TITLE
How to set http cookie and url redirect in goa？

### ISSUE THREAD

**Issue by JermineHu** [goadesign/goa#2360]
Sometimes maybe need to give front-end data through cookies and redirect other page！How should I use it in Goa？

**Comment by raphael** [comment]
Cookies are not supported directly in the design at this time. There are a couple of things you can do:
1. Use the HTTP `Header` DSL to store the value of the `Cookie` header in the request payload as a raw string (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie describes the string content)
2. Write a HTTP middleware that extract the cookies from the request (using the Go standard library `request.Cookies()` method) and stores them in the request payload.

I would also be happy to merge a PR that added native support to cookies in the DSL (similar to `Header`).

**Comment by JermineHu** [comment]
I temporarily modified the `server.go` file in the gen/http  directory to fix this problems in goa v3.x. I don't think it's an elegant way, because the generated file has been modified, which destroys the advantage of code generation. If the goa.context inject to service like goa v1.x `app.xxContext` object (include goa.RequestData and goa.ResponseData ), this problems will fix easy.

**Comment by raphael** [comment]
Modifying the generated code is going to cause a lot of issues for sure. You can easily create a middleware that adds the HTTP request to the context yourself. Something similar to https://github.com/goadesign/goa/blob/v3/http/middleware/request.go. You can then setup the middleware by calling the `Use` method on the generated HTTP server struct.

**Comment by JermineHu** [comment]
Thx a lot for your suggestions! I will try it do work!
