### ISSUE TITLE
Send file in form with files in Goa v1

### ISSUE THREAD

**Issue by sredxny** [goadesign/goa#2389]
Hello, in a personal project I am using Goa v1, right now I want to send a file in a form that also contains some fields. So, I would need something alike what is [here](https://github.com/goadesign/examples/tree/master/multipart) I tried to modify my payload to receive a file as well as the other fields, but, when I attempt to generate the code I get:

`Payload xxxxPayload contains an invalid type, action payloads cannot contain a file`

The action is defined as:

```
Action(tools.ActionNameAdd, func() {
		Routing(
			POST("/parentObject/:ID/objects"),
			POST("/objects"),
		)
		Params(func() {
			Param("ID", UUID)
		})
		Description("Adds a new resource")
		MultipartForm()
		Payload(ObjectInputPayload, func() {})
		Response(Created,"something")
		Response(BadRequest, ErrorMedia)
	})
```

And, the payload is defined as:

```
var ObjectInputPayload = Type("ObjectInputPayload", func() {
	Attribute("field1", String, "field1")
	Attribute("field2", String, "field2")
	Attribute("file", File, "uploaded file")
})
```

So, is possible to make this in Goa v1?

**Comment by MarkSonghurst** [comment]
I'm using Goa v1 and have a multipart form payload with File and String and Integer attributes in it.

```
var ExternalDocumentUpload = Type("ExternalDocumentUpload", func() {
	Description("An externally sourced document associated with a UELN.")
	Attribute("document", File, "Binary or Text formatted document.")
	Attribute("description", String, "Description of the document")
	Attribute("document_type", Integer)
	Attribute("source_system", Integer)
	Attribute("username", String, "Username of the user associated with the UELN. Can be empty.")

	Reference(UELN)
	Attribute("ueln")

	Required("document", "description", "document_type", "ueln", "source_system")
})
```

This generates and works without issue.
Here's my Action which uses the Payload:
```
	Action("upload", func() {
		Metadata("swagger:summary", "Upload a document associated with a UELN from an external system.")
		Security(APIKey)
		Routing(PUT("upload"))
		Headers(func() {
			Header("Accept-Language", func() {
				Default("en")
				Example("en")
			})
		})
		MultipartForm()
		Payload(ExternalDocumentUpload)
		Response(OK, func() {
			Media(ExternalDocumentUploadedMedia)
		})
	})

```

The only possible issue I see in your code is the empty `func(){}` declaration in your Payload call.
Maybe try removing that and seeing if it fixes your code generation issue.
```
Payload(ObjectInputPayload, func() {})
```

**Comment by sredxny** [comment]
Hi, indeed was my mistake, I was using the same payload in another action that didn't have the MultipartForm() section declared. Thank you so much

**Comment by raphael** [comment]
Thank you @MarkSonghurst , closing the issue.
