### ISSUE TITLE
Goa v3 API Key - superfluous behaviour in Swagger definition

### ISSUE THREAD

**Issue by MarkSonghurst** [goadesign/goa#2390]
Hi. New convert from Goa v1 to v3 here. I'm having some issues with API Key Security and the Goa generated OpenAPI spec.

I'm loading the generated spec into https://editor.swagger.io/ and using the Authorize button at the top of the page to set my API key.
Then scrolling down to one of my methods (all require an API Key), i'm still presented with the "Authorisation" header input field, which requires a value. Regardless of what I input here, when clicking Execute, the editor correctly uses the API Key I initially entered using the Authorize button. 

My issue here is one of User Experience - It's confusing to also have to enter a value in the "Authorisation" header input field, particularly as it's not actually used by the editor.

Goa v1 didn't behave this way  but I can see the DSL for Security has changed quite a lot for Goa v3, could this be a side-effect of needing to declare the Authorisation header in the HTTP section of each Method, rather than in Goa v1, where the Header was declared in the APIKeySecurity DSL ?

Goa v1
```
var APIKey = APIKeySecurity("api_key", func() {
	Header("X-API-Key")
})
```
Goa v3
```
// APIKeyAuth defines a security scheme that uses API keys.
var APIKeyAuth = APIKeySecurity("api_key", func() {
	Description("Secures endpoint by requiring an API key.")
})

// ...

var _ = Service("MyService", func() {
  //...
  Security(APIKeyAuth)
  //...
   Method("send", func() {
   //...
      HTTP(func() {
         POST("/something")
	 Header("key:Authorization") // Provide the API Key in Authorization header
         //...
// etc
}
```

For an example please load [https://github.com/goadesign/examples/blob/master/security/gen/http/openapi.yaml](url) into a Swagger Editor click the Authorise button and enter an API Key value of XXX, then scroll down to the `PUT /secure` method and click on Try It Out.
Enter YYY for the API Key and ZZZ for the JWT. Then click Execute. 
I get the following curl command:
```
curl -X PUT "https://localhost:80/secure?k=XXX" -H "accept: application/json" -H "Authorization: ZZZ"
```

I appreciate this is somewhat a cosmetic issue, but it would be great to address.

**Comment by morganhein** [comment]
I wonder if this is related to some odd behavior where the generated openapi spec creates two header fields for the auth, one with the information from toe APISecurityKey description, and the other from the APIKey from within the payload? It seems it's denoting that there are in fact two authentications required. I may be totally off, but this might be an indicator/related.

**Comment by nitinmohan87** [comment]
@MarkSonghurst In the security example you listed in your issue, `PUT /secure` endpoint is secured by both API Key and JWT token - https://github.com/goadesign/examples/blob/master/security/design/design.go#L120-L149

That's why you are getting the curl with both. Does that make sense?

I am not very familiar with Goa v1. But with v2/v3 you can secure your endpoint with more than one security scheme (AND or OR) https://godoc.org/goa.design/goa/dsl#Security

**Comment by MarkSonghurst** [comment]
@nitinmohan87 Thanks for the analysis, I agree that makes sense.
I'm going to close this ticket.
