### ISSUE TITLE
‘goa’: No such file or directory

### ISSUE THREAD

**Issue by Yvonne2017** [goadesign/goa#2394]
Following are part of my makefile. When I build it locally, it successed. 

**export GO_MOD=env GO111MODULE=on

install:
	$(GO_MOD) go get -u goa.design/goa/v3
	$(GO_MOD) go get -u goa.design/goa/v3/...
	$(GO_MOD) go get -u goa.design/goa/v3/cmd/goa	
	$(GO_MOD) go get github.com/onsi/ginkgo/ginkgo
	$(GO_MOD) go get github.com/onsi/gomega
	$(GO_MOD) go get github.com/onsi/gomega/...

generate: 
	$(GO_MOD) goa gen $(PROJECT_PKG)/design**

But when github action pick it up, it got the error.
**env GO111MODULE=on goa gen github.com/yvonne-zhang/design
env: ‘goa’: No such file or directory
make: *** [generate] Error 127
##[error]Makefile:34: recipe for target 'generate' failed**

Copied this part from my github action yaml if it is useful:
 **build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go**

**Comment by raphael** [comment]
Hello, the error indicates that the `goa` executable isn't in the path by the time `goa gen` is run. Maybe `PATH` should be updated to also include `$GOPATH/bin`?

**Comment by Yvonne2017** [comment]
Thank you @raphael ! That works for me.
