### ISSUE TITLE
`struct:field:type` generated code does not compile when using validators

### ISSUE THREAD

**Issue by tylerstillwater** [goadesign/goa#2403]
Follow-on to #2399 

When adding a validator to an attribute containing the `Meta("struct:field:type"...)` call, the generated code fails to compile.

```
gen/http/bug/server/types.go:39:62: cannot use *body.Bug (type types.Bug) as type string in argument to goa.ValidatePattern
gen/http/bug/client/cli.go:28:66: cannot use body.Bug (type types.Bug) as type string in argument to goa.ValidatePattern
```

It seems like this could be a pretty simple fix. What appears to be missing is simple type conversions.

If we have a custom type, it is almost always going to be defined as `type MyType <builtin>`, where `<builtin>` is one of the base types, like `string` or `int`.

Given that, the conversion code could be extrapolated from the base type in the Attribute.

For example:

```go
Attribute("bug", String, "bug", func() {
				Meta("struct:field:type", "types.Bug", "github.com/outdoorsy/goabug/types")
				MinLength(3)
				MaxLength(4)
				Pattern("^.*$")
			})
```

The attribute knows it is a `String` base type, with an override of `types.Bug`. The generator could check that base type and generate the appropriate conversions where necessary.

Currently, we have:

```go
if body.Bug != nil {
	err = goa.MergeErrors(err, goa.ValidatePattern("body.bug", *body.Bug, "^.*$"))
}
```

What we appear to need is:

```go
if body.Bug != nil {
	err = goa.MergeErrors(err, goa.ValidatePattern("body.bug", string(*body.Bug), "^.*$"))
}
```

I've attached an updated example zip file that demonstrates the issue. This change would need to affect all validators.

[goabug.zip](https://github.com/goadesign/goa/files/3923625/goabug.zip)

**Comment by raphael** [comment]
I'd be happy to merge a PR that did what is described above. While the end result is indeed simple there are many places to consider here so it's not as straightforward as it may seem :)

**Comment by tylerstillwater** [comment]
Yes I figured the "simplicity" of it is deceptive. Here be dragons!

Unfortunately I don't have the time to dig in and find all those dragons right now, so I won't be able to submit a PR on this for a while.

It would be very helpful if you could give me an idea of where to start looking for when I do have some time.

Thanks!
