### ISSUE TITLE
Generated CLI broken

### ISSUE THREAD

**Issue by satiar** [goadesign/goa#242]
**Issue:** 
CLI not building from generated code

**Error:**
**commands.go:95: cannot use nil as type int in argument to cc.Flags().IntVar**

Steps to repro:
1. Create a "service.go" design file that includes the following 'Action'
Action("modify", func() {
                Description("modify the service instance based on new configuration.")
                Routing(PUT("/:id"))

                Params(func() {
                        Param("volumeRebuild", Integer, "1= destroy and re-create volume(s) associated with Service Instance")
                })

                Response(OK)
                Response(NotFound)
        })

2. generate files via 'goagen'
3. build via 'go build'
4. generate the 'cli' via 'go build'. Error is returned at this stage
xxxxxx/commands.go:95: cannot use nil as type int in argument to cc.Flags().IntVar

Snippet from 'commands.go'

// RegisterFlags registers the command flags with the command line.
func (cmd *ProcessesComponentCommand) RegisterFlags(cc *cobra.Command) {
        cc.Flags().IntVar(&cmd.PsArgs, "psArgs", nil, "Arguments to use for 'ps'")
}

Thanks.

**Comment by raphael** [comment]
Added test in #248
