### ISSUE TITLE
struct:field:type doesn't generate expected request body struct types

### ISSUE THREAD

**Issue by maxmcd** [goadesign/goa#2420]
I have the following type:
```go
var EventFields = Type("EventFields", func() {
	Field(2, "name", String, "what is the name of this event")
	Field(7, "start_time", String, "the start time of the event", func() {
		Meta("struct:field:type", "time.Time", "time")
	})
})
```

Which generates the `time.Time` struct on a type that inherits EventFields
```go
type CreateEventRequest struct {
	// the id if the site
	SiteID string
	// what is the name of this event
	Name string
	// the start time of the event
	StartTime time.Time
```

The generated CreateEventRequestBody (for an http service) however uses a string:
```go
// CreateEventRequestRequestBody is used to define fields on request body types.
type CreateEventRequestRequestBody struct {
	// the id if the site
	SiteID string `form:"site_id" json:"site_id" xml:"site_id"`
	// what is the name of this event
	Name string `form:"name" json:"name" xml:"name"`
	// the start time of the event
	StartTime string `form:"start_time" json:"start_time" xml:"start_time"`
```

Which causes some compiler errors when trying to compile the http service. I have read some of the [related issues](https://github.com/goadesign/goa/issues/2403) and understand this is complicated functionality to support. I was wondering though why the type for CreateEventRequestRequestBody.StartTime is not just simply identical to what is created in the CreateEventRequest struct, I've temporarily fixed with just a `sed` script that replaces the necessary types. 

Am I doing something wrong here or is this the current expected behavior?

**Comment by raphael** [comment]
Thanks for the report. Are you able to provide a complete minimal design that reproduces the issue? This would help make sure we're looking at the same thing - thank you!

**Comment by maxmcd** [comment]
Upgrading to 3.0.9 resolved the issue (closing for now). Still interested in an example?

**Comment by raphael** [comment]
No all good, do provide one in case another issue pops up - thank you!
