### ISSUE TITLE
newly created app with DateTime type doesn't import time in app/media_types.go

### ISSUE THREAD

**Issue by bketelsen** [goadesign/goa#243]

**Comment by derekperkins** [comment]
Still getting this. @ernesto-jimenez?

**Comment by ernesto-jimenez** [comment]
This would happen due two issues:

 1. The generator is missing `time` in the `codegen.ImportSpec`
 2. There should be a test checking this that would detect problems generating a media type with DateTime.

I fixed all the `ImportSpec` definitions that resulted in failing tests in PR #234 ([example](https://github.com/goadesign/goa/pull/234/files#diff-1eea8bc9455d78956292830aff1511ea)) but there will definitely be definitions missing imports and test coverage.

Ideally all different combinations of generated code should be tested to make sure the resulting code is valid.

I'm wondering wether that must be done manually or it can be done with some kind of fuzzing: run the code generation with different inputs and report any combinations where the generation succeeds but the generated code is invalid.

**Comment by bketelsen** [comment]
Yeah I'm still getting this.
