### ISSUE TITLE
DateTime in v3 ?

### ISSUE THREAD

**Issue by chadgrant** [goadesign/goa#2440]
Trying this out, but stopped in my tracks ... undefined "DateTime"

I've looked through all the samples and can't find anything on Dates. Do you not support dates?

**Comment by tchssk** [comment]
You can use [`Format(FormatDateTime)`](https://godoc.org/goa.design/goa/dsl#Format) instead.

```go
// v1
Attribute("created_at", DateTime)

// v3
Attribute("created_at", String, func() {
	Format(FormatDateTime)
})
```

**Comment by tchssk** [comment]
FYI: [Comparison between Goa v1 vs. v3 about the design primitive types](https://dev.to/tchssk/comparison-between-goa-v1-vs-v3-about-the-design-primitive-types-3kpe)

**Comment by chadgrant** [comment]
That's unfortunate. Grpc supports Timestamps natively and this generates strings for all my models where I would want time.Time's :(

Really trying to avoid adding converters or turning payloads into DTO's

Thanks for the help though!

**Comment by raphael** [comment]
Protobuf does not define a native scalar type for time values (https://developers.google.com/protocol-buffers/docs/proto#scalar) - there is indeed an extension that you can import that implements time values using structs (google/protobuf/timestamp.proto). There's also no well defined default for HTTP. Having that type in v1 created issues where different use cases called for different ways to serialize the time value so v3 stays non-opinionated and lets you define how you want to marshal time values (e.g. integers that represent unix timestamps, strings that represent one of the various RFCs, struct a la protobuf extension etc.).

**Comment by chadgrant** [comment]
With http not sure that is the case. I’ve worked with maybe a dozen or more serializers across multiple languages and they all serialize 8601 to native date time structures.

You can certainly use strings/epoch integer types if you choose,(that is considered an anti pattern especially in interop) but the defaults are datetime<-> 8601 string

Thanks for checking it out

**Comment by raphael** [comment]
I guess my experience hasn't been the same. For example the 'Last-modified' HTTP header spec uses RFC2616, I've also worked with a number of APIs that use RFC3339 (which is why it's a built-in format in v3). I understand that it is a bit of extra work but there just wasn't a satisfactory "default" that would work in call cases.

**Comment by chadgrant** [comment]
Yeah, http is super old, but payload wise 8601 has been the de facto for a long time. json marshal/unmarshal in go uses 8601. 

I don’t wanna seem like I’m bashing on your project cuz I think it’s awesome.

I’d recommend putting some dates on your cellar example (persisted) 

I’d like to not be parsing string time stamps all over the place, I use audit fields everywhere in almost all important entities. 

In my use case, they’re only valid on GET’s, not being accepted/mapped via PUT/POST so it’s a bit goofy to have strings defined. I’d have to do multiple models or views everywhere

Anyways, my 2 cents. Happy new year!
