### ISSUE TITLE
`auth.go` is not generated in v3.0.8

### ISSUE THREAD

**Issue by kaito2** [goadesign/goa#2441]
`auth.go` is not generated even if the following command is executed in goa/example.

https://github.com/goadesign/examples/tree/master/security

```
goa example goa.design/examples/security/design
```

**Comment by tchssk** [comment]
After v3.0.9, The authentication methods are generated into each service file. See #2362.

**Comment by kaito2** [comment]
I got it! Thank you for your answer.
