### ISSUE TITLE
v3: Extra space is inserted when using example cli

### ISSUE THREAD

**Issue by kitagry** [goadesign/goa#2487]
I wrote design as followings.

```go
var _ = Service("test", func() {
	Method("add", func() {
		Payload(func() {
			Attribute("users", ArrayOf(String, func() {}))
		})

		HTTP(func() {
			GET("/add/{users}")
		})
	})
})
```

And, I generate codes by `goa gen` and `goa example`.
And I run `test-cli  test add --users '["hello", "world"]'`, But server got `["hello", "<Space>world"]`.

I think it is because users are Joined as followings in `gen/http/test/client/paths.go`

```go
fmt.Sprintf("/add/%v", strings.Join(usersSlice, ",<Space>"))
```

**Comment by raphael** [comment]
Thank you for the report! I think you are correct, the server decode code uses `usersRawSlice := strings.Split(usersRaw, ",")` (no space). Do you feel like taking a crack at making a PR to fix the problem? This is the line that needs to be fixed: https://github.com/goadesign/goa/blob/v3/http/codegen/service_data.go#L2562
