### ISSUE TITLE
Trouble: It dosen't work after Goagen update

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#249]
Recently I'm working for building a micro-service by `Goagen`, it's so efficient and I think I 've got used to this design language. Thanks.

But after updating new commit today, I meet some questions.

I have designed a `Resource` includes 4 `Action`:

```golang
var _ = Resource("CUserAccount", func() {
	BasePath("/accounts/C")
	DefaultMedia(AccountInformation)
	Action("NewAccount", func() {
		Routing(POST("/"))
		Description(" create a new account (checked by CIC)")
		Payload(func() {
			Member("cellphone_number", String)
			Member("password", String)
			
			Required("cellphone_number", "password")
		})
		Response("NewAccountCreated")
	})

	Action("CPointUserLogin", func() {
		Routing(POST("/login"))
		Description("C-point user login")
		Payload(func() {
			Member("cellphone_number", String)
			Member("password", String)
			Member("client_system", ClientSystemInfo)

			Required("cellphone_number", "password", "client_system")
		})
		Response(OK)
	})

	Action("CResetPassword", func() {
		Routing(POST("/resetpwd"))
		Description("reset C-point user's password (checked by CIC)")
		Payload(func() {
			Member("cellphone_number", String)
			Member("password", String)	//ask for new password

			Required("cellphone_number", "password")
		})
		Response(OK, "plain/text")
	})

	Action("CResetUserData", func() {
		Routing(PUT("/:user_id"))
		Description("3.4 Reset C-point-user's data")
		Params(func() {
			Param("user_id", String, "C-point-client UserID")
		})
		Payload(func() {
			Attribute("nick_name", String)
			Attribute("gender", Integer)
			Attribute("birthday", String)
			Attribute("company", String)
			Attribute("occupation", String)

		})
		Response(OK, "plain/text")
	})
})
```

Define `MediaType`:

```golang
var AccountInformation = MediaType("application/v1.new_account+json", func() {
	Description("create new acount media")
	TypeName("AccountInformation")
	Attributes(func() {
		Attribute("cellphone_number", String, "user cellphone number")
		Attribute("client_system", ClientSystemInfo, "system information of the client")
		Attribute("message_push_sdk", MessagePushSDK, "message pusher SDK")

		Links(func() {
			Link("client_system", "default")
		})

		Attribute("password", String, "user password")
		Attribute("user_id", String, "uesr id")
		Attribute("nick_name", String, "user nick name")
		Attribute("gender", Integer, "user gender")
		Attribute("birthday", String, "user birthday")
		Attribute("company", String, "user company")
		Attribute("occupation", String, "user occupation")
	})

	View("default", func() {
		Attribute("cellphone_number")
		Attribute("password")
		//		Attribute("client_system")
		Attribute("links")
	})

	View("userDescription", func() {	
		Attribute("nick_name")
		Attribute("gender")
		Attribute("birthday")	
		Attribute("company")
		Attribute("occupation")		
	})

	View("responseUserId", func() {
		Attribute("user_id")
	})
})
``` 

As you can see， `DefaultMedia(AccountInformation)` defined only ONE `MediaType` data structure `AccountInformation`, and `AccountInformation` has 3 `View` design. After using structure instead of using dynamic marshaling code, when I need to write `OK(200)` to response, it not as easy as before:

```
cannot use res (type *app.AccountInformationUserDescription) as type *app.AccountInformation in argument to ctx.OK
```

I don't know how to translate type `*app.AccountInformationUserDescription` into `*app.AccountInformation`, because the METHOD of `Links` has changed yet.

At the begin of this design-code, I have defined a 201 status by  `ResponseTemplate`, and used at above code.

```golang
ResponseTemplate("NewAccountCreated", func() {
		Description("New account resource created")
		Media(AccountInformation) //There can't appoint a media's view 
		Status(201)
	})
```

Before updating, I would `return ctx.NewAccountCreated(&res, View-name)` to appoint which `View` of media for response. But it doesn't work after updating to new version, and I haven't found any way to modify `Media(AccountInformation)` to appoint a media's view.

I think I haven't got the core idea of  `Goagen`, so I always meet questions when using it, especially after updating ;)

**Comment by raphael** [comment]
PR #241 explains the intent behind this change. The idea is that your controller code should instantiate the correct data structure for the view. So instead of creating a `AccountInformation` and trying to map that to a `AccountInformationUserDescription` create a `AccountInformationUserDescription` in the first place.

I would like to understand if that makes sense or whether in your model it would be better to have a data structure that represents the media type as a whole then have generated code that can produce the view media types. In general that seems inefficient but maybe there are use cases where that makes sense. Can you describe where you get the data from? how do you build `AccountInformation`?

Remember that you have the context object and that you should be able to tell which view to render using it. So the code that produce the data structure should be able to tell which one to produce. If the way you do views is standard you could also have a middleware that sets an explicit field in the context (`view`) so that the controllers and downstream code can easily tell which data structure to create.

**Comment by KerwinKoo** [comment]
@raphael Thank you very much!

I build `AccountInformation` just for receiving HTTP request payload (included in context). In old version I created a middle structure to temporary store it.

#241 is very useful for me. And it made more clearly  by using structure instead of using dynamic marshaling code.

I using `ctx.OKViewName` instead of `ctx.OK` that write back into response status, it works again.

Thanks!

**Comment by raphael** [comment]
Glad you got it to work, closing this issue.
