### ISSUE TITLE
When add String value to Required attribute in body in html generated code check if string == nil and this not acceptable in go cause string have zero value 

### ISSUE THREAD

**Issue by Mohamed-Adel-H** [goadesign/goa#2491]
Design :

```  
var _ = Service("foo", func() {

	Method("bar", func() {

		Payload(func() {
			Field(1, "user-id", String, "User Id")
			Required("user-id")
		})

               HTTP(func() {
			POST("/)
			Body(func() {
				Attribute("user-id", String, "User Id")
				Required( "user-id")
			})
			Response(StatusOK)
		})

})
```

the generated code :  
```	
if body.UserID == nil {
   err = goa.MergeErrors(err, goa.MissingFieldError("user-id", "body"))
}
```

**Comment by raphael** [comment]
Thank you for the report, clearly a bug.

**Comment by raphael** [comment]
Looking at this a bit closer, I believe the design is not correct - hard to tell without the full example. Goa should not generate invalid code anyway so there's probably a check missing somewhere but here is a complete example that I believe achieves what you are trying to do and works:
```go
package design

import . "goa.design/goa/v3/dsl"

var _ = Service("foo", func() {
	Method("bar", func() {
		Payload(func() {
			Attribute("user-id", String)
			Required("user-id")
		})
		HTTP(func() {
			POST("/")
			Body("user-id")
			Response(StatusOK)
		})
	})
})
```
See https://goa.design/design/http_mapping/ for more information on how the `Payload` of a method and the body of a HTTP request relate.

**Comment by Mohamed-Adel-H** [comment]
I think the problem that I use ``` Required( "user-id") ``` in the Body

**Comment by raphael** [comment]
Yeah I think you are correct, the following reproduces the issue:
```go
package design

import . "goa.design/goa/v3/dsl"

var _ = Service("foo", func() {
	Method("bar", func() {
		Payload(func() {
			Attribute("user-id", String)
		})
		HTTP(func() {
			POST("/")
			Body("user-id", func() {
				Required("user-id")
			})
			Response(StatusOK)
		})
	})
})
```
I think the tool should validate that the requiredness of attributes defined in a body is the same as what it is in the payload.

**Comment by raphael** [comment]
I added some checks so that the tool fails when using something like the example above.
