### ISSUE TITLE
Missing documentation for using contexts in v3

### ISSUE THREAD

**Issue by baccenfutter** [goadesign/goa#2492]
I can find documentation for using contexts in v1
- https://goa.design/v1/implement/context/

but they are not listed in the topnav of the v3 page, leading me to believe that they are no longer valid or have changed. At least the `With` functions seem to have been changed.

From all the documentation available (incl. v1) it isn't clear to me as a reader how to pass the JWT user-id from the `JWTAuth(ctx context.Context, token string, scheme *security.JWTScheme) (context.Context, error)` function to the handler functions.

Could you please elaborate and perhaps provide some docs or at least add an example for this use-case to:
- https://github.com/goadesign/examples

**Comment by raphael** [comment]
Thank you for the example, looks great! The use of context in v2 and v3 has changed to follow a more idiomatic approach and to account for updates in the standard library (for example HTTP requests now have a context field which wasn't the case when Goa v1 was originally written). The result is much cleaner and lands itself to writing code that makes better use of contexts with less risk for abuse. That being said having more documentation around that would certainly be helpful. If you feel inspired feel free to add a page at https://github.com/goadesign/goa.design/tree/master/content/implement! I'd be happy to review/complement if needed and merge. Thanks again!
