### ISSUE TITLE
Getting cannot find module

### ISSUE THREAD

**Issue by continuum-dipanjan-mazumder** [goadesign/goa#2511]
Hi ,

while running the below commands getting error build _/Users/apple/calc/design/goa402781663: cannot find module for path _/Users/apple/calc/design/goa402781663

- Created a directory in $HOME/calc/design
- go mod init calc
- cd /calc/design
- created design.go with the mentioned code.
- ran goa gen . calc/design

Got error : "build _/Users/apple/calc/design/goa402781663: cannot find module for path _/Users/apple/calc/design/goa402781663"

What is the mistake here?

**Comment by raphael** [comment]
The argument to the `goa` tool is the module import path - not the file path. So in your case run `goa gen calc/design` in $HOME/calc,

**Comment by continuum-dipanjan-mazumder** [comment]
I did that as well still getting the same error ,ran the goa command from $HOME/calc still no luck

**Comment by continuum-dipanjan-mazumder** [comment]
Sorry now i am getting different error about the version of goa that v3 package not found
build calc/goa366162488: cannot load goa.design/goa/v3/codegen: module goa.design/goa/v3@latest found (v3.1.1), but does not contain package goa.design/goa/v3/codegen

**Comment by raphael** [comment]
I would try updating Goa:
```
cd $HOME/calc
go get -u goa.design/goa/v3/...@v3
```
