### ISSUE TITLE
"unused" Type not generated

### ISSUE THREAD

**Issue by leoquack** [goadesign/goa#2512]
If you don't use Type in Result, ArrayOf or MapOf the Type will not get generated. Not sure if this is a bug or I'm making a feature request. The following does not generate the TestType struct in /gen folder unless you use it directly in a Result() of a method, or if you reference it in ArrayOf like the commented Attribute

using v3.1.1

```go
var TestType = Type("TestType", func() {
	Attribute("name", String, "Some name")
})

var TestResultType = ResultType("application/vnd.test.result.type", func() {
	Reference(TestType)

	Attributes(func() {
		Attribute("name")
		// Attribute("many_names", ArrayOf(TestType), "With this, TestType gets generated")
	})
})
```

My fear is this is intended behavior, and we'll have to duplicate alot of structs or re-think the whole structure of our application. Bummer because we are trying to upgrade from v1 and the codebase is too big for that

**Comment by raphael** [comment]
This is indeed by design but the good people at Goa have your back, see https://pkg.go.dev/goa.design/goa/v3/dsl?tab=doc#Meta
