### ISSUE TITLE
Serialize custom types using their given name?

### ISSUE THREAD

**Issue by trestletech** [goadesign/goa#2518]
I had hoped that custom types would be JSON-serialized using their given name, rather than the internal name used in the Go struct.

e.g. in the example below, I was hoping that calling `json.Marshal(someCustomPayload)` would generate an object that includes a JSON attribute named `code.attr`. In practice, I find that it generates an object with an attribute named `CodeAttr`.

```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var CustomPayload = Type("CustomPayload", func() {
	Field(1, "code.attr", String, "My custom attribute")
})

var _ = API("calc", func() {
	Server("calc", func() {
		Host("localhost", func() {
			URI("http://localhost:8000")
		})
	})
})

var _ = Service("calc", func() {
	Method("add", func() {
		Payload(CustomPayload)

		Result(Int)

		HTTP(func() {
			GET("/add/")
		})
	})
})
```

in gen/calc/service.go:
```
// CustomPayload is the payload type of the calc service add method.
type CustomPayload struct {
	// My custom attribute
	CodeAttr *string
}
```

Would it be feasible to add a JSON tag (and perhaps XML and whatever else is appropriate) to the `CodeAttr` here to preserve the given name when it's serialized to/from JSON?

**Comment by raphael** [comment]
Hello, a few things here that may help:

1. The types used for serialization/deserialization are generated in the transport specific package. These types contain the tags you expect, see https://github.com/goadesign/examples/blob/master/cellar/gen/http/sommelier/server/types.go#L20 for example. In particular this means that the JSON representation of the types use the attribute names defined in the design. The types generated in the service layer are intended to be used for the business logic which in general shouldn't require serialization.

2. If there is a case where the business logic does require serialization then the [Meta](https://pkg.go.dev/goa.design/goa/v3@v3.1.1/dsl?tab=doc#Meta) expression makes it possible to define tags explicitly (search for 'struct:tag:xxx'). These tags get generated at all levels.

Hope this helps!

**Comment by trestletech** [comment]
Indeed it is! Thanks for the explanation. I must have been looking at the wrong thing, but I think I'm seeing the desired behavior in production right now. Disregard!
