### ISSUE TITLE
compilation errors in gen files, if used UInt64 field in http payload.

### ISSUE THREAD

**Issue by a-mahamuni** [goadesign/goa#2521]
var _ = Service("calc", func() {
        Description("The calc service performs operations on numbers.")
        Method("add", func() {
            Payload(func() {
	            Field(1, "some_field", UInt64, "some field", func() {
	                Example(10000)
	            })
	        })
	        Result(Int)
	        HTTP(func() {
	            GET("/add")
	            Body(Empty)
		    Param("some_field")
	        })
	    })
	    Files("/openapi.json", "./gen/http/openapi.json")
    })

After running `goa gen calc/design` I am getting following content in file `calc/gen/http/calc/client/cli.go`

    // BuildAddPayload builds the payload for the calc add endpoint from CLI flags.
    func BuildAddPayload(calcAddSomeField string) (*calc.AddPayload, error) {
	    var err error
	    var someField *uint64
	    {
		    if calcAddSomeField != "" {
			    val, err := strconv.ParseUint(calcAddSomeField, 10, 64)
			    someField = &val
			    if err != nil {
				    return nil, fmt.Errorf("invalid value for someField, must be UINT64")
			    }
		    }
	    }
	    payload := &calc.AddPayload{
		    SomeField: someField,
	    }
	    return payload, nil
    }

which would result in:
    ./cli.go:18:6: err declared and not used

I tried changing UInt64 to UInt and it seems to work, as it generates the following code:

    // BuildAddPayload builds the payload for the calc add endpoint from CLI flags.
    func BuildAddPayload(calcAddSomeField string) (*calc.AddPayload, error) {
	    var err error
	    var someField *uint
	    {
		    if calcAddSomeField != "" {
			    var v uint64
			    v, err = strconv.ParseUint(calcAddSomeField, 10, 64)
			    val := uint(v)
			    someField = &val
			    if err != nil {
				    return nil, fmt.Errorf("invalid value for someField, must be UINT")
			    }
		    }
	   }
	   payload := &calc.AddPayload{
		    SomeField: someField,
	    }
	    return payload, nil
    }

**Comment by raphael** [comment]
Thank you for the detailed report, this is a bug.

**Comment by raphael** [comment]
This is fixed in HEAD and will be fixed in v3.1.2 / v2.1.2.
