### ISSUE TITLE
Request encoder does not distinguish empty slice vs nil slice

### ISSUE THREAD

**Issue by lobocv** [goadesign/goa#2525]
Hi there, I have an Update API which accepts an optional `[]string{}` slice parameter.
However I noticed the generated code for the HTTP client cannot distinguish between an empty slice and a nil slice. After some digging I found that it is because the generated struct for the RequestBody sets the field with a `json:"unverified_employer_names,omitempty"` tag.
If i manually change the generated code to remote the omitempty, it then works. I can tell on the server side that an empty slice was passsed, rather than nothing being passed (nil).

Is there a way to turn off the omitempty tag for certain fields? 
Come to think of it, this means there is no way to pass an optional field that happens to be the zero value.

**Comment by raphael** [comment]
This is correct: there is no way to distinguish between an empty slice or no slice being provided in an optional request payload slice field. This limitation only applies to slices and maps, in particular for primitive types one can always distinguish between the default value (e.g. 0 for integers) and nil. 

The idea here is that either the slice field is required in which case it should contain at least one element or it isn't in which case being empty or not provided should result in the same behavior. Having an API that requires distinguishing between these two and behaves differently depending on whether an empty slice is provided or not is in general not great. In particular it is dependent on the transport marshaling, for example that distinction would not work with gRPC/protobuf.

An example that has come up a few times is the need to implement patch semantic where the presence of the slice vs an empty slice would translate to ignoring the field when patching vs replacing it with an empty slice. A workaround for this case is to make it explicit either via a completely different endpoint ("reset slice" whatever the specific semantic is) or an additional field in the payload (e.g. a boolean). The advantage is a clearer semantic to clients and an API that is agnostic of encoding.

With that being all said we had [discussed](https://github.com/goadesign/goa/issues/2221) the possibility to introduce a new DSL function `Zero` that would make it possible to define what value should be considered the "zero" value by Goa when decoding. This would also enable the use case here. Would be happy to help put together a PR that implemented this proposal.

**Comment by lobocv** [comment]
Thank you for the detailed response Raphael!
I have already implemented something similar to what you mentioned and used `[]string{""}` as an indicator for an empty slice (perhaps a separate field may be more clear though).
The `Zero` would be useful here but it's not urgent anymore. 
I mostly wanted to report it in case it was an unknown bug. 

Thank you again!
