### ISSUE TITLE
Adding trailing / in path server.go 

### ISSUE THREAD

**Issue by cocktailer** [goadesign/goa#2557]
![image](https://user-images.githubusercontent.com/45057114/81662776-afc3c900-945b-11ea-86af-28a11bc7b426.png)
 This is breaking my existing app. Why do we introducing "/" in the end 

@nitinmohan87 @raphael

**Comment by raphael** [comment]
@cocktailer is the "/" added or is it present in the design? https://github.com/goadesign/goa/pull/2530 fixed the fact that the slash wasn't generated even though it was set in the design. However it shouldn't be added if it wasn't. If it is added and not present in the design can you please post a small repro (a small but complete design we can use to generate the code)? Thank you!

**Comment by kumarsiva07** [comment]
https://github.com/goadesign/examples/blame/969cd694f76f4c169ba87711f743e7adafb97376/cellar/gen/http/storage/server/paths.go#L17
https://github.com/goadesign/examples/blob/969cd694f76f4c169ba87711f743e7adafb97376/cellar/gen/http/storage/server/server.go#L76

You can check in the examples. @raphael

**Comment by saniales** [comment]
As far as I know this is expected behavior if you set the path WITHOUT the / in the design

**Comment by cocktailer** [comment]
@saniales trailing / in /storage/ is not needed. Why are we adding the trailing / in path even though not added in design?

**Comment by raphael** [comment]
I see I missed the case where the path is just a slash. Seems we should handle this case specially and not add the trailing slash when the path is just `"/"`. @ikawaha do you agree?. You could still have a trailing slash by adding it to the base path:
```go
var _ = Service("base_path_no_trailing", func() {
    HTTP(func() { Path("foo") })
    Method("slash_with_base_path_no_trailing", func() {
        HTTP(func() { GET("/") })
    })
    Method("trailing_with_base_path_no_trailing", func() {
        HTTP(func() { POST("/bar/") })
    })
})
var _ = Service("base_path_with_trailing", func() {
    HTTP(func() { Path("foo/") })
    Method("slash_with_base_path_with_trailing", func() {
        HTTP(func() { GET("/") })
    })
})
var _ = Service("no_base_path", func() {
    Method("slash_no_base_path", func() {
        HTTP(func() { GET("/") })
    })
    Method("trailing_no_base_path", func() {
        HTTP(func() { POST("/foo/") })
    })
})
```
Would result in the paths:
```
slash_with_base_path_no_trailing: /foo --> ** the case that needs to change **
trailing_with_base_path_no_trailing: /foo/bar/
slash_with_base_path_with_trailing: /foo/
slash_no_base_path: /
trailing_no_base_path: /foo/
```
(in every case if the method defines a path that does not have a trailing slash then the resulting route would not have one either)

**Comment by ikawaha** [comment]
I agree. It seems to be a bug.
> slash_with_base_path_no_trailing: /foo --> ** the case that needs to change **

**Comment by ikawaha** [comment]
I may be mistaken in saying this is a bug.

When a base path is specified and a '/' is set to the endpoint, it seems better not to add a trailing slash, but you can't explicitly add a trailing slash to the base path.

I was reviewing the Goa v1 specs, and when using the base path as-is for an endpoint, I was specifying an empty string for the endpoint.  This may seem like a strange designation, but this may be a more reasonable way of doing things.

If you decide not to add trailing slash when '/' is set, you need a special symbol (e.g., '//') to specify that trailing slash should be given.

**Comment by kumarsiva07** [comment]
```
var _ = Service("base_path_no_trailing", func() {
    HTTP(func() { Path("foo") })
    Method("slash_with_base_path_no_trailing", func() {
        HTTP(func() { GET("/") })
    })
})
```


I am expecting a path like **"/foo"** for the above design. But I am getting **/foo/**. 
So I think this is a bug. @ikawaha

**Comment by ikawaha** [comment]
```
var _ = Service("base_path_no_trailing", func() {
    HTTP(func() { Path("foo") })
    Method("slash_with_base_path_no_trailing", func() {
        HTTP(func() { GET("") }) // ← 
    })
})
```
This design generate **/foo**. But, it looks odd to specify an empty string as an endpoint. This may be a spec issue and not a bug.

**Comment by kumarsiva07** [comment]
Do you think https://github.com/goadesign/examples/blob/v2/cellar/design/sommelier.go design also an issue?  So far we followed these kinds of design. @ikawaha @raphael

**Comment by raphael** [comment]
I think this issue can be closed. To summarize: if a relative path ends with `/` then it is preserved *except* in the case where the relative path is just `/`. In this case the slash is not added to the base path. The slash can be added by using `./` instead of `/`.
