### ISSUE TITLE
CBOR encoding support

### ISSUE THREAD

**Issue by saniales** [goadesign/goa#2558]
It is possible to add a CBOR encoder and decoder to the list of supported ones:

content-type : `application/cbor`

candidate library: https://github.com/fxamacker/cbor

**Comment by raphael** [comment]
I'm wondering how widely used CBOR is? (looks interesting but to be transparent I had not heard about it before reading this issue :) ). Goa lets you use any encoder/decoder by injecting them when building the transport server. Maybe this is better as an example? could be added to https://github.com/goadesign/examples/tree/master/encodings. I'm especially wary of adding additional dependencies to Goa.

**Comment by x448** [comment]
@raphael, [CBOR (RFC 7049)](https://tools.ietf.org/html/rfc7049) is an [IETF Internet Standard](https://en.wikipedia.org/wiki/Internet_Standard) (not just a regular RFC) and is used by other standards such as W3C WebAuthn, FIDO2 CTAP2, COSE, etc. 

Also, [CDDL (RFC 8610)](https://tools.ietf.org/html/rfc8610) was approved last summer and it can represent both CBOR and JSON data structures unambiguously.

CBOR is widely used for IoT.  [EdgeX Foundry](https://github.com/edgexfoundry) (a Linux Foundation project) uses Go and fxamacker/cbor.  EdgeX Foundry has active coders from Dell, Intel, and other companies.

CBOR is gaining popularity in blockchains and smart contracts.  E.g., [go-filecoin](https://github.com/filecoin-project/go-filecoin), [oasislabs](https://github.com/oasislabs/oasis-core), [chainlink](https://github.com/smartcontractkit/chainlink), etc. use Go and fxamacker/cbor.  This month, [cadence](https://github.com/onflow/cadence) (new project) switched from Go's gob to CBOR.

Unlike CBOR, Go's [gob doesn't always preserve values](https://play.golang.org/p/0drzUw8O6w) and it can't be fixed without breaking Go 1.x compatibility.  CBOR didn't exist when Go 1.0 was released.

CBOR was inspired by JSON, MsgPack, etc. and ["The format is designed for decades of use."](https://tools.ietf.org/html/rfc7049#page-4)

Later this year, IETF is expected to approve a [2nd edition](https://tools.ietf.org/html/draft-ietf-cbor-7049bis) (CBOR editorial update plus errata) which is backwards compatible.  fxamacker/cbor already includes 2nd edition recommendations.

**Comment by raphael** [comment]
Thank you for the additional input, good to learn more about CBOR. I've added an example that shows how to use CBOR in a Goa service. See the [README](https://github.com/goadesign/examples/blob/master/encodings/README.md) for details. The full extent of the implementation is in the file [encoding.go](https://github.com/goadesign/examples/blob/master/encodings/cbor/encoding.go). As you can see it's only a few lines of code and I think it's better to leave this out of the built-in Goa encoders and decoders so as to avoid adding a dependency on a external package. The [built-in Goa encoders and decoders](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L6-L8) only rely on the Go standard library.

**Comment by saniales** [comment]
I see, awesome, can we set this as closed, along with #2559 ? @raphael

**Comment by raphael** [comment]
I think so, closing both issues.
