### ISSUE TITLE
msgpack encoding support

### ISSUE THREAD

**Issue by saniales** [goadesign/goa#2559]
It is possible to add a msgpack encoder and decoder to the list of supported ones:

content-type : `application/msgpack`

candidate library: https://github.com/vmihailenco/msgpack

**Comment by raphael** [comment]
Same comment as #2558, maybe this is better done as an example rather that built-in support which adds a dependency to an external package to all users of Goa.

**Comment by raphael** [comment]
Added a CBOR custom encoder/decoder to the [encodings](https://github.com/goadesign/examples/blob/master/encodings/) example. The exact same pattern can be used for any encoding including msgpack. Thanks for raising the issue!
