### ISSUE TITLE
Validation for array of emails fails

### ISSUE THREAD

**Issue by cocktailer** [goadesign/goa#2561]
I am passing `["test@gmail.com"]` for the below format but i am getting error `message: "body.emails[*] must match the regexp "email" but got value "test@gmail.com""`
```
Attribute("emails", ArrayOf(String, func() {
		Pattern(FormatEmail)
	})
```

**Comment by raphael** [comment]
Please provide a complete design so we can reproduce the issue, thank you!

**Comment by raphael** [comment]
Re-reading this and just realized it should use `Format` instead of `Pattern`:

```go
Attribute("emails", ArrayOf(String, func() {
		Format(FormatEmail)
	})
```

`Pattern` is for validating using regular expressions while `Format` checks for known formats (see the [DSL docs](https://pkg.go.dev/goa.design/goa/v3/dsl?tab=doc#Format)).
