### ISSUE TITLE
How to read cookies?

### ISSUE THREAD

**Issue by mrcaelumn** [goadesign/goa#2562]
this is how I read cookies in v1

//controller file
key, err := ctx.Cookie("key-of-cookies")
if err == nil {
      query["key-of-cookies"] = []string{key.Value}
}

and for v3 I haven't figure out the way of read cookies
could you help me?

**Comment by richardbowden** [comment]
this is interesting, I have need to read, but also set them during auth process, looking for guidance  for v3 ?

**Comment by richardbowden** [comment]
@mrcaelumn I just noticed this PR :)

https://github.com/goadesign/goa/pull/2576

**Comment by raphael** [comment]
I just added native support for cookies in the Goa DSL :) As is always the case, the generated transport code can be wrapped / overridden to do anything HTTP specific including handling cookies however the PR makes it possible to map cookies explicitly in the design.

I also created an [example](https://github.com/goadesign/examples/tree/master/cookies) to illustrate usage.

Would be great if you could try it out @richardbowden!

**Comment by richardbowden** [comment]
@raphael wow, that was quick, and thanks, this is so cool.. I will defiantly test this today.

when you say transport code can be wrapped, are you referring to the generated code that would be in say gen/http/name_of_api/server/server.go, then you would wrap func NewHealthyHandler(... for example ?

**Comment by mrcaelumn** [comment]
> I just added native support for cookies in the Goa DSL :) As is always the case, the generated transport code can be wrapped / overridden to do anything HTTP specific including handling cookies however the PR makes it possible to map cookies explicitly in the design.
> 
> I also created an [example](https://github.com/goadesign/examples/tree/master/cookies) to illustrate usage.
> 
> Would be great if you could try it out @richardbowden!

thank you very much.
