### ISSUE TITLE
goa usage indicates --out is a flag, when it is not

### ISSUE THREAD

**Issue by kmacmcfarlane** [goadesign/goa#2569]
On goa version 3.1.3 running on Ubuntu, the goa gen help shows invalid usage.

Repro:
```
goa gen
```
```
Usage:
  goa gen PACKAGE [--out DIRECTORY] [--debug]
  goa example PACKAGE [--out DIRECTORY] [--debug]
  goa version

... etc
```

The `--out` flag doesn't seem to work for me, but `-o` and `-output` do, so the documentation probably just needs to be updated on those first two usage lines.

**Comment by raphael** [comment]
whoops, thanks for the catch!
