### ISSUE TITLE
Error formatter for gRPC

### ISSUE THREAD

**Issue by najeira** [goadesign/goa#2573]
Generated HTTP Server `New` accept `formatter func(err error) goahttp.Statuser`.

I want to use a similar formatter for gRPC, which handles error responses.

**Comment by raphael** [comment]
Hello, the format of the error in gRPC is not something that Goa controls, it is set by the gRPC standard. Are you asking about changing the error message content?

**Comment by najeira** [comment]
The error model provided by Google is as follows.

```
message Status {
  int32 code = 1;
  string message = 2;
  repeated google.protobuf.Any details = 3;
}
```

I would like to control the `details` myself.

**Comment by raphael** [comment]
Got it, makes sense.

**Comment by raphael** [comment]
OK so you can already use custom types for describing errors in gRPC, for example:
```go
package design

import . "goa.design/goa/v3/dsl"

var SomeError = Type("SomeError", func() {
        Field(1, "Name", String, "Name of error")
        Field(2, "Code", Int, "Code of error")
        // .... Anything
})

var _ = Service("service", func() {
        Method("method", func() {
                Error("some_error", SomeError)
                GRPC(func() {
                        Response("some_error", CodeInvalidArgument)
                })
        })
})
```
The content of the custom error type gets marshaled into the `details` field of the returned status.

Does this do what you need?

Edit: probably not as I'm guessing you need to encode the built-in validation errors differently...

**Comment by najeira** [comment]
Thank you so much for showing me the sample!

I think I can handle errors with a custom error.

BTW, I think it inconvenient that the custom error is generated as a separate type for each method, I will issue it as another issue.
