### ISSUE TITLE
follow on re cookies

### ISSUE THREAD

**Issue by richardbowden** [goadesign/goa#2589]
ref #2583 

hey, thanks for your quick turnarounds on the fixes, very much appreciated. I am trying to get up to speed with the goa codebase, its taking me a while though :(.

I am also available for testing before they are merged if that helps with the debug process ?

Functionality needs to be tweaked a little.

so overall this works great, you can login, set a cookie, it gets passed on the next call and it can be checked, if its not present that we get an error, all good stuff..

the one caveat is the when logging in (currently using basic auth)... this is where we set the cookie. However, if a user logs in again, who already has a cookie, we need to able to check if they have a cookie or if a cooke has been "" to invalidate it, if not we issue one, if they do have a cooke set already we want to just return and not issue another one.

adding this to Cookie("session_id:SID") to HTTP(func() { to allow us to read the cookie, now fails if it does not exist, which breaks login.

It would be great to have Cookie("session_id:SID") take a bool for optional, and if it does not exist, pass an empty string for the cookie.

does that make sense ? I have written this 3 times :)

Method("login", func() {
		Error("unauthorized", String, "Credentials are invalid")

		Security(BasicAuth)

		Payload(func() {
			//session_id here is to allow the login function to check if there is actually a token, then we compare to the token stored in the backend
			//if session_id is empty, then we login them in, setting the session token in the Result that is set below

			UsernameField(1, "email", String, "email address that was used to sign up for an account", func() {
				Example("joe@domain.com")
				//Format(FormatEmail)
			})

			PasswordField(2, "password", String, "password you used to sign up for an account", func() {
				Example("password")
			})

			Required("email", "password")

		})

		//for setting generated session token if this is a new loging, store in the backend
		Result(func() {
			Attribute("session_id", String, "Session ID")
			Attribute("message", String, "User message")
			Required("session_id", "message")
		})

		HTTP(func() {

			POST("login")

			//here to allow reading of the session token if present in the request
			Cookie("session_id:SID")

			Response(StatusCreated, func() {
				//here to allow setting of the session token
				Cookie("session_id:SID")
				CookieHTTPOnly()
				//CookieSecure()
				CookieMaxAge(3600)
			})

			Response("unauthorized", StatusUnauthorized)
		})
	})

**Comment by raphael** [comment]
Thanks for offering to debug prior to merging. It should work the way you expect (i.e. if the payload had a `session_id` attribute that was not required then you'd get a nil pointer if the cookie wasn't set). There is an issue with the code being generated where the standard library request `Cookie` method returns an error if the cookie is absent and the generic error checking code catches that and fails the request. Seems there should be an additional check where if the error is specifically `http.ErrNoCookie` then the request does not fail.

I have fixed a few issues in the DSL validation that was causing the `goa` tool to panic if the DSL was incorrect (i.e. the code above where the cookie attribute is missing from the payload definition). I'll work on doing the above, will create a PR and ask you to validate further on that branch - thanks!

PS: happy to answer any question wrt the Goa code itself as you learn it.

**Comment by richardbowden** [comment]
no worries...great stuff....I will keep an eye out for the branch and get testing.

oh and your correct, the example above was missing the `Attribute("session_id", String, "Session ID")`

Thanks for the kind offer to help re code, what's the best channel to talk about code ? I am compiling a list of questions as I walk though it

**Comment by raphael** [comment]
@richardbowden  I created the branch `cookies_for_realz` which contains a fix for the above, please give it a shot.

**Comment by richardbowden** [comment]
@raphael test and works perfectly

**Comment by raphael** [comment]
Thank you!
