### ISSUE TITLE
Invalid View Mapper Generated For Anonymous Child Attributes

### ISSUE THREAD

**Issue by kmacmcfarlane** [goadesign/goa#2592]
go version: 1.14.3
goa version: v3.1.3 (I checked my go.sum file, and it is actually pulling this version in to my project as well)

I am trying to define some anonymous child attribute types to avoid making a few one-off type definitions, and I think I uncovered a bug. If instead of using an anonymous inner type in the attribute definition, and just use a type I define with `Type("something", func() { etc }` then it works as expected and doesn't generate errors (which is the way I'll go with it for now).

First, here's my simple repro scenario:

Service definition:
```
package goa

import (
	. "goa.design/goa/v3/dsl"
)

var _ = Service("repro", func() {
	Method("DoIt", func() {
		Result(result)
		HTTP(func() {
			POST("/repro")
			Response(StatusOK)
		})
	})
})

var result = ResultType("application/vnd.config.reproResult", func() {
	TypeName("ReproResult")

	Attribute("parent", func() {
		Attribute("child", String)
		Required("child")
	})
})
```

API definition:
```
package goa

import (
	. "goa.design/goa/v3/dsl"
)

var _ = API("ReproAPI", func(){
	Version("1.0.0")

	Server("Repro Server", func() {
		Services("repro")
		Host("localhost", func() { URI("http://localhost/")})
	})
})
```

When I run `goa gen` then `go vet ./...` then I get the following error:
```
# pathstuffhere/pkg/gen/repro
pkg/gen/repro/service.go:73:15: cannot use &struct { Child string } literal (type *struct { Child string }) as type *struct { Child *string } in assignment
pkg/gen/repro/service.go:76:4: cannot use &res.Parent.Child (type *string) as type string in field value
```

The generated code, indeed, seems not to be assigning to the anonymous struct type correctly in `gen/repro/service.go`:
```
// newReproResultView projects result type ReproResult to projected type
// ReproResultView using the "default" view.
func newReproResultView(res *ReproResult) *reproviews.ReproResultView {
	vres := &reproviews.ReproResultView{}
	if res.Parent != nil {
		vres.Parent = &struct {
			Child string
		}{
			Child: &res.Parent.Child,
		}
	}
	return vres
}
```

Note, if I remove the `Required` directive from the inner-most `child` attribute, then re-generation and running `go vet` yields a new problem with the generated code:
```
# somepath/pkg/gen/http/repro/server
vet: pkg/gen/http/repro/server/types.go:29:17: cannot use &(struct{Child *string} literal) (value of type *struct{Child *string}) as *struct{Child *string "form:\"child,omitempty\" json:\"child,omitempty\" xml:\"child,omitempty\""} value in assignment
# somepath/pkg/gen/http/cli/repro_server
vet: pkg/gen/http/cli/repro_server/cli.go:264:9: undeclared name: attributec
```

The generated code in this case in gen/repro/server/types.go:
```
// NewDoItResponseBody builds the HTTP response body from the result of the
// "DoIt" endpoint of the "repro" service.
func NewDoItResponseBody(res *reproviews.ReproResultView) *DoItResponseBody {
	body := &DoItResponseBody{}
	if res.Parent != nil {
		body.Parent = &struct {
			Child *string
		}{
			Child: res.Parent.Child,
		}
	}
	return body
}
```

Explicitly adding a default view to the result type also results in some problems:
```
	View("default", func() {
		Attribute("parent")
	})
```

generated output causes `go vet` errors:
```
pkg/gen/repro/service.go:73:15: cannot use &struct { Child string } literal (type *struct { Child string }) as type *struct { Child *string } in assignment
pkg/gen/repro/service.go:76:4: cannot use &res.Parent.Child (type *string) as type string in field value
```

**Comment by raphael** [comment]
@kmacmcfarlane thank you for the detailed report. I am working on a fix on the branch `fix_inline_object_results`. Can you please this branch a shot? Will merge PR #2593 once this branch works as expected. Thanks!

**Comment by kmacmcfarlane** [comment]
@raphael Thanks for the quick turnaround! Sorry it took me a few days to look at, I've been under the weather. I tried out the new version, and it looks like your changes have resolved the issue.

**Comment by raphael** [comment]
Thank you for verifying, PR merged!
