### ISSUE TITLE
How to get Header, URL Param, Dynamic Body in design

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#2599]
URL is  /events/{uuid}

```
[
    {
        "Dynamic1": "djfsd",
        "Dynamic2": "15379002020012999"
    }
]
```
I need Content-Type header also.
@raphael

**Comment by richardbowden** [comment]
To access headers you use http middleware

see section Transport Middleware, HTTP Middleware at this link https://goa.design/implement/middleware/ you have access to the raw request and response where you can read the headers, if you need to use them in your endpoint, then you add the content you require to the context.

url params etc, check out this link for an example of a payload and url params https://goa.design/learn/getting-started/ under the Design section.
