### ISSUE TITLE
Client returns error "failed to decode response body" when SkipResponseBodyEncodeDecode is set in the design document.

### ISSUE THREAD

**Issue by annsherinabraham** [goadesign/goa#2602]
Scenario:
1. There's an endpoint that can return error.
2. Make a bad request to the endpoint through the goa client .

Expected result:
The client receives the Bad request error

Observed Result:
The client receives an error (failed to decode response body)

On debugging, it appears that when SkipResponseBodyEncodeDecode is set, the generated client is creating a decoding error which states "failed to decode response body"  if there's an error returned by decodeResponse method. Ideally this error shouldn't be checked and just passed on. 

This is masking the actual error returned by the server.

**Comment by raphael** [comment]
Thank you for the report, this does seem to be a bug.

**Comment by raphael** [comment]
Can you please post a design that reproduces the issue here? thank you.

**Comment by annsherinabraham** [comment]
Sure, here's a design that will reproduce the bug.
`Method("Endpoint", func() {
		Payload(payload)
		Result(func() {
			Attribute("contentDisposition", String)
			Required("contentDisposition")
		})

		HTTP(func() {
			GET("/load/xls/")

			// Bypass response body encoder code generation to alleviate need for
			// loading the entire response body in memory.
			SkipResponseBodyEncodeDecode()

  			Params(func() {
				Param(params)
			})
			Response(StatusOK, func() {
				ContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
				Header("contentDisposition:Content-Disposition")
			})
		})
	})`

**Comment by annsherinabraham** [comment]
Sure, please find it below:

Method("Endpoint", func() {
		Payload(payload)
		Result(func() {
			Attribute("contentDisposition", String)
			Required("contentDisposition")
		})
		HTTP(func() {
			GET("/load/xls/")
			// Bypass response body encoder code generation to alleviate need for
			// loading the entire response body in memory.
			SkipResponseBodyEncodeDecode()
  			Params(func() {
				Param(params)
			})
			Response(StatusOK, func() {
				ContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
				Header("contentDisposition:Content-Disposition")
			})
		})
	})

**Comment by raphael** [comment]
Thank you for the report, this is now fixed.
