### ISSUE TITLE
A UserTypeDefinition with no Type set will cause a panic in goagen

### ISSUE THREAD

**Issue by bketelsen** [goadesign/goa#261]
in finalizeExample.go line 149, the Type is checked, but may be null if you've erroneously forgotten to set a type on your UTD.

**Comment by raphael** [comment]
In theory a type-less UTD shouldn't validate so should never be finalized. There's a lot of other code that relies on that so I'm not sure protecting in this one case makes a lot of sense. Could you describe a bit more how you got into this situation?

**Comment by dominicm** [comment]
@bketelsen Did PR https://github.com/goadesign/goa/pull/282 resolve this issue?
