### ISSUE TITLE
Error while attempting to install: unrecognized import path "goa.design/goa/v3/..."

### ISSUE THREAD

**Issue by Va1** [goadesign/goa#2611]
Hi guys,

We were using Goa at specific version (3.0.6) and since few hours ago we can not install it anymore. That's how we're doing it:
```
GO111MODULE=on go get goa.design/goa/v3@v3.0.6
```
```
go get goa.design/goa/v3@v3.0.6: unrecognized import path "goa.design/goa/v3" (parse https://goa.design/goa/v3?go-get=1: no go-import meta tags ())
```

We were thinking the issue is about us using older version, but doing the following (copied from readme, supposedly installs version 3.2.0) produces the same result:
```
GO111MODULE=on go get -u goa.design/goa/v3/...@v3
```
```
go get goa.design/goa/v3/...@v3: unrecognized import path "goa.design/goa/v3/..." (parse https://goa.design/goa/v3/...?go-get=1: no go-import meta tags ())
```

By the link `https://goa.design/goa/v3?go-get=1` there's indeed nothing now (404).

Our environment:
```
go version go1.12.9 darwin/amd64 
```

Please, help. It seems that the issue is due to some change on your side, but we're failing to understand so far.

Regards

**Comment by raphael** [comment]
There was a temporary problem with the origin (goa.design) that has been resolved now.

**Comment by Va1** [comment]
cool, it does work indeed. thank you
