### ISSUE TITLE
Example models in generated openapi documentation do not use "struct:tag:json" fields from annotations. Field names from struct used instead

### ISSUE THREAD

**Issue by mikhail-eremin** [goadesign/goa#2612]
For example, if I create type
```
var Company = Type("Company", func() {
	Attribute("CompanyName", String, func() {
		Meta("struct:tag:json", "name")
	})
})
```

And use this type as a payload in some method, e.g.
```
Method("CreateCompany", func() {
		Payload(func() {
			Field(1, "company", Company, "Company info")
			Required("company")
		})
	})
```
Example payload in openapi will look like
```
{
  "company": {
    "CompanyName": "Expedita debitis.",
  }
}
```
Whereas correct one is
```
{
  "company": {
    "name": "Expedita debitis.",
  }
}
```

Same behavior for example responses, json annotations are not taken into account, struct field names used in openapi documentation examples

**Comment by raphael** [comment]
What should be the behavior if an attribute has both "struct:tag:json" and "struct:tag:xml" metadata with different values? Or uses different encodings and only has "struct:tag:json" defined? Then generated OpenAPI spec wouldn't be correct either in these cases. Maybe we need a new Meta key to override the name used in OpenAPI specs.

**Comment by mikhail-eremin** [comment]
Hi, @raphael , thank you for the quick reply!
I didn't think from this perspective, as I don't see much real world examples when people are using XML apis :)
Just now I looked precisely to what is generated in openapi documentation, and this is what I see (example from my project, json fields in examples should be lowercased because I use struct:tag:json to override default keys which are uppercased)
```
...
"requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCandidateTokenRequestBody"
              },
              "example": {
                "candidate": {
                  "BusinessName": "Delectus dolore quia vero earum.",
                  "Email": "Rerum et ipsam facere enim ipsa et.",
                  "HasDigitalSignature": false,
                  "Name": "Culpa sunt ducimus expedita debitis dolorem velit."
                }
              }
            }
          }
        },
...
```
As far as I can see these exact examples are generated under "application/json" section, so it has separate presentation, and I think using json keys names from struct:tag:json meta is safe here, without extra meta, please correct me if I am missing something

P.S.  I show just payload example, responses examples are under "application/json" section too, and they have same structure, so same thing applies for responses

Thank you!

**Comment by raphael** [comment]
Ah yes that's a good point, OpenAPI v3 introduced that scoping. I think you're right that the name specified in the metadata should be used in this case.

**Comment by raphael** [comment]
Just a note that I did take a look at what it would take to implement support for this and it ended up being a bit complicated because we can't simply assume that the mime type is always JSON. We have to introduce another layer of abstraction that allows for different field name encodings depending on the mime type. I'd be happy to merge a PR that did that.
