### ISSUE TITLE
Using Multiple View of a ResultType in other ResultType returns incorrect response

### ISSUE THREAD

**Issue by sm43** [goadesign/goa#2613]
I have an example created [here](https://github.com/SM43/user-goa).
If you run the service and call `/user` API which returns `User` ResultType.
In [`User`](https://github.com/SM43/user-goa/blob/791d4f9650ce6e508243d5f134dee98fbdc371c0/design/type.go#L27), there are 2 `Attribute`, `latestCompany` &  `companies`.
In response to API, both should return `tiny` and `default` view of [`Company`](https://github.com/SM43/user-goa/blob/791d4f9650ce6e508243d5f134dee98fbdc371c0/design/type.go#L7). 
But returns the same view whichever is mentioned first.

**Comment by raphael** [comment]
Thank you this is now fixed.
