### ISSUE TITLE
OpenAPI 3.0 generation doesn't include schemas for servers

### ISSUE THREAD

**Issue by jerejones** [goadesign/goa#2619]
Given an api spec with the following:

```
Server("httpd", func() {
	Host("local", func() {
		URI("http://localhost")
	})
	Host("development", func() {
		URI("https://dev.mywebsite.tv")
	})
	Host("production", func() {
		URI("https://mywebsite.tv")
	})
})
```

The yaml output includes the following:

```
servers:
- url: localhost
- url: dev.mywebsite.tv
- url: mywebsite.tv
```

When using SwaggerUI, this causes the host used for making the api calls to be `localhostlocalhost` or `dev.mywebsite.tvlocalhost` or `mywebsite.tvlocalhost` (depending on the server selection).

Adding the schema to the servers section makes SwaggerUI work correctly. 

Ideally, the generated openapi3.yaml would include the following instead:

```
servers:
- url: http://localhost
- url: https://dev.mywebsite.tv
- url: https://mywebsite.tv
```

**Comment by jerejones** [comment]
I submitted a PR to handle this: https://github.com/goadesign/goa/pull/2621

**Comment by raphael** [comment]
Thank you for the clear report and the PR! I've merged the PR into the `v3` branch, would appreciate if you could also create a PR for the `v2` branch.

**Comment by jerejones** [comment]
Done.  I had issues getting unrelated unit tests to pass.  Hopefully, they pass in CI

**Comment by jerejones** [comment]
It would appear that I can not do a v2 PR as I can't get that branch to build locally or pass test locally.  And the tests that pass locally don't pass in CI.

The change itself is pretty simple.  Simply change `u.Host` to `u.String()` on line 400 of http/codegen/openapi/v3/builder.go

**Comment by raphael** [comment]
Fix has been merged in the `v2` branch.
