### ISSUE TITLE
POST request body should not be required when all attributes in it are optional

### ISSUE THREAD

**Issue by jimmy-ho** [goadesign/goa#2623]
A POST method's request body is currently required even when the attributes in it are optional. 

I have a use case where I have mapped most attributes as params, except for one that should be in the request body.

I have not marked this attribute as required, nor want it as a param cause the size can be big, but goa has still made the request body as required, meaning if I send an empty request body I get a missing required payload error.

The attribute in the request body is optional, requiring the need to send an empty JSON body which is odd behaviour.

Ideal fix is that the POST request body is not required if none of the attributes are required.

**Comment by raphael** [comment]
PR #2642 adds the ability to send empty HTTP request bodies when the request body type is defined using an optional payload attribute (and only in this case).

**Comment by raphael** [comment]
Change above released in v3.2.1.

**Comment by jtepe** [comment]
Sorry, but I fail to see where this feature is documented.
From what I can see in the code, I'd need to specify the request body like this
```go
Method("create", func() {
    Payload(func() {
        Attribute("foo", String)  // Not required or mapped to param
    })

    HTTP(func() {
        POST("/")
        Body("foo") // foo is not required, so this makes the body optional?
        Response(StatusCreated)
    })
})
```
Is this correct? @raphael

**Comment by t-morisawa** [comment]
The same thing happens in my environment.
(If I make a request with an empty request body in Body, it returns "missing required payload").

~Could the following modifications work?~
https://github.com/goadesign/goa/blob/v3/http/codegen/service_data.go#L1109

```
-					if !payload.IsRequired(o[0]) {
+					if payload.IsRequired(o[0]) {
```

This was a mistake. Sorry. However, request n the expected format does not work, so please let me reopen the issue after a little more research.

**Comment by felius-frank** [comment]
> The same thing happens in my environment. (If I make a request with an empty request body in Body, it returns "missing required payload").
> 

Hey Morisawa-san!

You can just write a handler to transform the empty body to a json empty body and add the handler. In the code, I assume it is a json body.
```
package middleware

import (
	"io"
	"net/http"
	"strings"
)

// Write and empty body "{}" when no body is passed in a post
func FixEmptyPostBody(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.ContentLength == 0 && r.Method == "POST" {
			r.Body = io.NopCloser(strings.NewReader("{}"))
		}
	})
}
```

Then add the handler to goa muxer : handler = internalmw.FixEmptyPostBody(handler).
I think this way is fair, because POST definition requires a body, and an empty body for application/json is "{}". So fixing an incorrect client case in the GOA framework feels wrong.
