### ISSUE TITLE
v3 Grpc capitalization incorrect after a number

### ISSUE THREAD

**Issue by oralordos** [goadesign/goa#2641]
When a method has a number and then some letters, grpc will capitalize the first letter after the number, but goa will expect it to be lower case.

```golang
package design

import . "goa.design/goa/v3/dsl"

var _ = API("grpc-spelling", func() {})

var _ = Service("test", func() {
	Method("clean-2fa", func() {
		GRPC(func() {})
	})
})
```

This design will generate a `test.pb.go` with a struct called `Clean2FaRequest`, but the rest of the grpc code will expect a struct called `Clean2faRequest`

**Comment by raphael** [comment]
Thank you for the report and nice repro, this is fixed in v3.2.1.
