### ISSUE TITLE
v3 Using tags and complicated types in a response tries to use pointers

### ISSUE THREAD

**Issue by oralordos** [goadesign/goa#2655]
When writing an http response that has multiple responses based on a tag, if one of the responses uses a sub-field that is a struct from a type, the generated code will try to get pointers of the fields, despite the requirement for values.
```golang
package design

import . "goa.design/goa/v3/dsl"

var _ = API("multi-response", func() {})

var Data = Type("data", func() {
	Attribute("id", Int64)
	Attribute("name", String)
	Required("id", "name")
})

var _ = Service("test", func() {
	Method("multi", func() {
		Result(func() {
			Attribute("tag", String)
			Attribute("body", Data)
			Required("tag")
		})

		HTTP(func() {
			GET("/")
			Response(StatusOK, func() {
				Tag("tag", "data")
				Body("body")
			})
			Response(StatusNoContent, func() {
				Body(Empty)
			})
		})
	})
})
```
The above design will have the error in the `NewMultiOKResponseBody` function in `gen/http/test/server/types.go`

**Comment by raphael** [comment]
Thank you for the report and the repro, #2658 fixes this issue.
