### ISSUE TITLE
v3 Having a single optional integer parameter has an unused err variable

### ISSUE THREAD

**Issue by oralordos** [goadesign/goa#2656]
When a method has an integer or other type that requires parsing from a string, and is optional, and comes from a param field, the generated code to create the payload will have an err variable that is unused. The err will be shadowed by a `:=` inside an if statement.
```golang
package design

import . "goa.design/goa/v3/dsl"

var _ = API("optional-int-param", func() {})

var _ = Service("test", func() {
	Method("param", func() {
		Payload(func() {
			Attribute("id", Int64)
		})

		HTTP(func() {
			GET("/")
			Param("id")
			Response(StatusNoContent)
		})
	})
})
```
The above design will have the error in the `BuildParamPayload` function in `gen/http/test/client/cli.go`

**Comment by raphael** [comment]
Thanks for the report and repro, this is fixed by #2662
