### ISSUE TITLE
Data type of method output declared twice

### ISSUE THREAD

**Issue by sevein** [goadesign/goa#2657]
I am seeing the following build issue in goa-generated code since I upgraded to v3.2.1:

```# github.com/sevein/goademo/api/gen/demo
api/gen/demo/service.go:59:6: GoademoStoredDemo redeclared in this block
	previous declaration at api/gen/demo/service.go:40:6
##[error]Process completed with exit code 2.
```

See [build output](https://github.com/sevein/goademo/runs/980198285) for more details.

I have set up a repository where the issue can be reproduced consistently: https://github.com/sevein/goademo.

**Comment by raphael** [comment]
Thanks for the report and the nice repro. This is fixed in #2660.
