### ISSUE TITLE
v3 Optional Param with validation generates unused err variable

### ISSUE THREAD

**Issue by oralordos** [goadesign/goa#2668]
Goa v3.2.3

When a query parameter with a validation that is not required is the only payload, a function is generated with an err that is not used. Related to #2656

```go
package design

import . "goa.design/goa/v3/dsl"

var _ = API("api", func() {})

var _ = Service("param", func() {
	Method("retrieve", func() {
		Payload(func() {
			Attribute("id", Int64, func() {
				Minimum(1)
			})
		})

		HTTP(func() {
			GET("")
			Param("id")
		})
	})
})
```

This design generates the bad function in `gen/http/param/client/cli.go`

**Comment by raphael** [comment]
Thank you for the report and repro, this is now fixed.
