### ISSUE TITLE
Accessing API using CLI gives incorrect result when ResultType has multiple views

### ISSUE THREAD

**Issue by sm43** [goadesign/goa#2671]
I have an example [here](https://github.com/SM43/user-goa).
If you run the service and invoke the API using CLI.
```
./user-cli user get
```
this returns response
```
{
    "ID": 1,
    "Name": "abc",
    "LatestCompany": {
        "ID": 0,
        "Name": "Redhat",
        "Location": ""
    },
    "Companies": [
        {
            "ID": 1,
            "Name": "Symantec",
            "Location": "India"
        },
        {
            "ID": 2,
            "Name": "Red Hat",
            "Location": "India"
        }
    ]
}
```
Here, view used for  `LatestCompany` is `tiny` which is supposed to return only `Name` but it returns all fields.

I am currently using goa in one other project where if the value for other fields are not defined then it breaks the API and returns
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78b3db]
```

I think this is similar to #2613. 
 
@raphael

**Comment by raphael** [comment]
Thank you for the report! This behavior is a result of the design behind views and what the generated CLI does. A view defines which fields in the result struct to initialize and validate but there is still a single type defined for the method result. The CLI prints the service method level result which has these fields defined. The generated code takes care of validating that fields present in a view definition (and only these) have valid values. So TL;DR the JSON serialized by the server is as you would expect:
```json
{
    "companies": [
        {
            "id": 1,
            "location": "India",
            "name": "Symantec"
        },
        {
            "id": 2,
            "location": "India",
            "name": "Red Hat"
        }
    ],
    "id": 1,
    "latestCompany": {
        "name": "Redhat"
    },
    "name": "abc"
}
```
This JSON gets unmarshaled into the result type by the client code which is what the CLI prints. Hopes that make sense.

**Comment by sm43** [comment]
@raphael Thanks for the explanation. :)
But I am getting another issue which is 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77205b]

goroutine 1 [running]:
github.com/sm43/user-goa/gen/http/user/client.unmarshalCompanyResponseBodyToUserviewsCompanyView(...)
	/home/smukhade/go/src/github.com/sm43/user-goa/gen/http/user/client/encode_decode.go:83
github.com/sm43/user-goa/gen/http/user/client.NewGetUserOK(0xc000012090, 0x7991c0)
	/home/smukhade/go/src/github.com/sm43/user-goa/gen/http/user/client/types.go:45 +0x8b
github.com/sm43/user-goa/gen/http/user/client.DecodeGetResponse.func1(0xc000076000, 0x0, 0x0, 0x0, 0x0)
	/home/smukhade/go/src/github.com/sm43/user-goa/gen/http/user/client/encode_decode.go:64 +0x2e9
github.com/sm43/user-goa/gen/http/user/client.(*Client).Get.func1(0x8c3ec0, 0xc0000a0000, 0x0, 0x0, 0x1e, 0x0, 0xc0000aac00, 0x0)
	/home/smukhade/go/src/github.com/sm43/user-goa/gen/http/user/client/client.go:67 +0x120
main.main()
	/home/smukhade/go/src/github.com/sm43/user-goa/cmd/user-cli/main.go:82 +0x53f

```
This is similar to what I am getting in another project.
I tried to recreate this in the example I shared with you. you can take a look [here](https://github.com/SM43/user-goa).
So, there are 3 cases I have created, the [3rd](https://github.com/SM43/user-goa/blob/39231b9548e65313a056af28009368814b20e217/user.go#L53) one seems to be breaking.  
HTTP response are correct but in CLI it breaks.

**Comment by raphael** [comment]
The above is clearly a bug, thank you for putting together a repro. Would you mind creating a new issue for the panic? thank you.

**Comment by sm43** [comment]
Created a Issue #2681
