### ISSUE TITLE
CORS not working for grpc methods

### ISSUE THREAD

**Issue by SantoshSah** [goadesign/goa#2675]
While generating code by `goa gen`, CORS /OPTIONS is not being mounted for gRPC methods. Actually CORS is not needed when methods are consumed in non browser clients but it needed while consuming in browser via [gRPC-Web](https://grpc.io/docs/languages/web/). It will be nice a feature to support OPTIONS method for gRPC end points.

**Comment by raphael** [comment]
Makes sense, this request is really for the [CORS plugin](https://github.com/goadesign/plugins/tree/v3/cors) (not something built directly into Goa). Happy to consider a PR that would add that to the plugin. Closing this issue here, please open it in the plugins repo, thank you!
