### ISSUE TITLE
Invalid code generation when multiple APIs use different views of a result type 

### ISSUE THREAD

**Issue by sm43** [goadesign/goa#2692]
I have an example created [here](https://github.com/SM43/user-goa/tree/view). Use the `view` branch of the repository.

I have 2 APIs defined in the [design](https://github.com/SM43/user-goa/blob/view/design/api.go). 
For both APIs, Result has the same ResultType `User` but with different views. 

API  `/user2` has `v1` view of `User`  &
API  `/user` has `default` view of `User`

When the code is generated, both are generated with the same view (v1).
This can be seen [here](https://github.com/SM43/user-goa/blob/072281b30e6094b90487ebeab9b208a2336d004b/gen/user/endpoints.go#L38). 

`NewGet2Endpoint` & `NewGetEndpoint` both have `NewViewedUser(res, "v1")`.

If the method [`get2`](https://github.com/SM43/user-goa/blob/072281b30e6094b90487ebeab9b208a2336d004b/design/api.go#L20) is moved after [`get`](https://github.com/SM43/user-goa/blob/072281b30e6094b90487ebeab9b208a2336d004b/design/api.go#L32). then the output is correct but the code generation is not.

The order of methods seems to be affecting the code generation. 

cc @raphael

**Comment by raphael** [comment]
Thank you for the report, this is now fixed.
