### ISSUE TITLE
Enhancement: Meta field to indicate a non-pointer field should be created for optional values

### ISSUE THREAD

**Issue by silverspace** [goadesign/goa#2695]
Hello,

I am interested in adding a new Meta field to indicate that we don't want a pointer field to be created for optional (non-required) values.

The motivation for this enhancement is supporting a PATCH endpoint that can differentiate between omitted fields and explicit `null` values for optional fields. See https://github.com/goadesign/goa/issues/2525#issuecomment-612512450 

Would you be open to a PR that adds a new `Meta` field for specifying that we don't want an optional field to be a pointer? For example: 
```
	Attribute("id", String, "ID of the resource", func() {
		Example("1234")
		Meta("struct:field:type", "null.String", "github.com/guregu/null")
		Meta("struct:field:pointer", "false")
	})
```

Thanks!

**Comment by raphael** [comment]
I would be open to it but fair warning this change is touching on a lot of different areas and has some pretty deep ramifications :) (server and client side, validations, marshalling and unmarshaling in HTTP vs gRPC etc.).
