### ISSUE TITLE
How to close the file server directory preview?

### ISSUE THREAD

**Issue by ldd27** [goadesign/goa#2713]
```
goa: v3.2.5
```
```
var _ = Service("Static", func() {
	Files("/static/{*filepath}", "./static/")
})
```

![image](https://user-images.githubusercontent.com/11850305/99019830-32a71700-2598-11eb-95d6-71781bb6f206.png)

**Comment by raphael** [comment]
Just making sure I understand the ask: do you need to return 404 for example instead of a listing of files of a given directory?

**Comment by ldd27** [comment]
Yes, I want to return 404 when I visit `http://localhost:30000/sn/static`

**Comment by raphael** [comment]
The file server implementation of Go does not support this built-in but it should be possible to write a HTTP middleware that does the check prior to the request being handled by it. Something like (I did not verify this code works :) ):
```go
// Forbid listing of given paths.
func ForbidListing(paths []string) func(http.Handler) http.Handler {
	return func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                        for _, p := range paths {
			        if strings.HasSuffix(r.URL.Path, p) {
                                    w.WriteHeader(http.StatusNotFound)
                                    return
                                }
                        }
                        h(w, r)
                }
       }
}
```
You can then "mount" the middleware as is done in the example generated code https://github.com/goadesign/examples/blob/master/basic/cmd/calc/http.go#L69-L73 so it would look something like:
```go
paths := // .... initialize paths
var handler http.Handler = mux
{
	handler = httpmdlwr.Log(adapter)(handler)
	handler = httpmdlwr.RequestID()(handler)
	handler = ForbidtListing(paths)(handler)
}
```
