### ISSUE TITLE
Customize basic validation errors

### ISSUE THREAD

**Issue by CDimonaco** [goadesign/goa#2718]
Hi all,

I'm currently trying to customize a predefined error, in particular the 
`InvalidLengthError`, I defined in my design file, the attribute in this way

```
Attribute("stuff", ArrayOf(StuffPayload), "The array of stuff", func() {
    MinLength(1)
})
```

The validation works, but I want to customize the error message, I saw the generated code part for this validation, and it's like 

```
if len(body.Stuff) < 1 {
	err = goa.MergeErrors(err, goa.InvalidLengthError("body.stuff", body.Stuff, len(body.Stuff), 1, true))
}
```

Is it possibile, in the current implementation to customize the message returned by this type of error, for the particular field or globally? Without of course modifying the auto generated code?

Thanks in advance :D

**Comment by raphael** [comment]
It is possible to provide an error "formatter" function when instantiating a generated HTTP handler or server (see [example](https://github.com/goadesign/examples/blob/43586fa90e05613de7413ac9fbb1720109d4b883/basic/gen/http/calc/server/server.go#L55)). The function is called prior to writing the response body and can thus override the [default](https://github.com/goadesign/goa/blob/5bc7dd952dc9bcdb941265a0044ec23c8fd07a2b/http/error.go#L38-L50).

**Comment by CDimonaco** [comment]
Thanks for your answer, but I need to modify the generated code, and this
not seems the most maintainable option..

Is in plan to add something like this in the dsl part of goa? The project
is open to contribution like this?

Il dom 22 nov 2020, 00:17 Raphael Simon <notifications@github.com> ha
scritto:

**Comment by raphael** [comment]
There is no need to modify the code generated by `goa gen`, the `formatter` argument is given to it by your code (you do need to change the default example generated by `goa example` but that is expected - this is why it is a different command). Happy to discuss alternatives but this ought to work for your use case, see https://goa.design/implement/error_handling/ (the bottom of the page).

**Comment by CDimonaco** [comment]
Thanks to all for the responses.

I will use the suggested approach :D
