### ISSUE TITLE
v3: Type error occurs in the generated code if defining ArrayOf query parameter

### ISSUE THREAD

**Issue by ayanamizuta** [goadesign/goa#2721]
Hello! Thanks for making and maintaining this powerful tool!
However, I had slight trouble in generated code.

# What I did
try to generate API spec for a design like this
```go
package design

import . "goa.design/goa/v3/dsl"

// API describes the global properties of the API server.
var _ = API("calc", func() {
    Title("Calculator Service")
    Description("HTTP service for adding numbers, a goa teaser")
    Server("calc", func() {
        Host("localhost", func() { URI("http://localhost:8088") })
    })
})

// Service describes a service
var _ = Service("calc", func() {
    Description("The calc service performs operations on numbers")
    // Method describes a service method (endpoint)

    Method("test", func() {
        Description("test")
        Payload(ArrayOf(UInt), func() {
            Description("test")
            Example([]uint{1, 2, 3})
        })

        Result(Empty)

        HTTP(func() {
            GET("/test")
            Param("id")
        })
    })
})
```

and generated some codes by `goa gen` and `goa example`, then did `go run ./cmd/calc`, the response was
```
gen/http/calc/server/encode_decode.go:39:5: not enough arguments to return
        have (error)
        want (interface {}, error)
```

# How I investigated
debug by [delve](https://github.com/go-delve/delve), and checked the when the code will be generated.

Finally I made following fix, and send PR
https://github.com/ayanamizuta/goa/commit/c8ea769835bf5620c14ccd1d9604f2c99b249f70

# Before I submit 
from https://github.com/goadesign/goa/issues I searched like "type error query parameter" but I couldn't find similar issue.

If a patch of this matter is scheduled, sorry.

**Comment by raphael** [comment]
Thank you for the report! this is indeed a bug.

**Comment by raphael** [comment]
Thank you for the fix!
