### ISSUE TITLE
Implementing exclusiveMaximum and exclusiveMinimum validation Json

### ISSUE THREAD

**Issue by selmison** [goadesign/goa#2726]
I noted that Goa hasn't implemented **exclusiveMaximum** and **exclusiveMinimum** validation Json. Is it possible add these validations?

- Add a "exclusiveMaximum" validation to the attribute. See http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.2.3.
- Add a "exclusiveMinimum" validation to the attribute. See http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.2.5

**Comment by raphael** [comment]
Can you elaborate a little bit on why `Maximum` and `Minimum` are not sufficient? these were omitted by design as they seemed redundant given that the design DSL is typically static.

**Comment by selmison** [comment]
For example, a product's price or any numeric value should be greater than zero (0.0...01)

```
var ProductDTO = Type("ProductDTO", func() {
	Description("Product Type")
	Attribute("id", String)
	Attribute("name", string)
	Attribute("price", Float32, func(){
             ExclusiveMinimum(0)
         })
	Required("id", "name", "price")
})
```

**Comment by raphael** [comment]
I see makes sense, there is such a thing as floats! duh :)
