### ISSUE TITLE
Callbacks support

### ISSUE THREAD

**Issue by jinhong-** [goadesign/goa#2731]
Hi,
Is there support for [callbacks](https://swagger.io/docs/specification/callbacks/)?

**Comment by raphael** [comment]
No the DSL doesn't make it possible to call out callbacks explicitly. It is certainly possible to implement callbacks using Goa, mechanically speaking it works, but the resulting Swagger won't make use of the "callbacks" construct (it will be a POST operation or whatever HTTP verb the callback method ends up using).

**Comment by jinhong-** [comment]
Got it. How can i integrate callbacks into the swagger specifications using DSL? Is there an easy way to extend the DSL to support it?

**Comment by jinhong-** [comment]
@raphael To give more context, we would like to utilize goa's DSL to generate the swagger specifications. It would be possible to modify the swagger file after it has been generated by goa but it would be not an ideal workflow. Any suggestions on how DSL can be easily extended?

**Comment by raphael** [comment]
The DSL can be extended fairly easily. I think the challenge here is going to be around the effect that the new DSL should have on the generated code. It would probably break the expectations of most Goa users if the DSL only affected the OpenAPI spec output - it would also have to change the generated server and client code. Would you be able to come up with a proposal that described what the DSL would look like and the effect it would have on the generated code?

**Comment by jinhong-** [comment]
@raphael I am thinking we do not change the generated code at all. Since the concept of callbacks is a concept that is entirely up to the server to handle, it will only affect the generated OpenAPI specification files. The use case i am having/thinking of is so that we are able to have a single way of generating the OpenAPI specification file. Without this feature, we would have to introduce a separate workflow to patch the specification file with the callback fields

**Comment by jinhong-** [comment]
For anyone who is trying to support callbacks in their swagger specifications, this is what i did:
As part of the build pipeline, i did a yaml merge to patch in the missing callback section that i defined in a separate file
