### ISSUE TITLE
v3: response of type MapOf(Int, String) not working as expected

### ISSUE THREAD

**Issue by pablomadoeryunc** [goadesign/goa#2739]
Hello,

I have this method in my design:
Method("last", func() {
		Description("Get the last logs")
		Payload(BreakerAcPayloadLastList)

		Result(MapOf(Int, String))

		HTTP(func() {
			GET("/last")
			Param("start_date", String, "Filter ...")
			Param("end_date", String, "Filter ...")
			Response(StatusOK)
			Response(StatusBadRequest)
		})
})

and the following implementation of the controller function:
func (s *breakerAcSvc) Last(ctx context.Context, p *breakerac.BreakerAcPayloadLastList) (res map[int]string, err error) {
		var mm = make(map[int]string)
		mm[10] = "ten"
		mm[11] = "eleven"
		return mm, nil
}

This is what I expected to obtain in the response:
{
  10: "ten",
  11: "eleven"
}

And this is what I actually obtained in the response:
{
  "10": "ten",
  "11": "eleven"
}

Altough the keys of the map are INT they seem to be transformed to STRING.
Is this the expected behaviour?. How can I get the behaviour I am expecting ?.

Thank you very much !

**Comment by raphael** [comment]
Hello, this is a limitation of JSON, JSON keys must always be strings. The Go JSON encoder converts the integer keys into strings. If you really need integer keys then you'll have to look into alternative encoders.

**Comment by pablomadoeryunc** [comment]
Thank you very much for the answer!
