### ISSUE TITLE
How can I define 'File' type on goa v3

### ISSUE THREAD

**Issue by igtm** [goadesign/goa#2747]
I've used goa v1 and I'm trying to upgrade v1 to v3.
but I couldn't find how to define File on goa v3
https://goa.design/blog/007-v_1_4_0/

so Are there any ways to do this?

**Comment by raphael** [comment]
Hello, v3 takes a different approach and lets you access the underlying reader directly so that you may write the content to a file or otherwise stream the content for other use cases. This is done via the [MultipartRequest](https://pkg.go.dev/goa.design/goa/v3/dsl#MultipartRequest) DSL.

**Comment by igtm** [comment]
Thank you for your quick reply!

I put some parts of my implementation [here](https://gist.github.com/igtm/ec7e325fdf8cf1d63f0a24ae5d2c15df) for someone like me because I could find any examples of the implementation on this repo and on Google.

**Comment by raphael** [comment]
This is great!
