### ISSUE TITLE
Why `Tag` func just allow string value

### ISSUE THREAD

**Issue by gainings** [goadesign/goa#2750]
I want to handling multiple success HTTP responses such as 200, 204.

According to godoc(https://github.com/goadesign/goa/blob/v2/dsl/response.go#L12-L17) , I thought about using Tag 
But, Result type have't any string types.
I don't want to add an attribute in Result type just for handling by tags
if value in `Tag` func argument allow any types, its nice

**Comment by raphael** [comment]
You can define the response body/headers explicitly in the design and omit the attribute used by the generated code to infer the response status.

**Comment by gainings** [comment]
@raphael thx to reply

when http status code NoContent(204), Body just allow `dls.Empty`.
So i definline in desing like this

```
			Response(StatusNoContent, func() {
				Body(Empty)
			})
```

But generated code not handling empty or not, and not have `w.WriteHeader(http.StatusNoContent)`.
Is this bug?

**Comment by raphael** [comment]
Can you post a design that reproduces the issue?

**Comment by gainings** [comment]
Sure.
This is sample design just include i want to do and reproduces above issue.
Want return httpStatusCode.NoContent if body is nil 

version: Goa version v3.2.6
goversion: go version go1.15.5 darwin/amd64

```
package design

import (
	. "goa.design/goa/v3/dsl"
	cors "goa.design/plugins/v3/cors/dsl"
)

// API describes the global properties of the API server.
var _ = API("dummy-api", func() {
	Title("dummy-api")
	Description("HTTP service for adding numbers, a goa teaser")
	Server("app", func() {
		Host("localhost", func() { URI("http://localhost:8088") })
	})
})

var DummyResponse = ResultType("application/vnd.goa.dummy", func() {
	Description("dummy response.")
	Attributes(func() {
		Attribute("values", ArrayOf(Int32), "values", func() {
			Example([]int32{0, 1, 2, 3})
		})
		Required("values")
	})
})

var _ = Service("mysvc", func() {

	Method("get", func() {
		Error("an_error")
		Result(DummyResponse)
		HTTP(func() {
			GET("/details")
			Response(StatusOK)
			Response(func() {
				Description("Response used when item already exists")
				Code(StatusNoContent)
				Body(Empty)
			})
			Response("an_error", StatusConflict)
		})
	})
})

```

**Comment by raphael** [comment]
Just circling back on this: The semantic of defining multiple responses is "here are all the possible responses". By default Goa does not know which response to send depending on what condition. The [Tag](https://pkg.go.dev/goa.design/goa/v3/dsl#Tag) DSL function makes it possible to tell Goa which status code to use depending on the shape of the result. The function identifies a field in the result object and maps the field values to status codes. So in your case you could have a special field in `DummyResponse` that indicates whether to use 200 OK or 204 No Content. If you didn't want that field to get serialized in the response you could combine that with views where the field used to differentiate are not included.

Something like (not tested):

```go
package design

import (
	. "goa.design/goa/v3/dsl"
	cors "goa.design/plugins/v3/cors/dsl"
)

// API describes the global properties of the API server.
var _ = API("dummy-api", func() {
	Title("dummy-api")
	Description("HTTP service for adding numbers, a goa teaser")
	Server("app", func() {
		Host("localhost", func() { URI("http://localhost:8088") })
	})
})

var DummyResponse = ResultType("application/vnd.goa.dummy", func() {
	Description("dummy response.")
	Attributes(func() {
		Attribute("values", ArrayOf(Int32), "values", func() {
			Example([]int32{0, 1, 2, 3})
		})
		Attribute("status", String, "indicates whether to respond with status 200 or 204")
		Required("values", "status")
	})
	View("default", func() {  // Omit "is_empty" in default view
		Attribute("values")
	}) 
})

var _ = Service("mysvc", func() {
	Method("get", func() {
		Error("an_error")
		Result(DummyResponse)
		HTTP(func() {
			GET("/details")
			Response(StatusOK) // Default response
			Response(StatusNoContent, func() {
				Description("Response used when item already exists")
				Body(Empty)
				Tag("status", "no_content") // The result "status" field should be set to "no_content"
			})
			Response("an_error", StatusConflict)
		})
	})
})
```
