### ISSUE TITLE
Question: websocket close behaviour

### ISSUE THREAD

**Issue by snowhork** [goadesign/goa#2752]
Hi, I have a question about websocket closing behaviour.

Websocket by generated code sends close message on Close().

https://github.com/goadesign/goa/blob/35c1af1aa69f433f26fc691875b3191c016e6329/http/codegen/websocket.go#L710

```
	if err = s.conn.WriteControl(
		websocket.CloseMessage,
		websocket.FormatCloseMessage(websocket.CloseNormalClosure, "server closing connection"),
		time.Now().Add(time.Second),
	); err != nil {
		return err
	}
```

But gorilla websocket default closeHandler is same.

https://github.com/gorilla/websocket/blame/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/conn.go#L1108

```
func (c *Conn) SetCloseHandler(h func(code int, text string) error) {
	if h == nil {
		h = func(code int, text string) error {
			message := FormatCloseMessage(code, "")
			c.WriteControl(CloseMessage, message, time.Now().Add(writeWait))
			return nil
		}
	}
	c.handleClose = h
}
```

So, if we use default CloseHandler, websocket sends duplicated messages on Close().

Is it expected?

**Comment by raphael** [comment]
Hello, good question! can you expand a little bit on how the default Gorilla websocket close handler gets called? The idea behind the code generated by Goa is to provide a consistent interface whether the streaming is done via websocket or gRPC so ideally the user code should use the generated function and not the default close handler.

**Comment by snowhork** [comment]
Thanks for your reply!

I think when Gollira websocket recieves closing message from the client (e.g. closing browser), the close handler is called.

https://github.com/gorilla/websocket/blob/master/conn.go#L945
```
		if err := c.handleClose(closeCode, closeText); err != nil {
			return noFrame, err
		}
```

https://github.com/gorilla/websocket/blob/master/conn.go#L1092
> // SetCloseHandler sets the handler for close messages received from the peer.
// The code argument to h is the received close code or CloseNoStatusReceived
// if the close message is empty. The default close handler sends a close
// message back to the peer.



When we use default ConnConfigurer, Gorilla websocket close handler uses default.
https://github.com/goadesign/goa/blob/5fbc0ce3fab2c55f3603da0bc69cc0e1416c36d3/http/codegen/server.go#L299
```
	if configurer == nil {
		configurer = &ConnConfigurer{}
	}
```

**Comment by snowhork** [comment]
@raphael Hi, any updates? Can I submit a patch?
