### ISSUE TITLE
Question: OpenID Connect

### ISSUE THREAD

**Issue by Nightapes** [goadesign/goa#2756]
OpenApi 3.0.0 supports OpenID Connect for authentication, is it planned to add this to Goa? 
https://swagger.io/docs/specification/authentication/openid-connect-discovery/

**Comment by raphael** [comment]
I would be happy to take a contribution that added OpenID support!

**Comment by sherodtaylor** [comment]
is there a reason not to support this?

**Comment by raphael** [comment]
No reason other than someone needs to do it! :)
