### ISSUE TITLE
Review the spelling and grammar of goa.design

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#277]
The goa web site content is maintained in the [goa.design](https://github.com/goadesign/goa.design) repo. There are typos waiting to be fixed there :)

1. Follow the instructions in the [README](https://github.com/goadesign/goa.design/blob/master/README.md) to set it up locally.
2. Review the content in the `content/` directory (not `content/reference` as this is automatically generated).
3. Send a PRs to [goa.design](https://github.com/goadesign/goa.design)

**Comment by stuartweir** [comment]
I'm definitely on this!

**Comment by raphael** [comment]
Awesome! thank you.

**Comment by raphael** [comment]
Fixed by https://github.com/goadesign/goa.design/pull/2
