### ISSUE TITLE
Allow collectionFormat=csv for query param arrays

### ISSUE THREAD

**Issue by seward** [goadesign/goa#2776]
Currently goa only supports `collectionFormat=multi` for query param arrays. Ideally we'd be able to support `csv` style query param arrays as well, so that we could query like `my.api/my-endpoint?filter=1,2,3` instead of only allowing `my.api/my-endpoint?filter=1&filter=2&filter=3`.

**Comment by raphael** [comment]
Makes sense, I could see an additional DSL function to specify the format in the HTTP `Param` DSL:
```go
var _ = Service("account", func() {
    Method("list", func() {
        Payload(ArrayOf(String))
        Result(ArrayOf(String))
        HTTP(func() {
            GET("/")
            Params(func() {
                Param("filter", func() {
                    CollectionFormat(CollectionCSV)
                })
            })
        })
    })
})
```
The implementation of `CollectionFormat` could add a metadata entry to the request parameter attribute that the code generation algorithm would make use of. I would be happy to merge a PR that did the above.
