### ISSUE TITLE
OpenAPI: Maps do not support specifying "additionalProperties" value type

### ISSUE THREAD

**Issue by silverspace** [goadesign/goa#2777]
The current implementation of HTTP codegen uses JSON Schema to generate the v2/v3 OpenAPI definition, which supports only `"additionalProperties": true` in the generated openapi.json definition:
https://github.com/goadesign/goa/blob/v3/http/codegen/openapi/json_schema.go#L48

This translates to the `Free Form Objects` representation of values for `additionalProperties` in OpenAPI: https://swagger.io/docs/specification/data-models/dictionaries/

However, since we are already specifying the Map's `value` type in the DSL definition, it would be ideal to generate `"additionalProperties": { "type": "string" }` for string value types, etc. 

A suitable workaround could also be to specify 
```
Meta("swagger:extension:additionalProperties", `{"type":"string"}`)
```
but that is not currently possible since only `x-` prefixes are allowed. 

I've worked around this by defining my own custom swagger extension `swagger:extension:x-additionalProperties`, but it would be nice to support this natively since it's part of the OpenAPI specification.

**Comment by raphael** [comment]
Agree, this would be a good addition to make.
