### ISSUE TITLE
Result Type is not used by PascalCase

### ISSUE THREAD

**Issue by flymedllva** [goadesign/goa#2781]
```
var ResultVariableTest = ResultType("ResultVariableTest", func() {
	Field(1, "success", Boolean, "Ok desc")
	Required("success")
})
```
and
`Result(ResultVariableTest)` in service method

Returns
```
Test(context.Context, *TestPayload) (res *Resultvariabletest, err error)
```

`res *Resultvariabletest` is not used by PascalCase. Is this how it should be?

**Comment by raphael** [comment]
Yes that is correct. The value given to `ResultType` is a mime type identifier - not the type name. If no type name is provided then Goa generates one by munging the mime type identifier. Use `TypeName` to specify the type name for a result type:
```go
var ResultVariableTest = ResultType("application/vnd.result-variable-test", func() {
        TypeName("ResultVariableTest")
	Field(1, "success", Boolean, "Ok desc")
	Required("success")
})
```

**Comment by flymedllva** [comment]
That is, if I want to write JSON, do I need to do this?
```
var ResultVariableTest = ResultType("application/json", func() {
        TypeName("ResultVariableTest")
	Field(1, "success", Boolean, "Ok desc")
	Required("success")
})
```
Is there no way to shorten the record?
Or I did not understand the meaning, why is this

**Comment by raphael** [comment]
That's correct. The argument given to `ResultType` is the default mime type used to write HTTP responses and not the type name.
