### ISSUE TITLE
Code is not being generated for header in GRPC expression

### ISSUE THREAD

**Issue by SantoshSah** [goadesign/goa#2787]
[Header docs](https://pkg.go.dev/goa.design/goa/dsl#Header) states that

 `Header may also appear in a method GRPC expression (to define headers sent in message metadata), or in a Response expression (to define headers sent in result metadata). `

but `goa gen` throws error `invalid use of Headers in API GRPC`. 

Below is sample code

```code
import (
	. "goa.design/goa/v3/dsl"
	cors "goa.design/plugins/v3/cors/dsl"
)

var _ = API("userapi", func() {
	Title("user Service")
	Version("1.0.0")
	Description("Service for managing users")
	Docs(func() { // Documentation links
		Description("doc description")
		URL("doc URL")
	})
	HTTP(func() {
		Headers(func() {
			Header("newheader", String, "Header Name", func() {
				Enum("val1", "val2")
			})
			Required("newheader")
		})
	})
	GRPC(func() {
		Headers(func() {
			Header("newheader", String, "Header Name", func() {
				Enum("val1", "val2")
			})
			Required("newheader")
		})
	})
	Server("user_server", func() {
		Host("localhost", func() {
			URI("http://0.0.0.0:8120")
			URI("grpc://0.0.0.0:8121")
		})
	})
})

```

**Comment by raphael** [comment]
Good catch! we had to introduce a different keyword for gRPC headers sent in requests because it was ambiguous, see https://pkg.go.dev/goa.design/goa/v3/dsl#Metadata.
