### ISSUE TITLE
How to specify "./calcpb" package for protoc-gen-go?

### ISSUE THREAD

**Issue by drognisep** [goadesign/goa#2788]
I'm trying to follow along with the getting started guide [here](https://goa.design/learn/getting-started/), and I'm getting an error when I try to run `goa gen calc/design`.

```
>goa gen calc/design
exit status 1
failed to run protoc: exit status 1: protoc-gen-go: invalid Go import path "calcpb" for "calc.proto"

The import path must contain at least one forward slash ('/') character.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
```

The calc.proto file is generated and I tried adding a package manually to see if that resolved the problem, but the file is generated anew, so my changes are reverted. How would I specify a different value for the package to ensure that protoc-gen-go is happy with creating the go code?

**Comment by drognisep** [comment]
For context, here's the generated proto file.
```
// Code generated with goa v3.2.6, DO NOT EDIT.
//
// calc protocol buffer definition
//
// Command:
// $ goa gen calc/design

syntax = "proto3";

package calc;

option go_package = "calcpb";

// The calc service performs operations on numbers
service Calc {
	// Add implements add.
	rpc Add (AddRequest) returns (AddResponse);
}

message AddRequest {
	// Left operand
	sint32 a = 1;
	// Right operand
	sint32 b = 2;
}

message AddResponse {
	sint32 field = 1;
}
```

**Comment by raphael** [comment]
Could you give the Goa branch `grpc_go_1_26` a try? I believe it fixes the issue.

**Comment by JermineHu** [comment]
**A temporary solution：**
Performing a downgrade operation. Some code like this: 
  ```golang
   go get -u goa.design/goa/v3/...@v3.2.6  \
     && go get -u github.com/golang/protobuf/protoc-gen-go@v1.4.3 \
     && go get google.golang.org/protobuf/...@v1.25.0 \
     && go get github.com/golang/protobuf/...@v1.4.3 
```

**Comment by raphael** [comment]
This has  been fixed in the head of the `v3` branch (https://github.com/goadesign/goa/pull/2791). The next release of Goa (`v3.3.0`) will require upgrading to `google.golang.org/protobuf`.

**Comment by drognisep** [comment]
Confirmed! It looks like the tutorial is generating correctly. Thank you!
