### ISSUE TITLE
Swagger UI is really missing here

### ISSUE THREAD

**Issue by Dmdv** [goadesign/goa#2795]
I used gin and chi a lot.
Swagger UI is really need here

**Comment by amanbolat** [comment]
Swagger spec file with yaml and json extensions are created after running `goa gen`. What else do you need?
I just use redoc-cli during the local development and just watch files above. After you push your code you can host it on S3 or your own server.

`redoc-cli serve -w path/to/openapi3.yaml -p 8080`

**Comment by raphael** [comment]
Closing this issue as there are many tools that can produce swagger UIs from the swagger definitions already generated by Goa.
