### ISSUE TITLE
goa374132955\main.go:22:30: unknown escape sequence

### ISSUE THREAD

**Issue by Dmdv** [goadesign/goa#2804]
Quite often I have this error when I run command:
**goa gen xxxxx\design**
goa374132955\main.go:22:30: unknown escape sequence

```
========
Content:
// Code generated by goa v3.3.1, DO NOT EDIT.
//
// Code Generator
//
// Command:
// goa

package main

import (
        "flag"
        "fmt"
        "os"
        "path/filepath"
        "sort"
        "strconv"
        "strings"
        "goa.design/goa/v3/codegen"
        "goa.design/goa/v3/codegen/generator"
        "goa.design/goa/v3/eval"
        goa "goa.design/goa/v3/pkg"
        _ "centralex.com\fireblocks\design"
)

func main() {
        var (
                out     = flag.String("output", "", "")
                version = flag.String("version", "", "")
                cmdl    = flag.String("cmd", "", "")
                ver int
        )
        {
                flag.Parse()
                if *out == "" {
                        fail("missing output flag")
```

**Comment by raphael** [comment]
The `goa` tool accepts the Go package import path as argument - not a file path. Assuming `goa` is run in a Go module named `foo` the command line should be `goa gen foo/design`. Typically a module name will be qualified, e.g. `goa.design/examples`, in this case the command should be `goa gen goa.design/examples/basic/design`. In particular a Go package import path always uses `/` - even on Windows.
