### ISSUE TITLE
How do I extend my type with a map of?

### ISSUE THREAD

**Issue by jinhong-** [goadesign/goa#2812]
I would like to be able to extend my type with a map. My object has 2 properties/fields, but i would like to define that on top of the 2 properties, the user can pass in any other properties. Essentially this is the equivalent of setting additionalProperties to true

**Comment by raphael** [comment]
This isn't possible at the moment. Obviously a type may have a field of type `MapOf(X,Y)` together with other fields but there is no way to "extend" a type with a map of. How would you represent that in Go?

**Comment by jinhong-** [comment]
I see. The way it might be possible to represent in go could be that on top of the structure, we could have an additional field which is a map[string]interface {}

For eg

```
type ApiModel struct {
  ID string
  Title string
  DynamicProperties map[string]interface{}
}
```

Additional properties will be bound to the DynamicProperties field

Or, we can simply use a map return type, and extend it with functions to get and set the fields we defined

For eg
```
type ApiModel map[string]interface{}

func (m *ApiModel) GetID() string

func (m *ApiModel) SetID(val string)
```
And so on

**Comment by raphael** [comment]
Makes sense, we'd also need to look at what that means for gRPC: from a transport POV gRPC wouldn't allow adding fields that were not defined in the proto file. One extra challenge here is that gRPC requires specifying the type of the map values. We could make it an error to use "extensible" types when using gRPC but that goes a little bit against the basic principle that Goa abstracts the transport layer for you (although that's already the case when using the type `Any`). Doing all of that would be quite a bit of work and could add substantially to the implementation complexity of Goa. At this point I'm not sure the ROI would be there (as compared to explicitly defining a map field in the design for example). Is this a showstopper for your use case or could you design things differently?

**Comment by jinhong-** [comment]
Ah right I forgot about the gRPC usage as we're only on HTTP at the moment. Right now it is not a show stopper but a very good to have since we are not using the payload yet. It is actually for designing our error response payload, similar to the one described [here](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#innererror--object)

In `innererror`, it supports dynamic adding of fields but as of now we could potentially just add a new property that is a MapOf(String,Any) which will generally work

If i would want to try to extend support for this feature, which parts of the code base should i start looking at?
