### ISSUE TITLE
"Command:" in generated code: erroneous $(GOPATH) substitution

### ISSUE THREAD

**Issue by michael-db** [goadesign/goa#2814]
I build in a container where GOPATH is /go. In generated code, I get:
```
// Command:
// $ goa gen path/to/my/package$(GOPATH)a
```
which should be
```
// Command:
// $ goa gen path/to/my/package/goa
```

**Comment by raphael** [comment]
This should be fixed by https://github.com/goadesign/goa/pull/2844.

**Comment by michael-db** [comment]
My apologies for the delay. This is certainly fixed in the current version. Thank you.
