### ISSUE TITLE
External code versions should be fully determined

### ISSUE THREAD

**Issue by michael-db** [goadesign/goa#2815]
The Goa Makefile does a "go get" of various packages, and the passing of the tests appears to be dependent on at least some of these. The tested compatible versions of any such package should be fully determined at each release, e.g., go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0, not go get google.golang.org/protobuf/cmd/protoc-gen-go. It is quite disconcerting to see the go.mod file change when a tagged release is built. It is not good idea to assume that upgrades of external code subsequent to a release will not break it.

**Comment by raphael** [comment]
That's fair, would you mind creating a PR that added the version to these dependencies?

**Comment by michael-db** [comment]
Thank you for Goa, Raphael. In principle, I would be happy to, however, as an employee of a large corporation whose principal business is not software, I have up to now not secured general permission from its legal department to make contributions to open source software, even though the company obviously benefits from it.

This is embarrassing, and I apologize. However, without making it into a formal pull request, I can tell you that to run the tests with goa v3.3.1 I used:

google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0
google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0

I was not concerned with linting and did not need to "go get" the other unversioned packages in the Makefile to run the tests.

(I will ask again to see if anything can be done about the legal position.)

**Comment by raphael** [comment]
Thank you for the details. https://github.com/goadesign/goa/pull/2847 pins the versions of the `protoc-gen-go` and `protoc-gen-go-grpc` tools. I left the linter tools unversioned as they don't affect the actual code and we want to detect any new linter errors as soon as possible.
