### ISSUE TITLE
Test files in goa v3

### ISSUE THREAD

**Issue by p3lli** [goadesign/goa#2818]
Hi everyone, I have started using v3 after some time. Previously I have always used v1.
I am missing the `*_test.go` files that were been generated along side every resource defined in `design.go`.
How does goa v3 handle the generation of the boilerplate for testing? Is there a new way I am missing?

**Comment by raphael** [comment]
Hello, Goa v3 does not currently generate equivalent test files. This would make a great [plugin](https://github.com/goadesign/plugins) contribution though!

**Comment by p3lli** [comment]
Hello, thank you for getting back to me so quickly.
I am still at a very early stage of a side project. Do you recommend to go back to v1 for the tests or it will be added to v3 in a future release, either as a plugin or in the original module?

What do you think about this repository https://github.com/ikawaha/goahttpcheck ?

**Comment by raphael** [comment]
@ikawaha has done a great job with [goahttpcheck](https://github.com/ikawaha/goahttpcheck), thank you for the pointer! At a high level it enables the same workflow that the test framework did in Goa v1: pass in your payload and get the response back for validation. Definitely worth giving it a shot.

**Comment by raphael** [comment]
Closing this issue, I'll add a pointer to `goahttpcheck` in the `README`.
