### ISSUE TITLE
Cannot generate shared Types and ResultTypes between services

### ISSUE THREAD

**Issue by saniales** [goadesign/goa#2824]
Hello, I am using a Type and a Result type in 2 services. 

What I am getting is that the same type object is generated in both packages with the same fields.

When I try to use one of them as a model for a repository, the following error appears

``` go
	offeredServices, err := s.servicesRepository.FindServicesByID(ctx, p.NewReservation.ServiceIds) // returns []*services.OfferedService
	if err != nil {
		return nil, MakeMonitoredError(reservations.MakeInternalServerError, "Cannot get services from IDs", s.logger, err)
	}

	res = &reservations.Reservation{
		Services: offeredServices, // breaks "cannot use offeredServices (variable of type []*services.OfferedService) as []*reservations.OfferedService value in struct literal"
	}
```

The designs look like this

``` go
// service.go

// ...
Method("GetAllServices", func() {
		Description("Gets all the services' data")

		Payload(func() {
			Token("token", String, "JWT used for authentication")

			Required("token")
		})

		Result(offeredServices)

		HTTP(func() {
			GET("/")

			Response(StatusOK)
		})
	})
// ...

var offeredService = ResultType("application/medy.care.service+json", "offered_service", func() {
	Extend(util.DomainObject)
	Reference(newOfferedServicePayload)

	Description("Represents a service offered in a reservation")

	Attributes(func() {
		util.Attribute("id", String, "The ID of the service offered", func() {
			Format(FormatUUID)
		})

		Attribute("name")
		Attribute("reference_rate")

		Required("id", "name", "reference_rate")
	})

	View("default", func() {
		Attribute("id")
		Attribute("name")
		Attribute("reference_rate")
	})

	View("id_only", func() {
		Attribute("id")
	})
})


```

``` go
//reservation.go

var reservation = ResultType("application/medy.care.reservation+json", "reservation", func() {
	Extend(util.DomainObject)
	Reference(newReservationPayload)

	Description("A reservation made by a user")

	util.Attribute("id", String, "The ID of the reservation", func() {
		Format(FormatUUID)
	})

	util.Attribute("services", ArrayOf(offeredService), "The list of services")
	util.Attribute("time_slot", timeSlot, "The time slot selected by the user")

	Attribute("requesting_people")
	Attribute("destination_address")
	Attribute("reservation_date")

	// coupon, not required
	Attribute("coupon_code")

	// COVID-consent, not required
	Attribute("covid_consented_at")

	// invoicing data, not required
	Attribute("invoice_data")

	Required("id", "services", "time_slot", "requesting_people", "destination_address", "reservation_date")

	View("default", func() {
		Attribute("id")
		Attribute("requesting_people")
		Attribute("services")
		Attribute("reservation_date")
		Attribute("coupon_code")
		Attribute("time_slot")
		Attribute("invoice_data")
	})

	View("id_only", func() {
		Attribute("id")
	})

	View("mongo", func() {
		Attribute("id")
		Attribute("requesting_people")
		Attribute("services")
		Attribute("reservation_date")
		Attribute("coupon_code")
		Attribute("time_slot")
		Attribute("invoice_data")
	})
})
```

why that? this makes me impossible to reuse types across services, which makes sort of useless the code generation itself, because I have to write all the model types (that is if I use ConvertTo or CreateFrom)

Can anybody help? thank you

**Comment by raphael** [comment]
Hello,

This is a fundamental design choice in Goa where each service Go package is completely decoupled from the package of other services. Introducing coupling by the way of shared packages that define common data types would break this and (not to sound pedantic - there are real consequences) is an anti-pattern when building microservices. Another aspect is that for non-trivial services reusing the data types defined in the endpoint layer in the business logic can also end up creating undesirable coupling. Practically speaking the domains are different and reusing the same exact types often ends up with weird side effects for example methods to persist the data that might require additional fields that are not relevant to endpoint code.

All of this does mean that additional code needs to be written to convert types between services and between layers in a given service however  "A little copying is better than a little dependency" :)

**Comment by saniales** [comment]
is there any example in doing that?
ConvertTo and CreateFrom seem to do the job, however they work with user defined structs

**Comment by raphael** [comment]
There really isn't much to it, just initialize the fields of the model struct using the fields of the generated struct. An alternative could be to use reflection, there are libraries that will do the copying for you for example https://github.com/jinzhu/copier. Personally I would just write the 20 lines of code to do the initialization.
