### ISSUE TITLE
how can i use embed for files.

### ISSUE THREAD

**Issue by chezgi** [goadesign/goa#2828]
i want to serve my static files from embed.FS

```go
//go:embed ui/swagger/*
var content embed.FS

var _ = Service("swagger", func() {
	HTTP(func() {
		Path("/swagger")
	})
	Files("/{*path}", "ui/swagger/")
})
```
is there any solution to this problem?

**Comment by chezgi** [comment]
i found a good post from [ikawaha](https://zenn.dev/ikawaha/articles/20210503-3d72f1747f43efd3bdc9)
it works.

**Comment by ikawaha** [comment]
I wrote an example to download a file from embed.FS by referring to [the file upload and download example](https://github.com/goadesign/examples/tree/master/upload_download).

I hope this is of some help to you.
https://github.com/ikawaha/examples/pull/1
