### ISSUE TITLE
Protoc package customization

### ISSUE THREAD

**Issue by arangamani** [goadesign/goa#2835]
## Problem
The current approach taken by Goa to generate the proto package simply takes the name of the service specified in the design (converted to camel case).
For example,
```go
var _ = Service("FooService", func() {
  Method("DoSomething", func() {
    // ...
  })
})

var _ = Service("BarService", func() {
  Method("DoSomethingElse", func() {
    // ...
  })
})
```
generates the protoc in the following format:
```
foo_service.FooService/DoSomething
bar_service.BarService/DoSomethingElse
```
Here, the protoc package `foo_service` is redundant with the name of the service which is already in the method path.

It would be helpful if we can customize the proto generated proto package. If we multiple services, we should be able to group them easily and this can be elegant to put multiple services behind an ingress such as Istio and the routing can be performed based on the prefix.

## Proposal

If we can allow the use of a `Meta` DSL to provide a custom package name for protoc, it will be helpful.
For example,
```go
var _ = Service("FooService", func() {
  Meta("protoc:package:name", "myapp.v1")
  Method("DoSomething", func() {
    // ...
  })
})

var _ = Service("BarService", func() {
  Meta("protoc:package:name", "myapp.v1")
  Method("DoSomethingElse", func() {
    // ...
  })
})

var _ = Service("FooServiceV2", func() {
  Meta("protoc:package:name", "myapp.v2")
  Meta("protoc:service:name", "FooService")
  Method("DoSomething", func() {
    // ...
  })
})
```
This can generate the protoc in the following format:
```
myapp.v1.FooService/DoSomething
myapp.v1.BarService/DoSomethingElse
myapp.v2.FooService/DoSomething
```
* The `protoc:package:name` tag is used to customize the name of the protoc package.
* The `protoc:service:name` tag is used to customize the name of the service. This can be helpful if we have multiple versions of the same service defined together.

**Comment by raphael** [comment]
#2841 adds the ability to specify custom protobuf package name by introducing a new `Package` DSL function:

```go
var GRPCService = Service("my_grpc_service", func() {
    GRPC(func() {
        Package("svc")
    })
    Method("add", func() {
        Payload(func() {
            Field(1, "a", Int)
            Field(2, "b", Int)
        })
        Result(Int)
    })
    GRPC(func() {})
})
```
