### ISSUE TITLE
Default HTTP error responses are not included in openapi.json schema

### ISSUE THREAD

**Issue by EmilLaursen** [goadesign/goa#2840]
Thank you for this library!

## Problem

The default HTTP ErrorResponse, from the default formatter, can output the status codes: 500, 504, 408, 503 and 400. This corresponds to `Fault`, `Timeout+Temporary`, `Timeout`, `Temporary` and `default`. Found [here](https://github.com/goadesign/goa/blob/3efab9fff655bee28b396a8502d2edf3d128d264/http/error.go#L56).

However, these status codes are not added to the generated `openapi3.json`, as valid endpoint responses. One consequence is that automated test tools such as [schemathesis](https://github.com/schemathesis/schemathesis), based on the OpenAPI 3 spec, will flag this as an error because the server can return status codes not listed in the spec.

If this is intentional, let me know and I will close the issue.

**Comment by raphael** [comment]
That makes sense, the flip side is that for a design that defines all the possible error responses explictely (best practice) then that could end up "polluting" the OpenAPI spec (e.g. not all operations may return a timeout error). Maybe we could introduce a DSL function that would let the design author specify when to generate the default error responses (`DocumentDefaultErrors()` or something like that which could be specified at the API, service or individual method level).

**Comment by EmilLaursen** [comment]
I think that is a fine compromise!
