### ISSUE TITLE
Return errors appropriately encoded

### ISSUE THREAD

**Issue by jim-slattery-rs** [goadesign/goa#285]
First noticed this problem in: https://github.com/goadesign/goa/pull/283
Documenting this issue in response to feedback from @raphael there.

400 errors are now coming back as a JSON object encoded in a string.
```json
"{\"kind\":\"invalid request\",\"msg\":\"...\"}"
```
 Ideally, they would come back as full JSON, or XML, or whatever encoding was appropriate:
```json
{
  "kind": "invalid request",
  "msg": "invalid encoding",
  "detail": [
    {
      "id":8,
      "title":"value does not match validation pattern",
      "msg":"raw.principal.href must match the regexp \"^/grs/(users|groups)/(\\\\d+)$\" but got value \"/grs/users/1a\""
    }
  ]
}
```
We need to make `TypedError` and `MultiError` (in error.go) marshal data structures rather than just provide an Error() string. The idea is to keep responses consistent when an error is returned from a controller or from HandleFunc.

**Comment by thecodethinker** [comment]
Where is `InvalidParamTypeError` definied? I've been digging around but I can't find it.

**Comment by raphael** [comment]
All the error handling code can be found in `error.go`: https://github.com/goadesign/goa/blob/master/error.go#L192

**Comment by thecodethinker** [comment]
Oh sorry, must've looked up `InvalidParameterTypeError`

**Comment by thecodethinker** [comment]
It looks like the problem is happening right when the error is being written to the `ResponseWriter`. I'm using delve to follow the execution but I can't see where exactly the error is being written out. But whatever is causing the problem is probably coming from there.

**Comment by raphael** [comment]
Errors are now properly encoded with the latest error handling refactor.
