### ISSUE TITLE
Controller actions may receive a `nil` payload, even when attributes are required

### ISSUE THREAD

**Issue by jim-slattery-rs** [goadesign/goa#287]
There's a special case in the `ApplicationController.HandleFunc()` that bypasses the unmarshaller when request ContentLength == 0.
This is good for actions with optional payloads: the action will be called and the payload will be nil.

But for actions with payloads containing required fields, those validations are never run and the action ends up getting called with a nil payload.

https://github.com/goadesign/goa/pull/286 had one naive solution, but it broke behavior for actions with truly optional payloads.

**Comment by advanderveer** [comment]
I'm running into this as well, is there a workaround do we have to check for `payload == nil` ourselfs?

**Comment by raphael** [comment]
For now the controller needs to do the check. There needs to be new DSL to specify that the payload as a whole cannot be nil - merely stating that some fields cannot be nil is not the same thing. This is a common issue that pretty much anyone runs into at some point though so we should address it. I'm thinking there could be a `RequirePayload` function part of the `Action` DSL.

**Comment by raphael** [comment]
After thinking about this a little bit more I prefer the proposal described in #507:

I would suggest adding a OptionalPayload function to the Action DSL since it's probably the rarer case:
```go
Action("foo", func() {
    OptionalPayload(MyPayloadType)
    // ...
} 
```

**Comment by jim-slattery-rs** [comment]
fixed by: https://github.com/goadesign/goa/pull/507
