### ISSUE TITLE
UInt64 format missed in openapi3

### ISSUE THREAD

**Issue by sivakumar07** [goadesign/goa#2876]
```
var Id = ResultType("application/vnd.id", func() {
	TypeName("Id")

	Attributes(func() {
		Field(1, "id", UInt64)

		Required("id")
	})

})
```

Openapi3 doesn't have a format in the openapi3.yaml. So open API generators generate code as int32 instead of int64. 

```
	Field(4,"port", Int, func() {
		Example(3306)
	})
```

This is generating openapi3.yaml with format int64. I think this should be int32.

**Comment by sivakumar07** [comment]
@raphael @nitinmohan87

**Comment by raphael** [comment]
Can you provide a complete minimal design that reproduces the issue, the YAML currently being generated and what you expect it to be instead? At face value I don't understand why it would be better for an integer designed as `UInt64` to cause the OpenAPI specification to use the format `int32` instead of `int64`.

**Comment by sivakumar07** [comment]
![Screenshot 2021-06-29 at 11 26 32 PM](https://user-images.githubusercontent.com/12998002/123845126-71c08780-d931-11eb-9825-58280f1e1261.png)
http/codegen/openapi/v3/types.go

We need to fix it here

**Comment by raphael** [comment]
Thank you for the code snippet! How would you suggest changing this code (given that there is no unsigned format in OpenAPI)?

Edit: Thank you for the PR! Given that an int is 64 bit for 64-bit architectures which is probably the most common case should the format be `int64` for `Int` and `UInt`?

**Comment by kumarsiva07** [comment]
OpenAPI doesn't have unsigned. So we can go with the integer. 

//Int and UInt - I guess these again depend on the architectures. So in terms of web API, we can go with int32. Do you want me to change it to int64?

**Comment by raphael** [comment]
Yeah I think using `int64` for `Int` and `UInt` would be better as it would probably match reality 99% of the time, thanks again!

**Comment by kumarsiva07** [comment]
Can you please merge this?

**Comment by raphael** [comment]
I don't see the change we just talked about: using the `int64` format for `Int` and `UInt`, I'll merge once that's done - thank you!
