### ISSUE TITLE
OpenAPI - Can we have service_name + action_name+requst_body instead of AddRequestBody1,AddRequestBody2..

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#2877]
OpenAPI - Can we have service_name + action_name+requst_body instead of AddRequestBody1,AddRequestBody2..

**Comment by raphael** [comment]
The names generated in the OpenAPI specification match the names used by the code generators, this would be a fairly significant change and I am not sure it would make sense (the resulting type names could end up being quite verbose). However it might be possible to add a `Meta` DSL to override the names generated by the OpenAPI generator - I'd be happy to merge a PR that did that.
