### ISSUE TITLE
Invalid http cli packages generated when API hosts more than one server

### ISSUE THREAD

**Issue by disintegrator** [goadesign/goa#2887]
Goa currently generates broken HTTP CLI support packages when an API declares more than one server.

## Given

**Goa version:** 3.4.3

```go
var _ = API("superapi", func() {
	Server("calc", func() {
		Services("calc")
		Host("localhost", func() {
			URI("http://localhost:8000")
		})
	})

	Server("zoo", func() {
		Services("zoo")
		Host("localhost", func() {
			URI("http://localhost:8001")
		})
	})

	HTTP(func() {
		Produces("application/json")
	})
})
```

## Expected

- Valid `gen/http/cli/zoo/cli.go` which only references the zoo service and its methods
- Valid `gen/http/cli/calc/cli.go` which only references the calc service and its methods

## Actual

The above packages are generated but they each references _all_ declared service method and have missing imports.

Reproduction repo: https://github.com/disintegrator/goa-2887

**Comment by raphael** [comment]
Thank you for the report and the repro, this is clearly a bug, I am looking into it.

**Comment by disintegrator** [comment]
Thanks for resolving this issue!
