### ISSUE TITLE
Proposal: Refactor DSL to use object oriented builder pattern instead of function calls

### ISSUE THREAD

**Issue by silverspace** [goadesign/goa#2897]
First of all, thank you for an awesome project for generating openapi3 documentation and super flexible golang templates. Our team has successfully been using GOA for some time now without issues. 

One suggestion that I have, which we have implemented on top of GOA, is to swap out the function based DSL with a Builder pattern instead. For example:
```
var GetWidgetsRequest = NewRequestPayload("GetWidgetsRequestObject").
	WithQueryParam(NewQueryParam("widgetType", NewString("A widget type").
		WithEnum("axe", "hammer", "shovel").
		WithExample("hammer")), Required).
	WithQueryParam(NewQueryParam("createdAfter",
		NewString("Return all widgets created after createdAfter, in RFC 3339 format.").
			WithFormat(expr.FormatDateTime).
			WithExample("2019-06-13T19:08:25Z")), Optional).
	WithQueryParam(NewQueryParam("name",
		NewString("Optional name of the widget").
			WithMinLength(1).
			WithMaxLength(100).
			WithExample("my_widget")), Optional).
	WithQueryParam(NewQueryParam("after",
		NewString("Optional pagination cursor, returns results after the previous page of results").
			WithFormat(expr.FormatUUID).
			WithExample("1529CEF1-4569-4157-83D4-20B546340C94")), Optional)

var WidgetResponse = NewObject("WidgetResponseObject", "Object descriptor for selected widgets").
	WithField("id", Required, NewString("ID of the widget").WithExample("12345")).
	WithField("name", Optional, NewString("Name of the widget").WithExample("Widget 12345")).
	WithEmbedded(WidgetSettings)

var PaginationResponse = NewObject("PaginationResponse", "Pagination parameters.").
	WithNamedField(NewNamedField("endCursor", NewString("Cursor identifier representing the last element in the response. This value should be used in conjunction with a subsequent request's 'after' query parameter. This may be an empty string if there are no more pages left to view.")), Required).
	WithNamedField(NewNamedField("hasNextPage", NewBoolean("True if there are more pages of results immediately available after this endCursor.").WithExample(true)), Required)

var GetWidgetsResponse = NewObject("GetWidgetsResponseObject", "Dictionary containing widgets").
	WithField("data", Required, NewArray(WidgetResponse, "List of widgets").
		WithMinLength(0).
		WithMaxLength(100)).
	WithField("pagination", Required, PaginationResponse)
```

The advantages that we have enjoyed are:
1. Available DSL options are easily discovered through IDE code completion. Example: 
![image](https://user-images.githubusercontent.com/15318933/128091570-d25d3c60-43ae-49c0-8831-957e65f5fdd5.png)
2. `eval.IncompatibleDSL()` becomes unnecessary, since the compiler enforces the DSL options.
3. Builder expressions are built as local variables, rather than appending to a global `eval.Context` variable. This enables lazy execution of designs, which affords a lot more flexibility when building targets: conditionally including endpoints and fields, sharing and extending definitions, etc. 
4. Types do not need to be defined at the top level, before endpoint definitions. We can embed type definitions directly into endpoint definitions. 
5. All primitives are strongly typed, so we don't need `interface{}` anywhere. For example, `WithEnum(vals ...int64)` for int64 types and `WithEnum(vals ...string)` for strings.

**Comment by raphael** [comment]
This seems like a great approach, I am wondering how best to incorporate it. It probably wouldn't make sense to wholesale replace the current DSL with it, this would at the very least require a new major release (v4?). It would be great to get some more usage and get feedback from other users (I'd want to try it out too :) ). Would it make sense to start as a plugin? We could have a link to it in the README and announce it in the slack channel. Did you already have an idea in mind?

**Comment by silverspace** [comment]
I don't think this necessarily requires a V4 breaking change version, as the builder approach can actually coexist with the DSL function based approach. The two possibilities for coexisting are:
1. Implement the builder on top of the existing DSL functions.
2. Have both the builder and DSL functions share the same underlying `expr` types and helper functions. 

We implemented our builder with (1) above; all of our `Build()` functions just invoke vanilla `goa` DSL functions. However, we also implemented a lot of custom builder functions and hard coded our implementation to `HTTP` for simplicity (see `WithQueryParam` above), so our implementation would not be well suited for your open source project. 

If the builder and DSL functions both shared the same underlying `expr` expressions and registration functions, then clients of `goa` could choose to use either the current function based DSL OR the builder, or possibly some combination of both. The main refactor that would be necessary for this is to stop using global variables to track state, or at least make it optional to generate code with local `expr` variables. If you could abstract away the global variable getters/setters from the underlying DSL implementation, then the same underlying implementation could be shared by both. 

Note: The main `gotchas` that I found while implementing this were:
1. Most primitive validations have to happen on the parent container, such as an Array, due to the way the DSL functions are designed. For this reason I added a `parentValidations()` to the interface, so that child components may pass validations to the parent container to invoke for them. 
2. In GOA, all `Types` must be defined at the top level, before any other DSL functions are invoked. Therefore, it is not possible to define a type inline in the endpoint definition. However, the builder does not have such restrictions, so we added a `Prepare` function to perform a first pass on the build chain to allow any user types to predeclare themselves.

**Comment by pot-code** [comment]
i managed to implement a builder myself so i can write code like this

```go
var _ = Service("department", func() {
	HTTP(func() {
		Path("/department")
	})

	dsl.Endpoint("read departments").
		Get("/").
		ResponseModel(ArrayOf(DepartmentListObject)).
		Create()

	dsl.Endpoint("read department").
		Get("/{id}").
		Param("id", String).
		ResponseModel(DepartmentRead).
		Create()

	dsl.Endpoint("create department").
		Post("/").
		RequestBody(DepartmentCreate).
		ResponseModel(DepartmentRead).
		UseInterceptor(dsl.ValidateRequestBodyInterceptor).
		Create()

	dsl.Endpoint("update department").
		Put("/{id}").
		Param("id", String).
		RequestBody(DepartmentUpdate).
		ResponseModel(DepartmentRead).
		UseInterceptor(dsl.ValidateRequestBodyInterceptor).
		Create()

	dsl.Endpoint("delete department").
		Delete("/{id}").
		Param("id", String).
		Create()
})
```
