### ISSUE TITLE
Goa gen error

### ISSUE THREAD

**Issue by jeffreylim-foodpanda** [goadesign/goa#2918]
Received the following error when we run `goa gen` 
`go get: malformed module path "goa865448624": missing dot in first path element`. Seems like this has got to do with the release of v3.5.1

**Comment by Bird87ZA** [comment]
@raphael sorry for tagging you directly, but we have a similar issue. Do you have any idea what this could be? All our builds are currently failing with the same error.

**Comment by anassrakibi** [comment]
I started to get the same since last Friday even If I'm using v3.3.1

**Comment by raphael** [comment]
It would help a lot if there was a simple design I could use to repro, the examples don't seem to have that problem.

**Comment by raphael** [comment]
Also it would help to know whether the services are HTTP only or make use of gRPC as there was a similar issue with the code generated for the gRPC transport that got fixed before. If using gRPC it would help to know the version of protoc and protoc-gen-go:
```
protoc-gen-go --version
protoc-gen-go v1.27.1
protoc --version
libprotoc 3.17.3
```

**Comment by anassrakibi** [comment]
@raphael I could produce it by simply trying this [example](https://github.com/goadesign/goa#1-design) from the readme file. I did the same thing as mentioned there but get the error above. 
```
> go version
go version go1.16.7 darwin/amd64
> goa gen goa/design
go get: malformed module path "goa495748234": missing dot in first path element

**Comment by Bird87ZA** [comment]
Can confirm @anassrakibi findings above. I also did the example in the readme and got this:

```
PS C:\Users\user\Dev> mkdir -p calcsvc/design
>> cd calcsvc
>> go mod init calcsvc


    Directory: C:\Users\user\Dev\calcsvc


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         9/13/2021   8:35 PM                design
go: creating new go.mod: module calcsvc
go: to add module requirements and sums:
        go mod tidy


PS C:\Users\user\Dev\calcsvc> goa gen calcsvc/design
go get: malformed module path "goa259458615": missing dot in first path element
```

**Comment by raphael** [comment]
Could someone confirm that the fix above does indeed resolve the issue? I'll release 3.5.2 if that's the case. The fix is merged in the `v3`  branch. Thank you @nitinmohan87!

**Comment by Bird87ZA** [comment]
Not sure if I'm doing this right, but:

I deleted the `calcsvc` folder, then ran `go get -u goa.design/goa/v3/...@v3`. Then I did the step in the readme again. But I get the same error.

Like I said, not sure if I did it the right way, never had to `go get` from a branch.

**Comment by raphael** [comment]
One way to make sure the test uses the latest goa is to clone the goa repo and then use the [replace](https://golang.org/ref/mod#go-mod-file-replace) directive in the test `go.mod` file, for example:
```
module ...

go 1.17

require (
...
)

replace goa.design/goa/v3 => /home/raphael/src/goa
``` 
Edit: the fix applies to the `goa` command itself so it also needs to be reinstalled explicitly:
```
cd /home/raphael/src/goa/cmd/goa
go install
```
All of this assumes goa is checked out underl `/home/raphael/src` - adjust accordingly.

**Comment by Bird87ZA** [comment]
Can confirm that this works now. Thanks @raphael for the assistance and @nitinmohan87 for the fix!

**Comment by anassrakibi** [comment]
I confirm it's working now. Thanks a lot for your support guys

**Comment by anassrakibi** [comment]
@raphael do you have a plan when the new tag will be available?

**Comment by raphael** [comment]
Great, thanks for verifying - I'll release now.

**Comment by raphael** [comment]
v3.5.2 is live! thank you again @nitinmohan87.
