### ISSUE TITLE
goa.ServiceError doesn't have any information about nested fields

### ISSUE THREAD

**Issue by paprikati** [goadesign/goa#2922]
imagine a payload:
```
{
  "user": { "name": "I have a very long name" }
}
```

If the name is too long (lets say it should be 7 chars) then goa throws a `goa.ServiceError`.
However, that error has no information telling me it's inside user, the `Field` is just set to `name`.

The same problem happens if you are validating an array of objects - I believe that I have no way of knowing which item in the array caused the problem.

Is this supported in a way I don't understand, or is this something we might be able to add to the library?

**Comment by raphael** [comment]
You are correct that currently the ServiceError struct only keeps track of the inner field name. The PR https://github.com/goadesign/goa/pull/2902 adds a `Field` err... field to the `ServiceError` struct that contains the name of the field when relevant. It would probably make sense for `Field` to contain a path rather than just a name.

**Comment by paprikati** [comment]
awesome - @lawrencejones is actually my colleague so super glad that he's already looking at this.

**Comment by paprikati** [comment]
I wonder if we can alter that PR to make it a path before we cut a release? otherwise I suspect it'll be a breaking change

**Comment by lawrencejones** [comment]
As a caution, I thought about providing path when I wrote that PR, but it's quite difficult when you don't know the transport. 

We'll need to get smarter than I was to do that right, I think.

**Comment by raphael** [comment]
Yes if we make that change we should do it before the next release. The validation logic [recurses ](https://github.com/goadesign/goa/blob/v3/codegen/validation.go#L199) and [constructs](https://github.com/goadesign/goa/blob/v3/codegen/validation.go#L216) the path in a "context" argument, that might help with implementing this. Maybe that argument needs to become a slice. Right now the convention is to concatenate field names with `"."` and to append `"[]"` for slice elements.

**Comment by paprikati** [comment]
Yeah I think we will want to build this context up while we are validating the struct. I'm still fairly new to Go but if I get time next week I might try to get this working. Or if anyone else fancies it, please give it a shot!

**Comment by raphael** [comment]
It just occurred to me that #2820 seems to tackle the same issue and could be a good starting point.
