### ISSUE TITLE
Request tracing for v3?

### ISSUE THREAD

**Issue by xeoncross** [goadesign/goa#2925]
It looks like [tracing was a part of version 1](https://goa.design/blog/004-xray/), but I don't see anything in the [plugins for tracing for v3](https://github.com/goadesign/plugins). 

I'm sure users of Goa are using some kind of tracing, what should be used right now? 

It looks like the server code is supposed to be written by the implementer of Goa, is that where people should [add a middleware to inject tracing](https://github.com/goadesign/examples/blob/master/basic/cmd/calc/http.go#L77)?

**Comment by raphael** [comment]
Goa v3 supports tracing as well, it has [native support](https://pkg.go.dev/goa.design/goa/v3@v3.5.2/http/middleware/xray) for AWS X-Ray and defines [transport agnostic middlewares](https://pkg.go.dev/goa.design/goa/v3@v3.5.2/middleware) to create and propagate trace IDs in the request context. There is an [example](https://github.com/goadesign/examples/tree/master/tracing) as well. It would be great to add native support to other tracing tools such as [opentelemetry](https://opentelemetry.io/docs/go/getting-started/).
