### ISSUE TITLE
Clarification needed in v3 getting started doc

### ISSUE THREAD

**Issue by elisarver** [goadesign/goa#2926]
In section "4. Document" of README.md, the user is instructed to add a File server for the openapi files.

The instruction to run `goa gen calcsvc/design` updates the gen'd code, but it does not add a service constructor to the command. Adding the lines 

```go
+ import openapisvr "calcsvc/gen/http/openapi/server"
// Configure the mux.
	calcsvr.Mount(mux, calcServer)
+	openapisvr.Mount(mux, openapiServer)
```

Will not compile, because openapiServer does not exist. This may require further instruction to regenerate the example, which is not present in the document.

Deleting the cmd directory, and rerunning the example subcomand results in a working solution:

```go
	var (
		calcServer    *calcsvr.Server
		openapiServer *openapisvr.Server
	)
	{
		eh := errorHandler(logger)
		calcServer = calcsvr.New(calcEndpoints, mux, dec, enc, eh, nil)
		openapiServer = openapisvr.New(nil, mux, dec, enc, eh, nil, nil)
		if debug {
			servers := goahttp.Servers{
				calcServer,
				openapiServer,
			}
			servers.Use(httpmdlwr.Debug(mux, os.Stdout))
		}
	}
	// Configure the mux.
	calcsvr.Mount(mux, calcServer)
	openapisvr.Mount(mux, openapiServer)
```

**Comment by raphael** [comment]
Thank you for bringing this up. The way file servers work was changed in https://github.com/goadesign/goa/pull/2839 but the README wasn't updated. This is now [fixed ](https://github.com/goadesign/goa/pull/2927) and I also [updated](https://github.com/goadesign/examples/commit/42cc9484a13c4cbf19950d4068710c5b533e1165) the [basic](https://github.com/goadesign/examples/tree/master/basic) example to reflect the change accordingly.
