### ISSUE TITLE
Condition-enabled endpoints

### ISSUE THREAD

**Issue by ciolo** [goadesign/goa#2953]
Hi,
I would like to enable some endpoints via some conditions, for example by setting an environment variable. I know I have to interact with the `controllers.go` file but I don't want `goagen bootstrap` to overwrite the file every time. 

Goa version: `v1.4.2`.

**Comment by raphael** [comment]
`goagen bootstrap` is not meant to be run each time the design is changed. This is the reason for having two different commands. The ideas is that `bootstrap` provides an example but then the code needs to be maintained "manually" (should be tested etc.). So you should be able to implement your own `main.go` file that reads environment variables and mounts the proper endpoints accordingly.

**Comment by ciolo** [comment]
Thank u very much!
