### ISSUE TITLE
Static File Hosting Index.html

### ISSUE THREAD

**Issue by kmacmcfarlane** [goadesign/goa#2960]
I discovered a frustrating problem when implementing a simple file server for swagger docs on goa v3. It appears that because goa uses `http.ServeFile()` under the hood for requests with wildcards, requests to `/docs/index.html` were returning 301 redirects to `./`.

Adding a specific `Files()` directive for the index.html file fixes the issue.

According to the `http.ServeFile` documentation, an alternative would be to use `http.ServeContent`, or possibly to just include the index.html behavior in the godoc and `Files()` documentation?

This worked for me.
```
var _ = Service("swagger", func() {

	Description("The documentation service serves the API openAPI definition.")

	Files("/docs/openapi.json", "./gen/http/openapi.json", func() {
		Description("JSON document containing the API openAPI definition")
	})
	Files("/docs/index.html", "./public/docs/index.html", func() {
		Description("Swagger docs index.html")
	})
	Files("/docs/{*filepath}", "./public/docs", func() {
		Description("Swagger UI dist files for viewing the API documentation (i.e. what you are reading right now).")
	})
})
```

**Comment by raphael** [comment]
Thank you for the report, yes documenting this behavior makes sense - would you be able to take a crack at it?

**Comment by kmacmcfarlane** [comment]
I tried to make a PR, but I'm struggling with the new token-based auth. I'm trying to edit the File() commentary to read ```
// Files defines an endpoint that serves static assets via HTTP. The logic for
// what to do when the filename points to a file vs. a directory is the same as
// the standard http package ServeFile function. If you do not explicitly name
// index.html, it will be redirected to ./ The path may end with a
// wildcard that matches the rest of the URL (e.g. {*filepath}). If it does the
// matching path is appended to filename to form the full file path, so:
```

**Comment by kmacmcfarlane** [comment]
For what it's worth, this is the permissions error I get when I try to push a branch:
```
remote: Permission to goadesign/goa.git denied to kmacmcfarlane.
fatal: unable to access 'https://github.com/goadesign/goa.git/': The requested URL returned error: 403
```

**Comment by raphael** [comment]
I believe you need to push to a branch in your own cloned repo then create a PR from there. You can only push directly to a repo if you are a maintainer.

**Comment by kmacmcfarlane** [comment]
Okay, I forked and now I made a PR across the repos. Thanks!
https://github.com/goadesign/goa/pull/2962

**Comment by raphael** [comment]
Thank you for the PR!
