### ISSUE TITLE
request payload verification runs before security check

### ISSUE THREAD

**Issue by yokomotod** [goadesign/goa#2963]
For secure endpoints which have required attributes, 
I expected to get a `401 Unauthorized` error response for any request without credentials.

But in fact, it seems that `400 Bad Request` is returned if the payload is invalid.

Is this a behavior by design?
Also, is there any way to make it return `401`?

### reproduction:

with security example 

https://github.com/goadesign/examples/tree/v3.5.3/security

```diff
	Method("signin", func() {
		Description("Creates a valid JWT")

		Security(BasicAuth)

		Payload(func() {
			Description("Credentials used to authenticate to retrieve JWT token")
			UsernameField(1, "username", String, "Username used to perform signin", func() {
				Example("user")
			})
			PasswordField(2, "password", String, "Password used to perform signin", func() {
				Example("password")
			})
			Required("username", "password")

+			Attribute("a", Int, "required attribute")
+			Required("a")
		})

		Result(Creds)

		HTTP(func() {
			POST("/signin")
+			Param("a")
			Response(StatusOK)
		})

	})
```

invalid credentials, valid attributes: `401`

```
$ curl -v -XPOST --user foo:bar 'localhost:8000/signin?a=1'

< HTTP/1.1 401 Unauthorized
"invalid username and password combination"
```

invalid credentials, **invalid** attributes: `400`  => should be `401` ?

```
$ curl -v -XPOST --user foo:bar 'localhost:8000/signin'

< HTTP/1.1 400 Bad Request
{"name":"missing_field","id":"ddyRblXH","message":"\"a\" is missing from query string; invalid value \"\" for \"a\", must be a integer","temporary":false,"timeout":false,"fault":false}
```

Invalid credentials, invalid attributes (missing auth params): `400` => should be `401` ?

(for this case, we can make this to `401` by removing `Required("username", "password")`, though)

```
$ curl -v -XPOST 'localhost:8000/signin?a=1'

< HTTP/1.1 400 Bad Request
{"name":"missing_field","id":"F8p32Z0q","message":"\"Authorization\" is missing from header","temporary":false,"timeout":false,"fault":false}
```

**Comment by raphael** [comment]
The payload validation occurs during decoding which needs to happen first. For example if a type isn't correct then decoding isn't possible and it might not be possible to retrieve the security credentials necessary to do the auth. One way to work around this would be to add a HTTP middleware that does the auth first but that would mean not using the built-in security support.

**Comment by jtepe** [comment]
One could also provide a custom request decoder that checks for the header first, and only then delegates to the generated decoder.

**Comment by raphael** [comment]
I like that as you still get the benefits of using Goa with this approach.

**Comment by raphael** [comment]
Marking this as closed, https://github.com/goadesign/goa/issues/2963#issuecomment-1024348021 is a good way to enforce that the request carries credentials prior to decoding it.
