### ISSUE TITLE
Integration with sqlc?

### ISSUE THREAD

**Issue by xeoncross** [goadesign/goa#2968]
Unfortunately, Goa still requires writing some Go code. I'd like to stop this nonsense. Any chance of integrating [sqlc](https://github.com/kyleconroy/sqlc) so the entire application can be reduced to writing a [few SQL statements](https://play.sqlc.dev/)?

**Comment by raphael** [comment]
Haha! Goa does support [plugins](https://goa.design/extend/plugins/) which make it possible to both extend the DSL and produce different outputs. This sounds like a great application for it. There could be a simple `SQL` DSL function that accepts the SQL statements that the plugin would simply collect and call `sqlc` on. Maybe it generates some glue code between the service methods and the code generated  by `sqlc` as well (a bit like it does today with `protoc`). Thanks for bringing that up - I didn't know about `sqlc` - looks interesting. 

PS: And I can't wait for the days computers can read people's mind and autogenerate all the code (wait hmm there might be some downsides :) ).

**Comment by xeoncross** [comment]
Yes, it is an interesting problem to figure out the load order. The SQL statements will be processed by sqlc and the model/store interface and entity structs generated. Then you could parse the go code using the [stdlibs AST](https://pkg.go.dev/go/ast) and use that to generate the service code that goa would then parse to generate it's code. 

I don't think that you can run this inside the goa generation though as it has already scanned the source code by the time PrepareFunc is called - so it's too late to use the sqlc output. Perhaps I'm looking at this backwards and goa should be a plugin on sqlc, which unfortunately [doesn't intend to support plugins](https://github.com/kyleconroy/sqlc/issues/288).

**Comment by xeoncross** [comment]
My mistake, seems [times have changed](https://github.com/kyleconroy/sqlc/pull/1333)

> This will be helpful in the future when we have plugin support.

**Comment by danicc097** [comment]
It seems like times now have definitely changed and sqlc [supports plugins](https://github.com/kyleconroy/sqlc/issues/288) if anyone wants to give it a try
