### ISSUE TITLE
Enum Validation of ArrayOf()

### ISSUE THREAD

**Issue by kmacmcfarlane** [goadesign/goa#2981]
The godoc for the DSL `Enum()` directive states that it can validate on attributes that are arrays. Trying to do something similar to the example produces errors on generation. I'm on the latest version of Goa V3.

```
var payloadType = Type("BaseType", func() {

	Attribute("items", ArrayOf(String), func() {
		Enum("a", "b")
	})

	Required("items")
})
```

```
$ goa gen github.com/kmacmcfarlane/goa-repro/internal/api/design
exit status 1
[internal/api/design/foo.go:30] value "a" at index 0 is incompatible with attribute of type array in attribute
[internal/api/design/foo.go:30] value "b" at index 1 is incompatible with attribute of type array in attribute
```

The same issue is the case when using `CollectionOf(X)` as well.

It appears that at a minimum this validation code would need to "unwrap" Array(X) to just be X in order for `IsCompatible()` to return true.
https://github.com/goadesign/goa/blob/97ab3e46fc3d82bd52473318d2b1b89ccc0243dd/dsl/validation.go#L72

With a little guidance, I could probably add a test that covers this and modify the behavior with a PR.

Reproduction branch:
https://github.com/kmacmcfarlane/goa-repro/tree/enum-array-validation

**Comment by raphael** [comment]
Hello, this is already supported, the correct syntax is:

```go
var payloadType = Type("BaseType", func() {

	Attribute("items", ArrayOf(String, func() {
		Enum("a", "b")
	}))

	Required("items")
})
```

**Comment by kmacmcfarlane** [comment]
Ahh, thanks for the clarification!
