### ISSUE TITLE
Goa should find its own errors if wrapper when encoding errors

### ISSUE THREAD

**Issue by pbennett** [goadesign/goa#3000]
I have a layer of libraries and I might use the MakeXXX error helpers to return errors that then get 'wrapped' using fmt.Errorf(".... :%w", err) to salt the message

The generated EncodeError functions don't support wrapping though.
ie:
```go
func EncodeTestError(encoder func(context.Context, http.ResponseWriter) goahttp.Encoder, formatter func(err error) goahttp.Statuser) func(context.Context, http.ResponseWriter, error) error {
	encodeError := goahttp.ErrorEncoder(encoder, formatter)
	return func(ctx context.Context, w http.ResponseWriter, v error) error {
		en, ok := v.(ErrorNamer)
		if !ok {
			return encodeError(ctx, w, v)
		}
		switch en.ErrorName() {
```

Instead of [which would find the nested goa error] (and I believe this is correct but haven't patched/tested it)
```go
var en *ErrorNamer
if !errors.As(err, &en) {
	return encodeError(ctx, w, v)
}
switch en.ErrorName()
```

**Comment by jtepe** [comment]
I am unsure whether that would be a breaking change :thinking: 
Consider the possibility of present code returning an error that somewhere down the line wraps an error type with a `ErrorName()` method. It is not an unreasonable choice of name, so it might be the case that some third-party library does this.
But now you suddenly get the result of calling `ErrorName()` instead of the usual `encodeError` behavior.

That being said, I think this request warrants some thinking about.

**Comment by pbennett** [comment]
The issue is, by returning that error *to goa itself* it's automatically not going to know what to do with it and it will be a 500.  Ah, is that your point?  Perhaps they're returning a different error, outside of goa related errors intentionally and wanting that to be a 500?  I still don't see why that wouldn't just be returning a literal different error, not wrapping the goa error.
Considering goa is trying to determine if the error is one of 'its' errors - unwrapping seems appropriate.   It does seem prudent to give it some thought but on the surface it seems the right choice to unwrap.

**Comment by jtepe** [comment]
From what I understand is that you want to use `MakeXXXError` generated from Goa (thereby getting a Goa `ErrorNamer`) but wrapping it further in another error which you then return. As a result, Goa treats it as some other error and not as an `ErrorNamer` (even though it is wrapped in your error).

What I want to point out is that there might be some existing code relying on that behavior. It returns an error, that wraps an error having a method `ErrorName`. It used to return a 500, but now returns something different. That's highliy unlikely of course, given that the string returned by `ErrorName()` still has to match one of the `switch` cases. But it could be, and you'll suddenly have different behavior than before. So I'm unsure if that would be a breaking change if implemented.

But I am still in favor of this change. It does make sense.

**Comment by raphael** [comment]
Good suggestion @pbennett  and good point @jtepe. I went ahead and made the change given that the trade-off seems worth it - the original code was written prior to Go 1.13 when error wrapping was introduced. The next Goa release will be a minor version bump to indicate that there is a change.
