### ISSUE TITLE
Problems with custom error formatter

### ISSUE THREAD

**Issue by maxott** [goadesign/goa#3003]
The 'formatter' `var formatter func(err error) goahttp.Statuser` which I can provide when instantiating an HTTP handlers seems to serve two different duties which I can't reconcile.

I have a REST API with multiple services, each implementing a similar CRUD pattern. In defining the DSL I can take advantage of Go  modules to factor out all the common code. Unfortunately, code generation duplicates all the code under the different namespaces created for each service.

I further implemented authorization as Goa middleware. That works fine but in order to properly render errors in the middleware layer, I added the same error formatter to all service instantiations. Again, that works fine for those errors, but now ALL other errors are calling the same formatter:

```
func EncodeCreateError(encoder func(context.Context, http.ResponseWriter) goahttp.Encoder, formatter func(err error) goahttp.Statuser) func(context.Context, http.ResponseWriter, error) error {
	encodeError := goahttp.ErrorEncoder(encoder, formatter)
	return func(ctx context.Context, w http.ResponseWriter, v error) error {
		en, ok := v.(ErrorNamer)
		if !ok {
			return encodeError(ctx, w, v)
		}
		switch en.ErrorName() {
		case "invalid-parameter":
			res := v.(*order.InvalidParameterValue)
			enc := encoder(ctx, w)
			var body interface{}
			if formatter != nil {
				body = formatter(res)
			} else {
				body = NewCreateInvalidParameterResponseBody(res)
			}
			w.Header().Set("goa-error", res.ErrorName())
			w.WriteHeader(http.StatusUnprocessableEntity)

```

Double duty for formatter comes from being used in both `encodeError := goahttp.ErrorEncoder(encoder, formatter)` as well as for any 'named' error. In the former we need it to return `goahttp.Statuser` as we don't know the http status code. However, the return value in the latter use really only cares about a serializable `interface{}`. 

With the current design I cannot selectively choose which errors I want to custom handle. I seem to be forced to choose between none or all. In addition, I can't even call `NewCreateInvalidParameterResponseBody` from the formatter as it doesn't return `goahttp.Statuser`. No need for it as the http status code is set in the following generated code.

I tried to avoid using a custom formatter, but for the middleware to return a 'defined' error it would need to determine which service is being called and then return the appropriate error implementation from the respective module (the code and everything else is identical as it's defined in a 'common' place for all service. That is most likely the best 'hack' for my situation as I'm already doing a lot of type gymnastics on the implementation side to minimize code duplication due to identical code generated in different modules.

As for the 'all or none' issue above I wonder if the following change in the generated code would work:

```
                         var body interface{}
			if formatter != nil {
				body = formatter(res)
			} 
                         if body == nil  {
				body = NewCreateInvalidParameterResponseBody(res)
			}
```
In this case the formatter could simply return `nil` for all the error types it doesn't want to deal with, in which case it falls back on the default.

Just curious if I'm missing something here.

Otherwise, I really enjoy coding with Goa and I hope to find time to write a blog post on how I'm using it with Caddy.

**Comment by raphael** [comment]
Thank you for the detailed explanation, that all makes sense. The ability to format error code is indeed tricky to put in place specifically in middleware for the reason you mention.

The reason for generating multiple separate packages for each service is to ensure that there is no coupling with shared code at runtime, this means that services can be versioned independently for example. It also scopes user type identifiers to the service package so multiple services in the same design can define different user types with the same name (which can also happen automatically as user types get generated automatically for inline payload or result definitions).

That being said there could be a new metadata tag that one can add to tell Goa to generate a given user type in a specific package (that would have to live under the `gen` folder). It would become the responsibility of the user to make sure that name clashes do not happen. This would help for the case above where a common design is shared: the imported type would carry the metadata tag and thus be generated only once.

The change you are suggesting above also makes sense - I'd be happy to merge a PR that implemented it.

**Comment by maxott** [comment]
Thank you for the quick reply. I understand the rational for generating different modules, but in my case I already use common code in the DSL definition because it's also logically the same and therefore it's a 'materialised' architecture decision. 

Where would you suggest I should start with better understanding the code generation process? Beside the simple fix I sketched out above, I would also like to see if I can auto-generate the caddy plugin I'm currently just hand-code with lots of cut&paste.

**Comment by raphael** [comment]
The code generation algorithm is orchestrated by the [generator.Generate](https://github.com/goadesign/goa/blob/v3/codegen/generator/generate.go) method which is called by the generated codegen tool and imports the user design package. This code first runs the DSL which instantiates expression structs from the `expr` package. Once that's done it iterates through the generators passing the [root expression](https://github.com/goadesign/goa/blob/v3/expr/root.go#L16) to each. [Plugins](https://github.com/goadesign/plugins) may also register additional root expressions. The default generators are the [endpoints](https://github.com/goadesign/goa/blob/v3/codegen/generator/service.go) generator that generate the transport agnostic code, the [Transport](https://github.com/goadesign/goa/blob/v3/codegen/generator/transport.go) generator that generates the HTTP and gRPC code and the [OpenAPI](https://github.com/goadesign/goa/blob/v3/codegen/generator/openapi.go) generator. Plugins may also register additional generators. 

That's the high level - lots more details obviously but that should get you going :)

**Comment by maxott** [comment]
Thanks!
