### ISSUE TITLE
Unhelpful error (panic) from `goa gen`

### ISSUE THREAD

**Issue by williammoran** [goadesign/goa#3029]
I have no idea what I'm doing wrong that is causing this. Of course, it's particularly difficult to correct my mistake if the program panics instead of providing a helpful error message. Looking at the goa code, it appears that it doesn't like something about how I'm specifying my package name, but I have no idea what to do to correct this other than just randomly try stuff.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7502ba]

goroutine 1 [running]:
main.NewGenerator({0x7ffe7892f35a, 0x3}, {0x7ffe7892f35e, 0x22}, {0x7e7480, 0x1})
	/home/wmoran2901/go/pkg/mod/goa.design/goa/v3@v3.5.5/cmd/goa/gen.go:63 +0x19a
main.generate({0x7ffe7892f35a, 0x3}, {0x7ffe7892f35e, 0x22}, {0x7e7480, 0x1}, 0x0)
	/home/wmoran2901/go/pkg/mod/goa.design/goa/v3@v3.5.5/cmd/goa/main.go:82 +0xc8
main.main()
	/home/wmoran2901/go/pkg/mod/goa.design/goa/v3@v3.5.5/cmd/goa/main.go:62 +0x451

**Comment by raphael** [comment]
Agree that Goa should not panic! Hard to tell the root cause of the issue without an example though - could you provide steps to reproduce this?

**Comment by williammoran** [comment]
> Agree that Goa should not panic! Hard to tell the root cause of the issue without an example though - could you provide steps to reproduce this?

I'm not opening a bug report to request tech support for Goa. This is a bug report that `goa gen` can panic for unknown reasons. Looking at the code, there's a clear failure to ensure that something that _could_ be nil isn't. If `goa gen` said something like, "invalid something something specified" it would probably do a lot more toward identifying the root cause than any description I could give of what I'm doing.

The *reason* that I don't think my steps to reproduce will be helpful is that I went and tried to run `goa gen` on the basic example from goadesign's repo and go the same error. I find it unlikely that the problem is related to anything other than something in my environment. However, I have no idea what part of my environment would be helpful to you?

If you can run `goa gen` on https://github.com/goadesign/examples/tree/master/basic without getting this error, then you'll have to help me understand in more detail what information is helpful to you.
