### ISSUE TITLE
Context Header vs Header()

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#303]
With the current embedding of `RequestData` and `ResponseData` in contexts one cannot do `ctx.Header()` to retrieve the response headers because it clashes with the `RequestData` embedded `*http.Request.Header`. Maybe add a `ResponseHeader()` and `RequestHeader` functions to `ResponseData` and `RequestData` respectively.

**Comment by abourget** [comment]
`goa.Response(ctx).Header()` does the job quite well..

**Comment by raphael** [comment]
Closing this as the plan going forward is to break out the context, see the [roadmap](roadmap.md).
