### ISSUE TITLE
Error types aren't documented properly in the openapi spec

### ISSUE THREAD

**Issue by pbennett** [goadesign/goa#3037]
The following dummy design.go file:

```go
package design

import (
	"net/http"

	. "goa.design/goa/v3/dsl"
	_ "goa.design/plugins/v3/zaplogger" // Enables the plugin
)

var _ = API(
	"dummy", func() {
		Server("testapi", func() {
			Host("localhost", func() {
				URI("http://localhost:80")
			})
		})
	},
)

var _ = Service(
	"dummy", func() {
		// Define top level errors and their default HTTP status codes when returned
		Error("someTestError", func() {
			Description("This description should be repeated in all references to the error in the openapi specs")
		})
		HTTP(func() { Response("someTestError", http.StatusNotAcceptable) })
		Error("anotherTest", func() {
			Description("This error should apply to every method")
		})

		Method("methodA", func() {
			Description("methodA test")
			Result(Boolean)
			HTTP(func() {
				GET("/methodA")
				Response(StatusNoContent, func() {
					Body(Empty)
				})
				Response("someTestError", http.StatusConflict)
			})
		})
		Method("methodB", func() {
			Description("methodB test")
			Result(Boolean)
			HTTP(func() {
				GET("/methodB")
				Response(StatusNoContent, func() {
					Body(Empty)
				})
				Response("anotherTest", http.StatusForbidden, func() { Description("Only this description shows up") })
			})
		})
	})
```

Produces openapi specs that have no mention anywhere of any of the error names, the methods possibly returning them (methods only listing the status code responses to generic errors), nor the descriptions provided.  Only the error in methodB has its description documented (even though it should have been inherited from the early definition).  Even then, the generated example error is always identical:
```
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
```

Particularly for common errors, they should be able to be defined as part of an API (particularly when its a possible return to many methods) and the error name and description should flow into the openap spec across all methods.

**Comment by raphael** [comment]
Thank you for the report, #3038 should address these issues. It removes the generation of examples altogether for error responses as there is no good way to guess a good message in general. The change adds the error name to the response description and takes into consideration the error description if there is one.
