### ISSUE TITLE
Metadata, tweak syntax for extensibility and simplicity

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#305]
We'd like to have something like:

    Metadata("struct:tag:json", "boo")
    Metadata("struct:tag:xml", "mama")

    Metadata("swagger:tag:backend", "Backend")
    Metadata("swagger:tag:backend:doc", "Big documentation")
    Metadata("swagger:tag:backend:url", "http://example.com")

This would introduce the convention of namespaces split by `:`.

This changes only slightly what is already there with the latest Metadata changes. It's more of a refinement than a big change.

I'll take a bit at it when I have a moment.

**Comment by raphael** [comment]
Looks great, thanks!
