### ISSUE TITLE
Custom authentication messages are not supported

### ISSUE THREAD

**Issue by eline001** [goadesign/goa#3064]
Custom authentication messages are not supported

**Comment by raphael** [comment]
Can you elaborate a bit? the way security works the service code implements the auth handler and can return any message/status code is appropriate.

**Comment by eline001** [comment]
eg: 

i am desiged  a param is  

```
Attribute("name", String, "coupon_name", func() { MaxLength(20) })
Required("name")
````
it notify  "required name an object" to me when I send request ,   but I want to get a message is "字段 name 不能为空"

**Comment by eline001** [comment]
![1652193001(1)](https://user-images.githubusercontent.com/74693301/167653151-22b64bb6-a2b3-44a3-b075-4fc9d58f9c6c.png)

I  see this code is hard code in funxtion

**Comment by raphael** [comment]
The last section of https://goa.design/implement/error_handling/ ("Overridding Validation Errors Serialization") shows how to use the error formatter to override the generated error messages. Maybe that works for you?

**Comment by eline001** [comment]
oh~, yes , ok, thanks
