### ISSUE TITLE
Using `HashOf()` prevents generation of a swagger file.

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#307]
The `GenerateExample` code makes an example a `map[interface{}]interface{}`.. and this doesn't compile through `json.Marshal()`.

Thus, when using `HashOf`, setting an explicit `Example(map[string]interface{}{"something": 123})` in the `Attribute()` definition will bypass the creation of the generated example, and thus at least work.

Ideally, we wouldn't need to set an example, but we'd have a generated example, or have the `map[interface{}]interface{}` automatically translated to a `map[string]interface{}` in the swagger generation. It would, in any case, be invalid Swagger to have an object that doesn't have a string as a key.

**Comment by raphael** [comment]
Thanks for the report! @DavyC do you think you could take a look?

**Comment by raphael** [comment]
@abourget did the fix above help?
