### ISSUE TITLE
Get matched pattern based on request

### ISSUE THREAD

**Issue by kun-qian** [goadesign/goa#3071]
Hello,

I've a request of getting matched endpoint pattern based on incoming request. I was looking into the `mux` struct  but it's unexported. 
Can someone give some suggestions of how to achieve that?

**Comment by raphael** [comment]
Goa generates [code](https://github.com/goadesign/examples/blob/master/basic/gen/http/calc/server/server.go#L51) that expects an implementation of the [Muxer interface](https://github.com/goadesign/goa/blob/v3/http/mux.go#L13-L51). The default implementation uses the private `mux` struct but your code can provide a different implementation. You might be able to follow the same pattern of wrapping a `httptreemux.ContextMux` and overriding / decorating as needed.
