### ISSUE TITLE
invalid host argument doesn't exit the process

### ISSUE THREAD

**Issue by nya1** [goadesign/goa#3077]
With the default auto-generated server code when providing an invalid host argument the server is not automatically exiting, only the error message is printed.

Example
  - code: https://github.com/goadesign/goa/blob/e1bc1170dc3668e2096147254e3db57ad3cef411/codegen/example/testdata/example_server_code.go#L112-L114
  - cli argument: `--host test.com`

I think the process is up waiting for a cancellation signal that is not triggered for this scenario, a `os.Exit(1)` after the print should stop the process and resolve the issue.

**Comment by raphael** [comment]
Hmm yeah maybe this should use `logger.Fatalf` instead, would you mind putting together a PR? Thank you!
