### ISSUE TITLE
Make function for custom error type not generated

### ISSUE THREAD

**Issue by avucic** [goadesign/goa#3087]
I follow documentation https://goa.design/implement/error_handling/ and section `Producing Errors` explains that generator should generate `MakeDivByZero` function. However I found that is not the case. I also tried example project [`examples/error` ](https://github.com/goadesign/examples/tree/master/error)but it looks related function is not generated either. I can see only `MakeTimeout` function generated. Am I missing something? How I can extend default error with custom fields?

I'm the newcomer for Go/Goa. I apologize if I miss some obvious things.

Thanks in advance

**Comment by raphael** [comment]
Goa only knows how to create errors of type `ErrorResult`. So if the code uses a custom error type it won't generate a `Make` method for it. Instead the user code can create such a method or use inline declarations.
