### ISSUE TITLE
v3: https scheme does not lead to the call of ListenAndServeTLS() method

### ISSUE THREAD

**Issue by pablomadoeryunc** [goadesign/goa#3091]
Hello, 
I am trying to use the https scheme so I included it in my API design.
From [this link](https://medium.com/rungo/secure-https-servers-in-go-a783008b36da) I understand that the ListenAndServeTLS() method should be called in the cmd/server/http.go generated file. 
However I continue seeing the ListenAndServe() method being called instead. 

Now I am planning to manually modify this generated file to call the ListenAndServeTLS() method and to pass the KEY and CERTIFICATE. Is there another way or a better way of doing this ?.

Thank you very much.

**Comment by raphael** [comment]
Hello, the example generated by `goa example` is just that - an example. The idea is that this code should be modified appropriately, tested etc. In particular, this command should not be re-run when modifying the design (but the `goa gen` command should and the code generated by the `goa gen` command should not be modified, tested etc.). For instance, the [clue weather example](https://github.com/goadesign/clue/tree/main/example/weather) uses a different way to write main files.

**Comment by pablomadoeryunc** [comment]
Thank you very much for clarifying this Raphael !
