### ISSUE TITLE
Add `GoaErrorName` as a replacement for `ErrorName`

### ISSUE THREAD

**Issue by ernesto-jimenez** [goadesign/goa#3105]
### What do we want to do?

We have a middleware that captures unexpected errors and sends them to our error reporting infrastructure.

So far, we had been using `errors.As(err, *goa.ServiceError)`. However, we are now defining some custom error types and we would like to avoid a massive type switch.

We would prefer a type check with an interface, such:

```go
type isGoaError interface {
  IsGoaError() bool
}

func middleware(...) ... {
  // ...
  if _, ok := err.(isGoaError); !ok {
    report(error)
  }
}
```

### Proposal

- Add `func (*goa.ServiceError) IsGoaError() bool`
- Generate the `IsGoaError` method for types with `Meta("struct:error:name")` (maybe `struct:error:type` instead?)
- Add some documentation. (where would be the right place?)

**Comment by raphael** [comment]
Having a simple way to check whether an error is a "design" error would be quite valuable. Looking into this I'm realizing that we may already  have it though: Goa already generates a `ErrorName() string` method on error types and this method also exists on the `ServiceError` struct. So maybe this proposal could be simply achieved by making the `ErrorNamer` interface more explicit (e.g. by defining it in the Goa package). If we had that code could do:
```go
if _, ok := err.(goa.ErrorNamer); !ok {
    report(error)
}
```
I guess this is slightly less explicit than `IsGoaError` but not having to introduce another concept seems worth it. The semantic of `ErrorName` is "name of error in the design" which is pretty Goa specific.

**Comment by ernesto-jimenez** [comment]
We looked at `ErrorName`, but any 3rd-party package could be returning an error that satisfies the `ErrorNamer` interface. It might be a way to filter things now (would need to check whether we use any packages that return errors that satisfy that interface), but it's an unsafe way to check whether something is a goa error.

**Comment by raphael** [comment]
Yeah I get the theoretical issue, I wonder how realistic it is though (at the end of the day a non-Goa error could also implement `IsGoaError` - the only "extra guarantee" is the lower likelihood). `ErrorName` might sound fairly generic but then again it would be interesting to do a quick survey. Another aspect that doesn't seem great about `IsGoaError` is that the return value is not super well defined. What would be the meaning of an implementation that returned `false`? does code need to call it to make sure it's true or is a type-check sufficient?  If we think `ErrorName` doesn't cut it then I'd be more in favor of deprecating it and renaming it to e.g., `GoaErrorName` (we'd leave the previous implementation, but it'd just call the new method).

**Comment by ernesto-jimenez** [comment]
Agreed. Adding `GoaErrorName()` and deprecating `ErrorName()` would probably be better.

`IsGoaError() == false` could be confusing, and having it be a method without a return might be even more confusing.
