### ISSUE TITLE
OK context responses with collections should use pointers

### ISSUE THREAD

**Issue by pzingg** [goadesign/goa#311]
I admit I'm a go newbie, but I found this discussion in Effective Go:

> There are major differences between the ways arrays work in Go and C. In Go,
> ...if you pass an array to a function, it will receive a copy of the array, not a pointer to it.
> The value property can be useful but also expensive; if you want C-like behavior and efficiency, you can pass a pointer to the array.

So I was wondering whether the `goagen` code that's emitted for `CollectionOf(MediaType)` in app/contexts.go, as used in a "list" operation, should have a signature like:

`func (ctx *ListBottleContext) OK(r *GoaExampleBottleCollection) error`

rather than

`func (ctx *ListBottleContext) OK(r GoaExampleBottleCollection) error`

where we have defined

`type GoaExampleBottleCollection []*GoaExampleBottle`

Right now, if you have large collections to return, I guess the generated code copies a (potentially large) array of pointers, which may not be that expensive, but if the code passed a pointer to the array (of pointers to media type structs), you would save that copying. I realize this will probably break code, but just a thought...

**Comment by raphael** [comment]
I would recommend you go over this: http://blog.golang.org/go-slices-usage-and-internals.
The generated code uses slices which point to the arrays.

**Comment by pzingg** [comment]
Thanks for the clarification (I guess I need to read a lot more go code to
understand when you can safely drop the asterisk, and the fact that almost
anytime you work with an array, you end up making a slice).

--
Peter Zingg
Technology Coordinator
Kentfield School District
