### ISSUE TITLE
Access http.Request from OAuth2 Security function

### ISSUE THREAD

**Issue by sherodtaylor** [goadesign/goa#3110]
I'm trying to access the `http.Request` from the OAuth2 service implementation. I want to pull some details from the object. Basically I want to check if there is a cookie auth and it requires an `http.Request` object.

generated security interface
```
type Auther interface {
	// OAuth2Auth implements the authorization logic for the OAuth2 security scheme.
	OAuth2Auth(ctx context.Context, token string, schema *security.OAuth2Scheme) (context.Context, error)
}
```

Can you pull the `http.Request` from `ctx`?

**Comment by raphael** [comment]
Yes, one can mount a HTTP middleware such as https://github.com/goadesign/goa/blob/v3/http/middleware/request.go to populate the context with the data needed by the security handler.
