### ISSUE TITLE
No mandatory field validation in generated grpc server

### ISSUE THREAD

**Issue by leedgbr** [goadesign/goa#3116]
From what I can see in the documentation I can find, it looks like I would expect `goa` to generate some logic on the server side to ensure that a `required` field is present in the request.  The definition below includes a `required` field `input_field`.  However, no such validation logic is generated for this field when I run `goa gen` on it.  Is this expected behaviour?  Am I doing this correctly?

```
package design

import (
	. "goa.design/goa/v3/dsl"
	_ "goa.design/plugins/v3/docs"
)

var _ = API("API", func() {
	Server("server", func() {
		Services("service")
	})
})

var _ = Service("service", func() {
	Method("operation", func() {
		Payload(APIRequest)
		StreamingResult(APIResponse)
		GRPC(func() {
			Response(CodeOK)
			Response("missing_field", CodeInvalidArgument)
		})
	})
	Error("missing_field")
})

var APIRequest = Type("APIRequest", func() {
	Field(1, "input_field", String, func() {})
	Required("input_field")
})

var APIResponse = Type("APIResponse", func() {
	Field(1, "id", String, func() {})
})
```

**Comment by raphael** [comment]
This should generate code that validates in the gRPC server type. This code is called from the gRPC decoder. Example: https://github.com/goadesign/examples/blob/058d812cfe7cebf66daa6389a38c3907464a8266/cellar/gen/grpc/storage/server/types.go#L310

**Comment by leedgbr** [comment]
Thanks for your prompt response.  Searching for references to `goa.MissingFieldError` under the [https://github.com/goadesign/examples/tree/master/cellar/gen](https://github.com/goadesign/examples/tree/master/cellar/gen) directory reveals that there are many more references under `http` than there are under `grpc`.  For example, there is no `grpc` code to return a `goa.MissingFieldError` for the  `name` field on `Bottle` in the request (which is defined as required in the goa contract), whereas there is for `http`?

**Comment by raphael** [comment]
Ah I understand now! Yes, Goa generates less validations for gRPC because the transport does not allow to differentiate between a missing or a zero value (e.g. https://github.com/goadesign/examples/blob/master/cellar/gen/grpc/storage/pb/goadesign_goagen_storage.pb.go#L124 is not a pointer). See https://github.com/goadesign/goa/issues/2221 for a proposal that isn't implemented yet that would make it possible to make that distinction (by allowing to define non-zero default values in the design).

**Comment by leedgbr** [comment]
Thank you.  That's great.
