### ISSUE TITLE
Generated grpc client does not seem to be mapping errors correctly

### ISSUE THREAD

**Issue by leedgbr** [goadesign/goa#3117]
In the scenario where a generated grpc server returns an error using the generated methods, e.g.:

```
type svc struct{}

func (s *svc) Operation(ctx context.Context, req *service.APIRequest, res service.OperationServerStream) (err error) {
        // do no processing - just return a missing field error to illustrate the case
	return service.MakeMissingField(errors.New("input_field"))
}
```

When serving requests, the generated `service.MakeMissingField` function is called to create a `goa.ServiceError`.  The goa generated server side code is then mapping this to a `status.Error` with the status that was defined in the api contract.  This is then put onto the wire via `protobuf` by the server.  This is all fine.

The issue is in the error handling of the generated client.  When using the generated grpc client to handle such a response, we first get the output stream for the request...

```
stream, err := serviceClient.Operation(ctx, &service.APIRequest{})
```

And then call `Recv()` to get the first result...

```
response, err := stream.Recv()
```

It is at this point that the error is returned by the client.  The error returned is a `status.Error`, rather than the original `goa.ServiceError`.  This means that the consumer needs to then somehow map the `status.Error` into a `goa.ServiceError`.  It seems that there is some logic in the generated client to perform this error mapping, as shown below.  However, this seems to be applied at the first step of receiving the output stream, rather than the second step of calling `stream.Recv()` to read the first response item.

Is someone able to clarify what the expected behaviour is here?  It seems the consumer using the generated grpc client code would ideally not need to deal with `status.Error`, and would only deal with `goa.ServiceError`?

```
// Operation calls the "Operation" function in servicepb.ServiceClient
// interface.
func (c *Client) Operation() goa.Endpoint {
	return func(ctx context.Context, v interface{}) (interface{}, error) {
		inv := goagrpc.NewInvoker(
			BuildOperationFunc(c.grpccli, c.opts...),
			EncodeOperationRequest,
			DecodeOperationResponse)
		res, err := inv.Invoke(ctx, v)
		if err != nil {
			resp := goagrpc.DecodeError(err)
			switch message := resp.(type) {
			case *goapb.ErrorResponse:
				return nil, goagrpc.NewServiceError(message)
			default:
				return nil, goa.Fault(err.Error())
			}
		}
		return res, nil
	}
}
```

**Comment by raphael** [comment]
Yes currently Goa only allows specifying errors returned by the initial method call. We would need to introduce something like `StreamingError` in the DSL to allow defining errors that can be returned by the `Recv` method (and this would have to be implemented for both gRPC and Websockets). This would be a great contribution.

**Comment by leedgbr** [comment]
Thank you for your response.  That explains it :)
