### ISSUE TITLE
v3.8.0 and after is non-fast-forard to v3.7.14 

### ISSUE THREAD

**Issue by tchssk** [goadesign/goa#3118]
It seems all of commit hash in v3 branch were changed, therefore all past tags were gone from the branch.
We would need to fix it.

My clone of v3 branch is here. https://github.com/tchssk/goa/tree/v3

**Comment by raphael** [comment]
Apologies for the mess. I was trying to remove binaries from the history, but this is causing too many problems. I restored the original tree and released v3.8.2.

**Comment by tchssk** [comment]
Thank you. I was able to merge to the existing branch. v3.8.0 and v3.8.1 are still in another commit history, but it seems difficult to fix, so It's OK. Thank you to quick fix!
