### ISSUE TITLE
Union attributes are not described by the OpenAPI specification

### ISSUE THREAD

**Issue by sevein** [goadesign/goa#3129]
Types that are only used as union attributes are not being described by Goa in the OpenAPI specification.
That makes sense given that they map as JSON-encoded strings, but it would be useful to have a mechanism that can be used to force a type to appear in the spec. I have tried both `type:generate:force` and `openapi:generate` with no luck.

Link to [conversation in Slack](https://gophers.slack.com/team/U043DU7LM).

Thank you!

**Comment by raphael** [comment]
#3142 makes the OpenAPI v3 spec generator generate schemas for "forced types" (i.e. types that have the `"generate:type:force"` metadata).
