### ISSUE TITLE
Attributes using struct:field:type can't always be used in route expressions

### ISSUE THREAD

**Issue by sevein** [goadesign/goa#3130]
I've been using `struct:field:type` successfully with some type attributes.

I've found one situation that produces un-buildable code, when these three conditions are true:
* The attribute using `struct:field:type` belongs to a `Payload` and,
* It's part of a route expression (e.g. `GET("/{id}")` and,
* The underlying type is not a string, (e.g. `uuid.UUID` is a `[16]byte`).

For example, in the following method, `id` is a `uuid.UUID` ([github.com/google/uuid](https://github.com/google/uuid)) and it's used in the `/{id}` route:

```go
Method("show", func() {
	Description("Show bottle by ID")
	Payload(func() {
		Field(1, "id", String, "ID of bottle to show", func() {
			Meta("struct:field:type", "uuid.UUID", "github.com/google/uuid")
		})
		Field(2, "view", String, "View to render", func() {
			Enum("default", "tiny")
		})
		Required("id")
	})
	Result(StoredBottle)
	Error("not_found", NotFound, "Bottle not found")
	HTTP(func() {
		GET("/{id}")
		Param("view")
		Response(StatusOK)
		Response("not_found", StatusNotFound)
	})
	GRPC(func() {
		Metadata(func() {
			Attribute("view")
		})
		Response(CodeOK)
		Response("not_found", CodeNotFound)
	})
})
```

These are the errors that I am seeing:

```
# goa.design/examples/cellar/gen/grpc/storage/server
grpc/storage/server/types.go:65:17: cannot convert message.Id (variable of type string) to type uuid.UUID
# goa.design/examples/cellar/gen/grpc/storage/client
grpc/storage/client/cli.go:46:17: cannot convert message.Id (variable of type string) to type uuid.UUID
grpc/storage/client/types.go:64:14: cannot convert payload.ID (variable of type uuid.UUID) to type string
```

It's not a deal breaker, but if there was interest in supporting this case I'm wondering if Goa could try to check if the type implements `encoding.TextMarshaler` or `encoding.TextUnmarshaler` and use them when available.

**Comment by raphael** [comment]
In the past I have tried implement a generic mechanism where it would be possible to provide marshaling/unmarshaling functions for custom types but that ended up adding a lot of complexity and in the end the trade-off just didn't seem worth it. So at this time it is the responsibility of the (Goa) end user to provide types that are compatible with the built-in marshaling/unmarshaling logic. Something that we may want to revisit in v4 :)

**Comment by sevein** [comment]
That makes sense, thank you!
