### ISSUE TITLE
Issues of the example generator

### ISSUE THREAD

**Issue by noblehng** [goadesign/goa#314]
First, in `design/example.go`:
* I think there is a typo [here](https://github.com/goadesign/goa/blob/07928cc4306802d5efe840d64d3b6fa05a0e3e64/design/example.go#L81), `minlength` should be `maxlength`. 
* And [this](https://github.com/goadesign/goa/blob/07928cc4306802d5efe840d64d3b6fa05a0e3e64/design/example.go#L99) could make a huge slice and cause OOM error.

Second, in `design/definitions.go`:
* The MakeMap() function [here](https://github.com/goadesign/goa/blob/07928cc4306802d5efe840d64d3b6fa05a0e3e64/design/definitions.go#L157) will panic if either the key or the value is nil.
* In the same switch of the above line, `AnyKind` isn't handled. I think one could just set `a.isCustomExample = true` for `AnyKind`.

**Comment by raphael** [comment]
Thank you for the detailed report! @DavyC sorry to bug again but would you have time to look into these? thank you!

**Comment by DavyC** [comment]
Yap, my fault. Thanks for catching those.

**Comment by DavyC** [comment]
Regarding to the OOM issue, perhaps, one solution would be to generate <10 examples in the array, in case e.g. `MinLength(1000)` or higher is given. Unfortunately, the example is no longer valid at this point... but an example with 1000 items in an array doesn't make too much sense either.

**Comment by noblehng** [comment]
I got the OOM error when using a large MaxLength(), something like `MaxInt32`.

**Comment by raphael** [comment]
Limiting to 10 max is probably good enough.

**Comment by raphael** [comment]
Thanks @DavyC !
