### ISSUE TITLE
About the error return parameter problem

### ISSUE THREAD

**Issue by isqiguo** [goadesign/goa#3145]
// Login implements Login.
func (s *abcsrvc) Login(ctx context.Context, p *abc.LoginPayload) (res *abc.LoginResult, err error) {
	res = &abc.LoginResult{}
	fmt.Println(p.Account, "::::", p.Password)
	is := true
	res.ID = is
	return res, errors.New("error")
}

The error I want is
{
    "code": 200,
    "msg": "",
    "data": null,  // interface{}
    "success": true
}

actual error return
{
    "name": "fault",
    "id": "evRYMdXV",
    "message": "error",
    "temporary": false,
    "timeout": false,
    "fault": true
}

请问怎么去更改呢？

**Comment by shivuslr41** [comment]
@isqiguo, The description is not very clear to understand the problem/issue!

If you are interested in having custom errors for your service, you can refer goa/examples/error design https://github.com/goadesign/examples/tree/master/error
