### ISSUE TITLE
Generate Tests for some/all things?

### ISSUE THREAD

**Issue by bketelsen** [goadesign/goa#315]
Moving a slack conversation to an issue so we can document thoughts better.

**Comment by bketelsen** [comment]
I would like to generate tests for controllers specifically, perhaps using generated(test?) data.
given this goa definition, I should get this response from a mocked controller.

I would also like to generate better integration tests for goa/gorma

**Comment by alaska** [comment]
I would like to test that, given valid input, valid data is returned.  I'm aware of the difficulties in generating this sort of test without access to the data, but I feel like decent skeletons could at least be generated and helper methods provided to do data validation.  Specifically, one of the things you often want are smoke tests that verify that some important correlation between search/mutation and data returned still holds (i.e. "I searched for items where the person is over 45 and interested in chess, verify this in the results I've retrieved")

**Comment by bketelsen** [comment]
@alaska would those tests not be dependent on the storage engine?

**Comment by alaska** [comment]
Yes and no?  I feel like the API is your promise that, given this request, you will do that thing, and the storage engine is how you accomplish that.  Plus, you might want to test that you are correctly interacting with your storage engine to accomplish what you want.  There are a lot of places this could go, and I'm interested in starting the discussion.  Some random ideas:

- Auto-generate route-level skeletonized testing using the base Go testing suite with examples of what kind of things you might do
- as above, but allowing for the option of a small variety (or be opinionated and pick one) of testing frameworks.
- auto generate benchmark skeletons for all routes.

**Comment by raphael** [comment]
Closing this as `goagen` now generates test helpers which allow setting up component level tests very easily. Create new issues with details if there is a need for more.
