### ISSUE TITLE
Goa attribute validation "ExclusiveMinimum" is not exclusive

### ISSUE THREAD

**Issue by KamenPNikolov** [goadesign/goa#3160]
Hello, 

Thank you guys for the awesome work, we appreciate it. While working with GOA I have recently stumbled upon a bug concerning the exclusive minimum when it comes to attribute validation. More specifically, the exclusive minimum behaves as an inclusive one - the value provided is still validated as if desired. The following DSL validates 0 as a proper value: 

var ExchangeRate = Type("ExchangeRate", func() {
	Attribute("rate", Float64, "Exchange rate for the currency.", func() {
		ExclusiveMinimum(0)
	})
})

Upon a request with a negative value, the message displayed also hints at non-exclusivity: "rate must be greater **or equal** than 0 but got value -0.1" e.g.

Thank you for your time.

**Comment by raphael** [comment]
Can you please provide a complete design that reproduces the issue? thank you!

**Comment by Bo0mer** [comment]
Here's a demo design file that I've used to reproduce the issue:

```go
package design

import . "goa.design/goa/v3/dsl"

// API describes the global properties of the API server.
var _ = API("calc", func() {
	Title("Calculator Service")
	Description("HTTP service for multiplying numbers, a goa teaser")
	Server("calc", func() {
		Host("localhost", func() { URI("http://localhost:8088") })
	})
})

// Service describes a service
var _ = Service("calc", func() {
	Description("The calc service performs operations on numbers")
	Method("multiply", func() {
		Payload(func() {
			Attribute("a", Int, "Left operand", func() {
				ExclusiveMinimum(0)
			})
			Attribute("b", Int, "Right operand")

			Required("a", "b")
		})
		Result(Int)
		HTTP(func() {
			GET("/multiply/{a}/{b}")
			Response(StatusOK)
		})
	})
})
```

`a` should have validation that it is strictly >0. But here is the generated code from `DecodeMultiplyRequest` in `server/encode_decode.go`:

```go
return func(r *http.Request) (interface{}, error) {
		var (
			a   int
			b   int
			err error

			params = mux.Vars(r)
		)
		{
			aRaw := params["a"]
			v, err2 := strconv.ParseInt(aRaw, 10, strconv.IntSize)
			if err2 != nil {
				err = goa.MergeErrors(err, goa.InvalidFieldTypeError("a", aRaw, "integer"))
			}
			a = int(v)
		}
		if a < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError("a", a, 0, true))
		}
		{
			bRaw := params["b"]
			v, err2 := strconv.ParseInt(bRaw, 10, strconv.IntSize)
			if err2 != nil {
				err = goa.MergeErrors(err, goa.InvalidFieldTypeError("b", bRaw, "integer"))
			}
			b = int(v)
		}
		if err != nil {
			return nil, err
		}
		payload := NewMultiplyPayload(a, b)

		return payload, nil
	}
```

Namely
```
		if a < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError("a", a, 0, true))
		}
```

So if `a` equals zero this won't return an error (but it should as zero should be excluded by ExclusiveMinimum.

Best,
Ivan

**Comment by raphael** [comment]
Thank you for the nice repro! this is fixed by https://github.com/goadesign/goa/pull/3184
