### ISSUE TITLE
v3: client/encode_decode.go has a type mismatch error

### ISSUE THREAD

**Issue by daegalus** [goadesign/goa#3166]
I was generating my code, and I am getting a weird type mismatch error.

in the `client/encode_decode.go` for a service, the `BuildUpdateRequest` tries to set a `*string` into a `string`

```go
func (c *Client) BuildUpdateRequest(ctx context.Context, v interface{}) (*http.Request, error) {
	var (
		id string
	)
	{
		p, ok := v.(*test.TestPayload)
		if !ok {
			return nil, goahttp.ErrInvalidType("test", "update", "*test.TestPayload", v)
		}
		id = p.ID // <<< Here is where the error happens
	}
```

The Error:
```
cannot use p.ID (variable of type *string) as string value in assignmentcannot use p.ID (variable of type *string) as string value in assignment
```

The thing is. the `delete` and `show` methods i added, that are nearly identical, outside of using DELETE and GET as their HTTP methods, work fine. `update` uses PUT

I have created an example repo where I reproduce the error here: https://github.com/Daegalus/goa-bug-example

If you run `goa gen test/design` and go into `gen/test/client/encode_decode.go` you will see the error.

I assume it is something to do with the `PUT` function. the `show` function is identical minus the `GET` function.

This happens in v3.9.1 and v3.10.0

**Comment by daegalus** [comment]
Looks like I made a typo in the `show` design definiton. Both `show` and `update` exhibit the error.

Might be related to the `Reference()` in the Result type `testMedia` pointing to `testPayload`, then using both in the Method definition appropriately.

**Comment by raphael** [comment]
Thank you for the nice repro, this is fixed by https://github.com/goadesign/goa/pull/3170. Just a note that it isn't necessary to call out path parameters as being required. Goa will treat all path parameters as required by default (since they have to be provided in the first place for the method to be even called).

**Comment by daegalus** [comment]
Thank you for the prompt fix. 

And that makes sense. This is my first time using Goa and I'm upgrading a code base from v1 to v3, so it's been an adventure.
