### ISSUE TITLE
how to assign the valida error 

### ISSUE THREAD

**Issue by nieshaoyu** [goadesign/goa#3183]
like :
MinLength(1)
MaxLength(8)
the result is 
`{
    "name": "invalid_length",
    "id": "rMVdnPeq",
    "message": "length of body.name must be lesser or equal than 8 but got value \"more than eight char\" (len=20)",
    "temporary": false,
    "timeout": false,
    "fault": false
}`

i want 
`{
    "name": "invalid_length",
    "id": "rMVdnPeq",
    "message": "the error message i wantd",
    "temporary": false,
    "timeout": false,
    "fault": false
}`

thanks!

**Comment by raphael** [comment]
Take a look at the last section of https://goa.design/implement/error_handling/ (Overridding Error Serialization). The code can provide a custom formatter to change how errors are returned.

**Comment by nieshaoyu** [comment]
Thank you very much
