### ISSUE TITLE
Broken references to user types used within other user types that have a struct:pkg:path Meta() tag

### ISSUE THREAD

**Issue by c-reeder** [goadesign/goa#3198]
When using a line like:

```
	Meta("struct:pkg:path", "types")
```

within a user type definition that contains an attribute of _another_ user type, a compilation error occurs in the struct definition because the package of the second type has not been imported in that file.

Example:
```
var FirstType = Type("FirstType", func() {
	Meta("struct:pkg:path", "types")
	Attribute("id", String)
	Attribute("name", String)
	Attribute("description", String)
	Attribute("thing", SecondType)
})

var SecondType = Type("SecondType", func() {
	Attribute("Description", String)
})
```

yields

```
package types

// FirstType is the payload type of the TestService service create method.
type FirstType struct {
	ID          *string
	Name        *string
	Description *string
	Thing       *SecondType
}
```

where  the following line fails to compile because `SecondType` is in a different package but not imported.
```
	Thing       *SecondType
```

Run the following in [this example repo to reproduce the issue](https://github.com/c-reeder/goa_issue):
```
make goa-gen
make build
```

**Comment by c-reeder** [comment]
@raphael , still very new to the goa source code, I've started trying too look into this issue a little bit and from what I'm seeing, a bit of new logic may be required to make this work.

As you'll see if you try out the example above, a dependency cycle would occur if we simply added the necessary import statement in the user type file since the type that it depends on is in the service package (which in turn depends on that custom user types package). 

My first instinct here is that maybe a change needs to be made such that using `Meta("struct:pkg:path", "types")` on a type, would cause all depended upon types (types used as fields in that user type), would need to be put in some package other than the service. 

I _think_ this would be an acceptable "breaking" change because it would only affect someone who was trying to use this Meta key in the way I described above (with another user type inside it), which as stated in the original post, doesn't seem to work at all. Hence, I _don't_ think changing the packages of user types included inside user types with this meta key would be a problem.

I'm curious to hear your thoughts on this or if there is anything I've not considered here. 

If we come to the conclusion that this is an acceptable change, we can brainstorm exactly how it would work.

Looking forward to hearing your insights!

**Comment by raphael** [comment]
Thanks for looking into it! The idea (and what I thought was the behavior but clearly there's a bug) is to have the type and all its dependencies put in the package identified via `struct:pkg:path`. So I wouldn't consider this a breaking change but rather a bug fix.

**Comment by c-reeder** [comment]
Okay, so for visibility, the plan is now that:
1. When the `struct:pkg:path` tag is set on a user type, any other user types that are used as fields within it need to be generated within the same package. E.g. in the original post, the `SecondType` should be generated in the "types" package as well. This should be true recursively.
2. If that meta tag is used more that once in the same design, but with different values in the meta statement (ex. one type has  `Meta("struct:pkg:path", "types1")` and another has `Meta("struct:pkg:path", "types2")`) then those two types cannot both contain a field of the same user type. Attempting to do so will raise an error. 
Full example **(will fail):**
```go
var FirstType = Type("FirstType", func() {
	Meta("struct:pkg:path", "types1")
	Attribute("id", String)
	Attribute("name", String)
	Attribute("description", String)
	Attribute("thing", ThirdType)
})

var SecondType = Type("SecondType", func() {
	Meta("struct:pkg:path", "types2")
	Attribute("Description", String)
	Attribute("thing", ThirdType)
})

var ThirdType = Type("ThirdType", func() {
	Attribute("Description", String)
})
```
3. However, it WILL still be permitted to use two different custom packages as long as the user types do not contain a user type field in common. 
Full Example **(will work)**
```go
var FirstType = Type("FirstType", func() {
	Meta("struct:pkg:path", "types1")
	Attribute("id", String)
	Attribute("name", String)
	Attribute("description", String)
	Attribute("thing", ThirdType)
})

var SecondType = Type("SecondType", func() {
	Meta("struct:pkg:path", "types2")
	Attribute("Description", String)
})

var ThirdType = Type("ThirdType", func() {
	Attribute("Description", String)
})
```
4. Also for simplicity, we will disallow setting a different custom package in a user type than the one set on a containing user type. Thus the following **will fail**
```go
var FirstType = Type("FirstType", func() {
	Meta("struct:pkg:path", "types1")
	Attribute("id", String)
	Attribute("name", String)
	Attribute("description", String)
	Attribute("thing", SecondType)
})

var SecondType = Type("SecondType", func() {
	Meta("struct:pkg:path", "types2")
	Attribute("Description", String)
})
```
5. Also we need to add a sentence or two to the documentation of the `struct:pkg:path` meta tag stated in points 2 and 4 above.
