### ISSUE TITLE
Cellar getting started example is throwing error

### ISSUE THREAD

**Issue by max-10001** [goadesign/goa#321]
Steps followed at http://goa.design/learn/guide.html

Error:
```
# cellar
.\bottle.go:28: cannot use ctx.BottleID (type int) as type *int in field value
.\bottle.go:29: cannot use fmt.Sprintf("Bottle #%d", ctx.BottleID) (type string) as type *string in field value
.\bottle.go:30: cannot use app.BottleHref(ctx.BottleID) (type string) as type *string in field value
```

go version: 1.5.3

Any ideas on why this might be happening.

**Comment by raphael** [comment]
Ah yes it was broken with a recent change with generated identifiers (used to be BottleId and is now BottleID). Thanks for the report.

**Comment by raphael** [comment]
Can't repro with latest.
