### ISSUE TITLE
gprc is not working in alpine linux

### ISSUE THREAD

**Issue by mcauto** [goadesign/goa#3215]
Ref. https://github.com/goadesign/goa/issues/3182

The above description is a problem that occurred after updating "protoc" to v3.15.8 on Alpine Linux.

The dynamic library connection does not seem to proceed normally on Alpine Linux.

**Comment by raphael** [comment]
Hello, this problem does not seem to be related to Goa - you may have better luck asking for help in gRPC forums. I do not use Alpine Linux so not sure why it wouldn't work.

**Comment by mcauto** [comment]
I don't think it's a problem with grpc. 
Because it can't find "protoc-gen-go" in goa.
"protoc-gen-go" path is registered in the environment variable PATH already.

**Comment by c-reeder** [comment]
@mcauto , What do you get if you run:
```bash
which protoc-gen-go
```

**Comment by mcauto** [comment]
> @mcauto , What do you get if you run:
> 
> ```shell
> which protoc-gen-go
> ```

@c-reeder Please refer to #3182 for details :)

**Comment by c-reeder** [comment]
Yes, I reviewed that issue before, but I don't see that information in there.

**Comment by mcauto** [comment]
> Yes, I reviewed that issue before, but I don't see that information in there.

I get below.

```
$which protoc-gen-go
/go/bin/protoc-gen-go
```
