### ISSUE TITLE
Required list attributes in Result are return as null if the value is empty

### ISSUE THREAD

**Issue by khaledez** [goadesign/goa#3216]
Let's say I have this design:
```go
import . "goa.design/goa/v3/dsl"

var TodosResult = Type("TodosResult", func() {
	Attribute("user", String, func() {
		Description("user ID")
	})

	Attribute("todos", ArrayOf(String), func() {
		Description("List of todos")
	})

	Required("user", "todos") // NOTE HERE todos IS REQUIRED
})

var _ = Service("todo-service", func() {
	Description("Simple Todo Service")
	Error("NotFound")

	Method("get-todos", func() {
		Description("Return a list of todos for user")
		Payload(String)
		Result(TodosResult)
		HTTP(func() {
			GET("/todos/{userID}")
			Response("NotFound", StatusNotFound)
		})
	})
})
```

The above design, generates this service endpoint:
```go
type Service interface {
	// Return a list of todos for user
	GetTodos(context.Context, string) (res *TodosResult, err error)
}
```

And If implement it like this:
```go
type TodosService struct {
}

func (service *TodosService) GetTodos(ctx context.Context, userID string) (res *api.TodosResult, err error) {
	var todos []string // empty list
	return &api.TodosResult{
		User:  userID,
		Todos: todos,
	}, nil
}
```

As you can see, the empty list has no memory allocated, so the returned http response is like this:
```json
{"user":"USER_ID","todos":null}
```

But the expected result to be like this:
```json
{"user":"USER_ID","todos":[]}
```

I checked the generated response decoder:
```go
// NewGetTodosResponseBody builds the HTTP response body from the result of the
// "get-todos" endpoint of the "todo-service" service.
func NewGetTodosResponseBody(res *todoservice.TodosResult) *GetTodosResponseBody {
	body := &GetTodosResponseBody{
		User: res.User,
	}
	if res.Todos != nil {
		body.Todos = make([]string, len(res.Todos))
		for i, val := range res.Todos {
			body.Todos[i] = val
		}
	}
	return body
}
```
It won't allocate an array if the value coming is nil.
I believe the generated code in this case should be like this, specially when the attribute is marked as `Required`:

```go
// NewGetTodosResponseBody builds the HTTP response body from the result of the
// "get-todos" endpoint of the "todo-service" service.
func NewGetTodosResponseBody(res *todoservice.TodosResult) *GetTodosResponseBody {
	body := &GetTodosResponseBody{
		User: res.User,
	}
	if res.Todos != nil {
		body.Todos = make([]string, len(res.Todos))
		for i, val := range res.Todos {
			body.Todos[i] = val
		}
	} else {
		body.Todos = []string{} // NEW CODE
	}
	return body
}
```

What do you think? Could you guide me to make the change and submit a PR?

**Comment by raphael** [comment]
The reason for this behavior is that in general it's not great to have an API or a client expect different behavior for a nil array vs. an empty array. Not all transports make it possible to differentiate (e.g. gRPC) and even with JSON some encoders will (de)serialize empty arrays as nil (as is the case in Go if the field has the tag `omitempty`).

That being said this change should be fairly easy to make and I'd be happy to accept a PR that made it. The `if` condition above comes from the "Go transformer" logic which is a generic algorithm that converts data structures, here is [the line](https://github.com/goadesign/goa/blob/v3/codegen/go_transform.go#L255). In this code:
* `code` contains the code that needs to be modified
* `tgtc.Type` contains the type of the target attribute - `expr.IsArray()` can be used to check whether it's an array
This code is used in many places so make sure to run all the tests using `make`, thank you!

**Comment by ernesto-jimenez** [comment]
For the record, this behaviour can cause trouble with generated OpenAPI clients with certain languages such as TypeScript.

The generated TypeScript type, when the attribute is required, would be set to `todos: Array<string>` rather than `todos?: Array<string>`, which means `todos` cannot be `null`.

**Comment by paprikati** [comment]
We've seen the same as Ernesto - would love to get this changed so we receive an empty array in all cases
