### ISSUE TITLE
generated contollers.go not building

### ISSUE THREAD

**Issue by kkeuning** [goadesign/goa#322]
seeing this output since updating goa yesterday:

controllers.go:23: interface contains embedded non-interface goa.Controller
controllers.go:43: service.ServeMux undefined (type goa.Service has no field or method ServeMux)
...

Reverting to older goa this morning to troubleshoot and confirm that works...

**Comment by raphael** [comment]
This looks like code that was generated with an old goagen. See the [goa-cellar](https://Github.com/goadesign/goa-cellar) example for code generated with the latest.

**Comment by kkeuning** [comment]
Old goagen was the primary issue.  Also regnerated main.go and all of the controllers to align with the latest updates.
