### ISSUE TITLE
required custom type attributes

### ISSUE THREAD

**Issue by lhelm-r7** [goadesign/goa#3229]
Hi, goa generates nil checks on fields when an attribute/field is set as required in the design. In my case, I have a custom type that is essentially standard json schema under the covers and cannot be compated to `nil`. Because If it’s a required attribute of the method’s payload then it works, if it’s optional then the if xx != nil code doesn’t cast correctly. 

The code generates fine without error but when I proceed to run my service, it errors below.

e.g
```
invalid operation: body.AttributeOfCustomType == nil (mismatched types <custom type> and untyped nil)
```

How does one get around this issue, or is there some special handling we can do around custom types? Thank you in advance.

**Comment by lhelm-r7** [comment]
Example of a rough design used 
```
func UpdateMethod() {
	Method("Update", func() {
		Description("some description here")
		Payload(PayloadModel)
		Result(ResponseModel)
		DefaultHTTP(func() {
			PUT("/{someId}")
			Response("notFound", StatusNotFound)
			Response("badRequest", StatusBadRequest)
			})
		})
	})
}
```
this is the payload
```
// UpdateSnippetPayload is the expected payload for the update snippet request
var UpdateSnippetPayload = Type("update_snippet_payload", func() {
	AttrSomeID()
	AttrStuffInPayload()
})

func AttrStuffInPayload() {
	AttrName(true, func() {
		Description("The name of the enitity")
		Example("Test Name")
	})
	Attribute("input", Any, func() {
		dsl.Meta("struct:field:type", "<name of custom type>", "<custom type location")
		Example(map[string]interface{}{})
	})
	Required("name", "input")
}
```
I want to have the Attribute `"input"` required but following issue I reported is happening. Looking for a work around or fix. In the description of the issue, the `input` attribute is the `AttributeOfCustomType` in the error. Sorry for all the generic naming.

**Comment by raphael** [comment]
I tried to repro the problem with the following design but the generated code compiles fine:
```go
package design

import . "goa.design/goa/v3/dsl"

var _ = Service("foo", func() {
	Method("bar", func() {
		Payload(BarPayload)
		HTTP(func() {
			GET("/{someID}")
		})
	})
})

var BarPayload = Type("BarPayload", func() {
	Attribute("someID", String)
	Attribute("name")
	Attribute("internal", Internal)
})

var Internal = Type("Internal", func() {
	Attribute("input", Any)
	Required("input")
})

```
Are you able to provide a full design that reproduces the problem?

**Comment by lhelm-r7** [comment]
Correct, the code generates fine no problem but I'm getting an error in the `/gen/http/<service_name>/server/types.go` for in the design you've provided would be the `ValidateInternalRequestBody`. e.g
```
// ValidateInternalRequestBody runs the validations defined on InternalRequestBody
func ValidateInternalRequestBody(body *InternalRequestBody) (err error) {
	if body.Internal == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("input", "body"))
	}
	return
}
```
This is erroring because `body.Internal` cannot be compared to `nil`. In our case `Internal` is of custom type that is essentially standard JSON. Do you see this error in your generated code?

Also could the `Meta` shown in my example be the cause of the problem? 
Is there a way that we could use our own validation on specific fields like this one?

Our custom type here is special because it supports marshaling and unmarshaling pgtype.JSONB under the covers.

**Comment by raphael** [comment]
The generated code here compiles fine since `body.Internal` is a pointer. Yeah, it could definitely be something that has to do with the use of `Meta`. Are you able to tweak the example above to re-create the error?
Also just FYI it seems that what you are trying to do is use generated types in the business logic / data layer. In general this is something that ends up causing issues because of the coupling it creates between transport, service and data layers. It's fine in very simple cases but most "real code" will benefit from introducing different types for the different layers and copying the data. Goa has a way to generate the copy algorithm too with [CreateFrom](https://pkg.go.dev/goa.design/goa/v3/dsl#CreateFrom) and  [ConvertTo](https://pkg.go.dev/goa.design/goa/v3/dsl#ConvertTo) even though in practice it's as simple to just write the code.
