### ISSUE TITLE
Enum generation is not working as expected 

### ISSUE THREAD

**Issue by sohombhattacharya** [goadesign/goa#3230]
Using enum in a field like so: 

```
Field(1, "type", String, func() {
	Enum("A", "B", "C", "D")
})
```

Generated the protobuf field: 

```
string type = 1;
```

but we are expecting something like

```
Type type = 1; 
```

Same issue on the generated Go struct.
There is no validation code generated either for the enum. 

Is this the right way to be using the enum feature in goa or is this the correct usage but this is a bug? Thanks!

**Comment by raphael** [comment]
Hello, the validation happens during encoding and decoding, for example: [design](https://github.com/goadesign/examples/blob/175371c1d354dca843ba22caa05d77fee5690e3c/cellar/design/storage.go#L31), [HTTP validation](https://github.com/goadesign/examples/blob/175371c1d354dca843ba22caa05d77fee5690e3c/cellar/gen/http/storage/server/encode_decode.go#L71-L75) and [gRPC validation](https://github.com/goadesign/examples/blob/175371c1d354dca843ba22caa05d77fee5690e3c/cellar/gen/grpc/storage/server/encode_decode.go#L58-L62).

**Comment by Albert-Coding** [comment]
Hello,

Yes, validation happens in code and that's great. 

I believe the ask is if goa could generate protobuf enums instead of strings. This would allow for a better devX as allowed values would be clarified at compile time instead of at runtime (ie when calling the endpoint).

Thoughts?

**Comment by raphael** [comment]
I am not sure that this would really help the developer experience. The service method types do not use the generated protobuf types, only the transport level types do, and these are only used by the generated Goa code - not the dev code. It would be fairly simple to change the code generating the protobuf to use enums but it would be a lot more complex to change the generated code that maps the service level types to the gRPC types (these methods would have to cast back and forth taking into account whether the field is a pointer at the service level, transport level or both). So I'm not sure that the added complexity is really worth it (again given that it would not change anything to the service level code).
