### ISSUE TITLE
Result type views are not always projected in the OpenAPI specification

### ISSUE THREAD

**Issue by sevein** [goadesign/goa#3253]
In my design, I have a result type `Thing` with a couple of views: `default` (id, name) and `extended` (id, name, age).

I have had mixed results trying to project the default view. In most cases the full set of attributes (including "age" was listed).

I've put together a repro with my attempts so far: [github.com/sevein/goademo@164b5369](https://github.com/sevein/goademo/tree/164b53697813dcdced6304d0006afeaba4ca93d2), namely here's the [design document](https://github.com/sevein/goademo/blob/164b53697813dcdced6304d0006afeaba4ca93d2/design/design.go).

Thank you in advance!

**Comment by raphael** [comment]
Thank you for the detailed report and all the details! `View` is supposed to be used in `Response` (globally for the entire response), `ResultType` or `CollectionOf`, so there's definitely an issue with the `plain-list-1` example but the others behave as expected. Will look into the `CollectionOf` issue.

**Comment by raphael** [comment]
The behavior of `CollectionOf` is fixed in https://github.com/goadesign/goa/pull/3255

**Comment by sevein** [comment]
Thank you!
