### ISSUE TITLE
Slack join link doesn't work.

### ISSUE THREAD

**Issue by egandro** [goadesign/goa#3271]
The link provided here to join slack doen't work any longer.

https://goa.design/extend/setup/

Can you please update the link?

Thx.

**Comment by raphael** [comment]
Hello, the link in the [README](https://github.com/goadesign/goa) does work (https://gophers.slack.com/messages/goa) - where did you find the link above?

**Comment by egandro** [comment]
@raphael  thx a lot

From here: https://goa.design/extend/setup/

```txt
You now have a fully functional Goa installation and are ready to start hacking! If you haven’t yet you should join the Slack [channel](https://gophers.slack.com/messages/goa/) (sign up [here](https://gophersinvite.herokuapp.com/)) to ask questions.
```

I could login (if I had an account) but I can't create a new account. That's the issue.

**Comment by egandro** [comment]
That is the right link: https://invite.slack.golangbridge.org/

Found here: https://forum.golangbridge.org/t/how-to-join-gopher-slack-channel/24915/4

**Comment by raphael** [comment]
Thanks, I added a button to the README that links to the signup page.
