### ISSUE TITLE
generated service code is incorrect when using `Meta` for shared types

### ISSUE THREAD

**Issue by lhelm-r7** [goadesign/goa#3284]
The generated code when using `Meta("struct:pkg:path", "types")` incorrectly generates functions that, according to the function description, "builds a value of type <shared attribute> from a value of type <shared attribute view>". 

e.g From example design below,  the function "transformTypesSimpleEntityViewToTypesSimpleEntitybuilds a value of type *types.SimpleEntity from a value of type *types.SimpleEntityView." You can see that `*types.SimpleEntityView` does not exist and therefore causes errors in the generated service code for both `serviceA` and `serviceB`. 

run `goa gen` on this example design
```
// SERVICE A
var _ = Service("serviceB", func() {
    Description("some description")
    Method("get", func() {
        Payload(func() {
            Attribute("id", String)
        })
        Result(SimpleResponse)

        HTTP(func() {
            GET("/{id}")
            Response(StatusOK)
        })
    })
})

// SERVICE B
var _ = Service("serviceB", func() {
    Description("some description")
    Method("create", func() {
        Payload(func() {
            Attribute("id", String)
        })
        Result(SimpleResponse)

        HTTP(func() {
            POST("/{id}")
            Response(StatusOK)
        })
    })
})

var SimpleResponse = ResultType("simple_response", func() {
	Description("The response data of the request")
	WrapData(SimpleEntity, true)()
})

// WrapData is a function that we use to wrap our response within a `data` field
func WrapData(resultType expr.UserType, isRequired bool) func() {
	return func() {
		Attribute("data", resultType, func() {
			Description("the data")
		})
		if isRequired {
			Required("data")
		}
	}
}

var SimpleEntity = Type("simple_entity", func() {
	Description("an instance of an entity")
	Attribute("id", String)
	Attribute("version", Version)
	Required("id", "version")
	Meta("struct:pkg:path", "types")
})

var Version = Type("version", func() {
	Description("The version of the entity")
	AttrName(true, func() {
		Description("The name of the version")
		Example("Test Name")
	})
	Required("name")
	Meta("struct:pkg:path", "types")
})
```

The issue raised in [#3240](https://github.com/goadesign/goa/issues/3240) did fix the initial problem but does not compile when trying to run the service due to the errors seen in the generated code. 

Thank you in advance for looking into this issue.

**Comment by raphael** [comment]
I tried to repro the issue but could not. It would help if you could provide a simple and complete design (one that does not make use of custom functions such as WrapData). The design should "just work" (the one above does not - I need to tweak it to make `goa gen` work). Also I think the problem is that the generated code does not compile? I tested by running `go test ./...` at the root of the module that contains the generated code and that worked fine but does not in your case correct?
