### ISSUE TITLE
Request - additional command line parameters for generation

### ISSUE THREAD

**Issue by bacanoo-io** [goadesign/goa#3285]
Please add additional parameters for generate separately  [ openapi, transport, service ]

**Comment by anhldbk** [comment]
+1

@raphael What do you think? I can make a PR to implement that.

**Comment by tchssk** [comment]
Perhaps that should be accomplished with a plugin.

Here are my implementation.
https://github.com/tchssk/goaplugins/tree/master/codegendisabler

**Comment by bacanoo-io** [comment]
Hi,
Thanks for your help. I will check this solution.

**Comment by bacanoo-io** [comment]
Solved
