### ISSUE TITLE
Generate mux for versioning has a problem

### ISSUE THREAD

**Issue by hiroosak** [goadesign/goa#329]
I'd like to use VersionParam.

```go
var _ = API("test", func() {
	VersionParam("version")
	BasePath("/api/:version")
})
```

When I did `gogen app -d somepackage/design`, this code was generated in `app/main.go`.

```go
  // Configure mux for versioning.
  if mux, ok := service.Mux.(*goa.RootMux); ok {
    mux.SelectVersionFunc = goa.PathSelectVersionFunc("/api/:version", "version")
  }
```

But `PathSelectVersionFunc` returns SelectVersionFunc and error. this code can't run.
I think that this function should return only SelectVersionFunc or modify template.

**Comment by raphael** [comment]
Thank you for the report! this is now fixed.
