### ISSUE TITLE
Is there a nice way to integrate AsyncAPI into goa?

### ISSUE THREAD

**Issue by egandro** [goadesign/goa#3303]
https://www.asyncapi.com/ 

It is like swagger/openapi but for websockets.

**Comment by raphael** [comment]
There isn't currently an easy way to integrate the two. Goa streaming payload and streaming results do make it possible to create async APIs with Goa where the data types are well defined. The built-in Goa code generators support both WebSockets (HTTP transport) and gRPC streaming (gRPC transport). As a first step it might be nice to have Goa generate an Async API definition similarly to how it generates an OpenAPI specification.
