### ISSUE TITLE
Make endpointsData public

### ISSUE THREAD

**Issue by mokiat** [goadesign/goa#3306]
Hi,

I am trying to write a plugin for Goa that tweaks a bit the generated endpoints. For my particular scenario, I have found two ways to approach this.

1. Extend the existing `endpoints.go` file with some additional methods of mine.
2. Modify the existing Goa templates with my own so that I can inject the desired functionality in the existing code.

Option 1 is the least effor to do, however, I could not find a way to discover the `*expr.Service` that is related to a given `endpoints.go` file. The only way I could do it was to find the `endpoints-init` section and then use reflection to access the Name field of the attached `endpointsData` struct.

Option 2 provides the most flexibility, with higher risk for a breaking change in the future but for this I definitely need to `endpointsData` struct.

Is it possible to have the `endpointsData` and `endpointsMethodData` structs public:
https://github.com/goadesign/goa/blob/fbf728f94bd2fd9f561e1d9ae4bc20b7d652e6e5/codegen/service/endpoint.go#L15-L47

This would enable both Option 1 and Option 2.

---

Side note: Having public structs is the current approach for the `http` files and is what is used by the Goa plugins:
https://github.com/goadesign/goa/blob/fbf728f94bd2fd9f561e1d9ae4bc20b7d652e6e5/http/codegen/service_data.go#L42

---

**Edit:** After checking my code in more detail, it turns out that just finding out the `*expr.Service` from a `*codegen.File` would not be sufficient. So I have simplified the description above to just making the two structures public, which would be the only enabler in this case.

**Comment by raphael** [comment]
Thank you for the clear explanation. That makes sense to me, Goa plugin developers should have access to the data structures that are used to populate the templates. I'd be happy to merge a PR that made these structs public.
