### ISSUE TITLE
goa gen results in "package src/goa-test/calc is not in std"

### ISSUE THREAD

**Issue by mikebz** [goadesign/goa#3350]
I am following the getting started tutorial, with one deviation that I am keeping my source under `~/src`

On the `goa gen` step I am getting this error:

```
 ~/src/goa-test » goa gen src/goa-test/calc
package src/goa-test/calc is not in std (/usr/local/Cellar/go/1.21.1/libexec/src/src/goa-test/calc)
```

Environmental information:
```
sw_vers
ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91

go version
go version go1.21.1 darwin/amd64
```

**Comment by raphael** [comment]
The path provided to `goa gen` is the Go import path of the design package - not the file path. So if the `design` package is under the root path of the project the argument given to `goa gen` should be whatever the module name is (content that appears after `module` in the `go.mod` file) appended with `/design`.
