### ISSUE TITLE
swagger: no format property for primitives

### ISSUE THREAD

**Issue by ZjMNZHgG5jMXw** [goadesign/goa#338]
In generated swagger files, primitives do not have a format property.
Also, Go's DateTime is translated to the swagger type date, however, correct would be type string with format date or dateTime. Similarly, Goa's Any is translated to the swagger type any, however, object would be the closest solution that seems to be accepted by the swagger editor without errors.

Disclaimer: I'm not a swagger expert. Correct me and close this issue, if I'm mistaken.

**Comment by raphael** [comment]
Thanks for the report! Adding formats to primitive types and using `string` with format `date-time` for the goa `DateTime` type makes a lot of sense. I don't think `object` is the right thing to use for `Any` though as an attribute of type `Any` could be a primitive type or an array for example.

**Comment by ZjMNZHgG5jMXw** [comment]
I agree in general. Nevertheless, using `any` as type in Swagger specification seems to lead to problems when you want to use the Swagger specification in combination with any other tool.

**Comment by raphael** [comment]
Then the other tools should be fixed. `Any` just doesn't tell you anything and should probably be avoided in the first place. Generating `object` in Swagger would be incorrect. If you know the type is an object then you can use `HashOf(String, Any)`.

**Comment by raphael** [comment]
Format and DateTime generations have been fixed, thanks!
