### ISSUE TITLE
Cannot access help forum

### ISSUE THREAD

**Issue by RichardJECooke** [goadesign/goa#3389]
Your forum, I think https://gophers.slack.com, has no register option, only a sign in option. When I try to sign in it tells me I'm not registered

**Comment by raphael** [comment]
Yeah slack requires registration, there is a link in the [README](https://github.com/goadesign/goa#readme) - click on the "SIGNUP" button.

**Comment by RichardJECooke** [comment]
I'm sorry but I can't see or search the word "slack" or "signup" anywhere on the readme you linked. Where is it please?

**Comment by raphael** [comment]
It's in a badge at the top of the file, the link is: https://invite.slack.golangbridge.org/ - sorry for not providing that in my previous reply.
