### ISSUE TITLE
Does Goa create client code as well as CLI code?

### ISSUE THREAD

**Issue by RichardJECooke** [goadesign/goa#3390]
I've through https://goa.design/learn/getting-started/ and done the example. 

I see Goa example creates a server stub, and CLI code for a client to call. But does it create client code that I could call inside another Golang app, not the terminal?  Or is this framework only a CLI generator and I need to use something else to create a client/server app?

The getting started document doesn't really explain what is in each folder and how it relates to each other.

So the `gen` folder contains agnostic endpoints and definitions. Ok.

And the `cmd` folder contains actual code you use, but no client code? And then there's the `calc.go` file sitting all by itself in the root folder. How does that relate to the `cmd` code?  Which folder imports which? 

And surely your single point of truth is your `design.go` file, from which you generate all other code. But the docs say we are not supposed to rerun `goa example`. So if we update `design.go`, do we have to update every `cmd` file by hand afterwards? This seems tedious.

And if your `calc.go` file is the main server implementation, then why does it even need the `cmd` folder? Can't it just use the definitions in the `gen` folder?  Please will you make your explanations on the getting started page for what each folder and file is for in one summary at the end, and more comprehensive for new users.

**Comment by raphael** [comment]
Hello!

Goa does generate both server and client code for all services defined in the design. The CLI generator takes advantage of the generated client package to build a tool on top. The `weather` example in the [clue](https://github.com/goadesign/clue) is probably a good place to look at what implementing a service client looks like, see the [forecaster service client](https://github.com/goadesign/clue/blob/main/example/weather/services/front/clients/forecaster/client.go) for example. In particular the `New` function which instantiates the client by leveraging the generated client package.

The `calc.go` in the root folder contains the actual business logic. Goa takes care of generating the transport code (both server and client side) as well as the endpoints layer. The user takes advantage of that code to create the actual servers and business logic.

The `goa example` command provides an example of a `main` but it certainly isn't the only way to write a main. The actual implementation will depend on a lot of other factors like other downstream dependencies that need to be instantiated (databases, cloud services etc.), the observability stack and other non-Goa dependencies. The same weather example shows an alternative implementation of a main package. At the end of the day the `main` package doesn't have to be modified much when the design changes. It only needs to be updated when new services are added or services are removed.

The source code for the website is located at https://github.com/goadesign/goa.design - please feel free to submit a PR with any clarification you think would help newcomers like you. I'd be happy to review and merge any submission!

**Comment by RichardJECooke** [comment]
Thanks.  I will definitely make a pull request to clarify the docs if I manage to understand it myself and get it working.

So in the Getting Started calc example - which file would I use on a client to get started?  (Not a CLI command, but an actual file in the /gen or /cmd that calls the server)

**Comment by raphael** [comment]
The code that needs to make calls to the Goa service would import the generated client, for example: https://github.com/goadesign/clue/blob/main/example/weather/services/front/clients/forecaster/client.go#L11. 

It then takes advantage of the generated [NewClient](https://github.com/goadesign/clue/blob/main/example/weather/services/forecaster/gen/grpc/forecaster/client/client.go#L27) function to instantiate a client endpoint "factory" object. The signature of the `NewClient` function depends on the underlying transport (HTTP or gRPC). For HTTP it takes an encoder and decoder which can be set to the default Goa [encoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L171) and [decoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L188). This object exposes [one method](https://github.com/goadesign/clue/blob/main/example/weather/services/forecaster/gen/grpc/forecaster/client/client.go#L36) for each service method that returns an endpoint. The endpoint can then be [called](https://github.com/goadesign/clue/blob/main/example/weather/services/front/clients/forecaster/client.go#L72) and/or [wrapped](https://github.com/goadesign/clue/blob/main/example/weather/services/front/clients/forecaster/client.go#L66) as needed.

**Comment by RichardJECooke** [comment]
Another confusion about your structure.  

- Your starting point is `/design`.
- Your definitions is `/gen`.
- Your implementation is `/cmd`.

All good. Your server implementation is in `cmd/calc/main.go`. This makes sense, as `/cmd` holds all the placeholder implementation code, and `calc` is the API name.

But why then is `calc.go` sitting in the root folder by itself?  It's a placeholder implementation of a service, so surely it belongs next to, or below, the placeholder implementation of the API. In other words, in `/cmd/calc/calc.go` or `/cmd/calc/services/calc.go`. 

![image](https://github.com/goadesign/goa/assets/5468805/de34815a-3289-4e82-8cf8-8ccb9462ef54)

**Comment by raphael** [comment]
The idea is that `calc.go` implements the service package which lives at the root. The service can be instantiated by the command line but that's not the only option. For example there could be multiple services instantiated in a single executable. This follows the clean architecture pattern where the service implements the business logic, the `gen` directory contains the transport logic and  `cmd` configures and puts everything together. I've used this same structure at scale (hundreds of services) and it works very well.

**Comment by RichardJECooke** [comment]
I've finished writing an article for Speakeasy with Goa that we'll publish soon. If you can see anything wrong with what I've said about Goa, please let me know - https://github.com/ritza-co/speakeasy-docs/blob/goa-guide/web/packages/marketing-site/src/pages/docs/api-frameworks/goa.mdx

I'll try to make a pull request to your docs for anything I think can be clearer soon.  I still don't understand why service implementations are kept in the root, bu thank you for trying to explain.

**Comment by raphael** [comment]
Awesome! looking forward to checking it out however I don't seem to have access to the link above (getting a 404).

**Comment by RichardJECooke** [comment]
Ah, sorry, they made the repository private. Here's another version - https://github.com/ritza-co/speakeasy-goa-example/commit/b802da73d60eccd93f81de02852f1b1d17faaf6d. Load diff will show it.

Otherwise the final article will soon appear under - https://www.speakeasyapi.dev/docs/api-frameworks/goa

**Comment by raphael** [comment]
Thanks for the link, the article looks awesome! Will have to checkout speakeasy :)

**Comment by RichardJECooke** [comment]
https://github.com/goadesign/goa.design/pull/145
