### ISSUE TITLE
Support OpenAPI V3 YAML/JSON oneof

### ISSUE THREAD

**Issue by ryanluu12345** [goadesign/goa#3395]
For context, already read the contents of this issue and understand the technical limitations: https://github.com/goadesign/goa/issues/3206

However, I'm wondering if there is any way the generated OpenAPI V3 YAML could use `oneof` that point to different OpenAPI type schemas. This would make it so that client generation tools can get specific typed schemas instead of the `Type, Value` combination that currently exists.

Please let me know challenges with this. Happy to discuss more!

**Comment by raphael** [comment]
I'd love to find a better way of encoding unions in a way that works across various encoders that is compatible with clients generated from the OpenAPI specification!

As mentioned in the linked issue the current implementation adds a `Type` field as the union discriminator and the value itself is serialized as a JSON string in the `Value` field. The client code that a `oneof` OpenAPI spec would generate would not be compatible with what the current implementation does. So it's not just a matter of updating the generated spec but it's mostly about how Goa handles union types in HTTP. We'd need to come up with a scheme that makes it possible for server and client Go methods to understand the underlying type so responses and/or requests can be unmarshaled correctly.

**Comment by seapike** [comment]
> So it's not just a matter of updating the generated spec but it's mostly about how Goa handles union types in HTTP. 

Isn't this actually exactly what's required? It seems that all that's missing is the enumeration of the acceptable types for the serialised value - the response is JSON anyway, what is stopping the generated spec from including the type references?
```
anyOf:
      - $ref: '#/components/schemas/Dog'
      - $ref: '#/components/schemas/Cat'
```

**Comment by raphael** [comment]
Not quite, the spec above would describe a response like:
```json
{ "pet1": { "bark": true }, "pet2": { "claws": 20 } }
```
where Goa generates:

```json
{ "pet1": { "Type": "dog", "Value": "{\"bark\":true}" }, "pet2": { "Type": "cat", "Value": "{\"claws\":20}" } }
```

Also to make the problem clearer the spec above would also work for:

```xml
<data><pet1><bark>true</bark></pet1><pet2><claws>20</claws></pet2></data>
```

where Goa generates:
```xml
<data><pet1><Type>dog</Type><Value>{"bark":true}</Value></pet1><pet2><Type>cat</Type><Value>{"claws":20}</Value></pet2></data>
```
