### ISSUE TITLE
Missing schemas in OpenAPI spec when using union types

### ISSUE THREAD

**Issue by sevein** [goadesign/goa#3416]
When using OneOf, I've noticed that some schemas are missing from the OpenAPI specification. In the example below, you can see that PackageCreatedEvent is listed in the OpenAPI document, but PackageUpdatedEvent is not. This issue appears to be linked to the fact that both event types use the same attribute names.

```go
var Event = Type("Event", func() {
	// ...
	OneOf("details", func() {
		Field(4, "package_created", PackageCreatedEvent)
		Field(5, "package_updated", PackageUpdatedEvent)
	})
})

var Item = Type("Item", func() {
	Field(1, "description", String)
})

// PackageCreatedEvent is included in the OpenAPI schema.
var PackageCreatedEvent = Type("PackageCreatedEvent", func() {
	Field(1, "id", Int, "Identifier of package")
	Field(2, "item", Item)
	Required("id")
	Meta("type:generate:force")
})

// PackageUpdatedEvent is ___NOT___ included in the OpenAPI schema ___UNLESS___ "item" is renamed.
var PackageUpdatedEvent = Type("PackageUpdatedEvent", func() {
	Field(1, "id", Int, "Identifier of package")
	Field(2, "item", Item)
	Required("id")
	Meta("type:generate:force")
})
```

Full example here: https://github.com/goadesign/examples/compare/master...sevein:examples:dev/union-openapi-missing-schemas.

**Comment by raphael** [comment]
I am not sure I see where `PackageCreatedEvent` gets generated in the OpenAPI specification in the example? In general though the OpenAPI specification generator will collapse type definitions that are structurally equivalent to avoid type sprawl for dynamically generated types. The `openapi:typename` Meta can be used to override the behavior and force the generation of the enclosing types using the given name.

**Comment by sevein** [comment]
> I am not sure I see where PackageCreatedEvent gets generated in the OpenAPI specification in the example?

In [`openapi3.yaml`](https://github.com/sevein/examples/blob/f0f379a2e50b7d9f9710e52b00dbb4ea6c5fb34f/streaming/gen/http/openapi3.yaml#L357-L388) (the link points to the schemas section of the spec), I can see `PackageCreatedEvent` and `PackageDeletedEvent` but `PackageUpdatedEvent` is missing.

> In general though the OpenAPI specification generator will collapse type definitions that are structurally equivalent to avoid type sprawl for dynamically generated types. The openapi:typename Meta can be used to override the behavior and force the generation of the enclosing types using the given name.

Ok, that makes sense. I've tried it and it works! Added an extra [commit](https://github.com/sevein/examples/commit/9b99aa13f2f78ec0c09b2005d38313ea92338ce3) to the repro branch with the changes.

Thank you for the clarification, this works for me. Do you want me to close the issue?

**Comment by raphael** [comment]
Yes I think we can close!
