### ISSUE TITLE
Proposed small refactor of certain DSL

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#342]
The `Description` DSL clause in `apidsl/api.go` looks like this now:

```
 func Description(d string) {
       if a, ok := apiDefinition(false); ok {
               a.Description = d
       } else if r, ok := resourceDefinition(false); ok {
               r.Description = d
       } else if a, ok := actionDefinition(false); ok {
               a.Description = d
       } else if m, ok := mediaTypeDefinition(false); ok {
               m.Description = d
       } else if a, ok := attributeDefinition(false); ok {
               a.Description = d
       } else if r, ok := responseDefinition(false); ok {
               r.Description = d
       } else if do, ok := docsDefinition(true); ok {
               do.Description = d
       }
 }
```

I propose getting rid of the different `whateverDefinition` and their funky boolean parameter, and opt for the clearer:

```
func Description(d string) {
	switch def := dslengine.CurrentDefinition().(type) {
	case *design.APIDefinition:
		def.Description = d
	case *design.ResourceDefinition:
		def.Description = d
	case *design.ActionDefinition:
		def.Description = d
	case *design.MediaTypeDefinition:
		def.Description = d
	case *design.AttributeDefinition:
		def.Description = d
	case *design.ResponseDefinition:
		def.Description = d
	case *design.DocsDefinition:
		def.Description = d
	default:
		dslengine.IncompatibleDSL()
	}
}
```

I've seen several cases type switches could simplify the code, ex: `apidsl/metadata.go`'s `Metadata()`.

But then, I thought of another way to do that. I'm currently working on Swagger Security support, and I'd definitely like to have a `Description()` and some `Metadata()` too.. but since it's in another package, I'd be forced to use a `SecurityDescription()` or `mypackage.Description()` but with `.` imports it would all break.  I'd like for my package to support the "original" `Description()` and `Metadata()`. Luckily, Go has awesome support for interfaces. Why not define `DescriptionSetter` and `MetadataSetter` ? define those methods on all the `Attribute/MediaType/*Definition` objects, and reduce the `Description()` DSL to:

```
func Description(d string) {
	setter, ok := dslengine.CurrentDefinition().(apidsl.DescriptionSetter)
	if !ok {
		dslengine.IncompatibleDSL()
		return
	}
	setter.SetDescription(d)
}

// in `apidsl.go` or some other reusable place.
type DescriptionSetter interface {
	SetDescription(string)
}
```

We could do the same with `Metadata` and a `MetadataSetter` interface.

The only worry I have is that it might bloat the documentation for those `ActionDefinition` and friends..

What do you think ?

**Comment by raphael** [comment]
Great idea! this paradigm is already used with `Attribute` (`Container` interface) and it makes sense to generalize it. We'd have to do it consistently though so we don't end up with a mix of "old style" and "new style" code.

**Comment by abourget** [comment]
Oh neat. Hadn't thought of making it the other way around.. instead of
having a Setter, having a getter like that. It would force us to reuse the
corresponding *Definition but that would be more than fine!

Regarding generalizing the naming, what about AttributeContainer interface
(instead of the current ContainerDefinition), MetadataContainer,
DescriptionContainer ?

I like your pattern a lot because having an "Attribute()" or "Metadata()"
method on the different *Definitinion objects it would also document which
of those objects support which DSL and provide an explanation of its
meaning in the objects' context.

Le dim. 6 mars 2016 22:54, Raphaël Simon <notifications@github.com> a
écrit :
