### ISSUE TITLE
Declare POST request contain an array of object

### ISSUE THREAD

**Issue by giangnh13579** [goadesign/goa#3426]
I have an request body template like this. 
```
[
    {
        "Id": 1415083386,
        "Name": "Name"
        // ... more attributes
    }
]
```
The request header has `Content-Type: application/json`. I've tried using `Attribute()` but it still requires a key for string.

```
var ArrayAttribute = Type("ArrayAttribute", func() {
    Attribute("Id", Int64)
    Attribute("Name",  String)
})

Payload(ArrayAttribute )
```

How can I represent a request payload with an array of object

**Comment by raphael** [comment]
Have you tried:
```go
Payload(ArrayOf(ArrayAttribute))
```

**Comment by giangnh13579** [comment]
> Have you tried:
> 
> ```go
> Payload(ArrayOf(ArrayAttribute))
> ```

Yes, I've tried it, but problem is the payload must contain other attrbutes, like `id` in param and `apiKey` in the header of request

Actually, I've solved problem by using [Body()](https://goa.design/design/http_mapping/). This is what i've done

```
var ArrayAttribute = Type("ArrayAttribute", func() {
    Attribute("Id", Int64)
    Attribute("Name",  String)
})

var MyPayload = Type("MyPayload", func() {
    Attribute("attributes", ArrayOf(ArrayAttribute ))
    // ... other attributes
})

// ...in Method
HTTP(func() {
    POST("/enpoint")
    Body("attributes")
    // ..other params
})

```
