### ISSUE TITLE
Errors are not being sent in actual JSON

### ISSUE THREAD

**Issue by thecodethinker** [goadesign/goa#343]
I've noticed that when an `InvalidParamTypeError` is launched goa returns this

`"[{\"id\":1,\"title\":\"invalid parameter value\",\"msg\":\"invalid value \\\"cfvbn\\\" for parameter \\\"right\\\", must be a integer\"}]"`

instead of actual, correctly formatted JSON. I changed the `Content-Type` header of the responses to `application/json` but that didn't change this issue.
I've been digging around the code but I can't see where this is getting sent.

**Comment by raphael** [comment]
There's already an open issue for this, closing as duplicate of #285
