### ISSUE TITLE
Bumping goa.design/plugins/v3 from 3.14.0 to 3.14.1 is causing my client generation to fail

### ISSUE THREAD

**Issue by ryanluu12345** [goadesign/goa#3433]
Currently I'm using `goadesign/goa` as my backend framework. I'm using `deepmap/oapi-codegen` as my client generator (using the generated OpenAPI file) because I like the simplicity of the code it outputs. 

After the latest update from 3.14.0 to 3.14.1, I'm noticing that I'm running into these failures on the client generation side:
```
../../../../pkg/mod/github.com/deepmap/oapi-codegen@v1.16.2/pkg/codegen/codegen.go:231:53: cannot use spec.Components.Responses (variable of type openapi3.ResponseBodies) as openapi3.Responses value in argument to GenerateResponseDefinitions
../../../../pkg/mod/github.com/deepmap/oapi-codegen@v1.16.2/pkg/codegen/codegen.go:403:54: cannot use swagger.Components.Responses (variable of type openapi3.ResponseBodies) as openapi3.Responses value in argument to GenerateTypesForResponses
../../../../pkg/mod/github.com/deepmap/oapi-codegen@v1.16.2/pkg/codegen/codegen.go:564:29: invalid operation: cannot index responses (variable of type openapi3.Responses)
../../../../pkg/mod/github.com/deepmap/oapi-codegen@v1.16.2/pkg/codegen/filter.go:7:29: cannot use swagger.Paths (variable of type *openapi3.Paths) as openapi3.Paths value in argument to excludeOperationsWithTags
../../../../pkg/mod/github.com/deepmap/oapi-codegen@v1.16.2/pkg/codegen/filter.go:10:29: cannot use swagger.Paths (variable of type *openapi3.Paths) as openapi3.Paths value in argument to includeOperationsWithTags
../../../../pkg/mod/github.com/deepmap/oapi-codegen@v1.16.2/pkg/codegen/filter.go:19:27: cannot range over paths (variable of type openapi3.Paths)
```
Wondering if you have any insights here? I looked at the changes made during the bump to 3.14.1 and noticed that github.com/getkin/kin-openapi was updated. Wondering if that would have caused this odd behavior?

**Comment by ryanluu12345** [comment]
Looking at the `deepmap/oapi/codegen` commits, I see that they also added support for the newest kinopenapi version. There appeared to have been breaking changes in kinopenapi. I'll go ahead and update them in lockstep then :)

https://github.com/deepmap/oapi-codegen/commit/1f53862bcc64573d3d0c4c105c71a8143e7b1816

Commenting for visibility ^

**Comment by ryanluu12345** [comment]
Yep, confirmed that updating the `deepmap/oapi-codegen` dependency to one that had the commit with `kin` upgrades worked: https://github.com/deepmap/oapi-codegen/commit/4ceb1d567792bb19895a9d71393e76f79ab61b2e

**Comment by raphael** [comment]
Thank you for sharing!
