### ISSUE TITLE
meta for externalDocs and deprecated?

### ISSUE THREAD

**Issue by xlanor** [goadesign/goa#3449]
I can see the Operations object has these fields, but I've been playing around with the DSL to try and set these fields but have not been able to get it to work.

How does one set them using Meta? Would be nice to have a good example

**Comment by raphael** [comment]
Hello, `externalDocs` is supported via the [Docs](https://pkg.go.dev/goa.design/goa/v3/dsl#Docs) DSL. There is no support today for `deprecated`, would be a great contribution though!

**Comment by xlanor** [comment]
@raphael - happy to contribute. which DSL would you reccomend I look under to begin working on deprecated?

**Comment by raphael** [comment]
Awesome! Probably the most straightforward way of adding `Deprecated` would be to introduce it as a new DSL function that simply adds a metadata to the method. The OpenAPI code generator would then look at whether this metadata is defined on a method and if so set the `Deprecated` field on the operation object. This would have to be done in both the `v2` and `v3` generators.

* [Example](https://github.com/goadesign/goa/blob/8888068def4be0e65239e5e67bb977b54bccb06a/dsl/error.go#L181-L191) that adds a meta entry. In this case the new `Deprecated` function would get the current scope using `eval.Current()` and make sure it's a `HTTPEndpointExpr`, similar to how the [route](https://github.com/goadesign/goa/blob/8888068def4be0e65239e5e67bb977b54bccb06a/dsl/http.go#L334-L338) function does it. It would then add the meta entry to the `HTTPEndpointExpr` object. 
* [Here is where](https://github.com/goadesign/goa/blob/97467d73ff575fa9ddb1f4d6e74f18f6dc5b77bd/http/codegen/openapi/v3/builder.go#L161) we may want to check for the metadata for `v3`. The check can use the `Last` method of the `MetaExpr` type simillar to how [mustGenerate](https://github.com/goadesign/goa/blob/97467d73ff575fa9ddb1f4d6e74f18f6dc5b77bd/http/codegen/openapi/v3/builder.go#L682) works 
* [Here is where](https://github.com/goadesign/goa/blob/041a69ddddbfe7ac838d8f35136438b2ee32585b/http/codegen/openapi/v2/builder.go#L644) the `Deprecated` field would have to be computed/set for `v2`.
* The new `Deprecated()` DSL function that adds the Meta to a method could be added [here](https://github.com/goadesign/goa/blob/af35d5f6170f6a5cea40acf197462c00088259d8/dsl/method.go#L39).

Thank you for taking this on!

**Comment by xlanor** [comment]
@raphael  - I have a PR ready, just need to run some tests (and write some).



Could you point me at any testing docs for new contribs? I'm getting failed tests even on v3 branch and trying to figure out if I'm missing something other than `go test`
