### ISSUE TITLE
Panic in main

### ISSUE THREAD

**Issue by zenbigjoe** [goadesign/goa#3473]
Latest version

panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
main.main()
main.go:25 +0x559

Seems to be os.Exit is missing after argument len check.
if len(os.Args) == 1 {
  usage()
  os.Exit(0)
}

**Comment by raphael** [comment]
Thanks, what was the command line that caused the panic?

**Comment by zenbigjoe** [comment]
System upgrade to windows 11 helped for me.
