### ISSUE TITLE
Rework context and type code generation to enable proper "required" and "default" attribute semantic

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#349]
# Background

Today the design DSL makes it possible to define attributes as being required:
```go
var MyType = Type("my_type", func() {
    Attribute("foo")
    Required("foo")
})
```
This has two consequences:
1. The generated `Validate` method checks that the value is initialized (the string is not empty in the example above) and if not returns an error.
2. The generated struct fields do not use a pointer (in the example above the Go type has a `foo` field of type `string`.

The generated Go type for the design above is thus:

```go
type MyType struct {
    Foo string `json:"foo" xml:"foo"`
}
```

# Problem Statement

The combination of the two consequences listed above results in incorrect behavior when the attribute type is a primitive type other than string. Taking integers as example if an integer attribute in the design is defined as being required the corresponding Go struct field is of type `int`. This makes it impossible to distinguish between the case where the zero value was set in the incoming request or created when decoding. As a result the generated `Validate` code does not check that these attributes are properly initialized in the incoming request state.

To complicate things further the DSL also allows specifying default values for attributes (the implementation of which is being worked in #203). The same issue arises for non pointer basic type fields: the code setting the default values cannot tell whether the zero value was intended or a result of the decoding.

# Goals

1. The generated code must always validate that the shape of incoming requests is correct as defined in the design.
2. The final code should avoid forcing dereferencing pointers for all basic types.
3. The generated code should not copy request state after deserialization.

# Proposal

The only way to achieve goal 1 without having special logic in every decoder is to use pointers to store the basic type values. This makes it possible for the generated `Validate` and `Finalize` methods to check for fields not provided in the request state in a generic fashion.

Achieving goal 2 means that there has to be another way to get at the values - the proposal is thus to introduce functions that do the dereferencing. For attributes that are not required and don't have a default value the proposal is to generate additional `HasXXX` methods that return a boolean indicating whether the underlying value is nil or not. This is so that the signature of attribute getters always return non pointer values. Note that under this proposal fields remain accessible but renamed to `XXXField` which is always of type pointer (unless the field holds a slice or a map).

So the type shown as example in the background section would now generate:
```go
type MyType struct {
    FooField *string `json:"foo" xml:"foo"`
}

func (t *MyType) Foo() (v string) {
    if t.FooField != nil {
        v = *t.FooField
    }
    return
}
```
Optional fields would also generate:
```go
func (t *MyType) HasBar() bool {
    return t.BarField != nil
}
```

**Comment by arangamani** [comment]
:+1:

**Comment by bketelsen** [comment]
Whoa, big change for Gorma.  But I'm +1

**Comment by abourget** [comment]
I like simplicity.. how can this be simplified ?

The `HasThings` could be validated by code directly, with `== nil` .. would those `Has` methods be necessary ?

why not `GetXXX` instead of the duo `HasXXX` and `XXXField` ? with the simple `XXX` as a pointer-rich field ?

**Comment by abourget** [comment]
Something along the lines:

```go
type MyType struct {
    Foo *string `json:"foo" xml:"foo"`
}

func (t *MyType) GetFoo() (v string) {
    if t.Foo != nil {
        v = *t.Foo
    }
    return
}

func main() {
    t := &MyType{}
    if t.Foo == nil {
        // do things.
    }
}
```

**Comment by raphael** [comment]
It seems to me that 99% of the time you'll want to use the function so I would rather have the field name be munged than the function name. At the end of the day with this proposal implemented all that will have to change in existing code is adding a `()` suffix. The fields will be pointers so a pain to deal with in most cases. Taking the [goa-cellar]() example:
```go
// Show retrieves the bottle with the given id.
func (b *BottleController) Show(ctx *app.ShowBottleContext) error {
	bottle := b.db.GetBottle(ctx.AccountID, ctx.BottleID)
	if bottle == nil {
		return ctx.NotFound()
	}
	return ctx.OK(ToBottleMedia(bottle))
}
```
becomes 
```
// Show retrieves the bottle with the given id.
func (b *BottleController) Show(ctx *app.ShowBottleContext) error {
	bottle := b.db.GetBottle(ctx.AccountID(), ctx.BottleID())
	if bottle == nil {
		return ctx.NotFound()
	}
	return ctx.OK(ToBottleMedia(bottle))
}```
which seems much more palatable than something like:
```
	bottle := b.db.GetBottle(ctx.GetAccountID(), ctx.GetBottleID())
```
or worse:
```
	var accountID int
	if ctx.AccountID != nil {
		accountID = *ctx.AccountID
	}
	var bottleID int
	if ctx.BottleID != nil {
		bottleID = *ctx.BottleID
	}
	bottle := b.db.GetBottle(accountID, bottleID)
```
With regards to the `HelpXXX` methods. I could be convinced to drop them. Again to me the usage pattern seems nice with them (pseudo code below):
```
	if ctx.HasYears() {
		dbquery = dbquery.Where("years=" + ctx.Years()
	}
```
rather than:
```
	if ctx.Years() != nil {
		dbquery = dbquery.Where("years=" + *ctx.Years()
	}
```
The `*` in the former code snippet is ugly and error prone.

**Comment by abourget** [comment]
What I was thinking, is we'd keep the same no-pointer for attributes-for-fields-with-default-values behavior. So we'd simply add `()` to those functions we want to avoid dealing with the pointer.

Wouldn't that work ?

**Comment by raphael** [comment]
Every field need to be a pointer to be able to implement "required" and "default". If it's not a pointer then the `Finalize` method that sets the default value cannot tell whether it should initialize the field or not if it has the zero value.

**Comment by raphael** [comment]
Updating the issue with the latest discussion on slack: an alternative to having all fields be pointers would be to generate a different struct than the one that is used to decode and copy the fields over. That "public" struct could use non-pointer fields for fields that are either required or have a default value. The performance hit would be minimal in the grand scheme of things. I'm liking this approach...

**Comment by abourget** [comment]
+1 on two structs ! _Simplicity is complex_, let goa take the hit, keeping simplicity for its users :-)

**Comment by raphael** [comment]
Closing this as dup of #203 since implementing the latter requires the double struct behavior.
