### ISSUE TITLE
Unexpected OpenAPI specification when using CollectionOf() + View()  in Attribute

### ISSUE THREAD

**Issue by neilogic1911** [goadesign/goa#3562]
My API design requirement is to ensure that the elements are included under the data attribute in the response of ListElements:
```
{
  "pageInfo": {
    // Page information goes here...
  },
  "data": [
    // List of elements goes here...
  ]
}
```
---
The Element type have two views: `default` and `tiny`. When these views appear in CollectionOf, everything works fine if the `tiny collection` passed directly to the `Result()`. However, when the collection is part of an attibute the tiny view will be not work correctly.

[demo repo](https://github.com/neilogic1911/goaviewcollection)

**Comment by raphael** [comment]
Thank you for the nice repro. This is fixed by #3567. Note that the explicit view should be defined on the collection, not on the result, i.e.:

```go
		Result(func() {
			Attribute("data", CollectionOf(Element, func() {
				View("tiny")
			}))
		})
```
