### ISSUE TITLE
version 3.19.0 break openapi generation

### ISSUE THREAD

**Issue by davideme** [goadesign/goa#3590]
With the same code in 3.18.2 and try to regenerate in 3.19, description and examples don't show up anymore.

```go
var AssetContractInfo = Type("AssetContractInfo", func() {
	Attribute("rent_amount", utils.MoneyAmount, "Rent amount for this asset,")
	Attribute("pay_now_amount", utils.MoneyAmount, "Pay now amount for this asset,")
	Attribute("contract_type", AssetContractType, "The contract type for this asset")
	Extend(utils.RentTenure)

	Required("contract_type")
})

var AssetContractType = Type("AssetContractType", String, func() {
	Enum("payNow", "rent")
})
```

<img width="987" alt="Screenshot 2024-09-12 at 10 31 11" src="https://github.com/user-attachments/assets/bf676bd8-93e9-4696-a695-aa62b5177d50">
<img width="651" alt="Screenshot 2024-09-12 at 10 33 40" src="https://github.com/user-attachments/assets/4d1fa1a1-131f-4313-8f1f-79e2d3045f56">

**Comment by raphael** [comment]
Thank you for the report, this does look like a regression - I'll take a look!

**Comment by raphael** [comment]
v3.19.1 fixes an issue that might explain this behavior, would you mind testing against it? If still broken can you please provide a full design to repro? thank you!

**Comment by davideme** [comment]
So I tested and fixing our generation issue, unfortunately it all other change of simplification of the OpenAPI, while they are welcome make the files hard to review, and especially that is changing all our Typescripts clients too.
