### ISSUE TITLE
[Feature request] Separate int32, and int64 

### ISSUE THREAD

**Issue by ceram1** [goadesign/goa#363]
I'm new to goa, and I found that I can't generate int64 property with `goagen app -d .....` 
But 'int64' is required in many case.

**Comment by raphael** [comment]
Can you give me an example of an API where `int64` is required?

**Comment by ceram1** [comment]
I'm not sure about int32, but int64 is required for generated entity ids.
One example would be a app which runs google app engine.

**Comment by raphael** [comment]
Makes sense. I'm thinking of making it possible to specify the format in the DSL, something like:
```go
var SumMedia = MediaType("application/vnd.goa.example.sum", func() {
	Description("Sum")
	Attributes(func() {
		Attribute("value", Integer, func() {
			Format("int64")
		})
	})
})
```
Would that work for your use case?

**Comment by ceram1** [comment]
Yes. It will work for me, and also suit for mirroring external api for web client to hide my api key.

**Comment by bits01** [comment]
+1 Another use case is large counters that need to be represented as uint64, the only choice today is Number which maps to float64, it works but not ideal to deal with the conversions.

**Comment by chriskaukis** [comment]
Just came across another use case. There may be a work around (like converting to time), but if storing Unix timestamp. In Go they are int64. 

https://golang.org/pkg/time/#Time.Unix

**Comment by advance512-demo** [comment]
+1

**Comment by gavinwade12** [comment]
+1

**Comment by raphael** [comment]
This is coming in [v2](https://github.com/goadesign/goa/blob/v2/design/types.go#L85-L100). I'm not planning on adding this to v1 at this point, closing the issue.
