### ISSUE TITLE
Use multiple parameters with ArrayOf in Params in an Action

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#365]
Right now, an ArrayOf(String) in a Parameter creates a string slice in generated code, by splitting the first parameter on ",". It seems not  possible to get the other values passed in in the request with multiple Params of the same name.

Since it is easy to split on a comma in client code, given a simple string, Goa would be better off supporting the more complex case of handling multiple parameters with the same name as ArrayOf(String).

**Comment by raphael** [comment]
I was looking into this and there seems to be value in the current behavior. Passing multiple parameters as a comma separated list in the URL is a fairly common pattern (we have apps that use it) and while it's true that splitting on comma is not hard the code also takes care of coercing to the right type (i.e. `[]int` `[]bool` etc.). At the end of the day removing the current behavior doesn't seem very attractive.

However it doesn't seem incompatible with supporting arrays being passed in as multiple values with the same key. The generate code could split on commas but also iterate over all values with the same keys if there's more than one. That seems like a good compromise and preferable to adding more complexity for example in the design to distinguish between the two cases.

**Comment by raphael** [comment]
Feel free to re-open if you see issues with this approach...

**Comment by raphael** [comment]
As per our discussion on Slack, adding a note about possible DSL to make it possible to specify the separator value:
```go
Param("multiple_sentences", ArrayOf(String), "Multiple sections of texts passed in the URL instead of the body", func() {
    ArraySeparator(".")
    // ...
})```
`ArraySeparator` could specify the empty string to force the use of multiple values. Not implementing this until there's enough push for it to avoid complicating the DSL to solve a corner case.
