### ISSUE TITLE
run go fmt on generated code

### ISSUE THREAD

**Issue by brasilikum** [goadesign/goa#375]
I think this is important so that minor changes to the generated code appear as minor changes in the diff-tools of git. Also go fmt is widely agreed on to generate the most consistent layout and therefore increasing ease of reading.

What's the opinion on this?

**Comment by raphael** [comment]
This is already done using the `go/format` package directly.

**Comment by raphael** [comment]
Closing for now, reopen if needed. The formatting happens here: https://github.com/goadesign/goa/blob/master/goagen/codegen/workspace.go#L240-L273.
