### ISSUE TITLE
Is any JWT working examples for latest version

### ISSUE THREAD

**Issue by windyboy** [goadesign/goa#390]
I check jwt.go doc, can not find example of create jwt token.
The goa-celler example only got basicauth example, no JWT

**Comment by raphael** [comment]
There is no built-in code for creating tokens at this point. It probably makes sense to have a default algorithm that accepts a generic data structure (`interface{}`?) and creates a token from it. That would make an excellent PR ;)

**Comment by aslakknutsen** [comment]
Just FYI. I've been struggling for a few days trying to find the same 'feature'. I ended up doing this for now:

My Auth Endpoint

```go
// Authorize runs the authorize action.
func (c *LoginController) Authorize(ctx *app.AuthorizeLoginContext) error {
	token := jwt.New(jwt.SigningMethodRS256)
	token.Claims["exp"] = time.Now().Add(time.Hour * 72).Unix()
	token.Claims["scopes"] = []string{"scope1", "scope2"}

	key, err := jwt.ParseRSAPrivateKeyFromPEM(([]byte(RSAPrivateKey)))
	if err != nil {
		panic(err)
	}

	tokenStr, err := token.SignedString(key)
	if err != nil {
		panic(err)
	}
	authToken := app.AuthToken{Token: tokenStr}
	return ctx.OK(&authToken)
}
```

```go
// RSAPrivateKey for signing JWT Tokens
// ssh-keygen -f test_rsa
var RSAPrivateKey = `-----BEGIN RSA PRIVATE KEY-----
--
-----END RSA PRIVATE KEY-----`

// RSAPublicKey for verifying JWT Tokens
// openssl rsa -in test_rsa -pubout -out test_rsa.pub
var RSAPublicKey = `-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----`
```

main.go
```go
        ...
	publicKey, err := token.ParseRSAPublicKeyFromPEM([]byte(RSAPublicKey))
	if err != nil {
		panic(err)
	}
	app.ConfigureJWTSecurity(service, jwt.New(publicKey, nil))
       ...
```

That seems to do the trix end-to-end. :)

**Comment by windyboy** [comment]
@raphael  got it.
@aslakknutsen  thanks.
I was not familiar with JWT ways, it mean give the private key to client, service only got public key to verify token.
And the token string is generated by the client, not the server. So JWT interface only got public key as parameter make sense.

**Comment by aslakknutsen** [comment]
@windyboy It depends on the way you use JWT I guess. The client may or may not need to deal with the signature/verification at all. A JWT Token is 'normally' generated by the Server and given to the Client. The Client can use that token as a clob when later communicating with the Server. So the Server signs it during creation and verifies it when the Client uses it later for authentication.

**Comment by raphael** [comment]
@aslakknutsen thank you for the example! I'd like to add a "security" folder to the [examples](https://github.com/goadesign/examples) with code for all 4 supported schemes (basic auth, api key, jwt and oauth2).

**Comment by raphael** [comment]
There is now a JWT example as part of the [security example](https://github.com/goadesign/examples/tree/master/security).
