### ISSUE TITLE
After go get error: `codegen/command.go:75: r.Flags().MarkHidden undefined`

### ISSUE THREAD

**Issue by aarongreenlee** [goadesign/goa#415]
Running `$  go get github.com/goadesign/goa/goagen` reports an error:

`# goadesign/goa/goagen/codegen/command.go:75: r.Flags().MarkHidden undefined (type *pflag.FlagSet has no field or method MarkHidden)`

I've forked the repo so I can investigate; however, I'm only kicking the goa tires now for the first time.

**Comment by raphael** [comment]
This sounds like a dependency is not up-to-date try with `go get -u`. The dependency in question is `github.com/spf13/pflag`.

**Comment by aarongreenlee** [comment]
Thanks, I should have checked that out first :)

**Comment by raphael** [comment]
np - glad it was that simple.
