### ISSUE TITLE
Consumes and Produces fails to add package to import 

### ISSUE THREAD

**Issue by DanielHeckrath** [goadesign/goa#416]
I tried to use Consumes and Produces to set a custom decoder/encoder as described in the [documentation](https://godoc.org/github.com/goadesign/goa/encoding).

There are 2 scenarios I tried and both failed

#### Only adding Package to the definition

```
package design

import (
	. "github.com/goadesign/goa/design" // Use . imports to enable the DSL
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("test-service", func() {
	Consumes("application/x-protobuf", func() {
		Package("github.com/goadesign/goa/encoding/gogoprotobuf")
	})
	Produces("application/x-protobuf", func() {
		Package("github.com/goadesign/goa/encoding/gogoprotobuf")
	})
})
```

This fails with the following error `/Users/daniel/go/src/github.com/DanielHeckrath/goa-test/app/controllers.go:27:31: expected selector or type assertion, found ','` because the generator is not falling back to `NewEncoder` and `NewDecoder` as indicated in the documentation for `Function`. The generated code looks like this.
 
```
// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder(gogoprotobuf., "application/x-protobuf")
	service.Decoder(gogoprotobuf., "application/x-protobuf")


	// Setup default encoder and decoder
	service.Encoder(gogoprotobuf., "*/*")
	service.Decoder(gogoprotobuf., "*/*")
}
```

#### Using both Package and Function

```
package design

import (
	. "github.com/goadesign/goa/design" // Use . imports to enable the DSL
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("test-service", func() {
	Consumes("application/x-protobuf", func() {
		Package("github.com/goadesign/goa/encoding/gogoprotobuf")
		Function("NewDecoder")
	})
	Produces("application/x-protobuf", func() {
		Package("github.com/goadesign/goa/encoding/gogoprotobuf")
		Function("NewEncoder")
	})
})
```

The generated initService function looks good when defining both package and function, but because the package is not imported it's not possible to build the project.

I was using 5e8c9824428e8bc7ffe1b9768141aa051af66e9d when I tried both variants

**Comment by raphael** [comment]
Thank you for the report, these are clearly bugs.

**Comment by DanielHeckrath** [comment]
I think the reason that the imports are missing for those samples is that there is a check if the encoder/decoder package contains `goadesign/goa` and only those packages that don't contain it are added to the import (see [generator.go](https://github.com/goadesign/goa/blob/3b08c200925108adc2166b29f14d221c4e70b427/goagen/gen_app/generator.go#L383-385))
