### ISSUE TITLE
wrong content type on show action

### ISSUE THREAD

**Issue by bketelsen** [goadesign/goa#431]
calling /thing (list) gives "application/vnd.thing+json"
calling /thing/1 (show) gives "application/vnd.thing" content type

I'll look at this in a bit, just wanted to record it.

**Comment by bketelsen** [comment]
same in goa-cellar:
https://github.com/goadesign/goa-cellar/blob/master/app/contexts.go

**Comment by potatogopher** [comment]
@bketelsen Is the work-around implemented in goa-cellar?

**Comment by raphael** [comment]
Today there's no way for goa to infer the correct media type modifier. The interface to encoder packages would have to be modified so the code generator could query them for the correct modified suffix. There is code that injects the "+json" modified but that was written prior to the introduction of generic encoders and should be removed. At this time the best option is to specify the modifier in the media type identifier in the design.
