### ISSUE TITLE
Am facing this issue while am running the server in local. Please let me know the root cause. Thanks in advance

### ISSUE THREAD

**Issue by vivinRajagopalan** [goadesign/goa#432]
m.router.ServeHTTP(rw, req)

net/http.(*conn).serve.func1(0xc082200700)
        C:/Go/bin/src/net/http/server.go:1389 +0xc8
panic(0xa8fb40, 0xc082002060)
        C:/Go/bin/src/runtime/panic.go:426 +0x4f7
accounts/vendor/github.com/goadesign/goa.(*adapter).logit(0xc082247180, 0xb5fdb8, 0x7, 0xc082200880, 0x8, 0x8, 0x32b4400)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/logging.go:95 +0x8b6
accounts/vendor/github.com/goadesign/goa.(*adapter).Info(0xc082247180, 0xb5fdb8, 0x7, 0xc082200880, 0x8, 0x8)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/logging.go:50 +0x5f
accounts/vendor/github.com/goadesign/goa.LogInfo(0x32b4450, 0xc0821cb380, 0xb5fdb8, 0x7, 0xc082200880, 0x8, 0x8)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/logging.go:107 +0x12d
accounts/vendor/github.com/goadesign/goa/middleware.LogRequest.func1.1(0x32b4450, 0xc0821cb380, 0x32b4888, 0xc0821f1040, 0xc082202460, 0x0, 0x0)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/middleware/log_request.go:33 +0x77e
accounts/vendor/github.com/goadesign/goa/middleware.RequestID.func1.1(0x32b4450, 0xc0821cb350, 0x32b4888, 0xc0821f1040, 0xc082202460, 0x0, 0x0)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/middleware/request_id.go:50 +0x416
accounts/vendor/github.com/goadesign/goa.New.func2(0x32b4888, 0xc0821f1040, 0xc082202460, 0x0)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/service.go:97 +0x540
accounts/vendor/github.com/goadesign/goa.(*mux).HandleNotFound.func1(0x32b4888, 0xc0821f1040, 0xc082202460)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/mux.go:67 +0x49
github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc0821d0540, 0x32b4888, 0xc0821f1040, 0xc082202460)
        C:/projects/go/src/github.com/dimfeld/httptreemux/router.go:190 +0x33a
accounts/vendor/github.com/goadesign/goa.(*mux).ServeHTTP(0xc0821c78e0, 0x32b4888, 0xc0821f1040, 0xc082202460)
        C:/projects/go/src/accounts/vendor/github.com/goadesign/goa/mux.go:83 +0x49
net/http.serverHandler.ServeHTTP(0xc082200480, 0x32b4888, 0xc0821f1040, 0xc082202460)
        C:/Go/bin/src/net/http/server.go:2081 +0x1a5
net/http.(*conn).serve(0xc082200700)
        C:/Go/bin/src/net/http/server.go:1472 +0xf35
created by net/http.(*Server).Serve
        C:/Go/bin/src/net/http/server.go:2137 +0x455

**Comment by raphael** [comment]
Thank you for the report, this was a bug recently introduced - it should now be fixed in latest master.
