### ISSUE TITLE
Consider application/problem+json type for errors, re Problem Details for HTTP APIs (draft-ietf-appsawg-http-problem-03)

### ISSUE THREAD

**Issue by jimmidyson** [goadesign/goa#463]
Standard problem document as per https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-03 is very similar to the error response type. This is used in recent APIs such as the [ACME spec](https://ietf-wg-acme.github.io/acme/) & provides a potentially more consistent for APIs error handling.

**Comment by raphael** [comment]
Thanks for the pointer! can you elaborate a little bit on what problem this is solving?

**Comment by jimmidyson** [comment]
It's not a problem, just using a standardised & IANA registered media type for error responses seemed reasonable :)

**Comment by raphael** [comment]
Makes sense, of course being a standard doesn't make it necessarily the right choice but perusing the doc didn't raise any red flags. Might make a good addition to v2.
