### ISSUE TITLE
Credentials in .travis.yml

### ISSUE THREAD

**Issue by vburenin** [goadesign/goa#483]
Are those credentials valid? did you consider removing them?

**Comment by arangamani** [comment]
@vburenin What credentials are you referring to? There are some identifiers which are okay to be in plain text. Some credentials are encrypted and only travis can decrypt then. See [here](https://docs.travis-ci.com/user/encryption-keys/) for more details.

**Comment by raphael** [comment]
Yup all encrypted, nothing to see here :)
