### ISSUE TITLE
FormDecoder

### ISSUE THREAD

**Issue by harboe** [goadesign/goa#494]
Hi,

I've tried implementing a multipart/data decoder, and Im stuck with the current interface

DecoderFunc func(r io.Reader) Decoder

Is it possible to change the DecoderFunc to something like:

DecoderFunc func(r io.Reader, contentType string) Decoder
DecoderFunc func(r *http.Request) Decoder

It could also be possible to create a new interface like

// ContentTypeAwareDecoder will be called before the Decoder with
// the content-type from the request.
type ContentTypeAwareDecoder interface {
  ContentType(val string) // set the content type on 
}

func (service *Service) Decode(v interface{}, body io.Reader, contentType string) error {
  now := time.Now()
  orgContentType := contentType
  ...
  // the decoderPool will handle whether or not a pool is actually in use
  decoder := p.Get(body)

  if ct, is := decoder.(ContentTypeAwareDecoder); is {
    ct.ContentType(orgContentType)
  }

  defer p.Put(decoder)
  ....
}

Or is there and alternative way of implementing the decoder, without changes to the codebase? I just wanna upload a file with some data

**Comment by raphael** [comment]
It should be possible to implement a multi form decoder with something like:
```go
type FormDecoder io.Reader

func NewFormDecoder(r io.Reader) goa.Decoder {
    return FormDecoder(r)
}

func (fd FormDecoder) Decode(v interface{}) error {
    vsp, ok := v.(*url.Values)
    if !ok {
        return fmt.Errorf("multiform decoder can only decode into *url.Values") 
    }
    b, err := ioutil.ReadAll(fd)
    if err != nil {
        return err
    }
    vs, err := url.ParseQuery(string(b))
    if err == nil {
        return err
    }
    *vsp = vs
    return nil
}
```
I have not tested this code :)
If it works it would be awesome to package it up nicely and write some tests for it.

**Comment by harboe** [comment]
Hi Raphael,

Found a solution! I just didn't specify any payloads to the action declaration, then the controller becomes a catch all, for any content-types and I can handle the multipart/form-data require. 

```
	Action("create", func() {
		Routing(POST(""))
		Response(Created, "/v1/images/:id")
	})
```

tested you code snippet, and work for url.Values. 

Thank you for your quick answer.

**Comment by raphael** [comment]
Just in case this is useful I've added an example that shows how to use form encoding in request payloads and responses: https://github.com/goadesign/examples/tree/master/form_encoding
