### ISSUE TITLE
Misuse of status code 400 with valid request body syntax

### ISSUE THREAD

**Issue by brycereitano** [goadesign/goa#500]
According to [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.5.1) a 400 status means: 
```
6.5.1.  400 Bad Request
   The 400 (Bad Request) status code indicates that the server cannot or
   will not process the request due to something that is perceived to be
   a client error (e.g., malformed request syntax, invalid request
   message framing, or deceptive request routing).
```

A better response code defined in [RFC4918](https://tools.ietf.org/html/rfc4918#section-11.2) would be 422:
```
11.2.  422 Unprocessable Entity
   The 422 (Unprocessable Entity) status code means the server
   understands the content type of the request entity (hence a
   415(Unsupported Media Type) status code is inappropriate), and the
   syntax of the request entity is correct (thus a 400 (Bad Request)
   status code is inappropriate) but was unable to process the contained
   instructions.  For example, this error condition may occur if an XML
   request body contains well-formed (i.e., syntactically correct), but
   semantically erroneous, XML instructions.
```

**Comment by raphael** [comment]
Thanks for the feedback! The 422 status code may or may not be appropriate. At the end of the day it really depends on how you want to design your API. 422 is an extension introduced by Microsoft for WebDAV in [RFC 4918](https://tools.ietf.org/html/rfc4918). It doesn't feel right to me that it would be the default generated by goa. It's easy enough to define your own response template that use that code.
