### ISSUE TITLE
client: no cli flags generated for BaseParams in API

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#534]
[design.txt](https://github.com/goadesign/goa/files/303128/design.txt)

```
var _ = API("cellar", func() {
	Title("The virtual wine cellar") 
	Description("A simple goa service")
	Scheme("http") 
	Host("localhost:8080")
	BaseParams(func() {
		Param("basefoo", String, "basefoo")
	})

```

The client-cli has no flag for `basefoo` and no way to use it from the client. If using the URL syntax in the cli, the query string gets URL encoded and it does not work.

**Comment by raphael** [comment]
Can you please provide a complete design? thank you!

**Comment by bits01** [comment]
Attached in the top comment.

**Comment by raphael** [comment]
Looking at this, it seems to be a misuse of the `BaseParams` DSL. The idea with this DSL used in the top level `API` definition is to provide values for the `BasePath` params - not query string parameters. Only the action can define query string parameters.

If there are query string parameters that you want to make available to all actions (like a version parameter) then use a Trait instead (define the trait in the API and use `UseTrait` in each resource).

**Comment by raphael** [comment]
OK looking at the comment it says the opposite... I will change the implementation to match the comment.

**Comment by bits01** [comment]
Thanks. Defining global query params is very useful. In my API I use a global "expand" query param so that the client can request specific links to be expanded in place (to avoid round-trips). This works quite well and it can apply not only to GET requests but to other types of requests that create/update resources and return the new/updated resource. Yes, a Trait would work, or a helper function in the DSL, but it's just nicer to have it in the API definition..

**Comment by raphael** [comment]
Makes sense - master should have the fix, can you please confirm?

**Comment by bits01** [comment]
Working. Thank you for the fix.
