### ISSUE TITLE
Make Trait top level

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#542]
Now that Traits can be used in Attributes(), it may make sense to promote Trait to be top level. It's a bit "ugly" to pollute the API with a bunch of attribute traits that are only used on some media types.

Another suggestion: allow Traits anywhere, or have an alternate Macro DSL that is just a snippet of DSL that can be re-used anywhere.

**Comment by raphael** [comment]
Thanks for opening the issue! making Traits top level makes sense. Not sure about the "anywhere" bit, the problem being that the DSL needs to apply against something - there has to be a current definition that it modifies.

**Comment by bits01** [comment]
Anywhere is probably too broad indeed, just to other DSLs that accept a `dsl ...func()` argument.

**Comment by raphael** [comment]
Traits don't exist in v2, the functionality is equivalent to writing helper Go functions in the design and doing so provides more flexibility.
