### ISSUE TITLE
Please document the need to have YAML installed

### ISSUE THREAD

**Issue by mpaquette1** [goadesign/goa#553]
The "teaser" application would not build for me until I figured out I was lacking YAML in my Go installation.  Please make it clear in the readme that this is necessary:

```$ go get gopkg.in/yaml.v2```

**Comment by raphael** [comment]
Thank you! the package is now an explicit dependency of `goagen` so that "go getting" `goagen` also "go gets" `gopkg.in/yaml.v2`.
https://github.com/goadesign/goa/pull/554/files

**Comment by raphael** [comment]
Fixed by #554
