### ISSUE TITLE
SupportedValidationFormats: support IP validation (as in IPv4 or IPv6)

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#557]
Currently an attribute can accept only one of `Format("ipv4")` or `Format("ipv6")`. There is no way to specify both IPv4 and IPv6 as accepted formats. An `ip` format that would allow either could work.

As a more general solution, the JSON schema `oneOf` could be useful, perhaps as a `OneOf` DSL, though I'm not sure how hard it would be to implement.

**Comment by bits01** [comment]
PR #664

**Comment by raphael** [comment]
Thanks for the PR!
