### ISSUE TITLE
codegen: Metadata("struct:field:name", "ATTR") full support

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#558]
Let's say we want to set a custom struct attribute name for a MediaType attribute that is an initialism:
```
Attribute("attr", CollectionOf(ATTRMedia), func() {
			Metadata("struct:field:name", "ATTR")
		})
Required("attr")
```

Two problems I ran into:

1. The generated `Validate()` method does not compile. It refers to `mt.Attr` even though the field correctly appears as `ATTR` in the generated struct

2. If the `attr` above is part of `links` (by using the `Link()` DSL) its name is still `Attr` rather than `ATTR` in the generated `MediaTypeLinks` struct.

**Comment by raphael** [comment]
I have fixed the first issue and cannot reproduce the second. If you still have the second issue please provide a complete example (complete design package). I'm spending too much time trying to guess what the original setup was... :)

**Comment by bits01** [comment]
(1) is fixed but (2) is still not fixed. Here's some similar DSL to what I'm using, for the links part:
```
var FooMedia = MediaType("application/vnd.foo+json", func() {
Description("Foo")
TypeName("Foo") // Go struct name
Attributes(func() {
Attribute("attr", CollectionOf(ATTRMedia), func() {
            Metadata("struct:field:name", "ATTR")
        })
Required("attr")

Links(func() {
		Link("attr")
	})
})

View("default", func() {
		Attribute("attr")
		Attribute("links")
	})
})
```

If you look at the generated `FooLinks` struct, it will have a field `Attr` instead of `ATTR`.

**Comment by bits01** [comment]
@raphael - should we reopen this issue for the 2nd part which is still not working or should I just file a new issue? Thanks.
