### ISSUE TITLE
Variable Structure in Responses

### ISSUE THREAD

**Issue by tsmaeder** [goadesign/goa#569]
I would like to allow a couple of different json object type to be the value of an attribute in a media type (value of field x can be this or that or that third thing). The number of different objects that can occur is small and finite. 
I haven't seen a way how to express that in the api dsl. Is there a way to do this?

**Comment by raphael** [comment]
Thus is not directly supported at the moment. What you can do today is define a type that contains the union of all the attributes and make them optional. Then document the alternatives. Would be good to add support to the JSON Schema "OneOf" which is what you are after. I'll leave this issue opened to keep track of that.

**Comment by tsmaeder** [comment]
Ok, thx for that clear answer.

**Comment by baijum** [comment]
Is this issue same as #612 ?

**Comment by raphael** [comment]
Hmm yes thank you, will close this one.
