### ISSUE TITLE
Examples fail with "invalid version string format "

### ISSUE THREAD

**Issue by dhrp** [goadesign/goa#571]
After a clean install of goa (go get -u github.com/goadesign/goa/...), and following the first steps of doing the cellar example, any attempt to run goagen [boostrap, app, swagger] fails as shown below. 

```
$ goagen bootstrap -d cellar/design
exit status 1
invalid version string format ""
```

It sounds like this may have something to to with PR #564, but I have not dug into it deeply. It is a new error as my projects that I started last week used to run just fine.

**Comment by raphael** [comment]
I am not able to reproduce this. Is there any chance that `goagen` may be using an older (e.g. vendored) `goa`? If not can you provide exact repro steps? thanks!

**Comment by dhrp** [comment]
I can reproduce it consistently (mac OS).

Steps to reproduce:
```
$ mkdir gothree
$ cd gothree/
$ export GOPATH=`pwd`
$ go get -u github.com/goadesign/goa/...
$ mkdir goa-adder
$ cd goa-adder/
$ mkdir design
$ cd design/
$ cat > design.go
package design

import (
        . "github.com/goadesign/goa/design"
        . "github.com/goadesign/goa/design/apidsl"
)

var _ = API("adder", func() {
        Title("The adder API")
        Description("A teaser for goa")
        Host("localhost:8080")
        Scheme("http")
})

var _ = Resource("operands", func() {
        Action("add", func() {
                Routing(GET("add/:left/:right"))
                Description("add returns the sum of the left and right parameters in the response body")
                Params(func() {
                        Param("left", Integer, "Left operand")
                        Param("right", Integer, "Right operand")
                })
                Response(OK, "text/plain")
        })

})
^C
goagen bootstrap -d goa-adder/design
exit status 1
invalid version string format ""
```

> Is there any chance that goagen may be using an older (e.g. vendored) goa? If not can you provide exact repro steps? thanks!

Since there is no goagen --version (or similar) option it is hard to show what version I'm using; but I assume that if I 'go get' it fresh I get the latest?

**Comment by raphael** [comment]
there is actually a `goagen version` command. It should print: ```
❯ goagen version
goagen v0.2.dev
The goa generation tool.
```

**Comment by dhrp** [comment]
hmm. Interesting. 

Is is possible the version available for mac differs from the one available on linux?, if the steps I described above are not sufficient to get a new version of goa / goagen, then how do I get a newer release?

On linux I get the version printed.
```
$ goagen version
goagen v0.2.dev
The goa generation tool.
```

On Mac I get: 
```
$ goagen version
Error: unknown command "version" for "goagen"
Run 'goagen --help' for usage.
```

**Comment by raphael** [comment]
There seems to be a few things wrong with the steps above:

1. the `goa-adder` directory should be created under `$GOPATH/src` and not `$GOPATH`
2. I don't see the $PATH env var being updated so it's probably not using the `goagen` you just go getted.

You need a `export PATH=$PATH:$GOPATH/bin` before calling `goagen`.

**Comment by raphael** [comment]
And no there is no difference between Linux or Mac. It just means that you are using an old version on Mac.

**Comment by dhrp** [comment]
Ok. Thanks for helping me work through this!

There seems to be a few things wrong with the steps above:

> the goa-adder directory should be created under $GOPATH/src and not $GOPATH
This I actually had done right; just forgot to copy over this step to above list.

> I don't see the $PATH env var being updated so it's probably not using the goagen you just go getted.

That's the crutch! when doing a new install the proper (new) binary gets build, but I did indeed forget to update my $PATH. I'm still a bit new to Go, so this was a dumb mistake. --- Still trying to figure out what command should be used then to update & rebuild the binaries. (just deleting the binary works, but seems a bit weird)

**Comment by raphael** [comment]
Good to hear you got it to work. In terms of updating a binary `go get -u github.com/goadesign/goa/goagen` is what you want although I guess you probably also want to make sure to update goa as a whole so `go get -u github.com/goadesign/goa/...` is probably better.
