### ISSUE TITLE
Management Infrastructure on top of goa

### ISSUE THREAD

**Issue by joeblew99** [goadesign/goa#578]
https://github.com/Mashape/kong

Looks like a very nice fit and agnostic to goa.

**Comment by raphael** [comment]
Yes looks nice, agreed. If you feel like contributing an example that showcases how to use it with goa I'd be happy to accept a PR to the [examples ](https://github.com/goadesign/examples) repo. Closing this issue as it really isn't an issue though.

**Comment by joeblew99** [comment]
I will keep it in mind and when i get to it send in a PR. At the moment i am playing with codegen of the gopherjs code to work with react & angular. If you know of others doing this, maybe worth adding it on the web site somewhere. Again i will PR that back when its in some sort of decent shape.
The intent is to use the DSL to generate the GUI for Master / Detail patterns. 
I am currently in two minds about how best to control the order that the fields display in the Web Master List, and the order of the fields in the Web Detail Form. If you have any ideas on this yell !

**Comment by raphael** [comment]
Great - looking forward to the PR!

Wrt fields ordering - seems to me that you could have a default (e.g. alphabetical) but that you also need to give the DSL author control. At the end of the day this is not something the code generator can guess...

**Comment by SantoshSah** [comment]
Is there any example available of using Kong with goa?
