### ISSUE TITLE
Unable to install goagen in 

### ISSUE THREAD

**Issue by juneym** [goadesign/goa#584]
I'm unable to install the `goagen` package on machine (mac osx). Following is the transcript:

```

THEMAC0001:~ rmartinez$ go version
go version go1.6.2 darwin/amd64

THEMAC0001:~ rmartinez$ sw_vers -productVersion 
10.11.4

THEMAC0001:~ rmartinez$ go get github.com/goadesign/goa

THEMAC0001:~ rmartinez$ go get github.com/goadesign/goa/goagen
# github.com/goadesign/goa/goagen/codegen
go/src/github.com/goadesign/goa/goagen/codegen/workspace.go:263: undefined: astutil.DeleteNamedImport

```

**Comment by raphael** [comment]
Strange I would have expected `go get` to pick up the dependency and install it. I can't reproduce either (created a new Go workspace and I could `go get` `github.com/goadesign/goa/goagen` just fine after getting `github.com/goadesign/goa`). 

The missing package is `golang.org/x/tools/go/ast/astutil`, try installing that (`go get golang.org/x/tools/go/ast/astutil`)  and see if there are errors.

**Comment by knadh** [comment]
Same issue here (`go1.6.2 linux/amd64`).
- `go get github.com/goadesign/goa` works.
- `go get github.com/goadesign/goa/goagen` fails with the following: `goadesign/goa/goagen/codegen/workspace.go:268: undefined: astutil.DeleteNamedImport`

`astutil` is installed.

```
$ go list ... | grep astutil

golang.org/x/tools/go/ast/astutil
```

**Comment by raphael** [comment]
Which version of Go is this?

**Comment by knadh** [comment]
@raphael I am not using vendoring.

**Comment by faxal** [comment]
@knadh maybe you have an old version. Try `go get -u golang.org/x/tools/go/ast/astutil`
