### ISSUE TITLE
Client code is not handling String Param nil check  

### ISSUE THREAD

**Issue by laszlohordos** [goadesign/goa#586]
The design code defines an action with optional and required Parameter like this:  
```
	Action("create", func() {
		Routing(
			POST(""),
		)
		Description("Create new resource")
		Params(func() {
			Param("id", String)
			Param("_fields", String)
			Required("id")
		})
		Payload(jsonPayload)
		Response(Created, "/users/[0-9]+")
		Response(BadRequest)
	})
```

The generated code checks for nil value but it's never true.   

```
func (c *Client) NewCreateUsersRequest(ctx context.Context, path string, payload CreateUsersPayload, id string, action *string, fields *string, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("id", id)

	if fields != nil {
		values.Set("_fields", *fields)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType != "*/*" {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
```

In the `command.go` when this method is called the `&cmd.Fields` has the default empty string value.

```
func (cmd *CreateUsersCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/users"
	}
	var payload client.CreateUsersPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.CreateUsers(ctx, path, payload, cmd.Id, &cmd.Fields, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}
```
The `CreateUsersCommand` struct defines `Fields` as string so the nil check is always false.
```
CreateUsersCommand struct {
		Payload     string
		ContentType string
		Fields      string
		Id          string
		PrettyPrint bool
	}
```

The generated URL contains the `_field=` that make make the target service to fail.

**Comment by raphael** [comment]
Thank you for the report, this is indeed a bug. Will take a look at it shortly.

**Comment by raphael** [comment]
ugh this is turning into a little bit of a nightmare.

The basic issue is that the `pflag` package doesn't let you easily distinguish between a flag being set to a default value or a flag not being set. So the alternatives are:

- Check whether a flag value is the zero value (`""` for strings, `0` for int etc.) and in this case substitute with `nil` prior to calling the client method. This has the obvious problem of not making it possible to use zero values.

- Come up with some default that then get compared to (e.g. `"IAMNOTSET"` for strings). If the flag has the default value then substitute with nil. However this doesn't work for bool and is a bit weird with ints.

- Create a set of new flag value types that implement the `pflag.Value` interface and track whether `Set` was called.

Seems like that last option is the best of the bunch but that's a ton of code for what is really a corner case :(

Maybe I'm missing something - if anyone has a better idea please share :)

**Comment by raphael** [comment]
I have cobbled together a fix. Basically the code now checks whether the flag is set by inspecting `os.Args` and if not sets the value to nil instead of using the default value. Not awesome but I can't think of anything better... See #588
