### ISSUE TITLE
Repository for 3rd party DSLs

### ISSUE THREAD

**Issue by verdverm** [goadesign/goa#597]
Wondering if there is a repository dedicated for 3rd party repositories?

gorma seems to be officially supported now? (and in its own repo)

Is there a plan or strategy moving forward?

---

I think that a central place for 3rd party DSLs will help foster an ecosystem and community.

**Comment by raphael** [comment]
Agree, a good start would be a dedicated page in `goa.design` that lists all such DSLs. Happy to accept PRs that create/update that page. When this page exists (and is not empty :) ) we can link to it from the main repo README.

**Comment by raphael** [comment]
Closing this for now.
