### ISSUE TITLE
Lowercase c:\ should be uppercase in goagen for Windows

### ISSUE THREAD

**Issue by JKhawaja** [goadesign/goa#598]
When running e.g.  `goagen bootstrap -d myapi\design` if `$GOPATH` is currently set at e.g. `C:\Projects\` on Windows box, goagen tool will return error e.g.`Go source file "c:\Projects\myapi\goagen828027691\design" not in Go workspace, adjust GOPATH C:\Projects\`. 

Changing the Windows `$GOPATH` variable to a lowercase `c:\Projects\` fixes the issue.

**Comment by raphael** [comment]
Thanks for the report! this should be fixed in master. Would you mind verifying?

**Comment by JKhawaja** [comment]
I still seem to be getting the same error. I cloned the master branch and ran the makefile  (which I believe generated me a new goagen binary) and uppercased the $GOPATH variable but still recieved same error as before.

**Comment by raphael** [comment]
Can you try running `go get -u github.com/goadesign/goa/...` and see if you still get the error?

**Comment by JKhawaja** [comment]
It seems to have "worked". But, now when running `goagen bootstrap -d cellar/design` it is returning an error: 
```
exit status 1
missing API definition, make sure design is properly initialized
```

**Comment by JKhawaja** [comment]
I seem to also be getting a different error on a personal project when running `goagen bootstrap -d myproject/design`: 
```
exit status 1
c:\$GOPATH\src\myproject\app does not contain a Go package
```

**Comment by raphael** [comment]
These issues seem different so I'm going to close this one. It looks like these could be vendoring issues? at least you'd get the same errors if things were not vendored properly.

**Comment by JKhawaja** [comment]
Even if the second error is (possibly but unlikely) related to vendoring, the first error: https://github.com/goadesign/goa/issues/598#issuecomment-231181696
only started occurring after the updated merge. Also, the second error is only run on a repo with a design package only so I am not sure how it could be looking for some other Go package.

**Comment by raphael** [comment]
OK I'm reopening the issue, will test on Windows.

**Comment by raphael** [comment]
That second error is probably due to dirty files that stayed around from previous failed generation attempts. It's the Go compiler complaining that the `app`  directory is empty or does not contain Go files. Can you start again from fresh?

**Comment by JKhawaja** [comment]
Tried everything fresh (including a new `go get -u github.com/goadesign/goa/...`) and still getting the same errors. :/

**Comment by raphael** [comment]
I'm able to use the latest `goagen` successfully on Windows. Closing this issue, please reopen and provide repro steps if you are still having problems.

**Comment by sunday9th** [comment]
When running  e.g. `goagen bootstrap -d goa-adder/design` if $GOPATH is set at e.g.  `D:\GO\pathPkg;D:\GO\pathWs` on Windows , goagen tool return error e.g. Go source file "D:\Go\pathWs\src\goa-adder\goagen375436827\design" not in Go workspace, adjust GOPATH d:\GO\pathPkg;d:\GO\pathWs 

Changing the Windows $GOPATH variable to a lowercase `d:\GO\pathPkg;d:\GO\pathWs` didn't fixes the issue.

2016/09/02
