### ISSUE TITLE
sqllite inc

### ISSUE THREAD

**Issue by joeblew99** [goadesign/goa#604]
Just wondering if sqllite is supported / envisaged.

Form has it: https://github.com/jinzhu/gorm/blob/master/dialects/sqlite/sqlite.go

But not sure if anyone has tried it yet.

**Comment by raphael** [comment]
Since gorma uses gorm in the backend I'm guessing it should mostly work. But I haven't actually tried it. If you have a need for it I would give it a shot and report any issues you find to the gorma repo.
