### ISSUE TITLE
vendored goagen broken?

### ISSUE THREAD

**Issue by kwk** [goadesign/goa#606]
Hey,

I'm working on a project that uses glide as its package manager. We followed [these instructions](http://goa.design/design/vendoring/) but we still get an this error when calling the `./vendor/github.com/goadesign/goa/goagen/goagen` binary:

```
$ ./vendor/github.com/goadesign/goa/goagen/goagen app -d github.com/goadesign/goa-cellar/design
invalid plugin package import path: cannot find package "github.com/goadesign/goa/goagen/gen_app" in any of:
	/usr/lib/golang/src/github.com/goadesign/goa/goagen/gen_app (from $GOROOT)
	/home/kkleine/go/src/github.com/goadesign/goa/goagen/gen_app (from $GOPATH)
```

# Reproducing the issue

To reproduce this issue you can start with a clean `$GOPATH` by temporarily renaming your old `$GOPATH` to `$GOPATH.bak``

```
$ mv -v $GOPATH $GOPATH.bak
$ mkdir -p $GOPATH/src/
$ mkdir -p $GOPATH/bin/
$ mkdir -p $GOPATH/pkg/
```

Download glide v0.11.0 from the release page https://github.com/Masterminds/glide/releases/tag/v0.11.0 and install in your `PATH` (not your `GOPATH`)

Now, clone the offical `goadesign/goa-cellar` example repo.

```
$ git clone https://github.com/goadesign/goa-cellar.git $GOPATH/src/github.com/goadesign/goa-cellar
$ cd $GOPATH/src/github.com/goadesign/goa-cellar
```

Run `glide init` and answer questions with `Y` and `M`.

This is how the `glide.yaml` looks on my computer:

```
package: github.com/goadesign/goa-cellar
import:
- package: github.com/goadesign/goa
  subpackages:
  - client
  - cors
  - design
  - design/apidsl
  - goatest
  - logging/log15
  - middleware
  - middleware/cors
  - middleware/security/basicauth
- package: github.com/inconshreveable/log15
  version: ^2.11.0
- package: github.com/spf13/cobra
- package: golang.org/x/net
  subpackages:
  - context
  - websocket
```

Run `glide install` to fetch the dependencies.

Now, build the goagen tool (This is from the [goa documentation](http://goa.design/design/vendoring/))

```
$ cd ./vendor/github.com/goadesign/goa/goagen
$ go build -v
$ cd ../../../../../
```

Now, run `goagen app` to get the error I get:

```
$ ./vendor/github.com/goadesign/goa/goagen/goagen app -d github.com/goadesign/goa-cellar/design
invalid plugin package import path: cannot find package "github.com/goadesign/goa/goagen/gen_app" in any of:
	/usr/lib/golang/src/github.com/goadesign/goa/goagen/gen_app (from $GOROOT)
	/home/kkleine/go/src/github.com/goadesign/goa/goagen/gen_app (from $GOPATH)
```

## Questions

Do you have any idea why this happens?

Why isn't the vendor directory checked for example? Only `$GOROOT` and `$GOPATH` are checked.

## Developement Environment

Double checking my go setup for `GO15VENDOREXPERIMENT=1`

```
$ go env
GOARCH="amd64"
GOBIN="/home/kkleine/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kkleine/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
My GOPATH contains only these directories:
```

# Restore your GOPATH

Don't forget to restore your old `$GOPATH`:

```
mv $GOPATH /tmp
mv -v $GOPATH.bak $GOPATH
```

**Comment by kwk** [comment]
Please see the updated description for a reproducible setup.

**Comment by raphael** [comment]
Thank you, this helps

**Comment by kwk** [comment]
@raphael I've also setup a smaller repo with no code all that demonstrates the problem. See https://github.com/kwk/broken-goagen

**Comment by kwk** [comment]
@raphael Searching for the error "invalid plugin package import path" revealed [this function](https://github.com/goadesign/goa/blob/master/goagen/codegen/workspace.go#L321):

```go
// PackageSourcePath returns the absolute path to the given package source.
func PackageSourcePath(pkg string) (string, error) {
	buildCtx := build.Default
	buildCtx.GOPATH = os.Getenv("GOPATH") // Reevaluate each time to be nice to tests
	wd, err := os.Getwd()
	if err != nil {
		wd = "."
	}
	p, err := buildCtx.Import(pkg, wd, 0)
	if err != nil {
		return "", err
	}
	return p.Dir, nil
}
```

Maybe it must be fixed to search in the local `vendor` dir as well, depending on `GO15VENDOREXPERIMENT`.

A colleague reported that in go 1.6 it works without any adjustment.

**Comment by kwk** [comment]
@raphael Reading up on this call `buildCtx.Import(pkg, wd, 0)` I noticed that the `ImportMode` should include `vendor` by default. hm

**Comment by raphael** [comment]
ugh I'm not able to reproduce this with Go 1.6.2:
```
~/go2/src/github.com/kwk/broken-goagen master*
❯ ./vendor/github.com/goadesign/goa/goagen/goagen app -d github.com/kwk/broken-goagen/design
app
app/contexts.go
app/controllers.go
app/hrefs.go
app/media_types.go
app/user_types.go
app/test
app/test/operands_testing.go

~/go2/src/github.com/kwk/broken-goagen master*
❯ echo $GOPATH
/home/raphael/go2

~/go2/src/github.com/kwk/broken-goagen master*
❯ ls $GOPATH/src/github.com/
kwk/
```
As you can see the only package is the `GOPATH` is the repro package yet `goagen` is able to generate just fine.

**Comment by raphael** [comment]
Which version of Go are you using? If not 1.6 is there a specific reason you can't use 1.6? (just trying to understand)

**Comment by raphael** [comment]
Can't repro - if you can provide a clear repro please reopen - thanks!

**Comment by mark-lb** [comment]
I'm seeing this bug with Go 1.6.2....
Following the instructions word for word with Glide, goagen is only inside the vendor directory:
```
go version
go version go1.6.2 linux/amd64
GOPATH=/home/mark/workspace/management/build/go /home/mark/workspace/management/build/go/src/server/vendor/github.com/goadesign/goa/goagen/goagen app -d server/design
invalid plugin package import path: cannot find package "github.com/goadesign/goa/goagen/gen_app" in any of:
        /usr/lib/go-1.6/src/github.com/goadesign/goa/goagen/gen_app (from $GOROOT)
        /home/mark/workspace/management/build/go/src/github.com/goadesign/goa/goagen/gen_app (from $GOPATH)
```

**Comment by mark-lb** [comment]
@kwk did you find a solution to this? Thanks

**Comment by kwk** [comment]
@mark-lb I guess yes. Take a look at http://github.com/almighty/almighty-core. There we have no problems. I am on Go 1.7 but our build systems run Go 1.6.

**Comment by mark-lb** [comment]
@kwk thanks for the pointer. But do you recall a specific fix for the issue? What was done wrong in the projects you noted on this issue, if you know? Thanks

**Comment by raphael** [comment]
@mark-lb just a sanity check: do you have `GO15VENDOREXPERIMENT` set to `0` in your environment? (it won't work if you do).

**Comment by mark-lb** [comment]
@raphael not only is the variable not set to 0, the issue also occurs with Go 1.7.4

**Comment by mark-lb** [comment]
Additionally, it's something specific to goagen. Building another package that has vendored dependencies (and I made sure that the GOPATH/src, pkg, and bin folders are devoid of 3rd party packages), even in the same vendor folder as the goa project, works.

**Comment by raphael** [comment]
Can you describe your setup (the entire content of your Go workspace, the value of GOPATH, the command that's failing). So far I haven't been able to reproduce the issue.

**Comment by mark-lb** [comment]
@raphael you can see the basic structure from the make output below.
GOPATH=/home/mark/workspace/management/gowork
The GOPATH is set in the makefile per command, as you can see below, including for the building of goagen
There is nothing in the GOPATH/src besides my code (the "server" package), and of course the vendor directory below it, created by Glide per the instructions on your site. 
The GOPATH/pkg and bin folders don't exist.
No symlinks anywhere in the path, which I believe cause issues for Go.
That's the gist of it. Anything else?
Thanks

```
Building goagen tool
cd /home/mark/workspace/management/gowork/src/server/vendor/github.com/goadesign/goa/goagen && GOPATH=/home/mark/workspace/management/gowork go build
Generating server framework with goagen tool
go version
go version go1.7.4 linux/amd64
GOPATH=/home/mark/workspace/management/gowork /home/mark/workspace/management/gowork/src/server/vendor/github.com/goadesign/goa/goagen/goagen bootstrap -d server/design
invalid plugin package import path: cannot find package "github.com/goadesign/goa/goagen/gen_app" in any of:
        /usr/local/go/src/github.com/goadesign/goa/goagen/gen_app (from $GOROOT)
        /home/mark/workspace/management/gowork/src/github.com/goadesign/goa/goagen/gen_app (from $GOPATH)
```

**Comment by mark-lb** [comment]
Well, I ended up switching to code-based generation which works for me.

**Comment by nidhinmohanc** [comment]
Getting following errors after running the command "go build"
main.go:5:2: cannot find package "github.com/goadesign/goa/client" in any of:
	/usr/lib/go-1.6/src/github.com/goadesign/goa/client (from $GOROOT)
	($GOPATH not set)
main.go:6:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/lib/go-1.6/src/github.com/spf13/cobra (from $GOROOT)
	($GOPATH not set)
main.go:7:2: cannot find package "goa-adder/client" in any of:
	/usr/lib/go-1.6/src/goa-adder/client (from $GOROOT)
	($GOPATH not set)
main.go:8:2: cannot find package "goa-adder/tool/cli" in any of:
	/usr/lib/go-1.6/src/goa-adder/tool/cli (from $GOROOT)
	($GOPATH not set)

**Comment by eladitzhakian** [comment]
Also getting this with go 1.7.4, glide 0.12.3

**Comment by tngan** [comment]
Getting this with go 1.8, glide 0.12.3
