### ISSUE TITLE
Proposal to allow encoders to specify an alternative media type and/or suffix

### ISSUE THREAD

**Issue by williambailey** [goadesign/goa#607]
I'm thinking that it would be handy if encoders were able to suggest an alternative `Content-Type` header to better reflect the content thats being sent to the client.

This is especially useful when using applications that look for suffix information when trying to parse `vnd.application/` media types. Swagger UI is a good example as without a `+json` suffix it won't pretty print the response.

Perhaps adding a `SuggestMediaType(mediaType string) string` method to the `Encoder` interface (or new `MediaTypeSuggester` interface if BC is a concern) that can then be called in the `func (service *Service) Send` function before the response gets sent. Routing through some kind of `func (encoder *HTTPEncoder) SuggestMediaType(accept string, mediaType string) string` function to choose the correct encoder.

``` go
func (service *Service) Send(ctx context.Context, code int, body interface{}) error {
    r := ContextResponse(ctx)
    if r == nil {
        return fmt.Errorf("no response data in context")
    }

    r.Header().Set(
        "Content-Type",
        service.Encoder.SuggestMediaType(
            ContextRequest(ctx).Header.Get("Accept"),
            r.Header().Get("Content-Type"),
        ),
    )

    r.WriteHeader(code)

    return service.EncodeResponse(ctx, body)
}
```

Potentially related to #431. 

Apologies for the implementation suggestion and psudo code example. I wanted to raise the proposal before I forgot as time is a bit pressing at this end to fully flesh out a PR with real implementation and tests.

**Comment by raphael** [comment]
I think what you are asking for already exists: in the design you can use [ContentType](http://goa.design/reference/goa/design/apidsl/#func-contenttype-a-name-apidsl-contenttype-a) to override the value of the `Content-Type` header. See the [docs](http://goa.design/reference/goa/design/apidsl/#func-mediatype-a-name-apidsl-mediatype-a) for an example.

**Comment by williambailey** [comment]
Can I override the value for each supported encoder in my application?

I like the `vnd.application/my.type` for each media type and would love for the server to send `vnd.application/my.type+json`, `vnd.application/my.type+xml`, `application/msgpack`, or `application/x-www-form-urlencoded` back to the client depending on what encoder was chosen due to the `Accept` request header.

**Comment by raphael** [comment]
No that's not currently supported and yes it's basically what #431 was about too. I'll leave this issue opened as a feature request.

**Comment by alexdias** [comment]
@raphael Hi, do you have any updates on this? We'd love to get this functionality in. I'm happy to do some work on it if you can point me in the right direction.
