### ISSUE TITLE
Goa uuid.UUID fail combined with Gorma, missing sql.Scanner and driver.Value interface

### ISSUE THREAD

**Issue by aslakknutsen** [goadesign/goa#609]
After Goa 'reimplemented' UUID over using satori/go.uuid, all interfaces the satori v implemented got lost.

The Postgres SQL Driver can't store/read the Goa UUID without the Value/Scanner interfaces.

**Comment by raphael** [comment]
Thanks! I left a few comments in the latest PR basically asking to revert a few places where the import was changed to satori's (the places that are used by the client code).
