### ISSUE TITLE
Gopath and design question

### ISSUE THREAD

**Issue by Roconda** [goadesign/goa#617]
Hi,

I'm very new to go, but goa seems to be a great fit for the API's I need to build. 

The location of the design file isn't very clear to me. I would assume that I could just make a gopath in ~/.go/randomGoPath and use that gopath for my project in ~/Documents/workspace/randomProject. If I understand the documentation, the design file has to be included within the gopath directory, am I correct?

How would one structure their project including the gopath?

I also used the example project to test(gopath within the project):
```sh
Tims-MacBook-Pro:tmp tim$ cd examples/
Tims-MacBook-Pro:examples tim$ ls
Makefile	README.md	adder		code_regen	form_encoding	gopherjs	graceful	guide		security	types		upload		websocket
Tims-MacBook-Pro:examples tim$ cd upload/
Tims-MacBook-Pro:upload tim$ ls
README.md	bin		design		generate.go	image.go	pkg		src
Tims-MacBook-Pro:upload tim$ export GOPATH=`pwd`
Tims-MacBook-Pro:upload tim$ export PATH=$PATH:$GOPATH/bin
Tims-MacBook-Pro:upload tim$ go get github.com/goadesign/goa && go get github.com/goadesign/goa/goagen
Tims-MacBook-Pro:upload tim$ go generate
invalid design package import path: cannot find package "github.com/goadesign/examples/upload/design" in any of:
	/usr/local/Cellar/go/1.6/libexec/src/github.com/goadesign/examples/upload/design (from $GOROOT)
	/tmp/examples/upload/src/github.com/goadesign/examples/upload/design (from $GOPATH)
generate.go:1: running "goagen": exit status 1
```

Many thanks,
Tim

**Comment by raphael** [comment]
Hello, in case you haven't yet I highly recommend reading [https://golang.org/doc/code.html](https://golang.org/doc/code.htm) - this should clarify a few things for you.

In short the design file should live in the design package which would typically be a sub-package of your project. The layout would be something like:

```
$GOPATH
├── bin
├── pkg
└── src
    └── github.com
        └── my-user
            └── my-project
                └── design
                    └── design.go
```
