### ISSUE TITLE
goagen doesn't complain if attributes don't exist in any view

### ISSUE THREAD

**Issue by narayandesai** [goadesign/goa#624]
Currently, if a MediaType is defined with an Attribute that isn't included in any view, that field isn't included in the generated data types. This seems like legitimate behavior to me, but should probably cause a runtime warning/error during code generation, since it is confusing to new users.

Thanks!
 -nld

**Comment by raphael** [comment]
I tried implementing this and realized that it's actually not that simple. For example the goa-cellar repo does this:
```go
		Response(OK, func() {
			Media(CollectionOf(Bottle, func() {
				View("default")
				View("tiny")
			}))
		})
```
which creates a media type with a subset of the views and which would then cause an error.
It may be possible to distinguish between generated and non-generated media types but I wonder how valuable that ends up being (plus there's the issue where a view may be used by a generated media type and not the original).

So I'm going to close this issue.
