### ISSUE TITLE
When using Files DSL, swagger file does not have a basePath

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#631]
Even though the design has a BasePath set on API, if the Files DSL is used, basePath is no longer set in the swagger file. That makes sense, but it would be useful to force it to have it, in particular if resources served via a Files DSL are hidden from swagger, see #628

**Comment by raphael** [comment]
The problem with that is if you did not hide the file servers then the path for these in the Swagger docs would be incorrect. I guess if all file servers are hidden then the basePath property could be set. I'll add a comment to that effect to the corresponding issue and close this one.

**Comment by zetsub0u** [comment]
Hi i understand the problem but the generated spec should still have an empty basePath, in my case some client libraries do weird things when they don't have a basePath, for example bravado generates urls concatenating the spec url with the endpoint url, if i manually add a basePath: '' it works fine.

**Comment by raphael** [comment]
OK reopening this issue.
