### ISSUE TITLE
No response returned when you specify Payload option for GET request in a Resource

### ISSUE THREAD

**Issue by faxal** [goadesign/goa#649]
While exploring goa today, I accidentally set `Payload` option in a `GET` action in a resource. 

When I tried to retrieve this resource request seems to get completed from goa stack, as logs show request as completed with the correct response code `400`.

```
2016/07/27 13:17:17 [INFO] started req_id=eKHn2uF76Q-1 GET=/api/v1/requests/123e4567-e89b-12d3-a456-426655440000 from=::1 ctrl=RequestController action=Show
2016/07/27 13:17:17 [INFO] params req_id=eKHn2uF76Q-1 requestID=123e4567-e89b-12d3-a456-426655440000
2016/07/27 13:17:17 [INFO] completed req_id=eKHn2uF76Q-1 status=400 error=SJzaUpVH bytes=92 time=3.23645ms
```

But nothing actually gets sent to the browser and it doesn't log the actual cause of the error.

If I put a print statement inside `ErrorHandler` I get:
`[SJzaUpVH] 400 invalid_request: missing required payload`

Which is exactly what I expected to see in the logs or in browser response.

My resource definition:
```
var _ = Resource("request", func() {
	BasePath("/requests")
	DefaultMedia(RequestMedia)

	Action("show", func() {
		Description("Get request by it's ID")
		Routing(GET("/:requestID"))
		Params(func() {
			Param("requestID", String, "Request ID")
		})
		Payload(RequestPayload)
		Response(OK)
		Response(NotFound)
	})
})
```

Of course it works if I remove the `Payload`  option, but would be nice to see the actual error. That would save a lot of debugging time.

**Comment by bits01** [comment]
Perhaps the ErrorHandler should have a debug option to log *all* errors to aid debugging. Or the current verbose option could serve both purposes.

**Comment by faxal** [comment]
@bits01 That is what threw me off, when I tried with chrome, didn't even show status code. But as you mentioned, it works with curl, postman etc.

PS: Firefox does show status code, but not the body. Which is understandable due to Content-Type.

**Comment by raphael** [comment]
There is a [LogResponse](http://goa.design/reference/goa/middleware/#func-logresponse-a-name-middleware-logresponse-a:37ab2f15ff048f67959bcac0a6032f32) middleware you can use in development to log all response bodies. Would that work?

**Comment by bits01** [comment]
Would it make sense to enable LogResponse by default in the initially generated code just like verbose is on? Then of course as you get more experience with goa you learn that you have to turn it off.

**Comment by raphael** [comment]
I find the current default setup strikes a good balance between too much logging and not enough. The case here of testing an API with a browser and not seeing the response in the browser doesn't seem strong enough that it warrants changing the default. Maybe there could be a commented out line that enables the `LogResponse` middleware to raise awareness.

**Comment by bits01** [comment]
I'm OK with it and only know about the browser "issue" because I ran into it in a previous life, but I can see how it can be frustrating for a new user excited to play with goa.
Not a bad idea to have the lines commented out by default.

**Comment by faxal** [comment]
:+1: on LogResponse. That is good enough for me. Like the commented out LogResponse idea, knows it exists.

**Comment by raphael** [comment]
OK closing this.
