### ISSUE TITLE
Examples for links do not respect MT link view

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#665]
See `goa-cellar` generated swagger files. The `Account` MT `link` view includes only `id` and `href` but the generated examples show a full view for Account links.

This causes a problem when MTs refer to other MTs in deep recursive structures. The generated swagger files can be really large and the swagger-ui has a hard time parsing them.

Not sure whether this is an issue with just the links or in general with any resource that specifies a default view other than `default` given the recent change in #661

**Comment by raphael** [comment]
Fixed in both master and v1, thanks!
