### ISSUE TITLE
Generated client incorrectly encodes arrays in query string

### ISSUE THREAD

**Issue by tve** [goadesign/goa#676]
The generated client produces an array encoding for the query string using ',' instead of a repetition of the param. E.g., `ids=1,2,3` instead of `ids=1&ids=2&ids=3`.

Also, the test whether a query string param is necessary should use `if len(array) > 0` instead of `if array != nil`.

**Comment by tve** [comment]
Looks like the test may not matter as much, I think you need to produce:
```
if len(databags) > 0 {
  for _, e := range databags {
    values.Add("databags", e)
  }
}
```

**Comment by raphael** [comment]
This should be fixed, thank you!
