### ISSUE TITLE
Required field validation not triggered on server when user inputs missing JSON fields in client

### ISSUE THREAD

**Issue by aslakknutsen** [goadesign/goa#687]
Assuming a API payload like:

``` go
var CreatePayload = Type("CreatePayload", func() {
    Attribute("type", String, "The type of the newly created item")
    Required("type")
})
```

The server side will generate:

``` go
type createPayload struct {
    Type *string `form:"type,omitempty" json:"type,omitempty" xml:"type,omitempty"`
}

type CreatePayload struct {
    Type string `form:"type" json:"type" xml:"type"`
}
```

When a non GOA generated client sends:

``` json
{}
```

The createPayload Validate() method will trigger as Type is missing.

The same createPayload/CreatePayload structs are generated for the client, but when used on the client side the outcome is slightly different.

When goa cli is executed with --payload "{}" the XCommand.Run method will parse the --payload value into the CreatePayload structure to pass the rich object to the client.Action method. 

Since this is a required Attribute, the CreatePayload Type is not a pointer and the parsed "{}" will be later sent to the server as '{"Type":""}'. 

At which point the server side accepts "" as a valid String value and bypass the server side validation passing the invalid object to the Controller.

**Comment by aslakknutsen** [comment]
One can argue the Controller need to handle "" anyway, but.. should the client change the input data 'randomly' ?

**Comment by aslakknutsen** [comment]
My first guess would be that the Client should go through the same dance with createPayload.Validate()|Pulbizie() to CreatePayload as the server does since it has all the validation rules there as well... The server may have changed it's validation rules since the client was generated tho..

**Comment by raphael** [comment]
This only affects the client tool correct? Not the client package. The server will return the error. So this would prevent the useless request which would be good but really we're talking about optimizing the tool so not something critical. What you described makes sense though, ideally the code would unmarshal in the private struct, validate and then create the public struct with `Publicize`.
