### ISSUE TITLE
Links to URLs in the apidsl reference document are rendered wrong

### ISSUE THREAD

**Issue by fd0** [goadesign/goa#692]
Hi,

I noticed that the links to external URLs in the API DSL reference document do not work, e.g. https://goa.design/reference/goa/design/apidsl/#func-oauth2security-a-name-apidsl-oauth2security-a contains the following HTML:
```html
<a href="a href=&quot;https://aaronparecki.com/2012/07/29/2/oauth2-simplified&quot;&gt;https://aaronparecki.com/2012/07/29/2/oauth2-simplified&lt;/a">Aaron Parecki’s
writeup</a>
```
(Note the extra `a href=` in the `href` attribute)

**Comment by raphael** [comment]
Thank you!  do you think you could move this issue to the goa.design repo? Thanks!

**Comment by fd0** [comment]
Sure: https://github.com/goadesign/goa.design/issues/35
