### ISSUE TITLE
How to do something before returning to client?

### ISSUE THREAD

**Issue by sipt** [goadesign/goa#693]
```
                           +----------------+
            Request        |                |
      +-------------------->  Middleware    |
      |                    |                |
      |                    +----------------+
      |                           |
      |                           |
+-----------+              +------v---------+
|           |              |                |
|   Client  |              |  Controller    |
|           |              |                |
+-----------+              +----------------+
      ^                           |
      |                           |
      |                           |
      |                    +------v---------+
      |      Response      |                |
      +--------------------+ <Do something> |
                           |                |
                           +----------------+
```
I want to do something before returning to client.
How to do it?

**Comment by jim-slattery-rs** [comment]
@sipt What kind of thing do you want to do?  Middleware can also do things after the controller returns. Your graph should look more like a stack where the request goes up through the middleware, to the controller, and back down through the middleware and back to the client.

**Comment by raphael** [comment]
Just to make sure: you can and should edit the generated controllers. The files generated by the `bootstrap` and `main` commands in the `main` package are yours: you should edit them and put the code you need in the functions that are in these files. They won't bet overwritten (as opposed to the files in the `app` package for example that do get overwritten).

**Comment by sipt** [comment]
@jim-slattery-rs @raphael 
I see.
Thanks.~(￣▽￣)~
