### ISSUE TITLE
fasthttp support

### ISSUE THREAD

**Issue by kirillDanshin** [goadesign/goa#708]
Hi! Thanks for awesome project.
Can you add fasthttp support?
I want to use goa but my projects can't handle its load with net/http.
Thanks.

**Comment by raphael** [comment]
This is not currently on the roadmap but I'm happy to help if you want to give it a shot. It should be possible to implement with a [plugin](http://goa.design/extend/generators/). The plugin implementation can leverage the existing code generation functions for the bulk of the work, it would only have to deal with generating the right glue code with the fasthttp server.
