### ISSUE TITLE
Typo in the readme about not regenerating the main.go on running the gen tool

### ISSUE THREAD

**Issue by sbose78** [goadesign/goa#709]
main.go and operands.go contain scaffolding code to help bootstrap the implementation. running goagen again does no recreate them so that it's safe to edit their content.

Needs to be 
->

main.go and operands.go contain scaffolding code to help bootstrap the implementation. running goagen again does *not* recreate them so that it's safe to edit their content.

**Comment by raphael** [comment]
Thanks for the fix!
