### ISSUE TITLE
Multiple CORS Origins or Origin Regex

### ISSUE THREAD

**Issue by matteosuppo** [goadesign/goa#718]
At the moment we can use wildcards only once, to define patterns such as `*.arduino.cc`.

But suppose I wanted to define a patterns such as `*.arduino.cc:*`, or multiple acceptable origins.

Is there a way to use multiple Origins?
If not, would it be a good idea to use a regular expression in the function Origin of the dsl?

**Comment by matteosuppo** [comment]
Maybe I should use a custom dsl? https://goa.design/extend/dsls.html

**Comment by raphael** [comment]
I wouldn't be opposed to extending the DSL to support regular expressions on top of wildcards. We'd need a way to differentiate though, maybe if the string starts and ends with `/` then it's considered to be defining a regexp?

**Comment by matteosuppo** [comment]
Sounds reasonable. This way it would be backward compatibile.  Tomorrow I'll hack something out.

**Comment by raphael** [comment]
Great, thank you!
