### ISSUE TITLE
Swagger definition for payload created twice

### ISSUE THREAD

**Issue by dobegor** [goadesign/goa#724]
Specifying a Payload with a non-anonymous UserType/MediaType struct leads goagen Swagger generator to create defintion of that type twice: as a separate (and probably unused) definition for type itself and a definiton for %ActionName%Payload.

**Comment by raphael** [comment]
Can you please provide a complete design to repro and indicate what's incorrect in the resulting swagger? will avoid some guess work :)

**Comment by raphael** [comment]
I believe this has been fixed, can you confirm?

**Comment by dobegor** [comment]
Yeah, LGTM. Awesome thanks!
