### ISSUE TITLE
Why can't datetime have a default value?

### ISSUE THREAD

**Issue by matteosuppo** [goadesign/goa#726]
Today I was writing this:

```
	Action("list", func() {
		Description("show a list of appointments for the selected time. If no interval is selected it shows the appointments of the current week")
		Routing(GET(""))
		Response(OK, CollectionOf(AppointmentMedia))
		Params(func() {
			Param("start", DateTime, "The start of the interval", func() {
				Default(now.BeginningOfWeek())
			})
			Param("end", DateTime, "The end of the interval", func() {
				Default(now.EndOfWeek())
			})
		})
	})
```

and I got 

```
datetime type cannot have a default value
```

I wonder why is that. Is there a shortcoming I'm not seeing?

**Comment by raphael** [comment]
I think that's because `DateTime` was added later. I don't see a reason why it couldn't be made to work - looks like an oversight.

**Comment by matteosuppo** [comment]
Maybe the Default value is resolved at compile time instead then at request time?

**Comment by raphael** [comment]
Default values are executed when the design is, i.e. when the generated generator tool is loaded. They are stored in a field which the code generation algorithm then uses to render the code. Here the code needs to generate something like `time.Parse(time.RFC3339, "{{ .Default.Format("RFC3339") }}")`.
