### ISSUE TITLE
prometheus metrics

### ISSUE THREAD

**Issue by maleck13** [goadesign/goa#730]
Hey guys, I really like the work you are doing here. I have been reading through the docs and trying it out. I was wondering if there is a way to hook in metrics of some form. For e.g prometheus. Would this require a plugin or is there a way to achieve this without a plugin

**Comment by raphael** [comment]
goa integrates https://github.com/armon/go-metrics and does a few things with:

1. It increments a counter any time a validation error occurs with the error message as key
2. It increments a counter any time a response is written with the response status code as key
3. It sends timing information for each encoding and decoding operation

go-metrics supports multiple backends, one of which is Prometheus.

goa also exposes a few helper functions your code can take advantage to send metrics information to the backend - see https://github.com/goadesign/goa/blob/master/metrics.go

**Comment by raphael** [comment]
It would also be trivial to add a middleware that sends timing information for each requests. PRs welcome! :)

**Comment by maleck13** [comment]
@raphael thanks for the reply and the links. Perhaps once I am more familiar with how everything fits together, I will take a look at creating a PR :)

I do have one other question. It is about the tests that are generated. They don't seem to be standard go tests. How do you run these generated tests. I assume 

```
go test

```

isn't going to work with them. If you would prefer I open a separate issue for this I don't mind

**Comment by raphael** [comment]
What's generated aren't tests but test helpers that your tests can take advantage of. The helpers take care of building the proper request, calling and validating the response (if the media type defines validations) and return the object to your tests for further checking.

**Comment by raphael** [comment]
Closing the issue, please join the slack channel - it's a better place for these types of questions.

**Comment by hectorj2f** [comment]
@raphael we're interesting on this, is there anything new about it ?

**Comment by raphael** [comment]
I'm guessing you are asking about the middleware? if so then no I don't think any progress has been made.

**Comment by hectorj2f** [comment]
@raphael Yes!. However I'll start by having a metrics endpoint in my API. I tried to get an idea on how to use or consume goa default metrics. I couldn't find any example. 

Is there any example ? 

Also, could I get an invitation to the Slack Channel ?

**Comment by raphael** [comment]
No example on metrics yet, another good contribution awaiting :)
Checkout https://gophersinvite.herokuapp.com/ to get an invitation for the gophers slack.
