### ISSUE TITLE
metrics: Replace armon/go-metrics with an Interface

### ISSUE THREAD

**Issue by bketelsen** [goadesign/goa#731]
Replace the built-in go-metrics dependency with an interface and separate package implementing the interface to remove this dependency.

This won't be an easy interface to create, an adapter to all the various metrics collection tools is probably overwhelming.  Perhaps we can export a channel of specific events and let the implementing packages consume & process those events?

**Comment by sovchinn** [comment]
Not sure if the implementation of this would solve my issue below but wanted to post here as a fyi:

I was checking out goa and noticed that the inclusion of this dependency prevents goa generated apps from being deployable onto Google App Engine Standard.

GAE Standard does not allow syscall imports and there is a syscall import here: github.com/armon/go-metrics/const_unix.go

Deployment throws with:
go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/armon/go-metrics/const_unix.go from GOPATH

Would you have any short-term workaround ideas other than switching away from GAE standard?

**Comment by raphael** [comment]
@sovchinn as discussed in slack there isn't a good workaround at the moment. I suggest opening an issue with the `go-metrics` repo.
