### ISSUE TITLE
generated client Path functions should fix //

### ISSUE THREAD

**Issue by tve** [goadesign/goa#732]
Should the generated *Path functions in the client use `path.Join` or otherwise eliminate '//' in generated paths?

**Comment by tve** [comment]
Mhh, `path.Join` understands `.` and `..` which may have undesirable side-effects...

**Comment by raphael** [comment]
Capturing your suggestion so it doesn't get lost...
```go
href = strings.TrimLeftFunc(href, func(r rune) bool { return r == '/' })
```
