### ISSUE TITLE
Use Response Content Type to specify API version

### ISSUE THREAD

**Issue by egbertp** [goadesign/goa#735]
First of all: great work, I really like Goa!

I would like to implement semantic versioning in my API. Using an other framework, I simply used the Accept header for this. E.g.: 

**API version 1**

``` sh
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/v1+json' 'http://example.com/cars'
```

**API version 2**

```
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/v2+json' 'http://example.com/cars'
```

I tried to implement this behaviour in Goa by creating two different mediatypes: 

``` go
var CarV1 = MediaType("application/vnd.paintshop.car.v1+json", func() {
    Description("Log Event")
    Reference(EventPayload)
    Attributes(func() {
        Attribute("type")
        Attribute("message")

        Required("type", "message")
    })

    View("default", func() {
        Attribute("type")
        Attribute("message")
    })
})

var CarV2 = MediaType("application/vnd.paintshop.car.v2+json", func() {
    Description("Car")
    Reference(CarPayload)
    Attributes(func() {
        Attribute("type")
        Attribute("message")
        Attribute("brand")
        Attribure("fuel")

        Required("type", "message")
    })

    View("default", func() {
        Attribute("type")
        Attribute("message")
        Attribute("brand")
        Attribure("fuel")
    })
})
```

This is the design code of my `car` resource

``` go
var _ = Resource("car", func() {

        DefaultMedia(LogEventV1)
        BasePath("/cars")


        Action("show", func() {
            Routing(
                GET("/:carID"),
            )
            Description("Retrieve car with given id.")
            Params(func() {
                Param("carID", Integer, "Car ID")
            })
            Response(OK)
            Response(NotFound)
            Response(BadRequest, ErrorMedia)
        })
```

My /cars/show function (not auto-generated) looks like this:

``` go
// Show runs the show action.
func (c *EventController) Show(ctx *app.ShowEventContext) error {
    // EventController_Show: start_implement

    // Put your logic here

    s := "Aston Martin"
    p := "Has a nice sound"
        res := &app.PaintshopCarV1{
            Type: s,
            Message: p,
       }
    return ctx.OK(res)
}
```

Now I have two questions:
1. How can I implement the controller, such that it responds different to a v2 request vs. a v1 request?
2. Can I use the 'Response Content Type' dropdown in swagger-ui to select `application/v1+json` and `application/v2+json`?

**Comment by raphael** [comment]
Thanks for the kind words! 

1. One way would be to look at the header itself directly in the controller (`ctx.RequestData.Header.Get("Accept")`). You could also write a middleware that parses the header and injects the version in the context.

2. That is not possible today but something that could be added fairly easily. The idea would be to make it possible to attach more than one `ContentType` to media types. Today the `ContentType` DSL sets the one value in the `MediaTypeDefinition` struct, it could append to a slice instead. The swagger code generator could then be modified to iterate over the slices and set the `Produces` field of `Operation`. The genapp code generator would also have to be modified to set the value with e.g. the first value in the slice (which would become the default value if the header is not already set). Today that code sets the header with the value of the `ContentType` field or it not set the value of the media type identifier (if not already set).

**Comment by tw-maustin** [comment]
I was looking to do this to, and I was wondering if it would make sense to add it right into the MediaType DSL and handle it there. 

something like 
```
MediaType("application/vnd.paintshopcar+json", func() {
    Description("a versioned car")
    ContentVersion(1)  
...
))
```
```
`Accept: application/vnd.paintshopcar+json version=1`
```
It seems like it would not be a huge amount of work to make it part of the system? Or am I overlooking something.

**Comment by raphael** [comment]
Thinking about this I realized there's another issue: a given response may only specify one media type. Having different media types for different versions requires a single response to be mapped to multiple media types. This would be a bigger change to implement (the client would also have to understand versioned requests and responses). Conceptually the feature makes sense though, happy to help with putting together a PR.

**Comment by raphael** [comment]
@tw-maustin your proposal makes sense to me. It's a little bit more narrow that allowing for multiple generic Content-Type which is probably a good thing.

**Comment by KerwinKoo** [comment]
@raphael Can you show any code demo for example 2? Thanks!

**Comment by raphael** [comment]
You would simply define different actions for each version, something like:
```go
var _ = Resource("versioned", func() {
    Action("show", func() {
        Routing(GET("/v1/versioned"))
        // ...
    })
    Action("showV2", func() {
        Routing(GET("/v2/versioned"))
        // ...
    })
})
```
As I write this I'm realizing one drawback is that you would have to define at least one of the routes using an absolute path since you can't change the prefix (so if the API specified `v1` as prefix you couldn't change that when defining the v2 paths other than by using absolute paths starting with `//`).

Solution 3 actually works quite well too. You would declare the trait defined in the example a few comments up then use it in versioned resources and/or actions:

```go
var _ = Resource("versioned", func() {
    UseTrait("versioned")
    // ...
```

Then you can have a middleware that extracts the version from the header or query strings.

**Comment by raphael** [comment]
I'm going to close this issue since at this point we've probably exhausted its usefulness..

**Comment by KerwinKoo** [comment]
@raphael  Thanks again!
