### ISSUE TITLE
gogen command not working [solved]

### ISSUE THREAD

**Issue by Odol** [goadesign/goa#741]
After install this packages
 
go get github.com/goadesign/goa
go get github.com/goadesign/goa/goagen

I try the command "goagen" but this not working :( 
the unicate way is create manually the binary from the package goagen 

OS: linux ubuntu v16.04

I 'm new to golang excuse my ignorance

**Comment by raphael** [comment]
Looks like you were able to make it work? Can you close the issue if that's the case or provide more details if not? Thanks!

**Comment by Odol** [comment]
Mmm in beego framework also have a tool called bee tool,  this 
I gave the same problem.

on your page say:
"bee is installed into GOPATH/bin by default. You need to add GOPATH/bin to your PATH, otherwise the bee command won’t work".

the solution for me, reference this binary manually :/
and working fine! Goa has the same problem mm, I could not tell if it only happens to me

MY GO ENV:

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/test"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

tanks for you response mate! 
you can close it if you want

**Comment by raphael** [comment]
sounds like you need to add `GOPATH/bin` to your `PATH` environment variable,
