### ISSUE TITLE
Design: MediaType and Type cannot use at same time

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#753]
I have defined a mediatype and a type:

```
var DealerPrivateData = apidsl.MediaType("application/qcoincenter.dealerRegister", func() {
    apidsl.Description("dealer private data register media")
    apidsl.TypeName("dealerPrivateData")
    apidsl.Attributes(func() {
        apidsl.Attribute("dealerID", design.String, "dealer uuid")
        apidsl.Attribute("dealerVerifyPwd", design.String, "dealer connecting password")
        apidsl.Attribute("dealer3DESPwd", design.String, "dealer 3des password")
        apidsl.Attribute("dealerHmacSHA1Pwd", design.String, "dealer HmacSHA1 password")
        apidsl.Attribute("dealerDec", design.String, "description of dealer")
        apidsl.Attribute("dealerSerialNO", design.String, "dealer serial NO.")
        apidsl.Attribute("priorityLevel", design.Integer, "dealer payment priority level")
        apidsl.Attribute("dealerStatus", design.Integer, `dealer Status:
            1: OK
            0: Frozen
            2: BlackList
            ...others`,
            func() {
                apidsl.Minimum(0)
            })
        apidsl.Attribute("dealerQCoinBalance", design.Integer, "dealer QCoin Balance")

        apidsl.Required("dealerVerifyPwd", "dealer3DESPwd", "dealerHmacSHA1Pwd",
            "dealerID", "dealerStatus", "dealerSerialNO", "priorityLevel",
            "dealerQCoinBalance")
    })

    apidsl.View("default", func() {
        apidsl.Attribute("dealerID")
        apidsl.Attribute("dealerVerifyPwd")
        apidsl.Attribute("dealer3DESPwd")
        apidsl.Attribute("dealerHmacSHA1Pwd")
        apidsl.Attribute("dealerStatus")
        apidsl.Attribute("dealerSerialNO")
        apidsl.Attribute("priorityLevel")
        apidsl.Attribute("dealerDec")
    })
})

// DealerAccount dealer account
var DealerAccount = apidsl.Type("DealerAccount", func() {
    apidsl.Attribute("dealerPrivateData", DealerPrivateData, "dealer private Data")
    apidsl.Attribute("dealerQCoinBalance", design.Integer, "dealer QCoin Balance")

    apidsl.Required("dealerPrivateData", "dealerQCoinBalance")
})

```

As what you can see, I defined a `MediaType` that named `DealerPrivateData`, with a "default" `View` also.  And I used it in `Type DealerAccount`.

It's OK when I run `goagen` to generate go source code. BUT it doesn't work after I run `go build`, it prints 

```
app/user_types.go:20: undefined: dealerPrivateData
```

Open file which the error info pointed out, It's 

```
// dealerAccount user type.
type dealerAccount struct {
    // dealer private Data
    DealerPrivateData *dealerPrivateData `form:"dealerPrivateData,omitempty" json:"dealerPrivateData,omitempty" xml:"dealerPrivateData,omitempty"`
    // dealer QCoin Balance
    DealerQCoinBalance *int `form:"dealerQCoinBalance,omitempty" json:"dealerQCoinBalance,omitempty" xml:"dealerQCoinBalance,omitempty"`
}
```

The struct `dealerPrivateData` undefined but **DealerPrivateData** defined.

How can I use `Type` to connect the struct which defined by `MediaType` at the same time?

Or are There other methods to reuse the design CODE?

**Comment by KerwinKoo** [comment]
I have updated goa to the latest commit 17712ecd397b264934b36c32e54f73423a2679dd

**Comment by raphael** [comment]
This is indeed a current limitation. Note that doing the above is not recommended, the recommended approach would be to define a type `DealerPrivateData` (not a media type). Then use that type in `DealerAccount` and also use it to define a new `DealerPrivateDataMT` media type using the `reference` keyword. See the last paragraph of https://goa.design/design/types/ .

**Comment by KerwinKoo** [comment]
Thank you @raphael , I think key word `reference` can resolve my prob.

**Comment by raphael** [comment]
I believe this is related to #772 in that goagen needs to generate the code for media types that are used as types.

**Comment by KerwinKoo** [comment]
The key `reference` works well. close this issue.

**Comment by bits01** [comment]
I'm running into the same issue. Could we please re-open if goa is to support MT attributes in a user type? If we want to not support it, then we should open another issue so that goagen fails with a descriptive error message that it is not allowed.

**Comment by bits01** [comment]
@raphael there was a comment on Slack that this may not be allowed come v2. If that's going to be the case, it's not worth fixing it but instead the "fix" should be to fail at gen time with an error.

**Comment by raphael** [comment]
My gut feeling is that we should fix it and make it work for v1, the syntax just lends itself to this use case. In v2 the syntax for where media types can be defined and used is more restrictive by design so it's unlikely you'll run into a case where it seems like a media type could be used but it cannot (and if you do it'll be clear why).
