### ISSUE TITLE
No OPTIONS handler for static file server

### ISSUE THREAD

**Issue by rootpd** [goadesign/goa#759]
For following resource:

```go
var _ = Resource("public", func() {
	Origin("*", func() {
		Methods("GET", "OPTIONS")
	})
	NoSecurity()
	Files("/swagger.json", "swagger/swagger.json")
})
```

Following controller snippet is generated:

```go
// MountPublicController "mounts" a Public resource controller on the given service.
func MountPublicController(service *goa.Service, ctrl PublicController) {
	initService(service)
	var h goa.Handler

	h = ctrl.FileHandler("/swagger.json", "swagger/swagger.json")
	h = handlePublicOrigin(h)
	service.Mux.Handle("GET", "/swagger.json", ctrl.MuxHandler("serve", h, nil))
	service.LogInfo("mount", "ctrl", "Public", "files", "swagger/swagger.json", "route", "GET /swagger.json")
}
```

All other controllers also include handlers for `OPTIONS` calls. I'd expect something like this be in the beginning of controller:

```go
service.Mux.Handle("OPTIONS", "/swagger.json", ctrl.MuxHandler("preflight", handlePublicOrigin(cors.HandlePreflight()), nil))
```

I stumbled upon the problem when I used Swagger UI locally - checked out and run `dist/index.html`. Google Chrome is internally doing `OPTIONS` request to the resource, but my Goa server is responding with 404 as it doesn't have handler associated with the call.

**Comment by raphael** [comment]
ugh a simple `GET` request like this should not involve a pre-flight request. I guess the Swagger UI must be sending non-standard HTTP headers :( Will look into adding a pre-flight handler.

**Comment by rootpd** [comment]
Now it gets weirder. I was able to get rid of an issue by changing the first statement to this:

```go
var _ = Resource("public", func() {
    Origin("*", func() {
        Methods("GET") // OPTIONS removed
    })
    NoSecurity()
    Files("/swagger.json", "swagger/swagger.json")
})
```

Apparently by setting this browser tried to make an OPTIONS call which then failed. Anyway, it might not be a real issue to handle, just a bad API definition.

**Comment by raphael** [comment]
I've added the generation for pre-flight handlers for file servers anyway as well as there's no way to guarantee a client won't send non standard headers. Fix is in `master` and `v1`
