### ISSUE TITLE
Unbuildable app generated when UserType.Field is type of MediaType using view without validations.

### ISSUE THREAD

**Issue by rootpd** [goadesign/goa#772]
Sorry for the title, I just wasn't able to make it shorter. The condition is just too edge :). In the end this is probably just missing validation within goagen for generating `Validate` function.

To reproduce, use following desing:

``` go
var MT1 = MediaType("application/vnd.mt1+json", func() {
    Attributes(func() {
        Attribute("foos", ArrayOf(MT2))
        // If I used CollectionOf(MT2), app would be buildable
    })
    View("default", func() {
        Attribute("foos")
    })
    Required("foos")
})

var MT2 = MediaType("application/vnd.mt2+json", func() {
    Attributes(func() {
        Attribute("bar", MT3)
    })
    View("default", func() {
        Attribute("bar", func() {
            View("tiny")
        })
    })
    Required("bar")
})

var MT3 = MediaType("application/vnd.mt3+json", func() {
    Attributes(func() {
        Attribute("bar", String)
        Attribute("baz", String)
        Required("bar")
    })
    View("default", func() {
        Attribute("bar") // single attribute with validation
    })
    View("tiny", func() {
        Attribute("baz") // single attribute without validation
    })
})
```

Run `goagen app -d $yourDesignPackage` or `goagen bootstrap -d $yourDesignPackage` so you have something quick to build.

My build failed on `app/media_types.go:114: e.Bar.Validate undefined (type *Mt3Tiny has no field or method Validate)`. In case the _tiny_ view contained at least one field requiring validation, the `Validate` method would get generated and the problem wouldn't occur.

Please let me know if you need the generated package or something else to clarify the issue.

**Comment by raphael** [comment]
Thanks for the detailed report, @arangamani do you think you could take a look?

**Comment by arangamani** [comment]
Sure.
