### ISSUE TITLE
Output indented JSON

### ISSUE THREAD

**Issue by gagliardetto** [goadesign/goa#778]
Hi all,

Thanks for creating and contributing to Goa!

I'd like to ask whether there is already a way to output indented JSON.

Thanks in advance.

**Comment by raphael** [comment]
Thanks! I'm guessing you are asking about the JSON schema output? there is no option today although it wouldn't be difficult to add one. That being said there are many other ways to get a formatted output, something like `cat schema/schema.json | python -mjson.tool` for example works fine.

**Comment by gagliardetto** [comment]
Hi Raphael

I'm talking about the case when the output is an `application/json` mediatype. The struct is marshalled, but not indented. Is there already a way to define a custom encoder/decoder?

**Comment by raphael** [comment]
ah got it. Using custom encoders and decoders is described here: https://goa.design/implement/encoding/ . It seems strange that your client would care though or to put it in another way it may make more sense to put that formatting in the client (obviously it's possible that doesn't make sense for your use case).

**Comment by gagliardetto** [comment]
Thanks! That's exactly what I've been looking for.
