### ISSUE TITLE
Using the app/test package with the same service from multiple goroutines causes a data race

### ISSUE THREAD

**Issue by luna-duclos** [goadesign/goa#794]
It looks like app/test tries to edit the passed service, which is not goroutine safe.
Either the app/test package needs to clearly document that if a service is passed in its functions are not goroutine safe, or this needs to be done in a safe manner (or not at all)

**Comment by raphael** [comment]
What do you suggest should be done? the test helpers need to override the encoder so they can capture the response. We can add a comment to the functions explicitly stating that but at the end of the day seems like it's the responsibility of the tests to guard against race conditions. Do you have a better idea?
