### ISSUE TITLE
Add Href function to MediaType dsl to auto-add href attributes

### ISSUE THREAD

**Issue by jsimonetti** [goadesign/goa#821]
This function would then auto populate the href for a response using the proper resource url.

Example:

```
// Account is the account resource media type.
var Account = MediaType("application/vnd.account+json", func() {
    Description("A tenant account")
    Attributes(func() {
        Attribute("id", Integer, "ID of account", func() {
            Example(1)
        })
        Href(Required())
        Attribute("name", String, "Name of account", func() {
            Example("test")
        })
        Attribute("created_at", DateTime, "Date of creation")
        Attribute("created_by", String, "Email of account owner", func() {
            Format("email")
            Example("me@goa.design")
        })

        Required("id", "name", "created_at", "created_by")
    })

    View("default", func() {
        Attribute("id")
        Href()
        Attribute("name")
        Attribute("created_at")
        Attribute("created_by")
    })

    View("tiny", func() {
        Description("tiny is the view used to list accounts")
        Attribute("id")
        Href()
        Attribute("name")
    })

    View("link", func() {
        Attribute("id")
        Href()
    })
})
```

Reason: currently you need to manually set the href on all objects return via a MT. Using (for example) Gorma, results in code that returns empty href's as Gorma is not aware that it's returned media needs to be transformed additionally. If you want to add href support to a project using Gorma you need to rewrite it's generated code (each time you generate new models).

**Comment by jsimonetti** [comment]
This would probably block on #556, since some form of finalization would be needed.

**Comment by raphael** [comment]
I like it! I would tweak it so that `Href` takes two arguments which are the name of the attribute to set with the href value and a (optional) description. I wouldn't use `Required()` the way you have it above, instead one would use the name given to `Href` in the `Required` list like other attributes.
