### ISSUE TITLE
MediaType referenced Payload doesn't inherit the validation

### ISSUE THREAD

**Issue by mattinsalto** [goadesign/goa#831]
I mean,
If we have a media type:

```
var Bottle = MediaType("application/vnd.bottle+json", func() {
    Attributes(func() {
        Attribute("id", Integer, "ID of bottle", func() {
            Example(1)
        })
        Attribute("href", String, "API href of bottle", func() {
            Example("/bottles/1")
        })
        Attribute("vineyard", String, "Name of the vineyard", func() {
            Example("Baigorri")
            MinLength(2)
            MaxLength(25)
        })
        Required("id", "href", "vineyard")
    })

    View("default", func() {
        Attribute("id")
        Attribute("href")
        Attribute("vineyard")
    })
})
```

And then we reference a payload to the media type:

```
var BottlePayload = Type("BottlePayload", func() {
    Reference(Bottle)
    Attribute("vineyard")
})
```

I was hopping attribute vineyard of the payload will inherit min and max length of Bottle media vineyard attribute, but it doesn't. Validate function of the payload doesn't check for length of vineyard. May be is a deliberate decision.

Thanks for sharing this great "framework". I like it very much.

**Comment by raphael** [comment]
Thanks for the report! Note that the recommended way of doing things is the opposite (the media type referencing the type), see https://goa.design/design/types/ for details. That being said this should work too so I'll leave this issue opened.

**Comment by mattinsalto** [comment]
OK, it makes sense to reference the type from the media type. Thanks.
