### ISSUE TITLE
Delay the evaluation of the CORS Origin value to runtime 

### ISSUE THREAD

**Issue by sergeleger** [goadesign/goa#833]
I would like to be able to specify the Origin values at runtime (without needing to change the GOA design). The simple use case is during development I'd provide "*" or even "somename.private", but in production I would use "example.com", or if I sell the app to a client they'd use something entirely different.

Am I missing something? 

One approach (patch?) might be to use environment variables:

``` golang
Origin("$MYCORS", ...)
```

The `handleXxxOrigin` function would then be responsible for getting the value from the environment, and calling either cors.MatchOrigin or cors.MatchOriginRegexp.

Another option might be to expose some of the handleXxxOrigins functionality via interfaces that we could implement. (I've done this with the goa.FileServer interface to solve the problem that directories are also hard coded in the design and not user configurable.)

Thanks

**Comment by raphael** [comment]
I understand the need for this but I'm not too sure on how to implement it. Using an environment variable doesn't seem great as it's basically an implicit dependency with no explicit contract in the code - nothing else uses environment variables. Having a way to set the value through an interface means that the code would have to synchronize the setting and the reading of the value which is also not that hot. I'll give it more thoughts but at this point if you have to change the value of the origin dynamically use your own middleware.

**Comment by tchssk** [comment]
In addition, swagger specification files cannot evaluate environment variables dynamically.
