### ISSUE TITLE
Use Decoder and Encoder based on Content-Encoding header

### ISSUE THREAD

**Issue by jarlefosen** [goadesign/goa#834]
As per now I'm unsure how to properly implement a Gzip Encoder and Decoder in Goa. I think a Middleware is the way to go, but I would like to append a Decoder to requests with header `Content-Encoding: gzip`, and an Encoder to `Accept-Encoding: gzip`.

Is this possible to do today?
The only way I see is to use either a middleware which I'm unable to set via design.go, or to create custom content types for encoded requests which isn't an optimal solution.

**Comment by raphael** [comment]
There is already a gzip middleware (https://github.com/goadesign/goa/tree/master/middleware/gzip). Does that not do what you need?

**Comment by jarlefosen** [comment]
If I'm not mistaken, that gzip middleware only encodes outgoing responses and not decoding incoming requests.
I would like to support the flow below:

```
[Client post request]
    |
    v
(Encoded with header "Content-Encoding: gzip")
    |
    v
[Middleware: decodes and removes header "Content-Encoding: gzip"]
    |
    v
[Controller: receives decoded body without header "Content-Encoding: gzip"]
```

Seems I have to create a similar middleware that handles incoming requests before the controller receives the request.

**Comment by raphael** [comment]
Ah yes I missed the fact that you needed Gzip decoding as well. I'd be happy to merge a PR that adds that capability to the existing middleware :)

**Comment by jarlefosen** [comment]
It looks like the framework is parsing the request before the middleware can get to the raw bytes, making it really hard for me to figure out where in the pipeline I'm supposed to decode it all.

Do you have any pointers for me?

With a middleware I'm unable to read the `http.Request.Body`, but I can get a hold of the `goa.ContextRequest(ctx).Payload`. The Payload is an interface `MessagePayload` already, but it cannot read it of course as the bytes are encoded using gzip.

In my dream world right now I would like to get a hold of the raw bytes coming from the request before the JSON parser does to modify everything according to the specified `Content-Encoding`. I do not want to create a new `Content-Type` that describes a bundled `application/json+gzip` request, as this has to be some kind of anti pattern.

I'm extremely very new to Go, so sorry if I'm missing something obvious.

**Comment by raphael** [comment]
Ugh sorry for not thinking it through (again!), you are correct that by the time the middleware gets hit the body has already been unmarshaled. The requirements for supporting this properly are similar to the requirements for https://github.com/goadesign/goa/pull/803: making it possible to have middlewares or middleware-like logic run prior to the request body being decoded.

In the PR linked above I suggest setting the decoder in the service startup code, something like the following:

```go
// ...
service := goa.New("...")
// ...
gzipDecoder := goa.NewHTTPDecoder()
gzipDecoder.Register(decodeGzip, "*/*") // Register gzip decoder for all content-types
service.Decoder = gzipDecoder
```
Where `decodeGzip` isa `goa.DecoderFunc`:

```
func decodeGzip(r io.Reader) goa.Decoder {
        // apply gzip decoding to `r`
        unzipped := gzip.NewReader(r)
        return json.NewDecoder(unzipped)
}
```
The obvious problem with this approach is that it assumes all incoming requests are encoded the same way (`JSON` in the example above). It seems goa is missing the ability to properly chain decoders which both the PR above and this use case requires.

### Introducing the `HTTPDecoderMiddleware` and `HTTPEncoderMiddleware` types

Here is a proposal that addresses the issues described above. The following function types are introduced:

```go
type (
    // A HTTPDecodeFunc decodes the content of  a reader given the value of a HTTP Content-Type
    // header and unmarshals the result into the given value `v`.
    HTTPDecodeFunc func(v interface{}, body io.Reader, contentType string) error

    // A HTTPEncodeFunc encodes the content of the given value `v` into the given writer using the
    // value of a HTTP Accept header.
    HTTPEncodeFunc func(v interface{}, resp io.Writer, accept string) error

    // A HTTPDecodeMiddleware wraps a decode function with arbitrary logic.
    HTTPDecodeMiddleware(HTTPDecodeFunc) HTTPDecodeFunc

    // A HTTPEncodeMiddleware wraps a encode function with arbitrary logic.
    HTTPEncodeMiddleware(HTTPEncodeFunc) HTTPEncodeFunc
)
```

The `Service` struct `Decoder` and `Encoder` fields are replaced with two new fields `DecodeFunc` and `EncodeFunc`. The types of these new fields are `HTTPDecodeFunc` and `HTTPEncodeFunc`. The `New` function creates default values for these new fields that invoke the HTTP decoder and encoder:

```go
func New(name string) *Service {
     // ...
		service      = &Service{
			Name:    name,
			Context: cctx,
			Mux:     mux,
			DecodeFunc: NewHTTPDecoder().Decode,
			EncodeFunc: NewHTTPEncoder().Encode,

			cancel: cancel,
		}
     // ...
```

The `Service` struct also implements two new methods `UseDecoder` and `UseEncoder`:

```go
// UseDecoder applies the decoder middleware to the current service decode function.
func (s *Service) UseDecoder(m HTTPDecodeMiddleware) {
   s.DecodeFunc = m(s.DecodeFunc)
}

// UseEncoder applies the encoder middleware to the current service encode function.
func (s *Service) UseEncoder(m HTTPEncodeMiddleware) {
   s.EncodeFunc = m(s.EncodeFunc)
}
```

Given the above you should be able to implement gzip decoding as a decoder middleware and the PR above can be updated to also use a decoder middleware.

This is probably more than what you were hoping for :) but this seems like a good capability to add to goa. Obviously any comment and/or criticism is more than welcome! Thank you for pushing this!

**Comment by jarlefosen** [comment]
With the current design, two different sets of Decoders/Encoders would make a lot of sense. However I would propose a strategy where `HTTPDecoder` and `HTTPEncoder` would get access to the actual `http.Request` and `http.ResponseWriter` references, a bit like you would write middleware for an ordinary http server in Go.

Two reasons why:

1. You're in full control over what is happening to the application, you can do conditional operations based on your own headers, be it `Content-Type` or `Content-Encoding` or some custom implementation that you use - it's all up to you.
2. Reusing standard http handlers in Goa would be very easy.

With your proposed strategy above, I'm still not able to read any header I'd like, nor modify the bytes as they arrive and pass them along to another middleware.

I think there needs to be three different stages of handlers/middleware/decoders here.

```
[Client sends request to server]
   |
( Headers and payload )
   |
   v
[HTTP Middleware] // Perfect place to modify byte-stream before it's parsed
   |
( Modified headers and modified payload )
   |
   v
[Encoder/Decoder] // From here and down everything works just the same as before
   v
[Middleware]
   v
[Controller]
```

The only difference here is that you can get early access to the request and do necessary modification to bytes and headers before they are eventually sent to decoders.
It would also make sense to add auth checks to this stage as you probably don't need to decode any messages from unauthorized clients.

What I have in mind when it comes to responsibilities:

**HTTP Middleware:**
Mainly look at headers and accept/deny requests early on if possible. Modify byte stream if another content encoding is in place.
When done, pass along the possibly modified headers and bytes.

**Encoders/Decoders**
These takes a string (byte array) and parses the body from JSON/XML/etc to your desired payload object. Just like it does today.

**Middleware**
Not quite sure what's needed here anymore since most can/should be done in HTTP Middleware, but it would work mostly the same as HTTP Middleware, except that it has a reference to the actual payload.

**Comment by raphael** [comment]
That makes sense, can you suggest an API for it? (as in the set of methods/functions added to the `goa` pacakge to support that functionality). A couple of small points:
* Using a standard HTTP handler in goa is trivial today, simply mount it directly on the `Mux`
* The post decoding middlewares are still very useful for things that create responses for example (e.g. error handler middleware)

**Comment by jarlefosen** [comment]
Ah yes, I suppose error handling is a great use case of the current middleware!

### Suggested API

I believe your API was almost to the point, but it was a bit too restrictive in terms of what information was available for the HttpMiddleware, so I'll just propose a more open alternative.

_But again, I'm really really new to Go, so please be critical to my suggestion below, I may have misunderstood something fundamental._


```go
type (
    // HTTPDecodeFunc decodes the request from a client before passing it along to a Decoder
    HTTPDecodeFunc func(w http.ResponseWriter, r *http.Response) error

    // HTTPEncodeFunc encodes the response from an Encoder before sending it back to the client
    HTTPEncodeFunc func(w http.ResponseWriter, header http.Header) error

    // A HTTPDecodeMiddleware wraps a HTTPDecodeFunc function with arbitrary logic.
    HTTPDecodeMiddleware(HTTPDecodeFunc) HTTPDecodeFunc

    // A HTTPEncodeMiddleware wraps a HTTPEncodeFunc function with arbitrary logic.
    HTTPEncodeMiddleware(HTTPEncodeFunc) HTTPEncodeFunc
)
```

`HTTPDecodeFunc` gets its hands on the pure request with all headers, and is able to modify the data. Should it have some reference to a context, or is that unnecessary? The request with its headers is just piped through the function, and out on the other end comes something similar yet not the same.

`HTTPEncodeFunc` works the same way, except this is for rewriting the response back to the client after an `Encoder` has had its way with the object.

**Now for the important question:** What is the disadvantage with a design like this?

_PS:_ I see now that maybe we should enrich the language a bit so we don't get confused by the ambiguity of Encoder vs HTTPEncodeFunc vs HTTPEncodeMiddleware vs Middleware 😄

**Comment by raphael** [comment]
I'm wondering whether this shouldn't be simplified to be just simple http middlewares. A couple of thoughts:
* Having the function return error is not useful because they sit before the error handler. They may as well just return a 500 directly.
* Distinguishing between encoding and decoding doesn't seem that useful either since we're talking about modifying the body before the rest of the chain has access to it and modifying the response after the rest of the chain has handled it. A standard middleware can do both.

So we could introduce a new `HTTPMiddleware` type which is the standard Go http middleware:
```go
type HTTPMiddleware func(http.Handler) http.Handler
```
And then have a way to "mount" these middlewares directly on a mux by adding a new `Use` method to the `ServeMux` interface.
```go
func (m *mux) Use(hm HTTPMiddleware) {
    m.handler = hm(m.handler)
}
```
Where `handler` is a new field of `mux` of type `http.Handler` initialized with `m.router.ServerHTTP`.

The usage would thus look like:
```go
service := goa.New("MyService")
service.Mux.Use(gzipMiddleware)
...
```

**Comment by jarlefosen** [comment]
Yes, this is great!

Would people understand that `service.Mux.Use(...)` is not the same as `service.Use(...)`?
Could there be another keyword involved, like `service.UseHttpMiddleware(gzipMiddleware)`, or would that be too much?

Anyways, I like this 👍

**Comment by raphael** [comment]
I *think* it should be clear as the idea is that anything related to the stdlib http handler is managed on the mux (i.e. mounting http handlers directly and now middlewares) while the service concerns itself with goa handlers and goa middlewares.

Do you feel like taking an initial stab a this? happy to review / help etc.

**Comment by jarlefosen** [comment]
Great! As long as it's reflected in some documentation and probably an overview which differentiates between each middleware/decoder it would be easy to discover the possibilities (and responsibilities) within each layer.

I can take a stab at it, but I'm a bit swamped right now, so a PR would come some time in the future. I'll shout out if (_when_) I need some input!

**Comment by raphael** [comment]
This specific issue is solved in v2 where the concept of controller is replaced with pure HTTP handlers. One can wrap the handler in middleware that can act prior to the decoding having occurred. Each endpoint can also be wrapped to insert logic that should occur after the decoding but prior to the actual service method being invoked.

**Comment by alexdias** [comment]
Is there any workaround for V1?
