### ISSUE TITLE
Media: ArrayOf() does not respect View

### ISSUE THREAD

**Issue by carlostrub** [goadesign/goa#835]
If a MediaType calls an array and we have a View selected that includes a non-default View for MediaOutput, the latter is not respected, i.e.

```
var MOutput = MediaType("application/vnd.xxx+json", func(){
   Attribute("output", ArrayOf(MediaOutput), "List of outputs.")
   View("default", func(){
    Attribute("output")
    })
   View("problem", func(){
     Attribute("output", func(){
           View("outProblem")
          }) 
    })
})
```

What should happen is that the struct in media_types.go looks something like
```
type XXX struct {
Output []*XXXOutputOutProblem
}
```
however, it only takes the array of the default view into this struct, while at the same time correctly create the XXXOutputOutProblem struct.

**Comment by raphael** [comment]
You should use CollectionOf to get a media type which will honor the views.
