### ISSUE TITLE
v2 - Design: Service and Endpoint DSL

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#845]
Implemented in package github.com/goadesign/goa/tree/v2-wip/design/dsl

**Comment by raphael** [comment]
The first pass is completed. 

Tests need to be added that cover all the DSL functions similarly to https://github.com/goadesign/goa/blob/v2-wip/design/dsl/description_test.go.

@maleck13 this would be a good place to get started if you'd like to help with the tests as you indicated in slack. Thakn you!

**Comment by maleck13** [comment]
Thanks @raphael  I have made a first pass on a test for feedback 
https://github.com/goadesign/goa/pull/846/files

**Comment by raphael** [comment]
@maleck13 Thanks! left a few comments in the code review, the structure of the test looks good though.

**Comment by raphael** [comment]
Wrote a specification for the DSL in the form of tests here:

https://github.com/goadesign/goa/blob/v2-wip/design/dsl/_spec

**Comment by tchssk** [comment]
I took a look at the DSL spec and now I have few questions. Would you answer that? @raphael

- Will we need at least one `Service()` for each designs (of `rest` or `rpc`)?
- When will we use multiple `Service()` in a design?

**Comment by raphael** [comment]
I'm not sure the DSL parser needs to validate that there is at least one service. You may want a design package with just types for testing or sharing.

Yes there can be as many service expressions as needed in a single design. It replaces the `Resource`  definition of `v1`.

Thanks for looking!

**Comment by tchssk** [comment]
Thank you for replying.

It seems that we will want a parsar that parses design from v1 to v2.

**Comment by raphael** [comment]
That's an interesting idea, not easy though :) The best would be if the tool took the v1 design definitions, created v2 design expressions from them (that part should be fairly simple) and then created the DSL back from the v2 expressions. 

* There is value in a tool that produces v2 expressions from v1 DSL because this would allow v2 code generation from v1 designs.
* There is also a lot of value in a tool that can take v2 expressions and "reverse engineer" the DSL, for example it could be used to create goa design from Swagger (assuming there is a Swagger to v2 expressions tool which should be fairly simple to write).

The second bullet is the one that's not easy :) But if you feel like giving this a shot I'd be more than happy to help. One caveat is that the v2 expressions are not completely finalized yet (esp. the transport specific expressions).

**Comment by tchssk** [comment]
I think so too. Direct converting from file (v1) to file (v2) is too sensitive to changes of specification.

Second point also seems to be related to #160. I'm trying to create that. I might be able to make use of this experience to v2.

**Comment by raphael** [comment]
Yes, the second bullet would give us #160. Happy to hear you might be able to help, this would  be a really awesome addition to v2!

**Comment by raphael** [comment]
Just a note that at this point I consider the `design` and `design/dsl` packages complete. I'm sure there will be tweaks needed later but for now I'm moving on to the `http/design` and `http/design/dsl` packages. So @maleck13 feel free to write tests for any DSL functions and if you find bugs please do let me know!

**Comment by raphael** [comment]
Another note that I'm moving the v2 branch from `v2-wip` to `v2`. This allows using `goa.design/goa.v2` as remote package. I've updated all the import path in goa to reflect that. A few consequences:

1. To work on v2 please do a `go get goa.design/goa.v2`.
2. Work from `$GOPATH/src/goa.design/goa`, checkout branch `v2`.
3. Make sure to use `goa.design/goa.v2` in all imports.

**Comment by maleck13** [comment]
@raphael Ok will switch to using that branch. Thanks for letting me know

**Comment by joeblew99** [comment]
great news on the DSL being ready for dog fooding.. thanks  @raphael , really awesome

**Comment by dalu** [comment]
please excuse my ignorance, is there documentation for v2?

**Comment by tchssk** [comment]
Now v2 is under construction but some documents with prefix `REQ_` are in `v2` branch.

**Comment by joeblew99** [comment]
I saw the accountant example.

wondering about:

1. If a mapping to GORM is planned as part of the V2 redesign, so that data
can be saved ina db.

2. the ability to use a GRPC protobuf is planned i see (
https://github.com/goadesign/goa/blob/v2/REQ_DESIGN.md#grpc-attribute-tags).
I am wondering if that is ready yet ? Or maybe an example is planned ?

thansk in advance

**Comment by raphael** [comment]
1. At this point there is no plan to have a gorma like plugin for v2. Obviously if someone wants to pick that up then great!

2. The initial release focuses on HTTP / REST but yes gRPC support is one of the driving requirements for v2. Will be adding gRPC to the example once we start that work.

**Comment by joeblew99** [comment]
ok good to know about Gorma - do you have a roughed our idea of how you envisage devs mapping the service code that goa produces down to the DB ?
I know there are a TON of ways to do it but would be useful to hear your thoughts if you have time.
