### ISSUE TITLE
When using JWT, CORS is not sent on 401

### ISSUE THREAD

**Issue by jeremyguarini** [goadesign/goa#886]
Hi,

I noticed that when using the jwt middleware, CORS was not being sent when I used an expired token. I would get a 401 and no access-control headers. After refreshing the jwt token, I would get back 2XX and proper CORS headers. 

I found that patching handleSecurity in the generated app/security.go to include the same CORS code that is found in some of the app/controllers.go func then a 401 would return CORS. Re-running goagen would replace the app/security.go so I updated my local copy of github.com/goadesign/goa/goagen/gen_app/writess.go (very end of file that writes fun handleSecurity()) and github.com/goadesign/goa/goagen/gen_app/generator.go generateSecurity() to include goa/cors. After these changes, running goagen now includes the CORS stuff in handleSecurity(). It's a hack that works for my case, though I don't have proper template code in writers.go to handle $policy.Methods  or $policy.Headers as found in other parts of writes.go.

If you need more information please let me know.

thanks,
Jeremy

**Comment by raphael** [comment]
Thanks for the report. Could you provide a complete design that reproduces the problem? thank you!

**Comment by jeremyguarini** [comment]
I’ve made a very simple app that demonstrates the issue. In the tar you’ll find:
* test run output
* steps that I did to build and run
* patch files for writer.go and generator.go
* main.go, login.go, test.go files already to go

I think all you will need to do is extract, review, build, and run. Then review the patch files to see what I want to be done and either apply the patch or copy and paste.

please let me know if you need anything else.

—
Jeremy

**Comment by jeremyguarini** [comment]
not sure if the attachment mad wit through, re-adding

[goadesign_bug.zip](https://github.com/goadesign/goa/files/605418/goadesign_bug.zip)

**Comment by raphael** [comment]
Thank you for all the details! PR #904 switches the order in which the security middleware and the CORS handler operates which should fix your issue.

**Comment by jeremyguarini** [comment]
Just tested and everything looks good. Thank you very much for such a quick turn-around. Keep up the good work.
