### ISSUE TITLE
Group CLI commands by resource

### ISSUE THREAD

**Issue by mark-lb** [goadesign/goa#899]
Currently the generated CLI is in the format `cli-command action resource`, e.g. `cellar-cli show bottle`, which is awkward and counterintuitive. Why not generate the CLI in the format `cellar-cli bottle show`, i.e. in the same order as in the DSL, which seems more natural?
Then an option such as `cellar-cli bottle --help` would list the available actions on the resource, etc., which to me seems more expected.

**Comment by raphael** [comment]
This was done this way for a couple of reasons:

1. It makes there command line read better. `show bottle href` is more natural than `bottle show href`.

2. More importantly I would make the reverse argument in that I find having to pick the action first helps with discovery. Answering the question "what can I show" is very interesting when dealing with an API from the command line tool. The reverse order makes more sense from a programmatic standpoint but the tool is mainly meant for interactive use.

There are definitely tradeoffs with both approaches but the current choice was explicit.

**Comment by mark-lb** [comment]
@raphael any chance to have this configurable - resource or action first?

**Comment by raphael** [comment]
I wouldn't be opposed to adding a flag to `goagen client` that would control the order. That is more work that it may seem at first though because it changes the data structures needed to generate the code as well as the templates. Happy to help if you feel like taking this on though.
