### ISSUE TITLE
goagen broken with vendor

### ISSUE THREAD

**Issue by perigee** [goadesign/goa#923]
Dear all, 

Using goagen `v1.0.0`,  when I generated vendor pkgs with `Godep` or `govendor`, and run goagen again, got:

```
missing API definition, make sure design is properly initialized
```
In such case, my workaround is:

- delete all dependencies in vendor folder
- regenerate by goagen
- reinstall all vendor dependencies

any idea, why this happens? Thank you in advance.

**Comment by raphael** [comment]
The way `goagen` works is that it generates the source code for the generator which imports the (user) design package. It then compiles and runs the generator code which generates the final output. What's happening here is that the the generator code is compiled with two copies of the goa `design` package - one that's imported by the generator code and one that's imported by the (user) design code (one is vendorered and the other isn't). The design code runs against its own copy when the DSL runs on process startup so the code generator code does not have the `design.Design` global variable initialized hence the error.

This is where the import statements for the generator code are written:
https://github.com/goadesign/goa/blob/master/goagen/meta/generator.go#L149-L150

The first line imports the goa design package used by the generator tool while the second line imports the user design package which itself imports the other copy of the goa design package. You need to make sure both endup importing the same (vendored) goa design package.

**Comment by raphael** [comment]
Reopening as this issue seems to pop up regularly. Would be good to get to the bottom of it.

**Comment by boyvanduuren** [comment]
I just hit this issue as well and was able to use Perigee's workaround successfully.

**Comment by perigee** [comment]
@boyvanduuren  I put a target in Makefile, just rename the vendor before generating the code, and rename it back;), very naive approach

**Comment by jaredbischof** [comment]
Hey @raphael, I think I figure this one out although I can't exactly explain it. When you use govendor to vendor goa into a project it only adds the packages that are used by your code (and recursively used packages). But, I noticed that the locations in the goa code where this error gets returned from were not vendored in my project. Therefore, I think there is some mixing of vendored and unvendored packages being used that causes some missing object to be used.

I was able to fix the issue in my project by removing all vendored goa packages and then running:

`govendor add -tree github.com/goadesign/goa`

This leads to some other confusing behavior where govendor says some other packages are external and you have to add them (probably used somewhere in the goa codebase), but when you add them it says they are used. However, if you just ignore the fact that govendor says you have unused packages in this case, everything works.

**Comment by dkeza** [comment]
Using goagen `v1.3.1` and dep `v0.5.0`

I also stumbled to this issue. I receive this error:
`missing API definition, make sure design is properly initialized`

At the end, I give up of using dep for now.

**Comment by BigBackBoom** [comment]
Faced exactly same problem.

**Comment by hiromaily** [comment]
+1

**Comment by panter-dsd** [comment]
I have the same problem.

**Comment by antlad** [comment]
> I have the same problem.

Just setup `dep` not to strip geogen from vendor folder. And then install `goagen` from vendor folader to match version exactly - all will be working
