### ISSUE TITLE
goagen gen does not allow custom flags

### ISSUE THREAD

**Issue by jsimonetti** [goadesign/goa#934]
When writing a custom Generator it might be nice to add extra command line arguments to the generator.
For example: 
`goagen gen -d <design> --pkg-path=<mygenerator> --custom-arg=notparsed`

In the current implementation it looks like cobra eats up the --custom-arg flag and tries to parse it.
This means that goagen with generate an error like: `Error: unknown flag: --custom-arg`

It would be nice if cobra ignored other flags, or if goagen could provide a way to add custom commandline args to a custom generator.

**Comment by jsimonetti** [comment]
one approach would be to use the `-` as argument and add all custom arguments after `-` to the Generator.
Cobra will stop parsing arguments after it sees a `-`
The command would then be:
`goagen gen -d <design> --pkg-path=<mygenerator> - --custom-arg=notparsed`

**Comment by raphael** [comment]
It would be ideal if any flag that the meta generator does not understand were passed through to the actual code generator. That was the intent of the code but that probably got broken with the switch to cobra.

**Comment by dan-compton** [comment]
I agree that no ```--``` should be required
