### ISSUE TITLE
Validation DSL ignored in ResponseTemplate

### ISSUE THREAD

**Issue by michaelboke** [goadesign/goa#943]
When using the ResponseTemplate Example from the [documentation](https://goa.design/reference/goa/design/apidsl/#func-responsetemplate-a-name-apidsl-responsetemplate-a) there is that part with the HEADER and location.
There are some notes on validating the contents of the `Location` header should match against `Pattern("[0-9A-F]+")`.

This validation logic is not generated in the return context.

I checked the generator files
goagen/gen_app/writers.go and the templates defined in var 
[ctxMTRespT](https://github.com/goadesign/goa/blob/fa0dc5a2b88abef1cb55696ac9faa3d09012211e/goagen/gen_app/writers.go#L593-L601), [ctxTRespT](https://github.com/goadesign/goa/blob/fa0dc5a2b88abef1cb55696ac9faa3d09012211e/goagen/gen_app/writers.go#L605-L610), [ctxNoMTRespT](https://github.com/goadesign/goa/blob/fa0dc5a2b88abef1cb55696ac9faa3d09012211e/goagen/gen_app/writers.go#L614-L623)

And there is no sign this is implemented.
Is this intended? or does the validation needs to take place here ?

**Comment by raphael** [comment]
Ah I realize now that I misunderstood when we chatted in slack about this. The *response* functions don't validate on purpose, the idea being that you have control on the code that produces the response content and thus can do the validation if you feel it's appropriate. This gives you control on the performance penalty you're willing to incur when writing responses.

This is in contrast with the code building the *request* context that does validate everything including the request headers if they have validations defined in the design.

**Comment by michaelboke** [comment]
ok... that does make sense. Thanks
