### ISSUE TITLE
CLI requires JSON encoded payload

### ISSUE THREAD

**Issue by mark-lb** [goadesign/goa#949]
Shouldn't the CLI accept parameter flags for the payload, same as for query and path params?
Thanks

**Comment by raphael** [comment]
It's actually very complex to do. Some data structures are hard to represent serialized in a non ambiguous way. It also makes for a pretty unwieldy set of command line flags. The initial implementation had discrete flags but it ended up being too complex to use and implement.

**Comment by mark-lb** [comment]
I get it for complex data types, but in many cases people put simple values in the body. Typical case is in POST request where it's illogical to have long paths for no reason, and not quite accepted to add query params. So how about have flags only for a flat map payload?

**Comment by raphael** [comment]
That's fine and goa allows you to define the command line flags however you want. The `main.go` file is generated as an example (as opposed to the command files and the `client` package which all get completely re-generated each time and that you cannot modify). So you are free to modify it and define you own flags.

**Comment by mark-lb** [comment]
@raphael not sure what you mean by your last comment. That's exactly what I want to do - define flags for the client side. Unclear to me how modifying main.go helps me on that. Am I missing something? Thanks

**Comment by mark-lb** [comment]
Ah I guess you mean tool/some-cli/main.go
Didn't see it documented anywhere that this file is not re-generated.
Are there any other client-side files that are also meant to be edited?
Thanks

**Comment by raphael** [comment]
`main.go` is the only file that's not re-generated. And yes, documentation is lacking in this area (for the client side as a whole). Would love to get more contributions to the [goa.design](https://github.com/goadesign/goa.design) repo :-P

**Comment by mark-lb** [comment]
@raphael well, I tried to modify the generated CLI command to use flags instead of requiring a JSON string - with no success. What I ended up doing is by brute force removing the command from the Cobra command tree, and replacing it with a new one which I wrote in identical style to the generated one - except for that one change. Here's my suggestion as to how it can easily be avoided in the framework:

Commands with request bodies may accept an optional "Encoder" function where the developer creates the JSON string based on input flags, instead of the user providing it. For example, in goa-cellar we could have something like the below. If `Encoder` is not defined, then a `payload` CLI flag is required, as today. If an Encoder exists, then the user just uses the defined flags and `payload` is left off the CLI, help, etc. Does this make sense?
```
Action("create", func() {
    Routing(POST(""),)
    Description("Record new bottle")
    Payload(BottlePayload, func() {
        Required("name", "vineyard", "varietal", "vintage", "color")
        Encoder(myJsonEncoder)
    })
    Response(Created, "^/accounts/[0-9]+/bottles/[0-9]+$")
    Response(NotFound)
    Response(BadRequest, ErrorMedia)
})
```

**Comment by raphael** [comment]
I don't think this works as a DSL construct. The DSL describes the design in the abstract, independently of specific outputs. Here we'd be adding DSL that only applies to the client tool code generation and is otherwise confusing.

If the generated `Command` structs could expose a `PreRun` field similar to the [cobra Command struct](https://godoc.org/github.com/spf13/cobra#Command) would that work for your use case? You could register a callback that massages the `Payload` field of the `Command` struct so that it's valid JSON. The generated code would look something like:

```go
	tmp2 := new(CreateBottleCommand)
	sub = &cobra.Command{
		Use:   `bottle ["/cellar/accounts/ACCOUNTID/bottles"]`,
		Short: ``,
		Long: `

Payload example:

{
   "color": "white",
   "country": "USA",
   "name": "Number 8",
   "region": "Napa Valley",
   "review": "Great and inexpensive",
   "sweetness": 1,
   "varietal": "Merlot",
   "vineyard": "Asti",
   "vintage": 2012
}`,
                // ADDED
                PreRunE: func(cmd *cobra.Command, args []string) error { return tmp2.PreRun(c, args) },
                // END ADDED
		RunE: func(cmd *cobra.Command, args []string) error { return tmp2.Run(c, args) },
	}
```
User code could then set the `PreRun` field of the `Command` structs prior to running.

**Comment by mark-lb** [comment]
If PreRun would have access to the flags and somewhere to store the payload - sure, that would work.
Nevertheless I'm not sure why my suggestion doesn't work as a DSL construct. Just as you display the payload example, this would assist in auto creating the payload. In any case, either would be a welcome improvement over the status today where I basically tossed the autogenerated command

**Comment by raphael** [comment]
The DSL describes the design in the abstract - independently of specific output generators. Generally there should not be constructs added to the DSL just to satisfy the needs of a specific generator. The DSL should not "know" what the generators need. It describes the API in the abstract in a way that is consistent and can be explained independently of code generation. How would you document  `Encoder` ? Another  - related - aspect is that a design goal of the DSL is to keep the number of "keywords" (functions) to a minimum and keep a small set of core patterns.

`Payload`  is a field of the `Command` structs so you'd have access to it in the `PreRun` hook. I would be happy to help anyone that wants to add this new field.

**Comment by raphael** [comment]
Reopening so we can keep track of the addition of the `PreRun` field to the generated `Command` structs.
