### ISSUE TITLE
global logger

### ISSUE THREAD

**Issue by perigee** [goadesign/goa#950]
Dear all, 

Anyway I can set a global logger, since for the moment I use context logger, don't want to pass the context in all my functions, thank you in advance. 

For the moment, i am using:

```
logger := goa.ContextLogger(ctx)
```

I have to pass `ctx` all a way around the functions, any chance that i can define a logger in package level? or any better solution?

**Comment by raphael** [comment]
You can extract the logger from the context like you have a above and pass it without the context or store it in a global variable. Note that using a global variable might create issues down the line (globals create coupling, hidden dependencies and potentially concurrency issues) so I'd recommend passing the logger down the call chain. You could store it as a field of a struct to avoid having to pass it down in every call.
