### ISSUE TITLE
How does one change the data format that is returned by validate?

### ISSUE THREAD

**Issue by jeremyguarini** [goadesign/goa#951]
Hi,

I'm looking at the data that is returned by the auto-validation when 'required' is used for an attribute. It has the following format:  {"id":"", "code":"", "status":400,"detail":""}

What I would like to do/have is a response that meets jsonapi requirements. See [http://jsonapi.org/format/#error-objects](http://jsonapi.org/format/#error-objects) for reference. Basically I want to take the existing format and wrap it such that 

> Error objects MUST be returned as an array keyed by `errors` in the top level of a JSON API document.

how do I got about defining the response for when a payload fails validation?

I'm thinking I need something like:
{ "errors" : [{"id":"", "code":"", "status":400,"detail":""}]}

thank you

**Comment by raphael** [comment]
You can override the package variables defined in [error.go](https://github.com/goadesign/goa/blob/master/error.go#L40-L74) so they produce the data structure you need. For the record goa initially followed the JSONAPI format but we found it not practical. As a client you really want the one error to handle and not a series of error. If there are multiple errors then the server knows how to combine them, the client does not know their semantic and thus can't.

**Comment by jeremyguarini** [comment]
Thanks for the info. I'm beginning to find out the same thing about jsonapi. While I can override the vars in error.go I'm having a tough time figuring out how to declare a new ErrorResponse struct. Any pointers in that area?

thanks

**Comment by raphael** [comment]
The variables are of type `ErrorClass` which is defined as:
```go
type ErrorClass func(message interface{}, keyvals ...interface{}) error
```
So the only requirement is that the returned value implements the `error` interface. An example of a `ErrorClass` implementation would be:

```
func (message interface{}, keyvals ...interface{}) *JSONAPIError {
    // See goa's NewErrorClass for examples on how to compute
    // ID, title etc.
    apiErr := &JSONAPIError{
         ID: id,
         Title: title,
         ...
    }
    return apiErr
}
```
Where `*JSONAPIError` implements `error`:
```
func (apiErr *JSONAPIError) Error() string {
    // serialize error message, see goa's ErrorResponse.Error for an example
    msg := ...
    return msg
}
```

**Comment by jeremyguarini** [comment]
Thank you for your help.
