### ISSUE TITLE
Unmarshalling JSON array with a null value causes runtime panic

### ISSUE THREAD

**Issue by leerobertw** [goadesign/goa#952]
I have defined in Design an endpoint which takes an array of objects 
var EnrollmentPayload = Type("EnrollmentPayload", func() {
	Attribute("plays", ArrayOf(Cadence), "The list of plays to be assigned to prospects", func() {
		MinLength(1)
	})
})

In testing, an array with a null value was sent to the endpoint.
{
  "plays": [null]
}

This causes the application to throw a panic runtime exception:
http: panic serving [::1]:65272: runtime error: invalid memory address or nil pointer dereference

Looking at the generated code, there is no check for nil before using the unmarshalled object
// Validate validates the cadence type instance.
func (ut *cadence) Validate() (err error) {
	if ut.ID == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "id"))
	}
...

**Comment by raphael** [comment]
Good catch, thank you for the report.
