### ISSUE TITLE
goa.client "completed" message is misleading

### ISSUE THREAD

**Issue by tve** [goadesign/goa#954]
The "completed" message in the goa client https://github.com/goadesign/goa/blob/master/client/client.go#L85 is misleading. In particular, the time printed only accounts for the reception of the HTTP response header and not for the actual reception of the body. An example:
```
[2016-12-07 10:17:50] DBUG started                        id=dKJJaUq7 GET=https://[...]
[2016-12-07 10:17:50] DBUG completed                      id=dKJJaUq7 status=200 time=103.521ms
[2016-12-07 10:18:50] DBUG fetch time                     num=75688 time=59.951192489s
```
In other words, the response header arrived in 103.5ms but receiving the full request took a minute. The message of "completed" is also misleading, it should be rephrased to "response header" or something like that because the request has not completed by the time it's printed.

**Comment by raphael** [comment]
Thanks for the report! Do you think it's worth wrapping the response body is an `io.Reader` that simply forwards the `Read` call to the actual response body, checks for EOF and logs when it's reached? Or should we simply change the text to "header received"?
