### ISSUE TITLE
There are unmerged features/fixes that were announced in v1.1.0.

### ISSUE THREAD

**Issue by ikawaha** [goadesign/goa#964]
I checked features/fixes that were [announced in v1.1.0](https://goa.design/blog/003-v1_1_0/).
The following PRs are probably not backported to the v1 branch.

* [ ] [Added the ability to dynamically add/remove keys](https://github.com/goadesign/goa/pull/818) 
* [ ] [Refactor JWT key resolver](https://github.com/goadesign/goa/pull/832)
* [ ] [Fix setting a default value to datetime](https://github.com/goadesign/goa/pull/758)
* [ ] [Add an interface instead of using testing.T](https://github.com/goadesign/goa/pull/733)
* [ ] [address issue #738 by creating a title for the test ](https://github.com/goadesign/goa/pull/780)
* [ ] [removed unneeded check which would make an unsafe concurrent modification](https://github.com/goadesign/goa/pull/736)
* [ ] [Modify metrics so that names are normalized to legal chars](https://github.com/goadesign/goa/pull/771)

Check List
---
### Programmatic Code Generation
* [x] https://github.com/goadesign/goa/pull/686
### Swagger Support Improvements
* [x] https://github.com/goadesign/goa/pull/779
* [x] https://github.com/goadesign/goa/pull/788
* [x] https://github.com/goadesign/goa/pull/790
* [x] https://github.com/goadesign/goa/pull/863
* [x] https://github.com/goadesign/goa/pull/858
* [x] https://github.com/goadesign/goa/pull/936
### Query String Array Parameters
* [x] https://github.com/goadesign/goa/pull/684
### Security Improvements
* [ ] https://github.com/goadesign/goa/pull/818 Added the ability to dynamically add/remove keys from the jwt security middleware after creation.
* [ ] https://github.com/goadesign/goa/pull/832 Refactor JWT key resolver
* [x] https://github.com/goadesign/goa/pull/823 
### CORS Support Improvements
* [x] https://github.com/goadesign/goa/pull/723
* [x] https://github.com/goadesign/goa/pull/717
* [x] https://github.com/goadesign/goa/pull/763
### Support for Modifying the goa Error Response Content-Type
* [x] https://github.com/goadesign/goa/pull/697
### Support for UUID parameters on the CLI
* [x] https://github.com/goadesign/goa/pull/701
### Logging
* [x] https://github.com/goadesign/goa/774
* [x] https://github.com/goadesign/goa/pull/792
### DSL
* [x] https://github.com/goadesign/goa/pull/816
### Miscellaneous
* [x] https://github.com/goadesign/goa/pull/837
* [x] https://github.com/goadesign/goa/pull/947
* [x] https://github.com/goadesign/goa/pull/953

### Payload Type Generation
* [x] https://github.com/goadesign/goa/pull/681
* [ ] https://github.com/goadesign/goa/pull/758 Fix setting a default value to datetime
* [x] https://github.com/goadesign/goa/pull/678
### Media Type Generation
* [x] https://github.com/goadesign/goa/pull/704
* [x] https://github.com/goadesign/goa/pull/702
### Examples Generation
* [x] https://github.com/goadesign/goa/pull/702
### Validations Generation
* [x] https://github.com/goadesign/goa/pull/740
* [x] https://github.com/goadesign/goa/pull/744
* [x] https://github.com/goadesign/goa/pull/957
### Test generation
* [x] https://github.com/goadesign/goa/pull/719
* [x] https://github.com/goadesign/goa/pull/721
* [ ] https://github.com/goadesign/goa/pull/733 Add an interface instead of using testing.T
* [ ] https://github.com/goadesign/goa/pull/780 address issue #738 by creating a title for the test file
* [x] https://github.com/goadesign/goa/pull/873
### Logging
* [ ] https://github.com/goadesign/goa/pull/736 removed unneeded check which would make an unsafe concurrent modification
### Swagger generation
* [x] https://github.com/goadesign/goa/pull/782
* [x] https://github.com/goadesign/goa/pull/825
### Metrics collection
* [ ] https://github.com/goadesign/goa/pull/771 Modify metrics so that names are normalized to legal chars
### Client
* [x] https://github.com/goadesign/goa/pull/784
* [x] https://github.com/goadesign/goa/pull/786
* [x] https://github.com/goadesign/goa/pull/960
* [x] https://github.com/goadesign/goa/pull/900

**Comment by raphael** [comment]
Thank you for catching this and for the PR! I have retagged `v1.1.0` with the missing commits.
