### ISSUE TITLE
why generate bottlePayload?

### ISSUE THREAD

**Issue by runner-mei** [goadesign/goa#966]
I run go genreate in the "github.com/goadesign/examples/guide"

In the genreate results, I found the bottlePayload and BottlePayload fields are the same, bottlePayload is only used in unmarshalShowBottlePayload.
My question is why not just use BottlePayload instead bottlePayload。
Why not remove bottlePayload and stay BottlePayload。
（oooo!  My English is poor。 Do you understand？）
````go
// ----- in user_tpes.go
// bottlePayload user type.
type bottlePayload struct {
	// status of bottle
	Status *int `form:"status,omitempty" json:"status,omitempty" xml:"status,omitempty"`
}
// BottlePayload user type.
type BottlePayload struct {
	// status of bottle
	Status int `form:"status" json:"status" xml:"status"`
}

// --- controllers.go
func unmarshalShowBottlePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &bottlePayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
````

**Comment by raphael** [comment]
The private types are necessary to perform validation. For example if a field is required on an object then the public type does not use a pointer but the private types does so that the generated code can check for nil and return a properly formatted error.
