### ISSUE TITLE
Can user custom define Context in v2?

### ISSUE THREAD

**Issue by runner-mei** [goadesign/goa#967]
Under the generated code would be:

```go
Update(ctx Context, resp *UpdateBottleResponse, req *UpdateBottleRequest) error
```

Context is defined by user, as follow:

```go
type Context {
  context.Context
  Db      sql.Db
  Field2  xxx
}

how to create Context?
db, err := sql.Open(xx, xx)
service := goa.New("xxxx", func(ctx context.Context) interface{}{
  return  &Context {Context:ctx,
      Db:  db,
      Field2:  xxx,
    }
})
```

**Comment by raphael** [comment]
This would break the rule where generated code does not have any dependency on user code - it's the other way around. To achieve this you could have a middleware that updates the context with the user provided data.
