### ISSUE TITLE
How to design router to receive URL like "http://a.com/b/?c=1&d=2"?

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#985]
I know goagen  can generate RESTFUL api, but how to design `Resource` to accept URL style as `"http://a.com/b/?`

**Comment by raphael** [comment]
Not sure I follow - there are a number of ways you can do what you are asking. The action path could be `/b` and have two params `c` and `d`. Or the resource base path could be `/b` and the action path be just `/` (with the two params as well).
```
var _ = resource("foo", func() {
    BasePath("/b")
    Action("bar", func() {
        Params(func() {
            Param("c")
            Param("d")
        })
    })
})
```
Check the [DSL reference](https://goa.design/reference/goa/design/apidsl/) for more information.

**Comment by KerwinKoo** [comment]
The example code you showed I have tested yet, but it not work. I know it's ok to route URL of "http://a.com/b?c=1&d=2", but I have to receive the URL like "http://a.com/b/?c=1&d=2" of [wifidog's URL protocol](http://dev.wifidog.org/wiki/doc/developer/WiFiDogProtocol_V1) It's `ping` format is : 

```
http://auth_sever/ping/?
gw_id=%s
sys_uptime=%lu
sys_memfree=%u
sys_load=%.2f
wifidog_uptime=%lu
```

There is a `/` between `ping` and `gw_id` as you see. 

Back to my source code: 

```
var _ = Resource("ping", func() {
	BasePath("/ping")

	Action("AnswerPing", func() {
		Routing(GET(""))
		Description("answer wifidog ping GET-Request")

		Params(func() {
			Param("q") //necessary
		})
		Response(OK, "text/plain")
	})
})
```

No matter I set `Routing(GET(""))` ,  `Routing(GET("/"))` or `BasePath("/ping/")` I can not get the right router result. Using the command of `curl 'localhost:8081/wifidog/ping/?q=2&a=4'` , the server demo responses nothing but get a result `<a href="/wifidog/ping?q=2&amp;a=4">Moved Permanently</a>.` of the command. Or using `http 'localhost:8081/wifidog/ping/?q=2&a=4'` it shows:

```
HTTP/1.1 301 Moved Permanently
Content-Length: 60
Content-Type: text/html; charset=utf-8
Date: Thu, 22 Dec 2016 02:48:42 GMT
Location: /wifidog/ping?q=2&a=4

<a href="/wifidog/ping?q=2&amp;a=4">Moved Permanently</a>.
```

How can I to come true this kind of URL router?

Sorry for my poor English.

**Comment by KerwinKoo** [comment]
@raphael  I have a try of using [echo](https://github.com/labstack/echo) web framework to create a demo:

```
package main

import (
	"net/http"

	"github.com/labstack/echo"
)

func main() {
	e := echo.New()
	e.GET("/wifidog/ping/", func(c echo.Context) error {
		q := c.QueryParam("q")
		return c.String(http.StatusOK, "Hello wifidog!  "+q)
	})

	e.Logger.Fatal(e.Start(":8082"))
}
```

It works well : 

```
$ http 127.0.0.1:8082/wifidog/ping/?q=2

HTTP/1.1 200 OK
Content-Length: 17
Content-Type: text/plain; charset=utf-8
Date: Thu, 22 Dec 2016 03:57:25 GMT

Hello wifidog!  2
```

**Comment by raphael** [comment]
OK I understand now :)
goa uses [httptreemux](https://github.com/dimfeld/httptreemux) to route the incoming requests. Read the [Trailing Slashes](https://github.com/dimfeld/httptreemux#trailing-slashes) section for information on the behavior of routes with a trailing slash. I think what you are after is setting `RedirectTrailingSlash` to false. Unfortunately there's no way to get to the underlying router directly from the interface (it's a information hiding trade-off to make it possible to plug other routers). So what you probably want to do is create your own mux which implements `ServeMux` similar to the goa `mux` type defined in `mux.go`. Change `NewMux` to set the `RedirectTrailingSlash` property.
