### ISSUE TITLE
Proposal: Allow validation values to be set at run time

### ISSUE THREAD

**Issue by mark-lb** [goadesign/goa#987]
Example of an implementation option:
Instead of (for example) have Minimum(1) enable doing something like Minimum(SomeGlobalVar) where SomeGlobalVar may be optionally initialized in the design file, but may also be updated at run time.

**Comment by raphael** [comment]
Remember that the DSL is not only for server code, it's also for clients, documentation, tests, other languages etc. This requires the information to be  available statically so the generators can produce the correct output. At a high level it is important that data only flows from design to runtime and never the other way around.

**Comment by mark-lb** [comment]
True, though often validation values become known only at runtime. So then we have to hand write the validator in the controller. It's mainly an annoyance if the same validator needs to be copy pasted between numerous controllers, so I was hoping to save on this issue.

**Comment by raphael** [comment]
Can you give an example of such a validation? I'm wondering if they could be expressed in the design or whether they are completely dynamic.

**Comment by mark-lb** [comment]
Let's assume the API manages a bunch of ports, and the paths look like `/ports/:portIndex/...` where portIndex could be from 0 to N with the number determined at runtime. Assume there may be many endpoints with the portIndex parameter. Make sense?

**Comment by raphael** [comment]
OK yes in this case that would have to be done in the controller.

**Comment by mark-lb** [comment]
Yup, so I was wondering if it could somehow be taken care of without a lot of copy pasted validation in the controllers. I guess a middleware would be one way to do it.

**Comment by raphael** [comment]
Yes a middleware would work well if the validation applies to all the endpoints of the controller. You probably know this already but you can call the `ErrInvalidRequest` error class function to return the same response the generated code would for invalid requests.
