### ISSUE TITLE
Payload types change based on validation

### ISSUE THREAD

**Issue by mark-lb** [goadesign/goa#989]
See full code below for a simplified example:
To recreate the issue:
1. goagen -d bootstrap
2. go build -o bug
3. Comment out `Required("name")` from the design
4. goagen -d bootstrap
5. go build -o bug
6. See compilation error: `./animal.go:25: invalid operation: animal.Name == "rex" (mismatched types *string and string)`

Design file:
```
package design // The convention consists of naming the design
// package "design"
import (
	. "github.com/goadesign/goa/design" // Use . imports to enable the DSL
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("bug", func() { // API defines the microservice endpoint and
	Title("blahblah")                                     // other global properties. There should be one
	Scheme("http")                                                           // the design.
	Host("localhost:8080")

	ResponseTemplate(Created, func(pattern string) {
		Description("Resource created")
		Status(201)
		Headers(func() {
			Header("Location", String, "href to created resource", func() {
				Pattern(pattern)
			})
		})
	})
})

var _ = Resource("animal", func() { // Resources group related API endpoints
	Action("create", func() {
		Routing(
			POST("/mypath"),
		)
		Payload(Animal)
		Response(BadRequest, ErrorMedia)
		Response(OK)
	})
})

var Animal = Type("animal", func() {
	Attribute("name", String, "an animal")
	Required("name")
})
```
animal.go
```
package main

import (
	"bug/app"
	"github.com/goadesign/goa"
	"fmt"
)

// AnimalController implements the animal resource.
type AnimalController struct {
	*goa.Controller
}

// NewAnimalController creates a animal controller.
func NewAnimalController(service *goa.Service) *AnimalController {
	return &AnimalController{Controller: service.NewController("AnimalController")}
}

// Create runs the create action.
func (c *AnimalController) Create(ctx *app.CreateAnimalContext) error {
	// AnimalController_Create: start_implement

	// Put your logic here
	animal := ctx.Payload
	if animal.Name == "rex" {
		fmt.Print("Rex!")
	}
	// AnimalController_Create: end_implement
	return nil
}
```

**Comment by raphael** [comment]
This is expected as the controller is only generated once. It's part of the of "scaffold" code which is generated as a help to you to get started quickly (like all the other files in the `main` package). The idea is that these files are yours, you should edit them, test them etc. It's as if you had written them from scratch except goa helps you get started quickly by generating an initial version. This is in contrast with the code in the `app`, `client` and `swagger` packages that cannot be edited and is re-generated from scratch each time.

**Comment by mark-lb** [comment]
@raphael thanks, this is well understood. But is it indeed expected for the types to change based on validation turned on and off?

**Comment by raphael** [comment]
Ah sorry for misunderstanding. Yes the `Required` validation is the only validation that changes the type. A required value can never be nil hence the zero value is never ambiguous. It's also a lot more practical to deal with fields that are not pointers. Optional fields though must be generated as pointers to distinguish between e.g. empty string and field not set by the client.

**Comment by mark-lb** [comment]
@raphael thanks for the explanation
